// allow: SIZE_OK - generated AI concepts TTS timing and local audio references.
import type { AiConceptsForBeginnersAudioTrack } from "./types";

export const aiConceptsForBeginnersAudio = [
  {
    audioFile: "generated/ai-concepts-for-beginners/open.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "LLM、Prompt、Context、RAG、Agent、MCP……第一次看到这串词，",
          startFrame: 0,
          durationInFrames: 345,
        },
        {
          id: "caption-2",
          text: "像不像菜单上突然出现了十一道缩写菜？",
          startFrame: 345,
          durationInFrames: 121,
        },
        {
          id: "caption-3",
          text: "别急。",
          startFrame: 466,
          durationInFrames: 77,
        },
        {
          id: "caption-4",
          text: "今天我们不开术语大会，",
          startFrame: 543,
          durationInFrames: 96,
        },
        {
          id: "caption-5",
          text: "改开一家 AI 餐厅。",
          startFrame: 639,
          durationInFrames: 59,
        },
        {
          id: "caption-6",
          text: "你会看到：",
          startFrame: 698,
          durationInFrames: 34,
        },
        {
          id: "caption-7",
          text: "有的是大脑，",
          startFrame: 732,
          durationInFrames: 36,
        },
        {
          id: "caption-8",
          text: "有的是订单，",
          startFrame: 768,
          durationInFrames: 58,
        },
        {
          id: "caption-9",
          text: "有的是工作台，",
          startFrame: 826,
          durationInFrames: 59,
        },
        {
          id: "caption-10",
          text: "有的是查资料的服务员，",
          startFrame: 885,
          durationInFrames: 73,
        },
        {
          id: "caption-11",
          text: "有的是工具插座，",
          startFrame: 958,
          durationInFrames: 128,
        },
        {
          id: "caption-12",
          text: "还有的是经理、流程、技能手册和临时小队。",
          startFrame: 1086,
          durationInFrames: 175,
        },
        {
          id: "caption-13",
          text: "等这家餐厅正常营业，",
          startFrame: 1261,
          durationInFrames: 72,
        },
        {
          id: "caption-14",
          text: "这些词就不会再挤成一锅字母汤。",
          startFrame: 1333,
          durationInFrames: 103,
        },
      ],
    },
    durationInFrames: 1436,
    durationInSeconds: 47.840813,
    format: "wav",
    narration:
      "LLM、Prompt、Context、RAG、Agent、MCP……第一次看到这串词，像不像菜单上突然出现了十一道缩写菜？[Question-ah] 别急。今天我们不开术语大会，改开一家 AI 餐厅。你会看到：有的是大脑，有的是订单，有的是工作台，有的是查资料的服务员，有的是工具插座，还有的是经理、流程、技能手册和临时小队。等这家餐厅正常营业，这些词就不会再挤成一锅字母汤。",
    provider: "voxcpm",
    sceneId: "open",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/llm.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "先看 LLM，",
          startFrame: 0,
          durationInFrames: 47,
        },
        {
          id: "caption-2",
          text: "也就是大语言模型。",
          startFrame: 47,
          durationInFrames: 77,
        },
        {
          id: "caption-3",
          text: "你可以把它想成一个读过海量菜谱、点评、对话和文章的超级厨师大脑。",
          startFrame: 124,
          durationInFrames: 246,
        },
        {
          id: "caption-4",
          text: "它最核心的本事，",
          startFrame: 370,
          durationInFrames: 56,
        },
        {
          id: "caption-5",
          text: "不是从抽屉里翻出一条完整答案，",
          startFrame: 426,
          durationInFrames: 108,
        },
        {
          id: "caption-6",
          text: "而是根据眼前文字，",
          startFrame: 534,
          durationInFrames: 70,
        },
        {
          id: "caption-7",
          text: "一步一步预测接下来什么最合适。",
          startFrame: 604,
          durationInFrames: 127,
        },
        {
          id: "caption-8",
          text: "所以它能写方案、解释代码、模仿语气，",
          startFrame: 731,
          durationInFrames: 159,
        },
        {
          id: "caption-9",
          text: "也可能一本正经地现编。",
          startFrame: 890,
          durationInFrames: 71,
        },
        {
          id: "caption-10",
          text: "训练让它拥有广泛经验，",
          startFrame: 961,
          durationInFrames: 87,
        },
        {
          id: "caption-11",
          text: "但训练结束后，",
          startFrame: 1048,
          durationInFrames: 60,
        },
        {
          id: "caption-12",
          text: "它并不会自动知道你公司刚更新的制度，",
          startFrame: 1108,
          durationInFrames: 127,
        },
        {
          id: "caption-13",
          text: "也不会凭空看到你桌面上的文件。",
          startFrame: 1235,
          durationInFrames: 89,
        },
      ],
    },
    durationInFrames: 1324,
    durationInSeconds: 44.111542,
    format: "wav",
    narration:
      "先看 LLM，也就是大语言模型。你可以把它想成一个读过海量菜谱、点评、对话和文章的超级厨师大脑。它最核心的本事，不是从抽屉里翻出一条完整答案，而是根据眼前文字，一步一步预测接下来什么最合适。所以它能写方案、解释代码、模仿语气，也可能一本正经地现编。训练让它拥有广泛经验，但训练结束后，它并不会自动知道你公司刚更新的制度，也不会凭空看到你桌面上的文件。",
    provider: "voxcpm",
    sceneId: "llm",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/prompt.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "接着是 Prompt，",
          startFrame: 0,
          durationInFrames: 64,
        },
        {
          id: "caption-2",
          text: "提示词。",
          startFrame: 64,
          durationInFrames: 35,
        },
        {
          id: "caption-3",
          text: "它就是你这一次递给厨师的订单。",
          startFrame: 99,
          durationInFrames: 96,
        },
        {
          id: "caption-4",
          text: "你写“做个网站”，",
          startFrame: 195,
          durationInFrames: 72,
        },
        {
          id: "caption-5",
          text: "相当于对厨房喊一句“来点吃的”，",
          startFrame: 267,
          durationInFrames: 148,
        },
        {
          id: "caption-6",
          text: "能出菜，",
          startFrame: 415,
          durationInFrames: 33,
        },
        {
          id: "caption-7",
          text: "但惊喜和惊吓都可能有。",
          startFrame: 448,
          durationInFrames: 86,
        },
        {
          id: "caption-8",
          text: "你写清楚观众是谁、目标是什么、有哪些限制、希望什么格式，",
          startFrame: 534,
          durationInFrames: 214,
        },
        {
          id: "caption-9",
          text: "就像说明两位用餐、不要香菜、预算一百、二十分钟上菜。",
          startFrame: 748,
          durationInFrames: 187,
        },
        {
          id: "caption-10",
          text: "Prompt 不是神秘咒语，",
          startFrame: 935,
          durationInFrames: 86,
        },
        {
          id: "caption-11",
          text: "也不是越长越高级。",
          startFrame: 1021,
          durationInFrames: 59,
        },
        {
          id: "caption-12",
          text: "它真正的价值，",
          startFrame: 1080,
          durationInFrames: 62,
        },
        {
          id: "caption-13",
          text: "是减少误解，",
          startFrame: 1142,
          durationInFrames: 45,
        },
        {
          id: "caption-14",
          text: "让模型知道这次到底要完成什么。",
          startFrame: 1187,
          durationInFrames: 109,
        },
      ],
    },
    durationInFrames: 1296,
    durationInSeconds: 43.167896,
    format: "wav",
    narration:
      "接着是 Prompt，提示词。它就是你这一次递给厨师的订单。你写“做个网站”，相当于对厨房喊一句“来点吃的”，能出菜，但惊喜和惊吓都可能有。你写清楚观众是谁、目标是什么、有哪些限制、希望什么格式，就像说明两位用餐、不要香菜、预算一百、二十分钟上菜。Prompt 不是神秘咒语，也不是越长越高级。它真正的价值，是减少误解，让模型知道这次到底要完成什么。",
    provider: "voxcpm",
    sceneId: "prompt",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/context.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "那 Context 呢？",
          startFrame: 0,
          durationInFrames: 40,
        },
        {
          id: "caption-2",
          text: "Context 是模型这一次工作时，",
          startFrame: 40,
          durationInFrames: 105,
        },
        {
          id: "caption-3",
          text: "真正能看见的全部内容。",
          startFrame: 145,
          durationInFrames: 102,
        },
        {
          id: "caption-4",
          text: "你的 Prompt 在里面，",
          startFrame: 247,
          durationInFrames: 62,
        },
        {
          id: "caption-5",
          text: "前面的聊天记录在里面，",
          startFrame: 309,
          durationInFrames: 79,
        },
        {
          id: "caption-6",
          text: "系统规则、检索回来的资料、工具结果，",
          startFrame: 388,
          durationInFrames: 141,
        },
        {
          id: "caption-7",
          text: "也可能在里面。",
          startFrame: 529,
          durationInFrames: 43,
        },
        {
          id: "caption-8",
          text: "把模型想成厨师，",
          startFrame: 572,
          durationInFrames: 63,
        },
        {
          id: "caption-9",
          text: "Context 就是当前工作台：",
          startFrame: 635,
          durationInFrames: 87,
        },
        {
          id: "caption-10",
          text: "订单、食材、过敏提醒、上一道菜做到哪一步，",
          startFrame: 722,
          durationInFrames: 160,
        },
        {
          id: "caption-11",
          text: "全摆在这里。",
          startFrame: 882,
          durationInFrames: 40,
        },
        {
          id: "caption-12",
          text: "工作台再大也有限，",
          startFrame: 922,
          durationInFrames: 67,
        },
        {
          id: "caption-13",
          text: "这就是上下文窗口。",
          startFrame: 989,
          durationInFrames: 73,
        },
        {
          id: "caption-14",
          text: "塞得太满，",
          startFrame: 1062,
          durationInFrames: 35,
        },
        {
          id: "caption-15",
          text: "重要信息会被淹没；",
          startFrame: 1097,
          durationInFrames: 85,
        },
        {
          id: "caption-16",
          text: "放错资料，",
          startFrame: 1182,
          durationInFrames: 41,
        },
        {
          id: "caption-17",
          text: "模型就会拿着昨天的菜单认真做今天的菜。",
          startFrame: 1223,
          durationInFrames: 143,
        },
      ],
    },
    durationInFrames: 1366,
    durationInSeconds: 45.528729,
    format: "wav",
    narration:
      "那 Context 呢？Context 是模型这一次工作时，真正能看见的全部内容。你的 Prompt 在里面，前面的聊天记录在里面，系统规则、检索回来的资料、工具结果，也可能在里面。把模型想成厨师，Context 就是当前工作台：订单、食材、过敏提醒、上一道菜做到哪一步，全摆在这里。工作台再大也有限，这就是上下文窗口。塞得太满，重要信息会被淹没；放错资料，模型就会拿着昨天的菜单认真做今天的菜。",
    provider: "voxcpm",
    sceneId: "context",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/rag.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "现在顾客问：",
          startFrame: 0,
          durationInFrames: 40,
        },
        {
          id: "caption-2",
          text: "我们公司今年的报销上限是多少？",
          startFrame: 40,
          durationInFrames: 96,
        },
        {
          id: "caption-3",
          text: "这件事可能没写进模型训练里。",
          startFrame: 136,
          durationInFrames: 91,
        },
        {
          id: "caption-4",
          text: "RAG，",
          startFrame: 227,
          durationInFrames: 31,
        },
        {
          id: "caption-5",
          text: "也就是检索增强生成，",
          startFrame: 258,
          durationInFrames: 109,
        },
        {
          id: "caption-6",
          text: "做法是先把问题拿去资料库搜索，",
          startFrame: 367,
          durationInFrames: 100,
        },
        {
          id: "caption-7",
          text: "找出最相关的几段，",
          startFrame: 467,
          durationInFrames: 70,
        },
        {
          id: "caption-8",
          text: "再把它们放回 Context，",
          startFrame: 537,
          durationInFrames: 76,
        },
        {
          id: "caption-9",
          text: "让 LLM 根据这些材料回答。",
          startFrame: 613,
          durationInFrames: 139,
        },
        {
          id: "caption-10",
          text: "像服务员跑去档案室，",
          startFrame: 752,
          durationInFrames: 84,
        },
        {
          id: "caption-11",
          text: "拿回最新版员工手册，",
          startFrame: 836,
          durationInFrames: 81,
        },
        {
          id: "caption-12",
          text: "厨师再照着做。",
          startFrame: 917,
          durationInFrames: 77,
        },
        {
          id: "caption-13",
          text: "RAG 不是给模型永久补课，",
          startFrame: 994,
          durationInFrames: 89,
        },
        {
          id: "caption-14",
          text: "它只是临时带资料进考场。",
          startFrame: 1083,
          durationInFrames: 87,
        },
        {
          id: "caption-15",
          text: "检索错了、资料旧了，",
          startFrame: 1170,
          durationInFrames: 76,
        },
        {
          id: "caption-16",
          text: "答案照样会歪，",
          startFrame: 1246,
          durationInFrames: 51,
        },
        {
          id: "caption-17",
          text: "所以 RAG 的关键不只是“有向量数据库”，",
          startFrame: 1297,
          durationInFrames: 146,
        },
        {
          id: "caption-18",
          text: "而是找得准、来源清、版本新。",
          startFrame: 1443,
          durationInFrames: 123,
        },
      ],
    },
    durationInFrames: 1566,
    durationInSeconds: 52.19775,
    format: "wav",
    narration:
      "现在顾客问：我们公司今年的报销上限是多少？这件事可能没写进模型训练里。RAG，也就是检索增强生成，做法是先把问题拿去资料库搜索，找出最相关的几段，再把它们放回 Context，让 LLM 根据这些材料回答。像服务员跑去档案室，拿回最新版员工手册，厨师再照着做。RAG 不是给模型永久补课，它只是临时带资料进考场。检索错了、资料旧了，答案照样会歪，所以 RAG 的关键不只是“有向量数据库”，而是找得准、来源清、版本新。",
    provider: "voxcpm",
    sceneId: "rag",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/function-calling.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "光会回答还不够，",
          startFrame: 0,
          durationInFrames: 63,
        },
        {
          id: "caption-2",
          text: "我们还想让 AI 查天气、订会议室、算价格。",
          startFrame: 63,
          durationInFrames: 156,
        },
        {
          id: "caption-3",
          text: "Function Calling，",
          startFrame: 219,
          durationInFrames: 45,
        },
        {
          id: "caption-4",
          text: "就是让模型不要直接假装事情已经办完，",
          startFrame: 264,
          durationInFrames: 147,
        },
        {
          id: "caption-5",
          text: "而是输出一张结构化工具单：",
          startFrame: 411,
          durationInFrames: 82,
        },
        {
          id: "caption-6",
          text: "调用哪个函数，",
          startFrame: 493,
          durationInFrames: 55,
        },
        {
          id: "caption-7",
          text: "需要哪些参数。",
          startFrame: 548,
          durationInFrames: 49,
        },
        {
          id: "caption-8",
          text: "比如不是说“我已经订好了”，",
          startFrame: 597,
          durationInFrames: 91,
        },
        {
          id: "caption-9",
          text: "而是交出“book_room，",
          startFrame: 688,
          durationInFrames: 92,
        },
        {
          id: "caption-10",
          text: "日期星期五，",
          startFrame: 780,
          durationInFrames: 41,
        },
        {
          id: "caption-11",
          text: "人数六人”。",
          startFrame: 821,
          durationInFrames: 52,
        },
        {
          id: "caption-12",
          text: "真正执行函数的是你的程序，",
          startFrame: 873,
          durationInFrames: 99,
        },
        {
          id: "caption-13",
          text: "模型负责判断何时调用、参数怎么填。",
          startFrame: 972,
          durationInFrames: 129,
        },
        {
          id: "caption-14",
          text: "注意，",
          startFrame: 1101,
          durationInFrames: 24,
        },
        {
          id: "caption-15",
          text: "Function Calling 不是函数自己，",
          startFrame: 1125,
          durationInFrames: 88,
        },
        {
          id: "caption-16",
          text: "也不是外部系统凭空听懂中文；",
          startFrame: 1213,
          durationInFrames: 101,
        },
        {
          id: "caption-17",
          text: "它是一种让模型提出工具请求的规范方式。",
          startFrame: 1314,
          durationInFrames: 120,
        },
      ],
    },
    durationInFrames: 1434,
    durationInSeconds: 47.794792,
    format: "wav",
    narration:
      "光会回答还不够，我们还想让 AI 查天气、订会议室、算价格。Function Calling，就是让模型不要直接假装事情已经办完，而是输出一张结构化工具单：调用哪个函数，需要哪些参数。比如不是说“我已经订好了”，而是交出“book_room，日期星期五，人数六人”。真正执行函数的是你的程序，模型负责判断何时调用、参数怎么填。注意，Function Calling 不是函数自己，也不是外部系统凭空听懂中文；它是一种让模型提出工具请求的规范方式。",
    provider: "voxcpm",
    sceneId: "function-calling",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/mcp.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "工具一多，",
          startFrame: 0,
          durationInFrames: 34,
        },
        {
          id: "caption-2",
          text: "新问题来了：",
          startFrame: 34,
          durationInFrames: 37,
        },
        {
          id: "caption-3",
          text: "每个数据库、文件系统、浏览器，",
          startFrame: 71,
          durationInFrames: 109,
        },
        {
          id: "caption-4",
          text: "都自己发明一套接线方法，",
          startFrame: 180,
          durationInFrames: 90,
        },
        {
          id: "caption-5",
          text: "厨房后墙很快就像一盘耳机线。",
          startFrame: 270,
          durationInFrames: 108,
        },
        {
          id: "caption-6",
          text: "MCP，",
          startFrame: 378,
          durationInFrames: 35,
        },
        {
          id: "caption-7",
          text: "Model Context Protocol，",
          startFrame: 413,
          durationInFrames: 64,
        },
        {
          id: "caption-8",
          text: "可以理解成 AI 工具世界的一套标准插座和菜单。",
          startFrame: 477,
          durationInFrames: 174,
        },
        {
          id: "caption-9",
          text: "MCP Server 把工具、资源和提示能力按统一方式暴露出来，",
          startFrame: 651,
          durationInFrames: 222,
        },
        {
          id: "caption-10",
          text: "MCP Client 负责连接和使用。",
          startFrame: 873,
          durationInFrames: 100,
        },
        {
          id: "caption-11",
          text: "Function Calling 更像一张具体工具单；",
          startFrame: 973,
          durationInFrames: 95,
        },
        {
          id: "caption-12",
          text: "MCP 更像让许多工具都能被发现、描述和接入的标准接口。",
          startFrame: 1068,
          durationInFrames: 208,
        },
        {
          id: "caption-13",
          text: "它不会自动让模型变聪明，",
          startFrame: 1276,
          durationInFrames: 81,
        },
        {
          id: "caption-14",
          text: "但会让接工具这件事少一点手搓转接头。",
          startFrame: 1357,
          durationInFrames: 133,
        },
      ],
    },
    durationInFrames: 1490,
    durationInSeconds: 49.637188,
    format: "wav",
    narration:
      "工具一多，新问题来了：每个数据库、文件系统、浏览器，都自己发明一套接线方法，厨房后墙很快就像一盘耳机线。MCP，Model Context Protocol，可以理解成 AI 工具世界的一套标准插座和菜单。MCP Server 把工具、资源和提示能力按统一方式暴露出来，MCP Client 负责连接和使用。Function Calling 更像一张具体工具单；MCP 更像让许多工具都能被发现、描述和接入的标准接口。它不会自动让模型变聪明，但会让接工具这件事少一点手搓转接头。",
    provider: "voxcpm",
    sceneId: "mcp",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/agent.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "当模型不只回答一次，",
          startFrame: 0,
          durationInFrames: 70,
        },
        {
          id: "caption-2",
          text: "而是能看目标、决定下一步、调用工具、读取结果、发现不对再调整，",
          startFrame: 70,
          durationInFrames: 265,
        },
        {
          id: "caption-3",
          text: "我们通常开始叫它 Agent，",
          startFrame: 335,
          durationInFrames: 76,
        },
        {
          id: "caption-4",
          text: "智能体。",
          startFrame: 411,
          durationInFrames: 24,
        },
        {
          id: "caption-5",
          text: "它像餐厅经理：",
          startFrame: 435,
          durationInFrames: 44,
        },
        {
          id: "caption-6",
          text: "先看订单和现场，",
          startFrame: 479,
          durationInFrames: 70,
        },
        {
          id: "caption-7",
          text: "安排查库存，",
          startFrame: 549,
          durationInFrames: 45,
        },
        {
          id: "caption-8",
          text: "发现缺货就换方案，",
          startFrame: 594,
          durationInFrames: 65,
        },
        {
          id: "caption-9",
          text: "最后确认菜有没有上对桌。",
          startFrame: 659,
          durationInFrames: 84,
        },
        {
          id: "caption-10",
          text: "Agent 的关键不是名字里有 AI，",
          startFrame: 743,
          durationInFrames: 87,
        },
        {
          id: "caption-11",
          text: "而是存在一个循环：",
          startFrame: 830,
          durationInFrames: 59,
        },
        {
          id: "caption-12",
          text: "观察、计划、行动、检查。",
          startFrame: 889,
          durationInFrames: 146,
        },
        {
          id: "caption-13",
          text: "循环越自由，",
          startFrame: 1035,
          durationInFrames: 50,
        },
        {
          id: "caption-14",
          text: "能力可能越强，",
          startFrame: 1085,
          durationInFrames: 95,
        },
        {
          id: "caption-15",
          text: "成本和风险也越高。",
          startFrame: 1180,
          durationInFrames: 60,
        },
        {
          id: "caption-16",
          text: "所以好 Agent 不只是“放它自己跑”，",
          startFrame: 1240,
          durationInFrames: 145,
        },
        {
          id: "caption-17",
          text: "还要有权限边界、停止条件、日志和人工确认。",
          startFrame: 1385,
          durationInFrames: 180,
        },
      ],
    },
    durationInFrames: 1565,
    durationInSeconds: 52.140125,
    format: "wav",
    narration:
      "当模型不只回答一次，而是能看目标、决定下一步、调用工具、读取结果、发现不对再调整，我们通常开始叫它 Agent，智能体。它像餐厅经理：先看订单和现场，安排查库存，发现缺货就换方案，最后确认菜有没有上对桌。Agent 的关键不是名字里有 AI，而是存在一个循环：观察、计划、行动、检查。循环越自由，能力可能越强，成本和风险也越高。所以好 Agent 不只是“放它自己跑”，还要有权限边界、停止条件、日志和人工确认。",
    provider: "voxcpm",
    sceneId: "agent",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/workflow.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "Workflow，",
          startFrame: 0,
          durationInFrames: 23,
        },
        {
          id: "caption-2",
          text: "工作流，",
          startFrame: 23,
          durationInFrames: 31,
        },
        {
          id: "caption-3",
          text: "和 Agent 很容易混。",
          startFrame: 54,
          durationInFrames: 56,
        },
        {
          id: "caption-4",
          text: "Workflow 像提前铺好的出餐轨道：",
          startFrame: 110,
          durationInFrames: 101,
        },
        {
          id: "caption-5",
          text: "接单、检查库存、烹饪、质检、上菜，",
          startFrame: 211,
          durationInFrames: 199,
        },
        {
          id: "caption-6",
          text: "每一步和分支基本由人先设计好。",
          startFrame: 410,
          durationInFrames: 107,
        },
        {
          id: "caption-7",
          text: "Agent 更像经理，",
          startFrame: 517,
          durationInFrames: 71,
        },
        {
          id: "caption-8",
          text: "会根据现场临时决定下一步。",
          startFrame: 588,
          durationInFrames: 89,
        },
        {
          id: "caption-9",
          text: "固定、重复、合规要求高的任务，",
          startFrame: 677,
          durationInFrames: 104,
        },
        {
          id: "caption-10",
          text: "Workflow 往往更稳、更便宜、更容易排错；",
          startFrame: 781,
          durationInFrames: 181,
        },
        {
          id: "caption-11",
          text: "开放、变化多、需要探索的任务，",
          startFrame: 962,
          durationInFrames: 124,
        },
        {
          id: "caption-12",
          text: "Agent 才更有价值。",
          startFrame: 1086,
          durationInFrames: 61,
        },
        {
          id: "caption-13",
          text: "现实系统经常把两者混用：",
          startFrame: 1147,
          durationInFrames: 89,
        },
        {
          id: "caption-14",
          text: "大流程走固定轨道，",
          startFrame: 1236,
          durationInFrames: 67,
        },
        {
          id: "caption-15",
          text: "只有少数需要判断的站点交给 Agent。",
          startFrame: 1303,
          durationInFrames: 107,
        },
      ],
    },
    durationInFrames: 1410,
    durationInSeconds: 46.977208,
    format: "wav",
    narration:
      "Workflow，工作流，和 Agent 很容易混。Workflow 像提前铺好的出餐轨道：接单、检查库存、烹饪、质检、上菜，每一步和分支基本由人先设计好。Agent 更像经理，会根据现场临时决定下一步。固定、重复、合规要求高的任务，Workflow 往往更稳、更便宜、更容易排错；开放、变化多、需要探索的任务，Agent 才更有价值。现实系统经常把两者混用：大流程走固定轨道，只有少数需要判断的站点交给 Agent。",
    provider: "voxcpm",
    sceneId: "workflow",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/skill.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "Skill，",
          startFrame: 0,
          durationInFrames: 26,
        },
        {
          id: "caption-2",
          text: "可以理解成给 Agent 准备的专业操作手册。",
          startFrame: 26,
          durationInFrames: 116,
        },
        {
          id: "caption-3",
          text: "它不只是随口一句 Prompt，",
          startFrame: 142,
          durationInFrames: 90,
        },
        {
          id: "caption-4",
          text: "而是一组可重复使用的说明：",
          startFrame: 232,
          durationInFrames: 84,
        },
        {
          id: "caption-5",
          text: "什么时候用、按什么步骤做、调用哪些工具、质量标准是什么，",
          startFrame: 316,
          durationInFrames: 234,
        },
        {
          id: "caption-6",
          text: "甚至附带脚本和模板。",
          startFrame: 550,
          durationInFrames: 80,
        },
        {
          id: "caption-7",
          text: "比如“制作 Remotion 视频”是一项 Skill，",
          startFrame: 630,
          durationInFrames: 165,
        },
        {
          id: "caption-8",
          text: "它会提醒先写旁白、让音频决定时长、优先复用组件、最后抽帧验收。",
          startFrame: 795,
          durationInFrames: 249,
        },
        {
          id: "caption-9",
          text: "Skill 不等于模型新学会了永久能力，",
          startFrame: 1044,
          durationInFrames: 127,
        },
        {
          id: "caption-10",
          text: "更像经理接到摄影任务时，",
          startFrame: 1171,
          durationInFrames: 80,
        },
        {
          id: "caption-11",
          text: "从柜子里拿出摄影制作手册，",
          startFrame: 1251,
          durationInFrames: 96,
        },
        {
          id: "caption-12",
          text: "按专业套路办事。",
          startFrame: 1347,
          durationInFrames: 48,
        },
      ],
    },
    durationInFrames: 1395,
    durationInSeconds: 46.4975,
    format: "wav",
    narration:
      "Skill，可以理解成给 Agent 准备的专业操作手册。它不只是随口一句 Prompt，而是一组可重复使用的说明：什么时候用、按什么步骤做、调用哪些工具、质量标准是什么，甚至附带脚本和模板。比如“制作 Remotion 视频”是一项 Skill，它会提醒先写旁白、让音频决定时长、优先复用组件、最后抽帧验收。Skill 不等于模型新学会了永久能力，更像经理接到摄影任务时，从柜子里拿出摄影制作手册，按专业套路办事。",
    provider: "voxcpm",
    sceneId: "skill",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/subagent.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "任务再大一点，",
          startFrame: 0,
          durationInFrames: 39,
        },
        {
          id: "caption-2",
          text: "主 Agent 可以派出 Subagent，",
          startFrame: 39,
          durationInFrames: 75,
        },
        {
          id: "caption-3",
          text: "也就是子代理。",
          startFrame: 114,
          durationInFrames: 87,
        },
        {
          id: "caption-4",
          text: "比如筹备发布会，",
          startFrame: 201,
          durationInFrames: 52,
        },
        {
          id: "caption-5",
          text: "主经理负责总体方案，",
          startFrame: 253,
          durationInFrames: 72,
        },
        {
          id: "caption-6",
          text: "同时让一个分队查场地、一个分队整理嘉宾资料、另一个分队检查预算。",
          startFrame: 325,
          durationInFrames: 246,
        },
        {
          id: "caption-7",
          text: "它们最好拥有清楚的任务边界和交付格式，",
          startFrame: 571,
          durationInFrames: 163,
        },
        {
          id: "caption-8",
          text: "能并行就并行；",
          startFrame: 734,
          durationInFrames: 64,
        },
        {
          id: "caption-9",
          text: "需要同一份文件、互相等待的工作，",
          startFrame: 798,
          durationInFrames: 115,
        },
        {
          id: "caption-10",
          text: "就别硬拆。",
          startFrame: 913,
          durationInFrames: 37,
        },
        {
          id: "caption-11",
          text: "子代理不是把同一句话复制给十个模型看谁声音大，",
          startFrame: 950,
          durationInFrames: 192,
        },
        {
          id: "caption-12",
          text: "而是有目的地分工，",
          startFrame: 1142,
          durationInFrames: 59,
        },
        {
          id: "caption-13",
          text: "最后仍由主 Agent 整合、审查和承担结果。",
          startFrame: 1201,
          durationInFrames: 124,
        },
      ],
    },
    durationInFrames: 1325,
    durationInSeconds: 44.156042,
    format: "wav",
    narration:
      "任务再大一点，主 Agent 可以派出 Subagent，也就是子代理。比如筹备发布会，主经理负责总体方案，同时让一个分队查场地、一个分队整理嘉宾资料、另一个分队检查预算。它们最好拥有清楚的任务边界和交付格式，能并行就并行；需要同一份文件、互相等待的工作，就别硬拆。[Uhm] 子代理不是把同一句话复制给十个模型看谁声音大，而是有目的地分工，最后仍由主 Agent 整合、审查和承担结果。",
    provider: "voxcpm",
    sceneId: "subagent",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/langchain.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "最后说 LangChain。",
          startFrame: 0,
          durationInFrames: 84,
        },
        {
          id: "caption-2",
          text: "它是一个帮助开发者连接模型、Prompt、检索、工具、Agent 和工作流的开发框架与生态。",
          startFrame: 84,
          durationInFrames: 344,
        },
        {
          id: "caption-3",
          text: "你可以把它看成一套厨房装修工具箱：",
          startFrame: 428,
          durationInFrames: 115,
        },
        {
          id: "caption-4",
          text: "有管道、有连接件、有现成模块，",
          startFrame: 543,
          durationInFrames: 137,
        },
        {
          id: "caption-5",
          text: "能更快把系统搭起来。",
          startFrame: 680,
          durationInFrames: 66,
        },
        {
          id: "caption-6",
          text: "但请记住，",
          startFrame: 746,
          durationInFrames: 31,
        },
        {
          id: "caption-7",
          text: "LangChain 不是 LLM，",
          startFrame: 777,
          durationInFrames: 60,
        },
        {
          id: "caption-8",
          text: "不是 RAG，",
          startFrame: 837,
          durationInFrames: 30,
        },
        {
          id: "caption-9",
          text: "也不等于 Agent；",
          startFrame: 867,
          durationInFrames: 58,
        },
        {
          id: "caption-10",
          text: "这些概念在没有 LangChain 时依然存在。",
          startFrame: 925,
          durationInFrames: 135,
        },
        {
          id: "caption-11",
          text: "你也可以用别的框架，",
          startFrame: 1060,
          durationInFrames: 61,
        },
        {
          id: "caption-12",
          text: "或者直接调用模型 API 自己搭。",
          startFrame: 1121,
          durationInFrames: 104,
        },
        {
          id: "caption-13",
          text: "学概念时先理解房子怎么住，",
          startFrame: 1225,
          durationInFrames: 88,
        },
        {
          id: "caption-14",
          text: "再决定要不要买这套电钻。",
          startFrame: 1313,
          durationInFrames: 74,
        },
      ],
    },
    durationInFrames: 1387,
    durationInSeconds: 46.208792,
    format: "wav",
    narration:
      "最后说 LangChain。它是一个帮助开发者连接模型、Prompt、检索、工具、Agent 和工作流的开发框架与生态。你可以把它看成一套厨房装修工具箱：有管道、有连接件、有现成模块，能更快把系统搭起来。但请记住，LangChain 不是 LLM，不是 RAG，也不等于 Agent；这些概念在没有 LangChain 时依然存在。你也可以用别的框架，或者直接调用模型 API 自己搭。学概念时先理解房子怎么住，再决定要不要买这套电钻。",
    provider: "voxcpm",
    sceneId: "langchain",
  },
  {
    audioFile: "generated/ai-concepts-for-beginners/close.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "现在把整家餐厅连起来：",
          startFrame: 0,
          durationInFrames: 79,
        },
        {
          id: "caption-2",
          text: "LLM 是大脑；",
          startFrame: 79,
          durationInFrames: 60,
        },
        {
          id: "caption-3",
          text: "Prompt 是这次订单；",
          startFrame: 139,
          durationInFrames: 64,
        },
        {
          id: "caption-4",
          text: "Context 是当前工作台；",
          startFrame: 203,
          durationInFrames: 84,
        },
        {
          id: "caption-5",
          text: "RAG 把相关资料送上台面；",
          startFrame: 287,
          durationInFrames: 87,
        },
        {
          id: "caption-6",
          text: "Function Calling 生成具体工具单；",
          startFrame: 374,
          durationInFrames: 91,
        },
        {
          id: "caption-7",
          text: "MCP 让工具更标准地接进来；",
          startFrame: 465,
          durationInFrames: 118,
        },
        {
          id: "caption-8",
          text: "Agent 负责动态决策；",
          startFrame: 583,
          durationInFrames: 136,
        },
        {
          id: "caption-9",
          text: "Workflow 提供稳定轨道；",
          startFrame: 719,
          durationInFrames: 68,
        },
        {
          id: "caption-10",
          text: "Skill 提供专业手册；",
          startFrame: 787,
          durationInFrames: 66,
        },
        {
          id: "caption-11",
          text: "Subagent 负责边界清楚的分工；",
          startFrame: 853,
          durationInFrames: 130,
        },
        {
          id: "caption-12",
          text: "LangChain 则是可选的搭建工具箱。",
          startFrame: 983,
          durationInFrames: 100,
        },
        {
          id: "caption-13",
          text: "下次再看到这些词，",
          startFrame: 1083,
          durationInFrames: 77,
        },
        {
          id: "caption-14",
          text: "不用背十一条定义。",
          startFrame: 1160,
          durationInFrames: 53,
        },
        {
          id: "caption-15",
          text: "只要问一句：",
          startFrame: 1213,
          durationInFrames: 87,
        },
        {
          id: "caption-16",
          text: "它在这家餐厅里，",
          startFrame: 1300,
          durationInFrames: 50,
        },
        {
          id: "caption-17",
          text: "到底是大脑、信息、工具，",
          startFrame: 1350,
          durationInFrames: 104,
        },
        {
          id: "caption-18",
          text: "还是组织方式？",
          startFrame: 1454,
          durationInFrames: 60,
        },
        {
          id: "caption-19",
          text: "答案通常就清楚了。",
          startFrame: 1514,
          durationInFrames: 56,
        },
      ],
    },
    durationInFrames: 1570,
    durationInSeconds: 52.329375,
    format: "wav",
    narration:
      "现在把整家餐厅连起来：LLM 是大脑；Prompt 是这次订单；Context 是当前工作台；RAG 把相关资料送上台面；Function Calling 生成具体工具单；MCP 让工具更标准地接进来；Agent 负责动态决策；Workflow 提供稳定轨道；Skill 提供专业手册；Subagent 负责边界清楚的分工；LangChain 则是可选的搭建工具箱。[laughing] 下次再看到这些词，不用背十一条定义。只要问一句：它在这家餐厅里，到底是大脑、信息、工具，还是组织方式？答案通常就清楚了。",
    provider: "voxcpm",
    sceneId: "close",
  },
] satisfies readonly AiConceptsForBeginnersAudioTrack[];
