// allow: SIZE_OK - generated Chinese F5 TTS timing and static audio references.
import {
  PIXELRAG_CHINESE_STANDALONE_COMPOSITION_ID,
  PIXELRAG_CHINESE_STANDALONE_CONTENT_FAMILY,
  PIXELRAG_CHINESE_STANDALONE_FPS,
  PIXELRAG_CHINESE_STANDALONE_HEIGHT,
  PIXELRAG_CHINESE_STANDALONE_PROFILE_ID,
  PIXELRAG_CHINESE_STANDALONE_WIDTH,
  type PixelRAGChineseStandaloneData,
} from "./types";

export const pixelragChineseStandaloneData = {
  contentFamily: PIXELRAG_CHINESE_STANDALONE_CONTENT_FAMILY,
  compositionId: PIXELRAG_CHINESE_STANDALONE_COMPOSITION_ID,
  fps: PIXELRAG_CHINESE_STANDALONE_FPS,
  height: PIXELRAG_CHINESE_STANDALONE_HEIGHT,
  profileId: PIXELRAG_CHINESE_STANDALONE_PROFILE_ID,
  scenes: [
    {
      accent: "#00d1ff",
      animationStyle: "tilt-rise",
      eyebrow: "开源项目",
      plainTitle: "先认识这个 GitHub 项目",
      points: ["PixelRAG"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-repo.png",
      secondaryAccent: "#ffb020",
      title: "PixelRAG",
      visualKind: "title-card",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-01-open.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "PixelRAG 是一个开源项目。",
            startFrame: 0,
            durationInFrames: 94,
          },
        ],
      },
      durationInFrames: 95,
      id: "pixelrag-zh-v3-01-open",
      narration: "PixelRAG 是一个开源项目。",
    },
    {
      accent: "#00d1ff",
      animationStyle: "flip-in",
      eyebrow: "核心差异",
      plainTitle: "网页画面也是信息",
      points: ["不是只读文字"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-repo.png",
      secondaryAccent: "#30d158",
      title: "让 AI 看网页",
      visualKind: "screenshot-card",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-02-see-web.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "它不只读文字，也看页面长相。",
            startFrame: 0,
            durationInFrames: 120,
          },
        ],
      },
      durationInFrames: 120,
      id: "pixelrag-zh-v3-02-see-web",
      narration: "它不只读文字，也看页面长相。",
    },
    {
      accent: "#ff6b4a",
      animationStyle: "whip-slide",
      eyebrow: "普通 RAG",
      plainTitle: "网页被压成文本",
      points: ["结构变平"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-repo.png",
      secondaryAccent: "#facc15",
      title: "只剩文字",
      visualKind: "text-crush",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-03-normal-rag.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "普通 RAG 常常先把页面压成文本。",
            startFrame: 0,
            durationInFrames: 125,
          },
        ],
      },
      durationInFrames: 126,
      id: "pixelrag-zh-v3-03-normal-rag",
      narration: "普通 RAG 常常先把页面压成文本。",
    },
    {
      accent: "#ff6b4a",
      animationStyle: "stack-pop",
      eyebrow: "丢了什么",
      plainTitle: "位置、关系、图表会变模糊",
      points: ["表格", "按钮", "图表"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-repo.png",
      secondaryAccent: "#7dd56f",
      title: "视觉线索",
      visualKind: "use-case-cards",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-04-lost-layout.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "表格、按钮、图表关系，",
            startFrame: 0,
            durationInFrames: 94,
          },
          {
            id: "cue-2",
            text: "很容易丢。",
            startFrame: 94,
            durationInFrames: 43,
          },
        ],
      },
      durationInFrames: 137,
      id: "pixelrag-zh-v3-04-lost-layout",
      narration: "表格、按钮、图表关系，很容易丢。",
    },
    {
      accent: "#7c5cff",
      animationStyle: "zoom-dive",
      eyebrow: "第一步",
      plainTitle: "先保留页面长相",
      points: ["网页截图"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#00d1ff",
      title: "先截图",
      visualKind: "screenshot-card",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-05-screenshot.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "PixelRAG 的第一步，",
            startFrame: 0,
            durationInFrames: 89,
          },
          {
            id: "cue-2",
            text: "是把网页截成图片。",
            startFrame: 89,
            durationInFrames: 57,
          },
        ],
      },
      durationInFrames: 146,
      id: "pixelrag-zh-v3-05-screenshot",
      narration: "PixelRAG 的第一步，是把网页截成图片。",
    },
    {
      accent: "#7c5cff",
      animationStyle: "slice-fan",
      eyebrow: "第二步",
      plainTitle: "把页面拆成更小证据",
      points: ["页面片段"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#ffb020",
      title: "切成片段",
      visualKind: "sliced-page",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-06-slices.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "再把图片切成更小的页面片段。",
            startFrame: 0,
            durationInFrames: 120,
          },
        ],
      },
      durationInFrames: 120,
      id: "pixelrag-zh-v3-06-slices",
      narration: "再把图片切成更小的页面片段。",
    },
    {
      accent: "#22d3ee",
      animationStyle: "cube-orbit",
      eyebrow: "第三步",
      plainTitle: "图片片段也能被搜索",
      points: ["视觉向量"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#a78bfa",
      title: "变成向量",
      visualKind: "vector-cubes",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-07-vector.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "每个片段，会变成视觉向量。",
            startFrame: 0,
            durationInFrames: 111,
          },
        ],
      },
      durationInFrames: 112,
      id: "pixelrag-zh-v3-07-vector",
      narration: "每个片段，会变成视觉向量。",
    },
    {
      accent: "#30d158",
      animationStyle: "index-deck",
      eyebrow: "第四步",
      plainTitle: "把向量放进索引",
      points: ["可检索"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#00d1ff",
      title: "建立索引",
      visualKind: "index-stack",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-08-index.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "这些向量被放进索引里。",
            startFrame: 0,
            durationInFrames: 94,
          },
        ],
      },
      durationInFrames: 95,
      id: "pixelrag-zh-v3-08-index",
      narration: "这些向量被放进索引里。",
    },
    {
      accent: "#ffb020",
      animationStyle: "result-pull",
      eyebrow: "搜索时",
      plainTitle: "先找回相关页面片段",
      points: ["问题", "片段"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#00d1ff",
      title: "找回证据",
      visualKind: "result-pull",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-09-query.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "提问时，系统会先找到相关页面片段。",
            startFrame: 0,
            durationInFrames: 146,
          },
        ],
      },
      durationInFrames: 146,
      id: "pixelrag-zh-v3-09-query",
      narration: "提问时，系统会先找到相关页面片段。",
    },
    {
      accent: "#ffb020",
      animationStyle: "flip-in",
      eyebrow: "回答时",
      plainTitle: "文字和画面一起参考",
      points: ["文本", "截图"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#30d158",
      title: "答案更接近页面",
      visualKind: "screenshot-card",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-10-answer.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "回答时，文字和画面一起参考。",
            startFrame: 0,
            durationInFrames: 120,
          },
        ],
      },
      durationInFrames: 120,
      id: "pixelrag-zh-v3-10-answer",
      narration: "回答时，文字和画面一起参考。",
    },
    {
      accent: "#30d158",
      animationStyle: "stack-pop",
      eyebrow: "适合场景",
      plainTitle: "网页问答、资料搜索、智能体",
      points: ["网页问答", "资料搜索", "智能体"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-readme.png",
      secondaryAccent: "#ffb020",
      title: "用在真实网页",
      visualKind: "use-case-cards",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-11-use.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "适合问答、搜索、智能体浏览。",
            startFrame: 0,
            durationInFrames: 120,
          },
        ],
      },
      durationInFrames: 120,
      id: "pixelrag-zh-v3-11-use",
      narration: "适合问答、搜索、智能体浏览。",
    },
    {
      accent: "#00d1ff",
      animationStyle: "zoom-dive",
      eyebrow: "一句话",
      plainTitle: "让 AI 不只读网页",
      points: ["真的看见网页"],
      screenshotFile: "generated/pixelrag-chinese-standalone/github-repo.png",
      secondaryAccent: "#ffb020",
      title: "看见网页",
      visualKind: "closing-card",
      audioFile: "generated/pixelrag-chinese-standalone/pixelrag-zh-v3-12-close.wav",
      captions: {
        language: "zh",
        cues: [
          {
            id: "cue-1",
            text: "简单说，PixelRAG 让 AI 真的看见网页。",
            startFrame: 0,
            durationInFrames: 140,
          },
        ],
      },
      durationInFrames: 140,
      id: "pixelrag-zh-v3-12-close",
      narration: "简单说，PixelRAG 让 AI 真的看见网页。",
    },
  ],
  title: "PixelRAG 中文开源项目介绍 V3",
  width: PIXELRAG_CHINESE_STANDALONE_WIDTH,
} satisfies PixelRAGChineseStandaloneData;
