// Auto-generated by scripts/generate-ai-daily-news-20260714-tts-clone.mjs
// Voice clone: LYY (high-fidelity clone_with_prompt)
// 2026-07-14T18:44:52.471Z

import type { AudioTrack } from "./types";

export const aiDailyNews20260714Audio: AudioTrack[] = [
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天 AI 行业的重心不在决定性的前沿大模型首发，",
          "startFrame": 0,
          "durationInFrames": 140
        },
        {
          "id": "caption-2",
          "text": "而在更系统的变化。",
          "startFrame": 140,
          "durationInFrames": 50
        },
        {
          "id": "caption-3",
          "text": "企业预算正在从传统软件转向 AI 基础设施，",
          "startFrame": 190,
          "durationInFrames": 123
        },
        {
          "id": "caption-4",
          "text": "数据中心开始遭遇电力与环保限制，",
          "startFrame": 313,
          "durationInFrames": 89
        },
        {
          "id": "caption-5",
          "text": "AI 搜索产品被要求为生成内容承担直接责任，",
          "startFrame": 402,
          "durationInFrames": 123
        },
        {
          "id": "caption-6",
          "text": "而资本继续涌向芯片、",
          "startFrame": 525,
          "durationInFrames": 56
        },
        {
          "id": "caption-7",
          "text": "垂直 Agent 和头部模型公司。",
          "startFrame": 581,
          "durationInFrames": 95
        },
        {
          "id": "caption-8",
          "text": "整个行业正在从模型能力竞赛，",
          "startFrame": 676,
          "durationInFrames": 78
        },
        {
          "id": "caption-9",
          "text": "进入电力、",
          "startFrame": 754,
          "durationInFrames": 28
        },
        {
          "id": "caption-10",
          "text": "芯片、",
          "startFrame": 782,
          "durationInFrames": 17
        },
        {
          "id": "caption-11",
          "text": "部署能力和监管责任的系统竞争。",
          "startFrame": 799,
          "durationInFrames": 84
        }
      ]
    },
    "durationInFrames": 883,
    "durationInSeconds": 29.44,
    "format": "wav",
    "narration": "今天 AI 行业的重心不在决定性的前沿大模型首发，而在更系统的变化。企业预算正在从传统软件转向 AI 基础设施，数据中心开始遭遇电力与环保限制，AI 搜索产品被要求为生成内容承担直接责任，而资本继续涌向芯片、垂直 Agent 和头部模型公司。整个行业正在从模型能力竞赛，进入电力、芯片、部署能力和监管责任的系统竞争。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "open"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/budget-shift.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "IBM 表示客户将部分预算从软件、",
          "startFrame": 0,
          "durationInFrames": 104
        },
        {
          "id": "caption-2",
          "text": "咨询和大型机转向 GPU 服务器、",
          "startFrame": 104,
          "durationInFrames": 104
        },
        {
          "id": "caption-3",
          "text": "存储和网络设备，",
          "startFrame": 208,
          "durationInFrames": 49
        },
        {
          "id": "caption-4",
          "text": "以提前锁定紧缺的 AI 基础设施。",
          "startFrame": 257,
          "durationInFrames": 104
        },
        {
          "id": "caption-5",
          "text": "多笔大型交易因此未能按期完成，",
          "startFrame": 361,
          "durationInFrames": 92
        },
        {
          "id": "caption-6",
          "text": "股价盘中一度下跌约百分之二十六。",
          "startFrame": 453,
          "durationInFrames": 98
        },
        {
          "id": "caption-7",
          "text": "与此同时，",
          "startFrame": 551,
          "durationInFrames": 31
        },
        {
          "id": "caption-8",
          "text": "台积电第二季度营收同比增长百分之三十六，",
          "startFrame": 582,
          "durationInFrames": 122
        },
        {
          "id": "caption-9",
          "text": "创历史新高，",
          "startFrame": 704,
          "durationInFrames": 37
        },
        {
          "id": "caption-10",
          "text": "预计净利润同比增长约百分之五十九，",
          "startFrame": 741,
          "durationInFrames": 104
        },
        {
          "id": "caption-11",
          "text": "连续第五个季度创纪录。",
          "startFrame": 845,
          "durationInFrames": 67
        },
        {
          "id": "caption-12",
          "text": "市场关注其是否将资本支出进一步上调。",
          "startFrame": 912,
          "durationInFrames": 110
        }
      ]
    },
    "durationInFrames": 1022,
    "durationInSeconds": 34.08,
    "format": "wav",
    "narration": "IBM 表示客户将部分预算从软件、咨询和大型机转向 GPU 服务器、存储和网络设备，以提前锁定紧缺的 AI 基础设施。多笔大型交易因此未能按期完成，股价盘中一度下跌约百分之二十六。与此同时，台积电第二季度营收同比增长百分之三十六，创历史新高，预计净利润同比增长约百分之五十九，连续第五个季度创纪录。市场关注其是否将资本支出进一步上调。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "budget-shift"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/perf-watt.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "NVIDIA 强调固定电力预算下能产生多少 Token，",
          "startFrame": 0,
          "durationInFrames": 149
        },
        {
          "id": "caption-2",
          "text": "这才是新的核心指标。",
          "startFrame": 149,
          "durationInFrames": 53
        },
        {
          "id": "caption-3",
          "text": "在部分 MoE 模型测试中，",
          "startFrame": 202,
          "durationInFrames": 74
        },
        {
          "id": "caption-4",
          "text": "GB300 NVL72 的每瓦性能可达 Hopper 平台的十到二十五倍。",
          "startFrame": 276,
          "durationInFrames": 197
        },
        {
          "id": "caption-5",
          "text": "同一天，",
          "startFrame": 473,
          "durationInFrames": 21
        },
        {
          "id": "caption-6",
          "text": "芯片创业公司 TYLsemi 完成四千三百万美元早期融资，",
          "startFrame": 494,
          "durationInFrames": 154
        },
        {
          "id": "caption-7",
          "text": "其方案将芯片拆分为可组合的芯粒，",
          "startFrame": 648,
          "durationInFrames": 85
        },
        {
          "id": "caption-8",
          "text": "宣称可将定制 AI 芯片开发成本降低接近一半。",
          "startFrame": 733,
          "durationInFrames": 122
        },
        {
          "id": "caption-9",
          "text": "技术竞争正从单卡算力，",
          "startFrame": 855,
          "durationInFrames": 58
        },
        {
          "id": "caption-10",
          "text": "转向每瓦收入、",
          "startFrame": 913,
          "durationInFrames": 37
        },
        {
          "id": "caption-11",
          "text": "每 Token 成本和芯片定制化。",
          "startFrame": 950,
          "durationInFrames": 92
        }
      ]
    },
    "durationInFrames": 1042,
    "durationInSeconds": 34.72,
    "format": "wav",
    "narration": "NVIDIA 强调固定电力预算下能产生多少 Token，这才是新的核心指标。在部分 MoE 模型测试中，GB300 NVL72 的每瓦性能可达 Hopper 平台的十到二十五倍。同一天，芯片创业公司 TYLsemi 完成四千三百万美元早期融资，其方案将芯片拆分为可组合的芯粒，宣称可将定制 AI 芯片开发成本降低接近一半。技术竞争正从单卡算力，转向每瓦收入、每 Token 成本和芯片定制化。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "perf-watt"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/legal-hallu.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "一项七月十三日发布的双语法律基准测试发现，",
          "startFrame": 0,
          "durationInFrames": 119
        },
        {
          "id": "caption-2",
          "text": "受测模型在 GDPR 条文查询上准确率达百分之九十四至一百，",
          "startFrame": 119,
          "durationInFrames": 170
        },
        {
          "id": "caption-3",
          "text": "但在资料稀缺的沙特数据保护法问题上，",
          "startFrame": 289,
          "durationInFrames": 102
        },
        {
          "id": "caption-4",
          "text": "错误引用或编造条文的比例达到百分之六十到七十七。",
          "startFrame": 391,
          "durationInFrames": 136
        },
        {
          "id": "caption-5",
          "text": "令人担忧的是，",
          "startFrame": 527,
          "durationInFrames": 40
        },
        {
          "id": "caption-6",
          "text": "百分之九十一的虚构引用仍然表现出不低于零点八的高置信度。",
          "startFrame": 567,
          "durationInFrames": 158
        },
        {
          "id": "caption-7",
          "text": "模型的自信程度，",
          "startFrame": 725,
          "durationInFrames": 45
        },
        {
          "id": "caption-8",
          "text": "不能作为可靠性依据。",
          "startFrame": 770,
          "durationInFrames": 56
        }
      ]
    },
    "durationInFrames": 826,
    "durationInSeconds": 27.52,
    "format": "wav",
    "narration": "一项七月十三日发布的双语法律基准测试发现，受测模型在 GDPR 条文查询上准确率达百分之九十四至一百，但在资料稀缺的沙特数据保护法问题上，错误引用或编造条文的比例达到百分之六十到七十七。令人担忧的是，百分之九十一的虚构引用仍然表现出不低于零点八的高置信度。模型的自信程度，不能作为可靠性依据。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "legal-hallu"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/regulation-wave.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "纽约州宣布对功率五十兆瓦及以上的新数据中心实施为期一年的建设禁令，",
          "startFrame": 0,
          "durationInFrames": 163
        },
        {
          "id": "caption-2",
          "text": "期间将制定统一的环境影响标准。",
          "startFrame": 163,
          "durationInFrames": 74
        },
        {
          "id": "caption-3",
          "text": "同一天，",
          "startFrame": 237,
          "durationInFrames": 20
        },
        {
          "id": "caption-4",
          "text": "德国媒体监管机构表示，",
          "startFrame": 257,
          "durationInFrames": 54
        },
        {
          "id": "caption-5",
          "text": "Google AI Overviews 和 Perplexity 生成的摘要属于服务提供者创建的内容，",
          "startFrame": 311,
          "durationInFrames": 252
        },
        {
          "id": "caption-6",
          "text": "因此可能需要直接为错误内容负责。",
          "startFrame": 563,
          "durationInFrames": 79
        },
        {
          "id": "caption-7",
          "text": "这改变了 AI 搜索的责任边界：",
          "startFrame": 642,
          "durationInFrames": 79
        },
        {
          "id": "caption-8",
          "text": "传统搜索提供链接，",
          "startFrame": 721,
          "durationInFrames": 44
        },
        {
          "id": "caption-9",
          "text": "AI 搜索生成答案，",
          "startFrame": 765,
          "durationInFrames": 49
        },
        {
          "id": "caption-10",
          "text": "平台可能成为内容发布者。",
          "startFrame": 814,
          "durationInFrames": 60
        }
      ]
    },
    "durationInFrames": 874,
    "durationInSeconds": 29.12,
    "format": "wav",
    "narration": "纽约州宣布对功率五十兆瓦及以上的新数据中心实施为期一年的建设禁令，期间将制定统一的环境影响标准。同一天，德国媒体监管机构表示，Google AI Overviews 和 Perplexity 生成的摘要属于服务提供者创建的内容，因此可能需要直接为错误内容负责。这改变了 AI 搜索的责任边界：传统搜索提供链接，AI 搜索生成答案，平台可能成为内容发布者。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "regulation-wave"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/governance.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "澳大利亚宣布在总理与内阁部内部设立 Office of AI，",
          "startFrame": 0,
          "durationInFrames": 154
        },
        {
          "id": "caption-2",
          "text": "统一协调不同政府部门的 AI 标准、",
          "startFrame": 154,
          "durationInFrames": 90
        },
        {
          "id": "caption-3",
          "text": "审批和监管。",
          "startFrame": 244,
          "durationInFrames": 30
        },
        {
          "id": "caption-4",
          "text": "目前该国尚无专门的综合 AI 法律。",
          "startFrame": 274,
          "durationInFrames": 90
        },
        {
          "id": "caption-5",
          "text": "与此同时，",
          "startFrame": 364,
          "durationInFrames": 25
        },
        {
          "id": "caption-6",
          "text": "Google DeepMind CEO Demis Hassabis 提议建立由美国主导、",
          "startFrame": 389,
          "durationInFrames": 224
        },
        {
          "id": "caption-7",
          "text": "行业出资的全球前沿 AI 测试机构，",
          "startFrame": 613,
          "durationInFrames": 90
        },
        {
          "id": "caption-8",
          "text": "在模型发布前进行网络、",
          "startFrame": 703,
          "durationInFrames": 55
        },
        {
          "id": "caption-9",
          "text": "生物和欺骗能力测试。",
          "startFrame": 758,
          "durationInFrames": 50
        },
        {
          "id": "caption-10",
          "text": "治理正在从分散的行业自律，",
          "startFrame": 808,
          "durationInFrames": 65
        },
        {
          "id": "caption-11",
          "text": "转向国家级的集中监管协调。",
          "startFrame": 873,
          "durationInFrames": 63
        }
      ]
    },
    "durationInFrames": 936,
    "durationInSeconds": 31.2,
    "format": "wav",
    "narration": "澳大利亚宣布在总理与内阁部内部设立 Office of AI，统一协调不同政府部门的 AI 标准、审批和监管。目前该国尚无专门的综合 AI 法律。与此同时，Google DeepMind CEO Demis Hassabis 提议建立由美国主导、行业出资的全球前沿 AI 测试机构，在模型发布前进行网络、生物和欺骗能力测试。治理正在从分散的行业自律，转向国家级的集中监管协调。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "governance"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/capital-flow.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "据路透社报道，",
          "startFrame": 0,
          "durationInFrames": 33
        },
        {
          "id": "caption-2",
          "text": "DeepSeek 新一轮融资讨论的投前估值约为七百一十亿美元，",
          "startFrame": 33,
          "durationInFrames": 148
        },
        {
          "id": "caption-3",
          "text": "并可能最快于二零二六年提交 IPO 申请。",
          "startFrame": 181,
          "durationInFrames": 100
        },
        {
          "id": "caption-4",
          "text": "面向中型企业的 AI 金融平台 Flex 完成七千万美元融资，",
          "startFrame": 281,
          "durationInFrames": 148
        },
        {
          "id": "caption-5",
          "text": "估值约十二亿美元，",
          "startFrame": 429,
          "durationInFrames": 43
        },
        {
          "id": "caption-6",
          "text": "较六个月前翻倍。",
          "startFrame": 472,
          "durationInFrames": 38
        },
        {
          "id": "caption-7",
          "text": "SoftBank CEO 孙正义预计，",
          "startFrame": 510,
          "durationInFrames": 91
        },
        {
          "id": "caption-8",
          "text": "到二零四零年全球 AI 投资需求可能达到每年五万亿美元。",
          "startFrame": 601,
          "durationInFrames": 134
        },
        {
          "id": "caption-9",
          "text": "资本正同时押注模型、",
          "startFrame": 735,
          "durationInFrames": 48
        },
        {
          "id": "caption-10",
          "text": "芯片和垂直 Agent，",
          "startFrame": 783,
          "durationInFrames": 57
        },
        {
          "id": "caption-11",
          "text": "但可闭环完成任务的业务系统才是真正的产品。",
          "startFrame": 840,
          "durationInFrames": 101
        }
      ]
    },
    "durationInFrames": 941,
    "durationInSeconds": 31.36,
    "format": "wav",
    "narration": "据路透社报道，DeepSeek 新一轮融资讨论的投前估值约为七百一十亿美元，并可能最快于二零二六年提交 IPO 申请。面向中型企业的 AI 金融平台 Flex 完成七千万美元融资，估值约十二亿美元，较六个月前翻倍。SoftBank CEO 孙正义预计，到二零四零年全球 AI 投资需求可能达到每年五万亿美元。资本正同时押注模型、芯片和垂直 Agent，但可闭环完成任务的业务系统才是真正的产品。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "capital-flow"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-14/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天的新闻给 Agent 开发者五个核心信号。",
          "startFrame": 0,
          "durationInFrames": 123
        },
        {
          "id": "caption-2",
          "text": "第一，",
          "startFrame": 123,
          "durationInFrames": 16
        },
        {
          "id": "caption-3",
          "text": "能否在有限 Token 和电力成本下长期运行。",
          "startFrame": 139,
          "durationInFrames": 123
        },
        {
          "id": "caption-4",
          "text": "第二，",
          "startFrame": 262,
          "durationInFrames": 16
        },
        {
          "id": "caption-5",
          "text": "能否验证每一次引用、",
          "startFrame": 278,
          "durationInFrames": 54
        },
        {
          "id": "caption-6",
          "text": "判断和外部操作。",
          "startFrame": 332,
          "durationInFrames": 43
        },
        {
          "id": "caption-7",
          "text": "第三，",
          "startFrame": 375,
          "durationInFrames": 16
        },
        {
          "id": "caption-8",
          "text": "能否接入真实业务系统并承担结果责任。",
          "startFrame": 391,
          "durationInFrames": 96
        },
        {
          "id": "caption-9",
          "text": "第四，",
          "startFrame": 487,
          "durationInFrames": 16
        },
        {
          "id": "caption-10",
          "text": "能否提供权限、",
          "startFrame": 503,
          "durationInFrames": 38
        },
        {
          "id": "caption-11",
          "text": "审计、",
          "startFrame": 541,
          "durationInFrames": 16
        },
        {
          "id": "caption-12",
          "text": "重试和人工接管机制。",
          "startFrame": 557,
          "durationInFrames": 54
        },
        {
          "id": "caption-13",
          "text": "第五，",
          "startFrame": 611,
          "durationInFrames": 16
        },
        {
          "id": "caption-14",
          "text": "能否把不稳定的模型能力包装成稳定可交付的服务。",
          "startFrame": 627,
          "durationInFrames": 123
        },
        {
          "id": "caption-15",
          "text": "面向 Agent 提供的 Skill、",
          "startFrame": 750,
          "durationInFrames": 102
        },
        {
          "id": "caption-16",
          "text": "工具服务、",
          "startFrame": 852,
          "durationInFrames": 27
        },
        {
          "id": "caption-17",
          "text": "执行验证和可靠性基础设施，",
          "startFrame": 879,
          "durationInFrames": 70
        },
        {
          "id": "caption-18",
          "text": "其商业价值正变得更加明确。",
          "startFrame": 949,
          "durationInFrames": 69
        }
      ]
    },
    "durationInFrames": 1018,
    "durationInSeconds": 33.92,
    "format": "wav",
    "narration": "今天的新闻给 Agent 开发者五个核心信号。第一，能否在有限 Token 和电力成本下长期运行。第二，能否验证每一次引用、判断和外部操作。第三，能否接入真实业务系统并承担结果责任。第四，能否提供权限、审计、重试和人工接管机制。第五，能否把不稳定的模型能力包装成稳定可交付的服务。面向 Agent 提供的 Skill、工具服务、执行验证和可靠性基础设施，其商业价值正变得更加明确。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "close"
  }
];
