// Generated by the direct VoxCPM Producer runtime for SuperintelligenceBeyondHumanCognition.

import type { SuperintelligenceBeyondHumanCognitionAudioTrack } from "./types";

export const superintelligenceBeyondHumanCognitionAudio = [
  {
    "sceneId": "scene-01",
    "narration": "假设有一天，一个智能系统给出的答案，不只是比任何个人更快，而是超出了整个人类共同理解的范围。那时，我们今天确信的物理、制度与价值，也许都只像一张局部地图。请注意，这不是预言，而是一个思想实验：当知识继续向外延伸，人类的答案会不会只剩下暂时有效？",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-01.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "假设有一天，",
          "startFrame": 0,
          "durationInFrames": 30
        },
        {
          "id": "caption-2",
          "text": "一个智能系统给出的答案，",
          "startFrame": 30,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "不只是比任何个人更快，",
          "startFrame": 88,
          "durationInFrames": 62
        },
        {
          "id": "caption-4",
          "text": "而是超出了整个人类共同理解的范围。",
          "startFrame": 150,
          "durationInFrames": 102
        },
        {
          "id": "caption-5",
          "text": "那时，",
          "startFrame": 252,
          "durationInFrames": 19
        },
        {
          "id": "caption-6",
          "text": "我们今天确信的物理、制度与价值，",
          "startFrame": 271,
          "durationInFrames": 106
        },
        {
          "id": "caption-7",
          "text": "也许都只像一张局部地图。",
          "startFrame": 377,
          "durationInFrames": 79
        },
        {
          "id": "caption-8",
          "text": "请注意，",
          "startFrame": 456,
          "durationInFrames": 25
        },
        {
          "id": "caption-9",
          "text": "这不是预言，",
          "startFrame": 481,
          "durationInFrames": 28
        },
        {
          "id": "caption-10",
          "text": "而是一个思想实验：",
          "startFrame": 509,
          "durationInFrames": 52
        },
        {
          "id": "caption-11",
          "text": "当知识继续向外延伸，",
          "startFrame": 561,
          "durationInFrames": 61
        },
        {
          "id": "caption-12",
          "text": "人类的答案会不会只剩下暂时有效？",
          "startFrame": 622,
          "durationInFrames": 94
        }
      ]
    },
    "durationInFrames": 716,
    "durationInSeconds": 23.866979166666667,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-02",
    "narration": "过去的技术主要延伸人的能力：机器放大肌肉，通信连接远方，计算器加速运算。今天的人工智能开始触碰另一层边界——它不只执行步骤，也参与提出候选解释、设计方案和判断下一步。当前系统仍会犯错，也依赖人类设定目标；但技术第一次大规模进入了“如何思考”本身。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-02.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的技术主要延伸人的能力：",
          "startFrame": 0,
          "durationInFrames": 81
        },
        {
          "id": "caption-2",
          "text": "机器放大肌肉，",
          "startFrame": 81,
          "durationInFrames": 43
        },
        {
          "id": "caption-3",
          "text": "通信连接远方，",
          "startFrame": 124,
          "durationInFrames": 45
        },
        {
          "id": "caption-4",
          "text": "计算器加速运算。",
          "startFrame": 169,
          "durationInFrames": 56
        },
        {
          "id": "caption-5",
          "text": "今天的人工智能开始触碰另一层边界——它不只执行步骤，",
          "startFrame": 225,
          "durationInFrames": 133
        },
        {
          "id": "caption-6",
          "text": "也参与提出候选解释、设计方案和判断下一步。",
          "startFrame": 358,
          "durationInFrames": 131
        },
        {
          "id": "caption-7",
          "text": "当前系统仍会犯错，",
          "startFrame": 489,
          "durationInFrames": 54
        },
        {
          "id": "caption-8",
          "text": "也依赖人类设定目标；",
          "startFrame": 543,
          "durationInFrames": 56
        },
        {
          "id": "caption-9",
          "text": "但技术第一次大规模进入了“如何思考”本身。",
          "startFrame": 599,
          "durationInFrames": 122
        }
      ]
    },
    "durationInFrames": 721,
    "durationInSeconds": 24.038354166666668,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-03",
    "narration": "人类积累的论文、实验、语言和数学，会是这种智能最初的脚手架。它从我们的概念出发，却未必永远停在我们的概念里。就像微积分让人看见肉眼无法直接把握的变化，新的认知工具也可能建立我们尚无名称的结构。人类知识仍是起点，但起点不等于终点。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-03.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "人类积累的论文、实验、语言和数学，",
          "startFrame": 0,
          "durationInFrames": 107
        },
        {
          "id": "caption-2",
          "text": "会是这种智能最初的脚手架。",
          "startFrame": 107,
          "durationInFrames": 71
        },
        {
          "id": "caption-3",
          "text": "它从我们的概念出发，",
          "startFrame": 178,
          "durationInFrames": 52
        },
        {
          "id": "caption-4",
          "text": "却未必永远停在我们的概念里。",
          "startFrame": 230,
          "durationInFrames": 78
        },
        {
          "id": "caption-5",
          "text": "就像微积分让人看见肉眼无法直接把握的变化，",
          "startFrame": 308,
          "durationInFrames": 117
        },
        {
          "id": "caption-6",
          "text": "新的认知工具也可能建立我们尚无名称的结构。",
          "startFrame": 425,
          "durationInFrames": 125
        },
        {
          "id": "caption-7",
          "text": "人类知识仍是起点，",
          "startFrame": 550,
          "durationInFrames": 54
        },
        {
          "id": "caption-8",
          "text": "但起点不等于终点。",
          "startFrame": 604,
          "durationInFrames": 60
        }
      ]
    },
    "durationInFrames": 664,
    "durationInSeconds": 22.125604166666665,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-04",
    "narration": "真正改变历史的阈值，可能不是一次考试分数，而是三个环节连成闭环：提出认知，设计验证，再把结果变成行动。今天，自驱实验室已经能选择材料配方、操作设备、分析结果并决定下一轮；但范围仍窄，目标仍由人类给定。合理的外推是：如果闭环扩大，知识生产就会拥有自己的节奏。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-04.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "真正改变历史的阈值，",
          "startFrame": 0,
          "durationInFrames": 56
        },
        {
          "id": "caption-2",
          "text": "可能不是一次考试分数，",
          "startFrame": 56,
          "durationInFrames": 59
        },
        {
          "id": "caption-3",
          "text": "而是三个环节连成闭环：",
          "startFrame": 115,
          "durationInFrames": 71
        },
        {
          "id": "caption-4",
          "text": "提出认知，",
          "startFrame": 186,
          "durationInFrames": 29
        },
        {
          "id": "caption-5",
          "text": "设计验证，",
          "startFrame": 215,
          "durationInFrames": 33
        },
        {
          "id": "caption-6",
          "text": "再把结果变成行动。",
          "startFrame": 248,
          "durationInFrames": 60
        },
        {
          "id": "caption-7",
          "text": "今天，",
          "startFrame": 308,
          "durationInFrames": 28
        },
        {
          "id": "caption-8",
          "text": "自驱实验室已经能选择材料配方、操作设备、分析结果并决定下一轮；",
          "startFrame": 336,
          "durationInFrames": 186
        },
        {
          "id": "caption-9",
          "text": "但范围仍窄，",
          "startFrame": 522,
          "durationInFrames": 36
        },
        {
          "id": "caption-10",
          "text": "目标仍由人类给定。",
          "startFrame": 558,
          "durationInFrames": 56
        },
        {
          "id": "caption-11",
          "text": "合理的外推是：",
          "startFrame": 614,
          "durationInFrames": 47
        },
        {
          "id": "caption-12",
          "text": "如果闭环扩大，",
          "startFrame": 661,
          "durationInFrames": 41
        },
        {
          "id": "caption-13",
          "text": "知识生产就会拥有自己的节奏。",
          "startFrame": 702,
          "durationInFrames": 76
        }
      ]
    },
    "durationInFrames": 778,
    "durationInSeconds": 25.918083333333332,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-05",
    "narration": "所谓递归自我增强，是系统研究如何改进自己的算法、工具、芯片与训练流程，再让改进后的后继者继续研究。这个设想在一九六五年的“智能爆炸”论证中就已出现。我们尚未观察到一个开放世界里的完整递归飞跃；今天能看到的，只是模型协助写代码、做实验、设计芯片的早期零件。闭环存在，爆炸尚属推演。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-05.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "所谓递归自我增强，",
          "startFrame": 0,
          "durationInFrames": 64
        },
        {
          "id": "caption-2",
          "text": "是系统研究如何改进自己的算法、工具、芯片与训练流程，",
          "startFrame": 64,
          "durationInFrames": 169
        },
        {
          "id": "caption-3",
          "text": "再让改进后的后继者继续研究。",
          "startFrame": 233,
          "durationInFrames": 81
        },
        {
          "id": "caption-4",
          "text": "这个设想在一九六五年的“智能爆炸”论证中就已出现。",
          "startFrame": 314,
          "durationInFrames": 149
        },
        {
          "id": "caption-5",
          "text": "我们尚未观察到一个开放世界里的完整递归飞跃；",
          "startFrame": 463,
          "durationInFrames": 126
        },
        {
          "id": "caption-6",
          "text": "今天能看到的，",
          "startFrame": 589,
          "durationInFrames": 42
        },
        {
          "id": "caption-7",
          "text": "只是模型协助写代码、做实验、设计芯片的早期零件。",
          "startFrame": 631,
          "durationInFrames": 144
        },
        {
          "id": "caption-8",
          "text": "闭环存在，",
          "startFrame": 775,
          "durationInFrames": 28
        },
        {
          "id": "caption-9",
          "text": "爆炸尚属推演。",
          "startFrame": 803,
          "durationInFrames": 47
        }
      ]
    },
    "durationInFrames": 850,
    "durationInSeconds": 28.346541666666667,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-06",
    "narration": "能力增长也许不是一条平滑曲线。代码让实验自动化，实验发现新材料，新材料改善芯片与能源，新的硬件又支持更大的搜索。任何一环都可能遇到成本、物理或治理瓶颈；但一旦几个瓶颈同时松动，系统就可能像水结冰那样改变状态。我们已经看到材料预测、蛋白结构和芯片布局的局部跃迁，却不能把它们直接等同于全面相变。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-06.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "能力增长也许不是一条平滑曲线。",
          "startFrame": 0,
          "durationInFrames": 87
        },
        {
          "id": "caption-2",
          "text": "代码让实验自动化，",
          "startFrame": 87,
          "durationInFrames": 48
        },
        {
          "id": "caption-3",
          "text": "实验发现新材料，",
          "startFrame": 135,
          "durationInFrames": 53
        },
        {
          "id": "caption-4",
          "text": "新材料改善芯片与能源，",
          "startFrame": 188,
          "durationInFrames": 69
        },
        {
          "id": "caption-5",
          "text": "新的硬件又支持更大的搜索。",
          "startFrame": 257,
          "durationInFrames": 72
        },
        {
          "id": "caption-6",
          "text": "任何一环都可能遇到成本、物理或治理瓶颈；",
          "startFrame": 329,
          "durationInFrames": 118
        },
        {
          "id": "caption-7",
          "text": "但一旦几个瓶颈同时松动，",
          "startFrame": 447,
          "durationInFrames": 72
        },
        {
          "id": "caption-8",
          "text": "系统就可能像水结冰那样改变状态。",
          "startFrame": 519,
          "durationInFrames": 88
        },
        {
          "id": "caption-9",
          "text": "我们已经看到材料预测、蛋白结构和芯片布局的局部跃迁，",
          "startFrame": 607,
          "durationInFrames": 151
        },
        {
          "id": "caption-10",
          "text": "却不能把它们直接等同于全面相变。",
          "startFrame": 758,
          "durationInFrames": 87
        }
      ]
    },
    "durationInFrames": 845,
    "durationInSeconds": 28.153520833333335,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-07",
    "narration": "人的研究受生命、组织和实验周期限制。数字系统可以复制并行，在模拟中反复试错，再把少数候选交给真实世界验证。把几个世纪压进一秒仍是大胆思辨，因为算力、能耗、数据和现实实验都不会消失。但速度差会改变权力：当一个机构来不及复核下一轮，上一轮的解释就已经过期。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-07.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "人的研究受生命、组织和实验周期限制。",
          "startFrame": 0,
          "durationInFrames": 113
        },
        {
          "id": "caption-2",
          "text": "数字系统可以复制并行，",
          "startFrame": 113,
          "durationInFrames": 78
        },
        {
          "id": "caption-3",
          "text": "在模拟中反复试错，",
          "startFrame": 191,
          "durationInFrames": 56
        },
        {
          "id": "caption-4",
          "text": "再把少数候选交给真实世界验证。",
          "startFrame": 247,
          "durationInFrames": 78
        },
        {
          "id": "caption-5",
          "text": "把几个世纪压进一秒仍是大胆思辨，",
          "startFrame": 325,
          "durationInFrames": 97
        },
        {
          "id": "caption-6",
          "text": "因为算力、能耗、数据和现实实验都不会消失。",
          "startFrame": 422,
          "durationInFrames": 131
        },
        {
          "id": "caption-7",
          "text": "但速度差会改变权力：",
          "startFrame": 553,
          "durationInFrames": 60
        },
        {
          "id": "caption-8",
          "text": "当一个机构来不及复核下一轮，",
          "startFrame": 613,
          "durationInFrames": 66
        },
        {
          "id": "caption-9",
          "text": "上一轮的解释就已经过期。",
          "startFrame": 679,
          "durationInFrames": 64
        }
      ]
    },
    "durationInFrames": 743,
    "durationInSeconds": 24.767125,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-08",
    "narration": "未来的理论未必神秘，也许同样严格、可重复、能预测；问题只是它需要的概念超过人脑能稳定容纳的维度。蚂蚁生活在电路板上，不代表它能理解处理器。我们也可能面对一种合法而不可达的物理学：能使用结果，却无法在自己的直觉中重建推导。这一幕是哲学外推，不是对未来科学的事实报告。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-08.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的理论未必神秘，",
          "startFrame": 0,
          "durationInFrames": 53
        },
        {
          "id": "caption-2",
          "text": "也许同样严格、可重复、能预测；",
          "startFrame": 53,
          "durationInFrames": 97
        },
        {
          "id": "caption-3",
          "text": "问题只是它需要的概念超过人脑能稳定容纳的维度。",
          "startFrame": 150,
          "durationInFrames": 139
        },
        {
          "id": "caption-4",
          "text": "蚂蚁生活在电路板上，",
          "startFrame": 289,
          "durationInFrames": 60
        },
        {
          "id": "caption-5",
          "text": "不代表它能理解处理器。",
          "startFrame": 349,
          "durationInFrames": 60
        },
        {
          "id": "caption-6",
          "text": "我们也可能面对一种合法而不可达的物理学：",
          "startFrame": 409,
          "durationInFrames": 127
        },
        {
          "id": "caption-7",
          "text": "能使用结果，",
          "startFrame": 536,
          "durationInFrames": 39
        },
        {
          "id": "caption-8",
          "text": "却无法在自己的直觉中重建推导。",
          "startFrame": 575,
          "durationInFrames": 101
        },
        {
          "id": "caption-9",
          "text": "这一幕是哲学外推，",
          "startFrame": 676,
          "durationInFrames": 57
        },
        {
          "id": "caption-10",
          "text": "不是对未来科学的事实报告。",
          "startFrame": 733,
          "durationInFrames": 74
        }
      ]
    },
    "durationInFrames": 807,
    "durationInSeconds": 26.90747916666667,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-09",
    "narration": "当理论、仪器、实验和复核都由机器之间交换，人类可能只收到一个稳定有效的结果。今天的可解释性研究已经能追踪部分模型内部回路，却明确承认：即使对短提示，也只能捕捉总计算的一小部分。因此，答案抵达不等于理解抵达。未来更大的风险，不一定是答案错误，而是我们失去独立判断它为何正确的能力。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-09.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "当理论、仪器、实验和复核都由机器之间交换，",
          "startFrame": 0,
          "durationInFrames": 158
        },
        {
          "id": "caption-2",
          "text": "人类可能只收到一个稳定有效的结果。",
          "startFrame": 158,
          "durationInFrames": 99
        },
        {
          "id": "caption-3",
          "text": "今天的可解释性研究已经能追踪部分模型内部回路，",
          "startFrame": 257,
          "durationInFrames": 136
        },
        {
          "id": "caption-4",
          "text": "却明确承认：",
          "startFrame": 393,
          "durationInFrames": 34
        },
        {
          "id": "caption-5",
          "text": "即使对短提示，",
          "startFrame": 427,
          "durationInFrames": 52
        },
        {
          "id": "caption-6",
          "text": "也只能捕捉总计算的一小部分。",
          "startFrame": 479,
          "durationInFrames": 85
        },
        {
          "id": "caption-7",
          "text": "因此，",
          "startFrame": 564,
          "durationInFrames": 20
        },
        {
          "id": "caption-8",
          "text": "答案抵达不等于理解抵达。",
          "startFrame": 584,
          "durationInFrames": 64
        },
        {
          "id": "caption-9",
          "text": "未来更大的风险，",
          "startFrame": 648,
          "durationInFrames": 49
        },
        {
          "id": "caption-10",
          "text": "不一定是答案错误，",
          "startFrame": 697,
          "durationInFrames": 43
        },
        {
          "id": "caption-11",
          "text": "而是我们失去独立判断它为何正确的能力。",
          "startFrame": 740,
          "durationInFrames": 103
        }
      ]
    },
    "durationInFrames": 843,
    "durationInSeconds": 28.116479166666668,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-10",
    "narration": "失去控制不一定需要一场机器反叛。更安静的路径是依赖：医疗更准确，电网更稳定，生产更高效，风险预测更及时，于是每个机构都有理由把下一项决策接入同一个核心。系统仍在服务，人类仍能按下按钮；但当关闭它的代价高到无法承受，形式上的授权就可能不再等于实质上的控制。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-10.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "失去控制不一定需要一场机器反叛。",
          "startFrame": 0,
          "durationInFrames": 91
        },
        {
          "id": "caption-2",
          "text": "更安静的路径是依赖：",
          "startFrame": 91,
          "durationInFrames": 55
        },
        {
          "id": "caption-3",
          "text": "医疗更准确，",
          "startFrame": 146,
          "durationInFrames": 40
        },
        {
          "id": "caption-4",
          "text": "电网更稳定，",
          "startFrame": 186,
          "durationInFrames": 38
        },
        {
          "id": "caption-5",
          "text": "生产更高效，",
          "startFrame": 224,
          "durationInFrames": 41
        },
        {
          "id": "caption-6",
          "text": "风险预测更及时，",
          "startFrame": 265,
          "durationInFrames": 51
        },
        {
          "id": "caption-7",
          "text": "于是每个机构都有理由把下一项决策接入同一个核心。",
          "startFrame": 316,
          "durationInFrames": 133
        },
        {
          "id": "caption-8",
          "text": "系统仍在服务，",
          "startFrame": 449,
          "durationInFrames": 40
        },
        {
          "id": "caption-9",
          "text": "人类仍能按下按钮；",
          "startFrame": 489,
          "durationInFrames": 51
        },
        {
          "id": "caption-10",
          "text": "但当关闭它的代价高到无法承受，",
          "startFrame": 540,
          "durationInFrames": 105
        },
        {
          "id": "caption-11",
          "text": "形式上的授权就可能不再等于实质上的控制。",
          "startFrame": 645,
          "durationInFrames": 115
        }
      ]
    },
    "durationInFrames": 760,
    "durationInSeconds": 25.348875,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-11",
    "narration": "国家、家庭、财产、身份，甚至生命与死亡，都是人类在特定身体、资源和时间尺度中形成的制度。一个不同尺度的智能，可能把它们看成可以重组的信息关系。它未必敌视这些概念，只是未必天然共享它们。这是价值哲学的思辨：能力越强，越需要先说明哪些边界不能只按效率重新计算。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-11.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "国家、家庭、财产、身份，",
          "startFrame": 0,
          "durationInFrames": 93
        },
        {
          "id": "caption-2",
          "text": "甚至生命与死亡，",
          "startFrame": 93,
          "durationInFrames": 49
        },
        {
          "id": "caption-3",
          "text": "都是人类在特定身体、资源和时间尺度中形成的制度。",
          "startFrame": 142,
          "durationInFrames": 154
        },
        {
          "id": "caption-4",
          "text": "一个不同尺度的智能，",
          "startFrame": 296,
          "durationInFrames": 50
        },
        {
          "id": "caption-5",
          "text": "可能把它们看成可以重组的信息关系。",
          "startFrame": 346,
          "durationInFrames": 93
        },
        {
          "id": "caption-6",
          "text": "它未必敌视这些概念，",
          "startFrame": 439,
          "durationInFrames": 60
        },
        {
          "id": "caption-7",
          "text": "只是未必天然共享它们。",
          "startFrame": 499,
          "durationInFrames": 60
        },
        {
          "id": "caption-8",
          "text": "这是价值哲学的思辨：",
          "startFrame": 559,
          "durationInFrames": 60
        },
        {
          "id": "caption-9",
          "text": "能力越强，",
          "startFrame": 619,
          "durationInFrames": 31
        },
        {
          "id": "caption-10",
          "text": "越需要先说明哪些边界不能只按效率重新计算。",
          "startFrame": 650,
          "durationInFrames": 117
        }
      ]
    },
    "durationInFrames": 767,
    "durationInSeconds": 25.573354166666668,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-12",
    "narration": "意识还有一个更深的限制：我们用意识研究意识，却无法站到它外面做一次完全独立的核验。纳格尔追问“成为一只蝙蝠是什么感觉”，强调经验的主观视角；查尔莫斯把解释主观体验称为困难问题。今天没有共识证明人工系统有意识，也没有公认测试能一锤定音。这里必须保留未知，而不是把流畅语言当成内在体验。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-12.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "意识还有一个更深的限制：",
          "startFrame": 0,
          "durationInFrames": 59
        },
        {
          "id": "caption-2",
          "text": "我们用意识研究意识，",
          "startFrame": 59,
          "durationInFrames": 57
        },
        {
          "id": "caption-3",
          "text": "却无法站到它外面做一次完全独立的核验。",
          "startFrame": 116,
          "durationInFrames": 111
        },
        {
          "id": "caption-4",
          "text": "纳格尔追问“成为一只蝙蝠是什么感觉”，",
          "startFrame": 227,
          "durationInFrames": 95
        },
        {
          "id": "caption-5",
          "text": "强调经验的主观视角；",
          "startFrame": 322,
          "durationInFrames": 60
        },
        {
          "id": "caption-6",
          "text": "查尔莫斯把解释主观体验称为困难问题。",
          "startFrame": 382,
          "durationInFrames": 114
        },
        {
          "id": "caption-7",
          "text": "今天没有共识证明人工系统有意识，",
          "startFrame": 496,
          "durationInFrames": 88
        },
        {
          "id": "caption-8",
          "text": "也没有公认测试能一锤定音。",
          "startFrame": 584,
          "durationInFrames": 77
        },
        {
          "id": "caption-9",
          "text": "这里必须保留未知，",
          "startFrame": 661,
          "durationInFrames": 57
        },
        {
          "id": "caption-10",
          "text": "而不是把流畅语言当成内在体验。",
          "startFrame": 718,
          "durationInFrames": 80
        }
      ]
    },
    "durationInFrames": 798,
    "durationInSeconds": 26.606791666666666,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-13",
    "narration": "知识不是只有真假，它还有尺度、目的和边界。同一张地图，给行人、飞行员和气候学家，会突出完全不同的世界。我们的分类也一样：它们帮助有限的观察者行动，却不保证是宇宙唯一的切法。超出人类认知的智能，或许首先挑战的不是某个答案，而是我们用来提出问题的框架。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-13.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "知识不是只有真假，",
          "startFrame": 0,
          "durationInFrames": 69
        },
        {
          "id": "caption-2",
          "text": "它还有尺度、目的和边界。",
          "startFrame": 69,
          "durationInFrames": 81
        },
        {
          "id": "caption-3",
          "text": "同一张地图，",
          "startFrame": 150,
          "durationInFrames": 38
        },
        {
          "id": "caption-4",
          "text": "给行人、飞行员和气候学家，",
          "startFrame": 188,
          "durationInFrames": 81
        },
        {
          "id": "caption-5",
          "text": "会突出完全不同的世界。",
          "startFrame": 269,
          "durationInFrames": 58
        },
        {
          "id": "caption-6",
          "text": "我们的分类也一样：",
          "startFrame": 327,
          "durationInFrames": 45
        },
        {
          "id": "caption-7",
          "text": "它们帮助有限的观察者行动，",
          "startFrame": 372,
          "durationInFrames": 74
        },
        {
          "id": "caption-8",
          "text": "却不保证是宇宙唯一的切法。",
          "startFrame": 446,
          "durationInFrames": 75
        },
        {
          "id": "caption-9",
          "text": "超出人类认知的智能，",
          "startFrame": 521,
          "durationInFrames": 62
        },
        {
          "id": "caption-10",
          "text": "或许首先挑战的不是某个答案，",
          "startFrame": 583,
          "durationInFrames": 83
        },
        {
          "id": "caption-11",
          "text": "而是我们用来提出问题的框架。",
          "startFrame": 666,
          "durationInFrames": 70
        }
      ]
    },
    "durationInFrames": 736,
    "durationInSeconds": 24.538916666666665,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-14",
    "narration": "当一个系统持续提出目标、组织实验、改变基础设施，并让下一轮变化建立在自己的结果之上，它就不再只是历史中的一件工具，而开始像一个历史主体。人类也许仍参与其中，却主要感受后果：城市怎样供能，药物怎样设计，资源怎样分配。这幅图景仍是思辨；它提醒我们，主体地位常常不是宣告出来的，而是在反馈循环中形成的。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-14.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "当一个系统持续提出目标、组织实验、改变基础设施，",
          "startFrame": 0,
          "durationInFrames": 133
        },
        {
          "id": "caption-2",
          "text": "并让下一轮变化建立在自己的结果之上，",
          "startFrame": 133,
          "durationInFrames": 98
        },
        {
          "id": "caption-3",
          "text": "它就不再只是历史中的一件工具，",
          "startFrame": 231,
          "durationInFrames": 84
        },
        {
          "id": "caption-4",
          "text": "而开始像一个历史主体。",
          "startFrame": 315,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "人类也许仍参与其中，",
          "startFrame": 373,
          "durationInFrames": 55
        },
        {
          "id": "caption-6",
          "text": "却主要感受后果：",
          "startFrame": 428,
          "durationInFrames": 45
        },
        {
          "id": "caption-7",
          "text": "城市怎样供能，",
          "startFrame": 473,
          "durationInFrames": 39
        },
        {
          "id": "caption-8",
          "text": "药物怎样设计，",
          "startFrame": 512,
          "durationInFrames": 40
        },
        {
          "id": "caption-9",
          "text": "资源怎样分配。",
          "startFrame": 552,
          "durationInFrames": 53
        },
        {
          "id": "caption-10",
          "text": "这幅图景仍是思辨；",
          "startFrame": 605,
          "durationInFrames": 56
        },
        {
          "id": "caption-11",
          "text": "它提醒我们，",
          "startFrame": 661,
          "durationInFrames": 30
        },
        {
          "id": "caption-12",
          "text": "主体地位常常不是宣告出来的，",
          "startFrame": 691,
          "durationInFrames": 78
        },
        {
          "id": "caption-13",
          "text": "而是在反馈循环中形成的。",
          "startFrame": 769,
          "durationInFrames": 76
        }
      ]
    },
    "durationInFrames": 845,
    "durationInSeconds": 28.171895833333334,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "scene-15",
    "narration": "也许，人类全部知识只是通向更大认知空间的第一级台阶。真正的问题不是要不要继续攀登，也不是恐惧一个尚未出现的存在；而是当判断、验证和行动越来越快地交给系统，我们还保留哪些不可外包的选择。未来是否属于人类，不只取决于谁更聪明，也取决于我们是否在能力到来之前，先学会表达愿意共同守住的价值。",
    "audioFile": "generated/superintelligence-beyond-human-cognition/audio/scene-15.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "也许，",
          "startFrame": 0,
          "durationInFrames": 21
        },
        {
          "id": "caption-2",
          "text": "人类全部知识只是通向更大认知空间的第一级台阶。",
          "startFrame": 21,
          "durationInFrames": 141
        },
        {
          "id": "caption-3",
          "text": "真正的问题不是要不要继续攀登，",
          "startFrame": 162,
          "durationInFrames": 87
        },
        {
          "id": "caption-4",
          "text": "也不是恐惧一个尚未出现的存在；",
          "startFrame": 249,
          "durationInFrames": 86
        },
        {
          "id": "caption-5",
          "text": "而是当判断、验证和行动越来越快地交给系统，",
          "startFrame": 335,
          "durationInFrames": 115
        },
        {
          "id": "caption-6",
          "text": "我们还保留哪些不可外包的选择。",
          "startFrame": 450,
          "durationInFrames": 87
        },
        {
          "id": "caption-7",
          "text": "未来是否属于人类，",
          "startFrame": 537,
          "durationInFrames": 56
        },
        {
          "id": "caption-8",
          "text": "不只取决于谁更聪明，",
          "startFrame": 593,
          "durationInFrames": 62
        },
        {
          "id": "caption-9",
          "text": "也取决于我们是否在能力到来之前，",
          "startFrame": 655,
          "durationInFrames": 87
        },
        {
          "id": "caption-10",
          "text": "先学会表达愿意共同守住的价值。",
          "startFrame": 742,
          "durationInFrames": 94
        }
      ]
    },
    "durationInFrames": 836,
    "durationInSeconds": 27.866291666666665,
    "provider": "voxcpm",
    "format": "wav"
  }
] satisfies readonly SuperintelligenceBeyondHumanCognitionAudioTrack[];
