import type { QualityGatedMaintainedProducerSampleManifest } from "../producer-samples/manifest";

const narrationAssetIds = Array.from(
  { length: 15 },
  (_, index) => `narration-scene-${String(index + 1).padStart(2, "0")}`,
);

export const superintelligenceBeyondHumanCognitionManifest = {
  sampleStatus: "maintained",
  compositionId: "SuperintelligenceBeyondHumanCognition",
  sampleName: "SuperintelligenceBeyondHumanCognition",
  slug: "superintelligence-beyond-human-cognition",
  contentFamily: "trend-briefing",
  canvasProfile: "portrait-9x16",
  styleProfileId: "cinematic-3d",
  localArtifactRoot: "public/generated/superintelligence-beyond-human-cognition/",
  ttsStatus: "generated-local",
  productionBrief: {
    audience: "General Chinese-speaking viewers without an AI or philosophy background.",
    publishingSurface: "Portrait mobile and social-video publishing surfaces.",
    durationTargetSeconds: 390,
  },
  narration: {
    required: true,
    provider: "voxcpm",
    mode: "high-fidelity-clone",
    scriptPath: "src/remotion/SuperintelligenceBeyondHumanCognition/script.ts",
    audioMetadataPath: "src/remotion/SuperintelligenceBeyondHumanCognition/audio.generated.ts",
  },
  assets: {
    manifestPath: "src/remotion/SuperintelligenceBeyondHumanCognition/assets.manifest.json",
  },
  soundDesign: {
    soundtrackModulePath: "src/remotion/SuperintelligenceBeyondHumanCognition/soundtrack.tsx",
    narrationAssetIds,
    bgmAssetIds: ["cinematic-bed"],
    ambienceAssetIds: ["spatial-air"],
    sfxAssetIds: ["chapter-bloom", "node-confirm", "phase-sweep", "historical-impact"],
  },
  validationModule: "src/remotion/SuperintelligenceBeyondHumanCognition/validation.ts",
  qualityModule: "src/remotion/SuperintelligenceBeyondHumanCognition/quality.ts",
  render: {
    metadataPath: "src/remotion/SuperintelligenceBeyondHumanCognition/render-metadata.json",
    cover16x9CompositionId: "SuperintelligenceBeyondHumanCognitionCover16x9",
    cover9x16CompositionId: "SuperintelligenceBeyondHumanCognitionCover9x16",
  },
  publishingCopyPath: "src/remotion/SuperintelligenceBeyondHumanCognition/publishing.md",
  reviewFrames: [
    { frame: 210, label: "scene-01-local-map", purpose: "Check opening sphere scale, title plane, and portrait caption safety." },
    { frame: 926, label: "scene-02-extended-cognition", purpose: "Check ability path hierarchy and settled cognition core." },
    { frame: 1647, label: "scene-03-knowledge-scaffold", purpose: "Check scaffold depth, constellation spacing, and readable copy." },
    { frame: 2103, label: "transition-chapter-ii", purpose: "Check chapter film-burn without blank or unsafe copy." },
    { frame: 2311, label: "scene-04-closed-loop", purpose: "Check cognition-validation-action loop closure and labels." },
    { frame: 3089, label: "scene-05-recursion", purpose: "Check nested successor hierarchy and reflective caption." },
    { frame: 3329, label: "dense-caption-recursion", purpose: "Check the densest recursive-self-improvement caption cue." },
    { frame: 3939, label: "scene-06-phase-change", purpose: "Check staircase depth, one focal step, and sound beat state." },
    { frame: 4784, label: "scene-07-time-compression", purpose: "Check outer clock, branching histories, and stable title." },
    { frame: 5319, label: "transition-chapter-iii", purpose: "Check chapter film-burn into cognitive-gap chapter." },
    { frame: 5527, label: "scene-08-inaccessible-physics", purpose: "Check unknown material geometry, symbols, and safe spacing." },
    { frame: 6334, label: "scene-09-opaque-science", purpose: "Check orbiting science loop and opaque result plane." },
    { frame: 7177, label: "scene-10-dependency", purpose: "Check infrastructure routing and core dominance." },
    { frame: 7729, label: "transition-chapter-iv", purpose: "Check chapter film-burn into value chapter." },
    { frame: 7937, label: "scene-11-value-labels", purpose: "Check detached value labels and central information body." },
    { frame: 8704, label: "scene-12-consciousness-mirror", purpose: "Check recursive observer mirrors and caption readability." },
    { frame: 9502, label: "scene-13-knowledge-frames", purpose: "Check scale-purpose-boundary nesting and focal hierarchy." },
    { frame: 10030, label: "transition-chapter-v", purpose: "Check final chapter film-burn and city-scale reveal." },
    { frame: 10238, label: "scene-14-historical-subject", purpose: "Check human-versus-city scale and historical-subject emphasis." },
    { frame: 11083, label: "scene-15-final-agency", purpose: "Check final path and agency question during narration." },
    { frame: 11679, label: "ending-settle", purpose: "Check the final settled question before narration ends, with no tail pause." },
  ],
  sourceFiles: [
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/SuperintelligenceBeyondHumanCognition.tsx", kind: "renderer" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/types.ts", kind: "types" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/script.ts", kind: "script" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/data.ts", kind: "data" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/audio.generated.ts", kind: "audio-metadata" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/manifest.ts", kind: "manifest" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/assets.manifest.json", kind: "asset-manifest" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/soundtrack.tsx", kind: "soundtrack" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/validation.ts", kind: "validation" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/quality.ts", kind: "quality" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/cover.tsx", kind: "cover" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/render-metadata.json", kind: "render-metadata" },
    { path: "src/remotion/SuperintelligenceBeyondHumanCognition/publishing.md", kind: "publishing-copy" },
    { path: "src/remotion/Root.tsx", kind: "root-registration" },
  ],
  promotionCandidates: [],
  notes: [
    "The film explicitly separates observed capabilities, plausible extrapolation, and philosophical speculation.",
    "All visual evidence is honest code-driven information graphics; seven reusable library searches returned no candidates.",
    "Private voice, narration, localized assets, review frames, covers, metadata, and MP4 remain local-only.",
  ],
} as const satisfies QualityGatedMaintainedProducerSampleManifest;
