// Generated by the direct VoxCPM Producer runtime for AiDaily20260720.

import type { AiDaily20260720AudioTrack } from "./types";

export const aiDaily20260720Audio = [
  {
    "sceneId": "open",
    "narration": "AI 日报，二零二六年七月二十日。截至北京时间二十三点五十六分。今天没有新的旗舰模型发布，真正的主线，是人工智能竞争正在从模型参数，扩展成模型、专用芯片、电力、运行容量和内容溯源的一体化竞争。决定产品能不能扩张的，越来越不是榜单分数，而是每一个 Token 的成本、可用算力，以及合规架构。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 日报，",
          "startFrame": 0,
          "durationInFrames": 28
        },
        {
          "id": "caption-2",
          "text": "二零二六年七月二十日。",
          "startFrame": 28,
          "durationInFrames": 92
        },
        {
          "id": "caption-3",
          "text": "截至北京时间二十三点五十六分。",
          "startFrame": 120,
          "durationInFrames": 91
        },
        {
          "id": "caption-4",
          "text": "今天没有新的旗舰模型发布，",
          "startFrame": 211,
          "durationInFrames": 82
        },
        {
          "id": "caption-5",
          "text": "真正的主线，",
          "startFrame": 293,
          "durationInFrames": 33
        },
        {
          "id": "caption-6",
          "text": "是人工智能竞争正在从模型参数，",
          "startFrame": 326,
          "durationInFrames": 96
        },
        {
          "id": "caption-7",
          "text": "扩展成模型、专用芯片、电力、运行容量和内容溯源的一体化竞争。",
          "startFrame": 422,
          "durationInFrames": 178
        },
        {
          "id": "caption-8",
          "text": "决定产品能不能扩张的，",
          "startFrame": 600,
          "durationInFrames": 73
        },
        {
          "id": "caption-9",
          "text": "越来越不是榜单分数，",
          "startFrame": 673,
          "durationInFrames": 46
        },
        {
          "id": "caption-10",
          "text": "而是每一个 Token 的成本、可用算力，",
          "startFrame": 719,
          "durationInFrames": 96
        },
        {
          "id": "caption-11",
          "text": "以及合规架构。",
          "startFrame": 815,
          "durationInFrames": 56
        }
      ]
    },
    "durationInFrames": 871,
    "durationInSeconds": 29.019791666666666,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "google",
    "narration": "先看 Google。据报道，Google 正开发代号 Frozen v2 的服务器芯片，尝试把 Gemini 的部分模型信息直接固化进硬件，而不是每次都从外部内存加载。项目独立于 TPU，最快可能在二零二八年部署。研发目标是按单位功耗计算，把 Token 服务效率提高到最新自研 AI 芯片的六到十倍。但它仍在设计阶段，具体固化多少模型信息、能否量产，都需要后续验证。方向很清楚：模型与硬件联合设计，换取更低延迟、功耗和 Token 成本；代价则是软硬件耦合更深，芯片周期可能追不上模型迭代。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/google.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "先看 Google。",
          "startFrame": 0,
          "durationInFrames": 28
        },
        {
          "id": "caption-2",
          "text": "据报道，",
          "startFrame": 28,
          "durationInFrames": 30
        },
        {
          "id": "caption-3",
          "text": "Google 正开发代号 Frozen v2 的服务器芯片，",
          "startFrame": 58,
          "durationInFrames": 108
        },
        {
          "id": "caption-4",
          "text": "尝试把 Gemini 的部分模型信息直接固化进硬件，",
          "startFrame": 166,
          "durationInFrames": 114
        },
        {
          "id": "caption-5",
          "text": "而不是每次都从外部内存加载。",
          "startFrame": 280,
          "durationInFrames": 76
        },
        {
          "id": "caption-6",
          "text": "项目独立于 TPU，",
          "startFrame": 356,
          "durationInFrames": 53
        },
        {
          "id": "caption-7",
          "text": "最快可能在二零二八年部署。",
          "startFrame": 409,
          "durationInFrames": 57
        },
        {
          "id": "caption-8",
          "text": "研发目标是按单位功耗计算，",
          "startFrame": 466,
          "durationInFrames": 77
        },
        {
          "id": "caption-9",
          "text": "把 Token 服务效率提高到最新自研 AI 芯片的六到十倍。",
          "startFrame": 543,
          "durationInFrames": 115
        },
        {
          "id": "caption-10",
          "text": "但它仍在设计阶段，",
          "startFrame": 658,
          "durationInFrames": 42
        },
        {
          "id": "caption-11",
          "text": "具体固化多少模型信息、能否量产，",
          "startFrame": 700,
          "durationInFrames": 93
        },
        {
          "id": "caption-12",
          "text": "都需要后续验证。",
          "startFrame": 793,
          "durationInFrames": 35
        },
        {
          "id": "caption-13",
          "text": "方向很清楚：",
          "startFrame": 828,
          "durationInFrames": 42
        },
        {
          "id": "caption-14",
          "text": "模型与硬件联合设计，",
          "startFrame": 870,
          "durationInFrames": 49
        },
        {
          "id": "caption-15",
          "text": "换取更低延迟、功耗和 Token 成本；",
          "startFrame": 919,
          "durationInFrames": 106
        },
        {
          "id": "caption-16",
          "text": "代价则是软硬件耦合更深，",
          "startFrame": 1025,
          "durationInFrames": 72
        },
        {
          "id": "caption-17",
          "text": "芯片周期可能追不上模型迭代。",
          "startFrame": 1097,
          "durationInFrames": 94
        }
      ]
    },
    "durationInFrames": 1191,
    "durationInSeconds": 39.716229166666665,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "nvidia",
    "narration": "第二个信号来自 NVIDIA。Omniverse 库被加入 Agent Toolkit，开放 RTX 传感器模拟、GPU 物理模拟和 CAD 到 SimReady 等组件。Agent 可以检查三维场景、发现资产问题、添加碰撞、质量和摩擦属性，还能把普通 CAD 转成机器人训练所需的 OpenUSD 仿真资产。这意味着 Agent 不再只操作代码、文档和浏览器，也开始进入数字孪生、工业设计和机器人训练环境。软件执行器，正在变成能参与构建物理世界模型的运行主体。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/nvidia.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "第二个信号来自 NVIDIA。",
          "startFrame": 0,
          "durationInFrames": 56
        },
        {
          "id": "caption-2",
          "text": "Omniverse 库被加入 Agent Toolkit，",
          "startFrame": 56,
          "durationInFrames": 81
        },
        {
          "id": "caption-3",
          "text": "开放 RTX 传感器模拟、GPU 物理模拟和 CAD 到 SimReady 等组件。",
          "startFrame": 137,
          "durationInFrames": 169
        },
        {
          "id": "caption-4",
          "text": "Agent 可以检查三维场景、发现资产问题、添加碰撞、质量和摩擦属性，",
          "startFrame": 306,
          "durationInFrames": 197
        },
        {
          "id": "caption-5",
          "text": "还能把普通 CAD 转成机器人训练所需的 OpenUSD 仿真资产。",
          "startFrame": 503,
          "durationInFrames": 163
        },
        {
          "id": "caption-6",
          "text": "这意味着 Agent 不再只操作代码、文档和浏览器，",
          "startFrame": 666,
          "durationInFrames": 148
        },
        {
          "id": "caption-7",
          "text": "也开始进入数字孪生、工业设计和机器人训练环境。",
          "startFrame": 814,
          "durationInFrames": 127
        },
        {
          "id": "caption-8",
          "text": "软件执行器，",
          "startFrame": 941,
          "durationInFrames": 34
        },
        {
          "id": "caption-9",
          "text": "正在变成能参与构建物理世界模型的运行主体。",
          "startFrame": 975,
          "durationInFrames": 104
        }
      ]
    },
    "durationInFrames": 1079,
    "durationInSeconds": 35.9746875,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "kimi",
    "narration": "再看 Kimi K3。Moonshot AI 表示，发布后四十八小时内请求量远超预测，接近现有计算集群上限，因此暂停新的消费者订阅，并优先保障现有付费用户。K3 总参数量二点八万亿，重点面向编程和 Agent 长任务。这类任务需要多轮调用、工具执行和结果验证，单位用户消耗远高于普通聊天。它揭示了一个现实：模型权重可以开放，但要大规模、低价格、稳定地提供推理服务，仍然需要昂贵的 GPU、电力和调度系统。模型发布能力，不等于服务交付能力。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/kimi.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "再看 Kimi K3。",
          "startFrame": 0,
          "durationInFrames": 42
        },
        {
          "id": "caption-2",
          "text": "Moonshot AI 表示，",
          "startFrame": 42,
          "durationInFrames": 73
        },
        {
          "id": "caption-3",
          "text": "发布后四十八小时内请求量远超预测，",
          "startFrame": 115,
          "durationInFrames": 101
        },
        {
          "id": "caption-4",
          "text": "接近现有计算集群上限，",
          "startFrame": 216,
          "durationInFrames": 67
        },
        {
          "id": "caption-5",
          "text": "因此暂停新的消费者订阅，",
          "startFrame": 283,
          "durationInFrames": 80
        },
        {
          "id": "caption-6",
          "text": "并优先保障现有付费用户。",
          "startFrame": 363,
          "durationInFrames": 72
        },
        {
          "id": "caption-7",
          "text": "K3 总参数量二点八万亿，",
          "startFrame": 435,
          "durationInFrames": 74
        },
        {
          "id": "caption-8",
          "text": "重点面向编程和 Agent 长任务。",
          "startFrame": 509,
          "durationInFrames": 82
        },
        {
          "id": "caption-9",
          "text": "这类任务需要多轮调用、工具执行和结果验证，",
          "startFrame": 591,
          "durationInFrames": 115
        },
        {
          "id": "caption-10",
          "text": "单位用户消耗远高于普通聊天。",
          "startFrame": 706,
          "durationInFrames": 91
        },
        {
          "id": "caption-11",
          "text": "它揭示了一个现实：",
          "startFrame": 797,
          "durationInFrames": 41
        },
        {
          "id": "caption-12",
          "text": "模型权重可以开放，",
          "startFrame": 838,
          "durationInFrames": 53
        },
        {
          "id": "caption-13",
          "text": "但要大规模、低价格、稳定地提供推理服务，",
          "startFrame": 891,
          "durationInFrames": 115
        },
        {
          "id": "caption-14",
          "text": "仍然需要昂贵的 GPU、电力和调度系统。",
          "startFrame": 1006,
          "durationInFrames": 106
        },
        {
          "id": "caption-15",
          "text": "模型发布能力，",
          "startFrame": 1112,
          "durationInFrames": 45
        },
        {
          "id": "caption-16",
          "text": "不等于服务交付能力。",
          "startFrame": 1157,
          "durationInFrames": 60
        }
      ]
    },
    "durationInFrames": 1217,
    "durationInSeconds": 40.55952083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "science",
    "narration": "AI for Science 也在从演示走向闭环。Bristol Myers Squibb 将采购基于 NVIDIA Vera Rubin 的 DGX SuperPOD，用于药物靶点发现、候选筛选和临床开发。公司称，现有 AI 工具已把部分实验药物制备周期缩短约百分之二十到三十，但实际效果仍需药物管线验证。材料领域，英国 CuspAI 完成四点五亿美元 B 轮融资，并组织超过四十五家机构参与 AI Materials Foundry。竞争重点已经从模型能否提出假设，升级为能否把假设推进到仿真、合成路线和真实实验。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/science.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI for Science 也在从演示走向闭环。",
          "startFrame": 0,
          "durationInFrames": 100
        },
        {
          "id": "caption-2",
          "text": "Bristol Myers Squibb 将采购基于 NVIDIA Vera Rubin 的 DGX SuperPOD，",
          "startFrame": 100,
          "durationInFrames": 195
        },
        {
          "id": "caption-3",
          "text": "用于药物靶点发现、候选筛选和临床开发。",
          "startFrame": 295,
          "durationInFrames": 120
        },
        {
          "id": "caption-4",
          "text": "公司称，",
          "startFrame": 415,
          "durationInFrames": 27
        },
        {
          "id": "caption-5",
          "text": "现有 AI 工具已把部分实验药物制备周期缩短约百分之二十到三十，",
          "startFrame": 442,
          "durationInFrames": 172
        },
        {
          "id": "caption-6",
          "text": "但实际效果仍需药物管线验证。",
          "startFrame": 614,
          "durationInFrames": 91
        },
        {
          "id": "caption-7",
          "text": "材料领域，",
          "startFrame": 705,
          "durationInFrames": 24
        },
        {
          "id": "caption-8",
          "text": "英国 CuspAI 完成四点五亿美元 B 轮融资，",
          "startFrame": 729,
          "durationInFrames": 125
        },
        {
          "id": "caption-9",
          "text": "并组织超过四十五家机构参与 AI Materials Foundry。",
          "startFrame": 854,
          "durationInFrames": 107
        },
        {
          "id": "caption-10",
          "text": "竞争重点已经从模型能否提出假设，",
          "startFrame": 961,
          "durationInFrames": 106
        },
        {
          "id": "caption-11",
          "text": "升级为能否把假设推进到仿真、合成路线和真实实验。",
          "startFrame": 1067,
          "durationInFrames": 132
        }
      ]
    },
    "durationInFrames": 1199,
    "durationInSeconds": 39.9706875,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "regulation",
    "narration": "政策方面，欧盟委员会发布人工智能法案第五十条透明度义务指南，相关义务从二零二六年八月二日开始适用。提供者需要告知用户正在与 AI 交互，并为 AI 生成或修改的文本、音频、图像和视频添加机器可读取的标记。部署企业还需要披露 Deepfake、未经人工审查的公共利益类 AI 文本、情绪识别和生物特征分类。行为准则可以自愿加入，但透明度要求本身是法律义务。工程上，水印、来源、人工编辑记录和生成链路，必须进入内容存储、导出和分发架构，而不只是界面上的一个标签。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/regulation.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "政策方面，",
          "startFrame": 0,
          "durationInFrames": 38
        },
        {
          "id": "caption-2",
          "text": "欧盟委员会发布人工智能法案第五十条透明度义务指南，",
          "startFrame": 38,
          "durationInFrames": 146
        },
        {
          "id": "caption-3",
          "text": "相关义务从二零二六年八月二日开始适用。",
          "startFrame": 184,
          "durationInFrames": 115
        },
        {
          "id": "caption-4",
          "text": "提供者需要告知用户正在与 AI 交互，",
          "startFrame": 299,
          "durationInFrames": 101
        },
        {
          "id": "caption-5",
          "text": "并为 AI 生成或修改的文本、音频、图像和视频添加机器可读取的标记。",
          "startFrame": 400,
          "durationInFrames": 216
        },
        {
          "id": "caption-6",
          "text": "部署企业还需要披露 Deepfake、未经人工审查的公共利益类 AI 文本、情绪识别和生物特征分类。",
          "startFrame": 616,
          "durationInFrames": 228
        },
        {
          "id": "caption-7",
          "text": "行为准则可以自愿加入，",
          "startFrame": 844,
          "durationInFrames": 72
        },
        {
          "id": "caption-8",
          "text": "但透明度要求本身是法律义务。",
          "startFrame": 916,
          "durationInFrames": 91
        },
        {
          "id": "caption-9",
          "text": "工程上，",
          "startFrame": 1007,
          "durationInFrames": 38
        },
        {
          "id": "caption-10",
          "text": "水印、来源、人工编辑记录和生成链路，",
          "startFrame": 1045,
          "durationInFrames": 122
        },
        {
          "id": "caption-11",
          "text": "必须进入内容存储、导出和分发架构，",
          "startFrame": 1167,
          "durationInFrames": 109
        },
        {
          "id": "caption-12",
          "text": "而不只是界面上的一个标签。",
          "startFrame": 1276,
          "durationInFrames": 67
        }
      ]
    },
    "durationInFrames": 1343,
    "durationInSeconds": 44.755833333333335,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "power",
    "narration": "资本正在给电力和土地重新定价。Hut 8 签署第二份十五年、价值九十八亿美元的 AI 数据中心租约，使得州 Beacon Point 一吉瓦园区全部完成商业化。新协议增加三百五十二兆瓦 IT 容量，该客户在园区的总容量达到七百零四兆瓦。基础租期合同总值达到一百九十六亿美元。拥有电力接入和可立即建设土地的旧矿企，正在转型为 AI 基础设施供应商。算力竞争，进一步变成电力、土地和交付时间的竞争。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/power.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "资本正在给电力和土地重新定价。",
          "startFrame": 0,
          "durationInFrames": 104
        },
        {
          "id": "caption-2",
          "text": "Hut 8 签署第二份十五年、价值九十八亿美元的 AI 数据中心租约，",
          "startFrame": 104,
          "durationInFrames": 147
        },
        {
          "id": "caption-3",
          "text": "使得州 Beacon Point 一吉瓦园区全部完成商业化。",
          "startFrame": 251,
          "durationInFrames": 144
        },
        {
          "id": "caption-4",
          "text": "新协议增加三百五十二兆瓦 IT 容量，",
          "startFrame": 395,
          "durationInFrames": 85
        },
        {
          "id": "caption-5",
          "text": "该客户在园区的总容量达到七百零四兆瓦。",
          "startFrame": 480,
          "durationInFrames": 108
        },
        {
          "id": "caption-6",
          "text": "基础租期合同总值达到一百九十六亿美元。",
          "startFrame": 588,
          "durationInFrames": 113
        },
        {
          "id": "caption-7",
          "text": "拥有电力接入和可立即建设土地的旧矿企，",
          "startFrame": 701,
          "durationInFrames": 110
        },
        {
          "id": "caption-8",
          "text": "正在转型为 AI 基础设施供应商。",
          "startFrame": 811,
          "durationInFrames": 94
        },
        {
          "id": "caption-9",
          "text": "算力竞争，",
          "startFrame": 905,
          "durationInFrames": 35
        },
        {
          "id": "caption-10",
          "text": "进一步变成电力、土地和交付时间的竞争。",
          "startFrame": 940,
          "durationInFrames": 125
        }
      ]
    },
    "durationInFrames": 1065,
    "durationInSeconds": 35.5155625,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "signals",
    "narration": "把今天的信号放在一起：专用芯片追求效率，Kimi 暴露容量瓶颈，电力资产被长期锁定，制药和材料建立实验闭环，医疗并购争夺数据入口，欧盟则把内容标记变成法律义务。它们共同指向同一件事：AI 产品的上限，正由效率、容量、能源、数据和合规组成的完整系统决定。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/signals.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "把今天的信号放在一起：",
          "startFrame": 0,
          "durationInFrames": 47
        },
        {
          "id": "caption-2",
          "text": "专用芯片追求效率，",
          "startFrame": 47,
          "durationInFrames": 60
        },
        {
          "id": "caption-3",
          "text": "Kimi 暴露容量瓶颈，",
          "startFrame": 107,
          "durationInFrames": 61
        },
        {
          "id": "caption-4",
          "text": "电力资产被长期锁定，",
          "startFrame": 168,
          "durationInFrames": 65
        },
        {
          "id": "caption-5",
          "text": "制药和材料建立实验闭环，",
          "startFrame": 233,
          "durationInFrames": 63
        },
        {
          "id": "caption-6",
          "text": "医疗并购争夺数据入口，",
          "startFrame": 296,
          "durationInFrames": 64
        },
        {
          "id": "caption-7",
          "text": "欧盟则把内容标记变成法律义务。",
          "startFrame": 360,
          "durationInFrames": 95
        },
        {
          "id": "caption-8",
          "text": "它们共同指向同一件事：",
          "startFrame": 455,
          "durationInFrames": 67
        },
        {
          "id": "caption-9",
          "text": "AI 产品的上限，",
          "startFrame": 522,
          "durationInFrames": 42
        },
        {
          "id": "caption-10",
          "text": "正由效率、容量、能源、数据和合规组成的完整系统决定。",
          "startFrame": 564,
          "durationInFrames": 165
        }
      ]
    },
    "durationInFrames": 729,
    "durationInSeconds": 24.2893125,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "close",
    "narration": "对 Agent 开发者，行动清单有六项：算力预算和限流；跨模型、跨硬件路由；长任务恢复和重试；工具与内容来源记录；机器可读标记；以及仿真到真实执行的验证闭环。下一阶段的 Agent，不只会调用工具，还要在资源受限、过程可追溯、结果可验证的系统里持续运行。这就是今天的 AI 日报。",
    "audioFile": "generated/ai-daily-2026-07-20/audio/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "对 Agent 开发者，",
          "startFrame": 0,
          "durationInFrames": 43
        },
        {
          "id": "caption-2",
          "text": "行动清单有六项：",
          "startFrame": 43,
          "durationInFrames": 42
        },
        {
          "id": "caption-3",
          "text": "算力预算和限流；",
          "startFrame": 85,
          "durationInFrames": 57
        },
        {
          "id": "caption-4",
          "text": "跨模型、跨硬件路由；",
          "startFrame": 142,
          "durationInFrames": 74
        },
        {
          "id": "caption-5",
          "text": "长任务恢复和重试；",
          "startFrame": 216,
          "durationInFrames": 123
        },
        {
          "id": "caption-6",
          "text": "工具与内容来源记录；",
          "startFrame": 339,
          "durationInFrames": 96
        },
        {
          "id": "caption-7",
          "text": "机器可读标记；",
          "startFrame": 435,
          "durationInFrames": 43
        },
        {
          "id": "caption-8",
          "text": "以及仿真到真实执行的验证闭环。",
          "startFrame": 478,
          "durationInFrames": 113
        },
        {
          "id": "caption-9",
          "text": "下一阶段的 Agent，",
          "startFrame": 591,
          "durationInFrames": 34
        },
        {
          "id": "caption-10",
          "text": "不只会调用工具，",
          "startFrame": 625,
          "durationInFrames": 42
        },
        {
          "id": "caption-11",
          "text": "还要在资源受限、过程可追溯、结果可验证的系统里持续运行。",
          "startFrame": 667,
          "durationInFrames": 163
        },
        {
          "id": "caption-12",
          "text": "这就是今天的 AI 日报。",
          "startFrame": 830,
          "durationInFrames": 77
        }
      ]
    },
    "durationInFrames": 907,
    "durationInSeconds": 30.231708333333334,
    "provider": "voxcpm",
    "format": "wav"
  }
] satisfies readonly AiDaily20260720AudioTrack[];
