// Generated by the direct VoxCPM Producer runtime for AiDaily20260721.

import type { AiDaily20260721AudioTrack } from "./types";

export const aiDaily20260721Audio = [
  {
    "sceneId": "open",
    "narration": "AI 日报，二零二六年七月二十一日。今天没有跨代旗舰模型发布，但产业方向非常清晰。模型竞争正从单纯追求最强能力，转向低成本专用模型、主权 AI、物理 AI、Agent 交易基础设施和数据中心容量。Google 推出三款轻量 Gemini 却继续推迟旗舰，微软通过数十亿美元协议购买 Mistral 的欧洲算力，BlackRock 与 MGX 则将数百亿美元投入数据中心。AI 的竞争单位，正在从模型扩大为模型、算力、数据主权和实际部署。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 日报，",
          "startFrame": 0,
          "durationInFrames": 31
        },
        {
          "id": "caption-2",
          "text": "二零二六年七月二十一日。",
          "startFrame": 31,
          "durationInFrames": 74
        },
        {
          "id": "caption-3",
          "text": "今天没有跨代旗舰模型发布，",
          "startFrame": 105,
          "durationInFrames": 82
        },
        {
          "id": "caption-4",
          "text": "但产业方向非常清晰。",
          "startFrame": 187,
          "durationInFrames": 63
        },
        {
          "id": "caption-5",
          "text": "模型竞争正从单纯追求最强能力，",
          "startFrame": 250,
          "durationInFrames": 96
        },
        {
          "id": "caption-6",
          "text": "转向低成本专用模型、主权 AI、物理 AI、Agent 交易基础设施和数据中心容量。",
          "startFrame": 346,
          "durationInFrames": 215
        },
        {
          "id": "caption-7",
          "text": "Google 推出三款轻量 Gemini 却继续推迟旗舰，",
          "startFrame": 561,
          "durationInFrames": 118
        },
        {
          "id": "caption-8",
          "text": "微软通过数十亿美元协议购买 Mistral 的欧洲算力，",
          "startFrame": 679,
          "durationInFrames": 126
        },
        {
          "id": "caption-9",
          "text": "BlackRock 与 MGX 则将数百亿美元投入数据中心。",
          "startFrame": 805,
          "durationInFrames": 153
        },
        {
          "id": "caption-10",
          "text": "AI 的竞争单位，",
          "startFrame": 958,
          "durationInFrames": 37
        },
        {
          "id": "caption-11",
          "text": "正在从模型扩大为模型、算力、数据主权和实际部署。",
          "startFrame": 995,
          "durationInFrames": 154
        }
      ]
    },
    "durationInFrames": 1149,
    "durationInSeconds": 38.298791666666666,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "google",
    "narration": "先看 Google。今天发布了三款轻量 Gemini 模型。Gemini 3.6 Flash 面向高频低延迟通用任务。Gemini 3.5 Flash-Lite 主打更低成本的大规模推理。而 Gemini 3.5 Flash Cyber 是专门针对网络安全场景的模型。备受关注的 Gemini 3.5 Pro 仍停留在合作伙伴测试阶段，原计划六月发布，延期压力主要来自编码和 Agent 任务。Google 同时确认已开始训练 Gemini 4。大模型市场正在形成两条路线：旗舰模型负责复杂推理编码和前沿能力，轻量模型负责高并发低延迟和低成本专用任务。企业最终不会为所有请求调用最强模型，而是通过模型路由，把大部分任务分配给更便宜的 Flash 或 Mini 类模型。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/google.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "先看 Google。",
          "startFrame": 0,
          "durationInFrames": 33
        },
        {
          "id": "caption-2",
          "text": "今天发布了三款轻量 Gemini 模型。",
          "startFrame": 33,
          "durationInFrames": 89
        },
        {
          "id": "caption-3",
          "text": "Gemini 3.6 Flash 面向高频低延迟通用任务。",
          "startFrame": 122,
          "durationInFrames": 128
        },
        {
          "id": "caption-4",
          "text": "Gemini 3.5 Flash-Lite 主打更低成本的大规模推理。",
          "startFrame": 250,
          "durationInFrames": 142
        },
        {
          "id": "caption-5",
          "text": "而 Gemini 3.5 Flash Cyber 是专门针对网络安全场景的模型。",
          "startFrame": 392,
          "durationInFrames": 159
        },
        {
          "id": "caption-6",
          "text": "备受关注的 Gemini 3.5 Pro 仍停留在合作伙伴测试阶段，",
          "startFrame": 551,
          "durationInFrames": 153
        },
        {
          "id": "caption-7",
          "text": "原计划六月发布，",
          "startFrame": 704,
          "durationInFrames": 41
        },
        {
          "id": "caption-8",
          "text": "延期压力主要来自编码和 Agent 任务。",
          "startFrame": 745,
          "durationInFrames": 103
        },
        {
          "id": "caption-9",
          "text": "Google 同时确认已开始训练 Gemini 4。",
          "startFrame": 848,
          "durationInFrames": 104
        },
        {
          "id": "caption-10",
          "text": "大模型市场正在形成两条路线：",
          "startFrame": 952,
          "durationInFrames": 80
        },
        {
          "id": "caption-11",
          "text": "旗舰模型负责复杂推理编码和前沿能力，",
          "startFrame": 1032,
          "durationInFrames": 118
        },
        {
          "id": "caption-12",
          "text": "轻量模型负责高并发低延迟和低成本专用任务。",
          "startFrame": 1150,
          "durationInFrames": 142
        },
        {
          "id": "caption-13",
          "text": "企业最终不会为所有请求调用最强模型，",
          "startFrame": 1292,
          "durationInFrames": 110
        },
        {
          "id": "caption-14",
          "text": "而是通过模型路由，",
          "startFrame": 1402,
          "durationInFrames": 59
        },
        {
          "id": "caption-15",
          "text": "把大部分任务分配给更便宜的 Flash 或 Mini 类模型。",
          "startFrame": 1461,
          "durationInFrames": 136
        }
      ]
    },
    "durationInFrames": 1597,
    "durationInSeconds": 53.22770833333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "microsoft",
    "narration": "第二件事，Microsoft 与 Mistral 扩大欧洲 AI 合作。Microsoft 同意在未来投入数十亿美元，使用 Mistral 位于欧洲的计算基础设施。Azure 客户将能够通过 Mistral 在法国的数据中心开发和运行 AI 软件，为受监管行业提供一种不完全依赖美国控制基础设施的选择。合作还包括 Mistral Medium 3.5 和 OCR 4 进入 Microsoft Foundry，Medium 3.5 接入 Copilot Studio，企业还可通过 Azure Local 在自有数据中心运行 Mistral 开放模型。这次合作不包含股权投资。这笔交易体现了一种新的云计算模式：Microsoft 的软件分发与企业客户，加上 Mistral 的模型和欧洲数据中心，形成主权云与全球云的混合交付。大型云厂商不再只卖自己的模型，也开始整合不同地区的模型和基础设施，以满足数据驻留、私有部署和监管要求。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/microsoft.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "第二件事，",
          "startFrame": 0,
          "durationInFrames": 33
        },
        {
          "id": "caption-2",
          "text": "Microsoft 与 Mistral 扩大欧洲 AI 合作。",
          "startFrame": 33,
          "durationInFrames": 107
        },
        {
          "id": "caption-3",
          "text": "Microsoft 同意在未来投入数十亿美元，",
          "startFrame": 140,
          "durationInFrames": 90
        },
        {
          "id": "caption-4",
          "text": "使用 Mistral 位于欧洲的计算基础设施。",
          "startFrame": 230,
          "durationInFrames": 94
        },
        {
          "id": "caption-5",
          "text": "Azure 客户将能够通过 Mistral 在法国的数据中心开发和运行 AI 软件，",
          "startFrame": 324,
          "durationInFrames": 181
        },
        {
          "id": "caption-6",
          "text": "为受监管行业提供一种不完全依赖美国控制基础设施的选择。",
          "startFrame": 505,
          "durationInFrames": 152
        },
        {
          "id": "caption-7",
          "text": "合作还包括 Mistral Medium 3.5 和 OCR 4 进入 Microsoft Foundry，",
          "startFrame": 657,
          "durationInFrames": 172
        },
        {
          "id": "caption-8",
          "text": "Medium 3.5 接入 Copilot Studio，",
          "startFrame": 829,
          "durationInFrames": 89
        },
        {
          "id": "caption-9",
          "text": "企业还可通过 Azure Local 在自有数据中心运行 Mistral 开放模型。",
          "startFrame": 918,
          "durationInFrames": 175
        },
        {
          "id": "caption-10",
          "text": "这次合作不包含股权投资。",
          "startFrame": 1093,
          "durationInFrames": 76
        },
        {
          "id": "caption-11",
          "text": "这笔交易体现了一种新的云计算模式：",
          "startFrame": 1169,
          "durationInFrames": 101
        },
        {
          "id": "caption-12",
          "text": "Microsoft 的软件分发与企业客户，",
          "startFrame": 1270,
          "durationInFrames": 83
        },
        {
          "id": "caption-13",
          "text": "加上 Mistral 的模型和欧洲数据中心，",
          "startFrame": 1353,
          "durationInFrames": 99
        },
        {
          "id": "caption-14",
          "text": "形成主权云与全球云的混合交付。",
          "startFrame": 1452,
          "durationInFrames": 94
        },
        {
          "id": "caption-15",
          "text": "大型云厂商不再只卖自己的模型，",
          "startFrame": 1546,
          "durationInFrames": 93
        },
        {
          "id": "caption-16",
          "text": "也开始整合不同地区的模型和基础设施，",
          "startFrame": 1639,
          "durationInFrames": 118
        },
        {
          "id": "caption-17",
          "text": "以满足数据驻留、私有部署和监管要求。",
          "startFrame": 1757,
          "durationInFrames": 116
        }
      ]
    },
    "durationInFrames": 1873,
    "durationInSeconds": 62.44202083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "alphabet",
    "narration": "Alphabet 方面，已将二零二六年资本支出预期提高至一千八百亿到一千九百亿美元，并计划通过股权融资约八百五十亿美元。虽然 Google Cloud 销售快速增长，但 Gemini 旗舰模型延期，使市场开始关注巨额基础设施支出能否及时转化为模型领先和企业收入。这代表资本市场的评价方式正在发生变化。数据中心建了多少、GPU 买了多少已经不够，投资者开始要求企业证明这些算力能产生可持续收入。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/alphabet.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Alphabet 方面，",
          "startFrame": 0,
          "durationInFrames": 35
        },
        {
          "id": "caption-2",
          "text": "已将二零二六年资本支出预期提高至一千八百亿到一千九百亿美元，",
          "startFrame": 35,
          "durationInFrames": 177
        },
        {
          "id": "caption-3",
          "text": "并计划通过股权融资约八百五十亿美元。",
          "startFrame": 212,
          "durationInFrames": 115
        },
        {
          "id": "caption-4",
          "text": "虽然 Google Cloud 销售快速增长，",
          "startFrame": 327,
          "durationInFrames": 82
        },
        {
          "id": "caption-5",
          "text": "但 Gemini 旗舰模型延期，",
          "startFrame": 409,
          "durationInFrames": 76
        },
        {
          "id": "caption-6",
          "text": "使市场开始关注巨额基础设施支出能否及时转化为模型领先和企业收入。",
          "startFrame": 485,
          "durationInFrames": 199
        },
        {
          "id": "caption-7",
          "text": "这代表资本市场的评价方式正在发生变化。",
          "startFrame": 684,
          "durationInFrames": 109
        },
        {
          "id": "caption-8",
          "text": "数据中心建了多少、GPU 买了多少已经不够，",
          "startFrame": 793,
          "durationInFrames": 134
        },
        {
          "id": "caption-9",
          "text": "投资者开始要求企业证明这些算力能产生可持续收入。",
          "startFrame": 927,
          "durationInFrames": 141
        }
      ]
    },
    "durationInFrames": 1068,
    "durationInSeconds": 35.60177083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "specialization",
    "narration": "AI 模型进一步走向专业化。Gemini 3.5 Flash Cyber 是今天最值得关注的产品信号。它不是让一个超大模型处理所有问题，而是针对网络安全工作负载优化成本和能力。未来企业模型架构可能逐渐变为：普通文本走低成本模型，编码任务走编程模型，网络安全走 Cyber 模型，图像或文档走多模态模型，只有高风险复杂任务才调用旗舰推理模型。技术壁垒也会从拥有一个模型 API，转向模型路由、任务评估、失败重试和总成本控制。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/specialization.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 模型进一步走向专业化。",
          "startFrame": 0,
          "durationInFrames": 81
        },
        {
          "id": "caption-2",
          "text": "Gemini 3.5 Flash Cyber 是今天最值得关注的产品信号。",
          "startFrame": 81,
          "durationInFrames": 161
        },
        {
          "id": "caption-3",
          "text": "它不是让一个超大模型处理所有问题，",
          "startFrame": 242,
          "durationInFrames": 105
        },
        {
          "id": "caption-4",
          "text": "而是针对网络安全工作负载优化成本和能力。",
          "startFrame": 347,
          "durationInFrames": 117
        },
        {
          "id": "caption-5",
          "text": "未来企业模型架构可能逐渐变为：",
          "startFrame": 464,
          "durationInFrames": 96
        },
        {
          "id": "caption-6",
          "text": "普通文本走低成本模型，",
          "startFrame": 560,
          "durationInFrames": 61
        },
        {
          "id": "caption-7",
          "text": "编码任务走编程模型，",
          "startFrame": 621,
          "durationInFrames": 58
        },
        {
          "id": "caption-8",
          "text": "网络安全走 Cyber 模型，",
          "startFrame": 679,
          "durationInFrames": 71
        },
        {
          "id": "caption-9",
          "text": "图像或文档走多模态模型，",
          "startFrame": 750,
          "durationInFrames": 85
        },
        {
          "id": "caption-10",
          "text": "只有高风险复杂任务才调用旗舰推理模型。",
          "startFrame": 835,
          "durationInFrames": 113
        },
        {
          "id": "caption-11",
          "text": "技术壁垒也会从拥有一个模型 API，",
          "startFrame": 948,
          "durationInFrames": 101
        },
        {
          "id": "caption-12",
          "text": "转向模型路由、任务评估、失败重试和总成本控制。",
          "startFrame": 1049,
          "durationInFrames": 146
        }
      ]
    },
    "durationInFrames": 1195,
    "durationInSeconds": 39.84677083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "agent-payments",
    "narration": "Agent 开始需要独立的支付基础设施。Agent 支付创业公司 Natural 完成三千万美元融资，试图构建专门面向自主 Agent 的支付系统。现有银行卡、ACH 和支付网关基本围绕人类发起和确认交易设计。Agent 若要自动寻找供应商、协商价格、采购服务并完成付款，还需要解决授权额度、身份验证、交易审计和异常撤销等问题。这意味着 Agent 商业闭环不只是理解任务、调用工具、返回结果，而会扩展为身份认证、权限委托、供应商选择、合同或订单、支付、发票与审计以及争议处理。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/agent-payments.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Agent 开始需要独立的支付基础设施。",
          "startFrame": 0,
          "durationInFrames": 99
        },
        {
          "id": "caption-2",
          "text": "Agent 支付创业公司 Natural 完成三千万美元融资，",
          "startFrame": 99,
          "durationInFrames": 138
        },
        {
          "id": "caption-3",
          "text": "试图构建专门面向自主 Agent 的支付系统。",
          "startFrame": 237,
          "durationInFrames": 107
        },
        {
          "id": "caption-4",
          "text": "现有银行卡、ACH 和支付网关基本围绕人类发起和确认交易设计。",
          "startFrame": 344,
          "durationInFrames": 192
        },
        {
          "id": "caption-5",
          "text": "Agent 若要自动寻找供应商、协商价格、采购服务并完成付款，",
          "startFrame": 536,
          "durationInFrames": 171
        },
        {
          "id": "caption-6",
          "text": "还需要解决授权额度、身份验证、交易审计和异常撤销等问题。",
          "startFrame": 707,
          "durationInFrames": 183
        },
        {
          "id": "caption-7",
          "text": "这意味着 Agent 商业闭环不只是理解任务、调用工具、返回结果，",
          "startFrame": 890,
          "durationInFrames": 175
        },
        {
          "id": "caption-8",
          "text": "而会扩展为身份认证、权限委托、供应商选择、合同或订单、支付、发票与审计以及争议处理。",
          "startFrame": 1065,
          "durationInFrames": 288
        }
      ]
    },
    "durationInFrames": 1353,
    "durationInSeconds": 45.111354166666665,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "physical-ai",
    "narration": "物理 AI 继续从原型走向客户现场。英国机器人公司 Humanoid 完成一点五二亿美元 A 轮融资，投后估值约十三点五亿美元。公司计划今年第四季度，将测试版机器人部署到制造、物流和零售等客户现场，并启动轮式机器人的规模化生产。融资参与者包括工业企业 Schaeffler 和 Bosch，说明人形机器人资本开始与真实制造供应链结合，而不只是风险投资机构进行概念性押注。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/physical-ai.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "物理 AI 继续从原型走向客户现场。",
          "startFrame": 0,
          "durationInFrames": 94
        },
        {
          "id": "caption-2",
          "text": "英国机器人公司 Humanoid 完成一点五二亿美元 A 轮融资，",
          "startFrame": 94,
          "durationInFrames": 167
        },
        {
          "id": "caption-3",
          "text": "投后估值约十三点五亿美元。",
          "startFrame": 261,
          "durationInFrames": 88
        },
        {
          "id": "caption-4",
          "text": "公司计划今年第四季度，",
          "startFrame": 349,
          "durationInFrames": 61
        },
        {
          "id": "caption-5",
          "text": "将测试版机器人部署到制造、物流和零售等客户现场，",
          "startFrame": 410,
          "durationInFrames": 138
        },
        {
          "id": "caption-6",
          "text": "并启动轮式机器人的规模化生产。",
          "startFrame": 548,
          "durationInFrames": 84
        },
        {
          "id": "caption-7",
          "text": "融资参与者包括工业企业 Schaeffler 和 Bosch，",
          "startFrame": 632,
          "durationInFrames": 131
        },
        {
          "id": "caption-8",
          "text": "说明人形机器人资本开始与真实制造供应链结合，",
          "startFrame": 763,
          "durationInFrames": 122
        },
        {
          "id": "caption-9",
          "text": "而不只是风险投资机构进行概念性押注。",
          "startFrame": 885,
          "durationInFrames": 113
        }
      ]
    },
    "durationInFrames": 998,
    "durationInSeconds": 33.261604166666665,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "eu-regulation",
    "narration": "政策方面，欧盟委员会发布人工智能法案第五十条实施指南，相关透明度义务从二零二六年八月二日开始适用。AI 系统提供者需要告知用户正在与 AI 系统交互，并为 AI 生成或修改的内容加入机器可读取标记，使平台和检测工具能够识别 AI 内容。部署者还需要披露 Deepfake 内容、未经人工审查的公共利益类 AI 内容、情绪识别系统和生物特征分类系统。这意味着 AI 内容标记不能只是在界面上显示一句由 AI 生成。企业需要把生成来源、模型信息、编辑记录和机器可读标记写入内容生产和导出流程。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/eu-regulation.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "政策方面，",
          "startFrame": 0,
          "durationInFrames": 27
        },
        {
          "id": "caption-2",
          "text": "欧盟委员会发布人工智能法案第五十条实施指南，",
          "startFrame": 27,
          "durationInFrames": 123
        },
        {
          "id": "caption-3",
          "text": "相关透明度义务从二零二六年八月二日开始适用。",
          "startFrame": 150,
          "durationInFrames": 135
        },
        {
          "id": "caption-4",
          "text": "AI 系统提供者需要告知用户正在与 AI 系统交互，",
          "startFrame": 285,
          "durationInFrames": 140
        },
        {
          "id": "caption-5",
          "text": "并为 AI 生成或修改的内容加入机器可读取标记，",
          "startFrame": 425,
          "durationInFrames": 142
        },
        {
          "id": "caption-6",
          "text": "使平台和检测工具能够识别 AI 内容。",
          "startFrame": 567,
          "durationInFrames": 100
        },
        {
          "id": "caption-7",
          "text": "部署者还需要披露 Deepfake 内容、未经人工审查的公共利益类 AI 内容、情绪识别系统和生物特征分类系统。",
          "startFrame": 667,
          "durationInFrames": 289
        },
        {
          "id": "caption-8",
          "text": "这意味着 AI 内容标记不能只是在界面上显示一句由 AI 生成。",
          "startFrame": 956,
          "durationInFrames": 173
        },
        {
          "id": "caption-9",
          "text": "企业需要把生成来源、模型信息、编辑记录和机器可读标记写入内容生产和导出流程。",
          "startFrame": 1129,
          "durationInFrames": 254
        }
      ]
    },
    "durationInFrames": 1383,
    "durationInSeconds": 46.09429166666666,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "blackrock",
    "narration": "资本层面，BlackRock 与阿布扎比基金 MGX 支持的财团完成对 Aligned Data Centers 的四百亿美元收购，并额外投入五十亿美元增长资本。Aligned 目前拥有五十一个数据中心园区，超过六点四吉瓦的运营及规划容量，面向超大规模云厂商和 AI 客户。财团计划初期投入约三百亿美元股权资本，加上债务后总部署规模可能达到一千亿美元。这笔交易再次说明，AI 资本正大量流向土地、电力、冷却系统和数据中心，而不只是模型公司。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/blackrock.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "资本层面，",
          "startFrame": 0,
          "durationInFrames": 23
        },
        {
          "id": "caption-2",
          "text": "BlackRock 与阿布扎比基金 MGX 支持的财团完成对 Aligned Data Centers 的四百亿美元收购，",
          "startFrame": 23,
          "durationInFrames": 240
        },
        {
          "id": "caption-3",
          "text": "并额外投入五十亿美元增长资本。",
          "startFrame": 263,
          "durationInFrames": 93
        },
        {
          "id": "caption-4",
          "text": "Aligned 目前拥有五十一个数据中心园区，",
          "startFrame": 356,
          "durationInFrames": 108
        },
        {
          "id": "caption-5",
          "text": "超过六点四吉瓦的运营及规划容量，",
          "startFrame": 464,
          "durationInFrames": 98
        },
        {
          "id": "caption-6",
          "text": "面向超大规模云厂商和 AI 客户。",
          "startFrame": 562,
          "durationInFrames": 98
        },
        {
          "id": "caption-7",
          "text": "财团计划初期投入约三百亿美元股权资本，",
          "startFrame": 660,
          "durationInFrames": 115
        },
        {
          "id": "caption-8",
          "text": "加上债务后总部署规模可能达到一千亿美元。",
          "startFrame": 775,
          "durationInFrames": 122
        },
        {
          "id": "caption-9",
          "text": "这笔交易再次说明，",
          "startFrame": 897,
          "durationInFrames": 48
        },
        {
          "id": "caption-10",
          "text": "AI 资本正大量流向土地、电力、冷却系统和数据中心，",
          "startFrame": 945,
          "durationInFrames": 165
        },
        {
          "id": "caption-11",
          "text": "而不只是模型公司。",
          "startFrame": 1110,
          "durationInFrames": 57
        }
      ]
    },
    "durationInFrames": 1167,
    "durationInSeconds": 38.884875,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "iqe",
    "narration": "光通信供应链继续受益于 AI 数据中心。英国半导体晶圆厂商 IQE 将二零二六年营收增长预期从约百分之二十上调至超过百分之三十。主要动力来自用于 AI 数据中心光通信设备的磷化铟产品需求。AI 集群规模扩大后，服务器之间的数据传输正成为重要瓶颈。资本和订单因此开始从 GPU 向光模块、光子器件、高速网络和先进封装扩散。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/iqe.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "光通信供应链继续受益于 AI 数据中心。",
          "startFrame": 0,
          "durationInFrames": 116
        },
        {
          "id": "caption-2",
          "text": "英国半导体晶圆厂商 IQE 将二零二六年营收增长预期从约百分之二十上调至超过百分之三十。",
          "startFrame": 116,
          "durationInFrames": 275
        },
        {
          "id": "caption-3",
          "text": "主要动力来自用于 AI 数据中心光通信设备的磷化铟产品需求。",
          "startFrame": 391,
          "durationInFrames": 191
        },
        {
          "id": "caption-4",
          "text": "AI 集群规模扩大后，",
          "startFrame": 582,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "服务器之间的数据传输正成为重要瓶颈。",
          "startFrame": 640,
          "durationInFrames": 106
        },
        {
          "id": "caption-6",
          "text": "资本和订单因此开始从 GPU 向光模块、光子器件、高速网络和先进封装扩散。",
          "startFrame": 746,
          "durationInFrames": 235
        }
      ]
    },
    "durationInFrames": 981,
    "durationInSeconds": 32.69025,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "trends",
    "narration": "把今天的信号放在一起。模型走向专业化，成本成为核心指标，主权 AI 商业化，Agent 形成交易闭环，物理 AI 进入部署期，资本继续流向算力，内容溯源成为法律要求。对 Agent 开发者来说，最值得关注的不是某一个模型的榜单变化，而是 Agent 运行环境正在快速完整化。用轻量模型和专用模型控制推理成本，根据数据主权要求选择模型与运行地区，为 Agent 建立身份支付额度和交易审计，为生成内容记录来源及机器可读标记，将模型能力与真实设备生产系统和业务流程连接，用一次成功任务的总成本而不是单纯 Token 单价评估系统。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/trends.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "把今天的信号放在一起。",
          "startFrame": 0,
          "durationInFrames": 73
        },
        {
          "id": "caption-2",
          "text": "模型走向专业化，",
          "startFrame": 73,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "成本成为核心指标，",
          "startFrame": 119,
          "durationInFrames": 53
        },
        {
          "id": "caption-4",
          "text": "主权 AI 商业化，",
          "startFrame": 172,
          "durationInFrames": 57
        },
        {
          "id": "caption-5",
          "text": "Agent 形成交易闭环，",
          "startFrame": 229,
          "durationInFrames": 68
        },
        {
          "id": "caption-6",
          "text": "物理 AI 进入部署期，",
          "startFrame": 297,
          "durationInFrames": 61
        },
        {
          "id": "caption-7",
          "text": "资本继续流向算力，",
          "startFrame": 358,
          "durationInFrames": 54
        },
        {
          "id": "caption-8",
          "text": "内容溯源成为法律要求。",
          "startFrame": 412,
          "durationInFrames": 72
        },
        {
          "id": "caption-9",
          "text": "对 Agent 开发者来说，",
          "startFrame": 484,
          "durationInFrames": 56
        },
        {
          "id": "caption-10",
          "text": "最值得关注的不是某一个模型的榜单变化，",
          "startFrame": 540,
          "durationInFrames": 107
        },
        {
          "id": "caption-11",
          "text": "而是 Agent 运行环境正在快速完整化。",
          "startFrame": 647,
          "durationInFrames": 122
        },
        {
          "id": "caption-12",
          "text": "用轻量模型和专用模型控制推理成本，",
          "startFrame": 769,
          "durationInFrames": 108
        },
        {
          "id": "caption-13",
          "text": "根据数据主权要求选择模型与运行地区，",
          "startFrame": 877,
          "durationInFrames": 132
        },
        {
          "id": "caption-14",
          "text": "为 Agent 建立身份支付额度和交易审计，",
          "startFrame": 1009,
          "durationInFrames": 113
        },
        {
          "id": "caption-15",
          "text": "为生成内容记录来源及机器可读标记，",
          "startFrame": 1122,
          "durationInFrames": 119
        },
        {
          "id": "caption-16",
          "text": "将模型能力与真实设备生产系统和业务流程连接，",
          "startFrame": 1241,
          "durationInFrames": 131
        },
        {
          "id": "caption-17",
          "text": "用一次成功任务的总成本而不是单纯 Token 单价评估系统。",
          "startFrame": 1372,
          "durationInFrames": 151
        }
      ]
    },
    "durationInFrames": 1523,
    "durationInSeconds": 50.76083333333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "close",
    "narration": "模型仍在快速变化，但模型路由、权限、支付、溯源和稳定执行将成为更持久的基础设施。这就是今天的 AI 日报。",
    "audioFile": "generated/ai-daily-2026-07-21/audio/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "模型仍在快速变化，",
          "startFrame": 0,
          "durationInFrames": 51
        },
        {
          "id": "caption-2",
          "text": "但模型路由、权限、支付、溯源和稳定执行将成为更持久的基础设施。",
          "startFrame": 51,
          "durationInFrames": 216
        },
        {
          "id": "caption-3",
          "text": "这就是今天的 AI 日报。",
          "startFrame": 267,
          "durationInFrames": 59
        }
      ]
    },
    "durationInFrames": 326,
    "durationInSeconds": 10.880583333333334,
    "provider": "voxcpm",
    "format": "wav"
  }
] satisfies readonly AiDaily20260721AudioTrack[];
