import type { VoiceProfiledQualityGatedMaintainedProducerSampleManifest } from "../producer-samples/manifest";

export const aiDaily20260721Manifest = {
  sampleStatus: "maintained",
  compositionId: "AiDaily20260721",
  sampleName: "AiDaily20260721",
  slug: "ai-daily-2026-07-21",
  contentFamily: "trend-briefing",
  canvasProfile: "portrait-9x16",
  styleProfileId: "hand-drawn-explainer",
  localArtifactRoot: "public/generated/ai-daily-2026-07-21/",
  ttsStatus: "generated-local",
  productionBrief: {
    audience:
      "Agent developers and technical practitioners following daily AI infrastructure signals.",
    publishingSurface: "9:16 vertical social video and local review.",
    durationTargetSeconds: 487,
  },
  narration: {
    required: true,
    provider: "voxcpm",
    voiceProfileId: "science-explainer-young-male",
    mode: "high-fidelity-clone",
    scriptPath: "src/remotion/AiDaily20260721/script.ts",
    audioMetadataPath: "src/remotion/AiDaily20260721/audio.generated.ts",
  },
  assets: {
    manifestPath: "src/remotion/AiDaily20260721/assets.manifest.json",
  },
  validationModule: "src/remotion/AiDaily20260721/validation.ts",
  qualityModule: "src/remotion/AiDaily20260721/quality.ts",
  render: {
    metadataPath: "src/remotion/AiDaily20260721/render-metadata.json",
    cover16x9CompositionId: "AiDaily20260721Cover16x9",
    cover9x16CompositionId: "AiDaily20260721Cover9x16",
  },
  publishingCopyPath: "src/remotion/AiDaily20260721/publishing.md",
  reviewFrames: [
    { frame: 200, label: "opening-scope", purpose: "Check the opening expanding-scope diagram and portrait caption clearance." },
    { frame: 800, label: "google-tracks", purpose: "Check the two-track divergence visual and caption fit." },
    { frame: 1600, label: "microsoft-mistral", purpose: "Check the sovereign cloud hybrid diagram." },
    { frame: 2800, label: "alphabet-capex", purpose: "Check the big number and gauge visual." },
    { frame: 3800, label: "specialization-routing", purpose: "Check the model routing flow diagram." },
    { frame: 5300, label: "agent-payments", purpose: "Check the agent payment loop expansion." },
    { frame: 6600, label: "physical-ai", purpose: "Check the Humanoid robot deployment visual." },
    { frame: 7800, label: "eu-regulation", purpose: "Check the EU AI Act obligations checklist." },
    { frame: 9000, label: "blackrock", purpose: "Check the $40B data center acquisition visual." },
    { frame: 10200, label: "iqe-photonics", purpose: "Check the photonics supply chain diagram." },
    { frame: 11200, label: "trends-summary", purpose: "Check the seven-trend summary synthesis." },
    { frame: 12000, label: "trends-late", purpose: "Check the late-state synthesis remains legible." },
    { frame: 13200, label: "close-pillars", purpose: "Check the five infrastructure pillars." },
    { frame: 14200, label: "close-late", purpose: "Check the final hold state and safe area." },
  ],
  sourceFiles: [
    { path: "src/remotion/AiDaily20260721/AiDaily20260721.tsx", kind: "renderer" },
    { path: "src/remotion/AiDaily20260721/types.ts", kind: "types" },
    { path: "src/remotion/AiDaily20260721/script.ts", kind: "script" },
    { path: "src/remotion/AiDaily20260721/data.ts", kind: "data" },
    { path: "src/remotion/AiDaily20260721/audio.generated.ts", kind: "audio-metadata" },
    { path: "src/remotion/AiDaily20260721/manifest.ts", kind: "manifest" },
    { path: "src/remotion/AiDaily20260721/assets.manifest.json", kind: "asset-manifest" },
    { path: "src/remotion/AiDaily20260721/validation.ts", kind: "validation" },
    { path: "src/remotion/AiDaily20260721/quality.ts", kind: "quality" },
    { path: "src/remotion/AiDaily20260721/cover.tsx", kind: "cover" },
    { path: "src/remotion/AiDaily20260721/render-metadata.json", kind: "render-metadata" },
    { path: "src/remotion/AiDaily20260721/publishing.md", kind: "publishing-copy" },
    { path: "src/remotion/Root.tsx", kind: "root-registration" },
  ],
  promotionCandidates: [],
  notes: [
    "Generated narration, review frames, covers, metadata, and MP4 stay local-only.",
    "All 12 beats are code-led hand-drawn information graphics; failed source-capture attempts are recorded outside the frame.",
    "The narration uses science-explainer-young-male in high-fidelity-clone mode with no fallback.",
    "All 12 scenes plus 2 meaning-changing late states and both centered covers must be visually reviewed; final MP4 export is user-owned.",
  ],
} as const satisfies VoiceProfiledQualityGatedMaintainedProducerSampleManifest;