// Generated by the direct VoxCPM Producer runtime for the terminal TCP handshake proof.

import type { TcpHandshakeTerminalAudioTrack } from "./types";

export const tcpHandshakeTerminalAudio = [
  {
    sceneId: "syn",
    narration: "第一步，客户端发送 SYN，并带上自己的初始序列号，请求建立 TCP 连接。",
    audioFile: "generated/tcp-handshake-terminal/audio/syn.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第一步，",
          startFrame: 0,
          durationInFrames: 28,
        },
        {
          id: "caption-2",
          text: "客户端发送 SYN，",
          startFrame: 28,
          durationInFrames: 52,
        },
        {
          id: "caption-3",
          text: "并带上自己的初始序列号，",
          startFrame: 80,
          durationInFrames: 66,
        },
        {
          id: "caption-4",
          text: "请求建立 TCP 连接。",
          startFrame: 146,
          durationInFrames: 57,
        },
      ],
    },
    durationInFrames: 203,
    durationInSeconds: 6.779041666666667,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "syn-ack",
    narration: "第二步，服务端回复 SYN-ACK，既确认客户端的序列号，也发送自己的初始序列号。",
    audioFile: "generated/tcp-handshake-terminal/audio/syn-ack.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第二步，",
          startFrame: 0,
          durationInFrames: 25,
        },
        {
          id: "caption-2",
          text: "服务端回复 SYN-ACK，",
          startFrame: 25,
          durationInFrames: 77,
        },
        {
          id: "caption-3",
          text: "既确认客户端的序列号，",
          startFrame: 102,
          durationInFrames: 62,
        },
        {
          id: "caption-4",
          text: "也发送自己的初始序列号。",
          startFrame: 164,
          durationInFrames: 64,
        },
      ],
    },
    durationInFrames: 228,
    durationInSeconds: 7.6026875,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "ack",
    narration: "第三步，客户端发送 ACK 完成确认，双方进入已建立状态，可以开始传输数据。",
    audioFile: "generated/tcp-handshake-terminal/audio/ack.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第三步，",
          startFrame: 0,
          durationInFrames: 26,
        },
        {
          id: "caption-2",
          text: "客户端发送 ACK 完成确认，",
          startFrame: 26,
          durationInFrames: 75,
        },
        {
          id: "caption-3",
          text: "双方进入已建立状态，",
          startFrame: 101,
          durationInFrames: 59,
        },
        {
          id: "caption-4",
          text: "可以开始传输数据。",
          startFrame: 160,
          durationInFrames: 55,
        },
      ],
    },
    durationInFrames: 215,
    durationInSeconds: 7.1781041666666665,
    provider: "voxcpm",
    format: "wav",
  },
] satisfies readonly TcpHandshakeTerminalAudioTrack[];
