#!/usr/bin/env node
/* global process */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  createVoxcpmProducerRequestPlan,
  requestProducerNarrationAsset,
  runProducerAudioGeneration,
} from "../../../../../scripts/lib/producer-audio/index.js";

const sampleNameNarrationBeats = [
  { id: "open", ttsText: "Start with the real topic and the viewer promise.", language: "en" },
  { id: "proof", ttsText: "Show one concrete source, data point, or product state.", language: "en" },
  { id: "close", ttsText: "End with the reusable takeaway.", language: "en" },
];

const root = "src/remotion/producer-samples/scaffold/SampleName";
await runProducerAudioGeneration({
  compositionId: "SampleName",
  beats: sampleNameNarrationBeats,
  createRequestPlan: (beat) => createVoxcpmProducerRequestPlan({
    beat,
    mode: "controllable-clone",
    referenceId: process.env.SAMPLE_NAME_VOICE_REFERENCE_ID,
    referenceText: process.env.SAMPLE_NAME_VOICE_REFERENCE_TEXT,
  }),
  requestNarration: ({ plan }) => requestProducerNarrationAsset({ origin: process.env.AI_VIDEO_STUDIO_ORIGIN ?? "http://127.0.0.1:3000", plan }),
  fallbackPolicy: "forbid",
  metadata: {
    header: "Generated by scripts/lib/producer-audio for SampleName.",
    exportName: "sampleNameAudio",
    typeImport: { name: "SampleNameAudioTrack", path: "./types" },
    destination: `${root}/audio.generated.ts`,
  },
  duration: {
    source: await readFile(`${root}/types.ts`, "utf8"),
    constantName: "SAMPLE_NAME_DURATION_IN_FRAMES",
    destination: `${root}/types.ts`,
  },
  summaryDestination: "public/generated/sample-name/tts-summary.json",
  writeOutputs: true,
  writeTextFile: async (destination, content) => {
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, content);
  },
});

// Then run: npm run producer:validate -- --module src/remotion/producer-samples/scaffold/SampleName/validation.js
// Then run: npm run producer:stills -- --composition SampleName
