#!/usr/bin/env node

import { readFile } from "node:fs/promises";

import {
  createVoxcpmProducerRequestPlanForProfile,
  readProducerVoxcpmConfig,
  requestProducerNarrationAsset,
  runProducerAudioGeneration,
} from "../../../../../scripts/lib/producer-audio/index.js";

const sampleNameNarrationBeats = [
  {
    id: "open",
    narrationRequired: true,
    ttsText: "Start with the real topic and the viewer promise.",
    language: "en",
    voiceControl: "Natural, clear explanation, medium pace, restrained ending",
  },
  {
    id: "proof",
    narrationRequired: true,
    ttsText: "Show one concrete source, data point, or product state.",
    language: "en",
    voiceControl: "Natural, clear explanation, medium pace, restrained ending",
  },
  {
    id: "close",
    narrationRequired: true,
    ttsText: "End with the reusable takeaway.",
    language: "en",
    voiceControl: "Natural, clear explanation, medium pace, restrained ending",
  },
];

const root = "src/remotion/SampleName";
const slug = "sample-name";
const voiceProfileId = "lyy" /* VOICE_PROFILE_ID */;
const voiceMode = "high-fidelity-clone" /* VOICE_MODE */;
const voxcpmConfig = readProducerVoxcpmConfig();

await runProducerAudioGeneration({
  compositionId: "SampleName",
  beats: sampleNameNarrationBeats,
  createRequestPlan: (beat) =>
    createVoxcpmProducerRequestPlanForProfile({
      beat,
      profileId: voiceProfileId,
      mode: voiceMode,
      ...(voiceMode === "controllable-clone" ? { control: beat.voiceControl } : {}),
    }),
  requestNarration: ({ plan }) =>
    requestProducerNarrationAsset({ config: voxcpmConfig, plan, slug }),
  progressDestination: `public/generated/${slug}/audio/progress.json`,
  metadata: {
    header: "Generated by the direct VoxCPM Producer runtime for SampleName.",
    exportName: "sampleNameAudio",
    typeImport: { name: "SampleNameAudioTrack", path: "./types" },
    destination: `${root}/audio.generated.ts`,
  },
  duration: {
    source: await readFile(`${root}/types.ts`, "utf8"),
    constantName: "SAMPLE_NAME_DURATION_IN_FRAMES",
    destination: `${root}/types.ts`,
  },
  summaryDestination: `public/generated/${slug}/audio/summary.json`,
  writeOutputs: true,
});

// Then run: npm run producer:validate -- --module src/remotion/SampleName/validation.ts
// Then run: npm run producer:stills -- --composition SampleName
