// Auto-generated by scripts/generate-ai-daily-news-20260713-tts-clone.mjs
// Voice clone: LYY (high-fidelity clone_with_prompt)
// 2026-07-13T17:50:19.278Z

import type { AudioTrack } from "./types";

export const aiDailyNews20260713Audio: AudioTrack[] = [
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天 AI 行业的重心不在新模型发布，",
          "startFrame": 0,
          "durationInFrames": 97
        },
        {
          "id": "caption-2",
          "text": "而在算力基础设施、",
          "startFrame": 97,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "能源成本、",
          "startFrame": 143,
          "durationInFrames": 26
        },
        {
          "id": "caption-4",
          "text": "资本集中和社会治理。",
          "startFrame": 169,
          "durationInFrames": 51
        },
        {
          "id": "caption-5",
          "text": "Meta、",
          "startFrame": 220,
          "durationInFrames": 26
        },
        {
          "id": "caption-6",
          "text": "Intel、",
          "startFrame": 246,
          "durationInFrames": 31
        },
        {
          "id": "caption-7",
          "text": "Helsing 公布的大额投资，",
          "startFrame": 277,
          "durationInFrames": 82
        },
        {
          "id": "caption-8",
          "text": "以及美国围绕数据中心电价的政策动作共同说明：",
          "startFrame": 359,
          "durationInFrames": 113
        },
        {
          "id": "caption-9",
          "text": "AI 竞争已经从谁的模型更强，",
          "startFrame": 472,
          "durationInFrames": 77
        },
        {
          "id": "caption-10",
          "text": "扩展为谁能够获得电力、",
          "startFrame": 549,
          "durationInFrames": 56
        },
        {
          "id": "caption-11",
          "text": "芯片、",
          "startFrame": 605,
          "durationInFrames": 15
        },
        {
          "id": "caption-12",
          "text": "数据中心、",
          "startFrame": 620,
          "durationInFrames": 26
        },
        {
          "id": "caption-13",
          "text": "资本和政府支持。",
          "startFrame": 646,
          "durationInFrames": 40
        }
      ]
    },
    "durationInFrames": 686,
    "durationInSeconds": 22.88,
    "format": "wav",
    "narration": "今天 AI 行业的重心不在新模型发布，而在算力基础设施、能源成本、资本集中和社会治理。Meta、Intel、Helsing 公布的大额投资，以及美国围绕数据中心电价的政策动作共同说明：AI 竞争已经从谁的模型更强，扩展为谁能够获得电力、芯片、数据中心、资本和政府支持。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "open"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/meta-infra.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Meta 宣布将路易斯安那州 Hyperion 数据中心容量提升至 5GW，",
          "startFrame": 0,
          "durationInFrames": 224
        },
        {
          "id": "caption-2",
          "text": "投资超 500 亿美元，",
          "startFrame": 224,
          "durationInFrames": 71
        },
        {
          "id": "caption-3",
          "text": "并表示未来三年将在美国基础设施和就业投入约 6000 亿美元。",
          "startFrame": 295,
          "durationInFrames": 183
        },
        {
          "id": "caption-4",
          "text": "同一天，",
          "startFrame": 478,
          "durationInFrames": 24
        },
        {
          "id": "caption-5",
          "text": "Intel 启动 50 亿欧元投资升级爱尔兰工厂。",
          "startFrame": 502,
          "durationInFrames": 147
        },
        {
          "id": "caption-6",
          "text": "5GW 已经接近大型区域电力系统规模，",
          "startFrame": 649,
          "durationInFrames": 112
        },
        {
          "id": "caption-7",
          "text": "说明头部模型公司的核心资产正在从模型权重扩展到电力合同、",
          "startFrame": 761,
          "durationInFrames": 165
        },
        {
          "id": "caption-8",
          "text": "土地、",
          "startFrame": 926,
          "durationInFrames": 18
        },
        {
          "id": "caption-9",
          "text": "水资源和自有算力集群。",
          "startFrame": 944,
          "durationInFrames": 64
        }
      ]
    },
    "durationInFrames": 1008,
    "durationInSeconds": 33.6,
    "format": "wav",
    "narration": "Meta 宣布将路易斯安那州 Hyperion 数据中心容量提升至 5GW，投资超 500 亿美元，并表示未来三年将在美国基础设施和就业投入约 6000 亿美元。同一天，Intel 启动 50 亿欧元投资升级爱尔兰工厂。5GW 已经接近大型区域电力系统规模，说明头部模型公司的核心资产正在从模型权重扩展到电力合同、土地、水资源和自有算力集群。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "meta-infra"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/waze-voice.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Google 旗下 Waze 推出新的 AI 功能，",
          "startFrame": 0,
          "durationInFrames": 144
        },
        {
          "id": "caption-2",
          "text": "用户可以通过自然语言报告路况，",
          "startFrame": 144,
          "durationInFrames": 83
        },
        {
          "id": "caption-3",
          "text": "并获得个性化导航体验。",
          "startFrame": 227,
          "durationInFrames": 61
        },
        {
          "id": "caption-4",
          "text": "信号很简单：",
          "startFrame": 288,
          "durationInFrames": 33
        },
        {
          "id": "caption-5",
          "text": "语音模型正在从聊天入口进入驾驶、",
          "startFrame": 321,
          "durationInFrames": 89
        },
        {
          "id": "caption-6",
          "text": "导航等持续在线场景，",
          "startFrame": 410,
          "durationInFrames": 56
        },
        {
          "id": "caption-7",
          "text": "AI 的交互面正在从对话框扩展到每一次日常使用。",
          "startFrame": 466,
          "durationInFrames": 134
        }
      ]
    },
    "durationInFrames": 600,
    "durationInSeconds": 20,
    "format": "wav",
    "narration": "Google 旗下 Waze 推出新的 AI 功能，用户可以通过自然语言报告路况，并获得个性化导航体验。信号很简单：语音模型正在从聊天入口进入驾驶、导航等持续在线场景，AI 的交互面正在从对话框扩展到每一次日常使用。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "waze-voice"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/gpt56-agent.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "OpenAI 于七月九日发布 GPT-5.6 系列，",
          "startFrame": 0,
          "durationInFrames": 132
        },
        {
          "id": "caption-2",
          "text": "旗舰模型 Sol 引入 ultra 模式，",
          "startFrame": 132,
          "durationInFrames": 106
        },
        {
          "id": "caption-3",
          "text": "利用多个子 Agent 并行执行复杂任务。",
          "startFrame": 238,
          "durationInFrames": 106
        },
        {
          "id": "caption-4",
          "text": "它的重要性不只是基准成绩，",
          "startFrame": 344,
          "durationInFrames": 66
        },
        {
          "id": "caption-5",
          "text": "而是模型产品结构正在发生变化：",
          "startFrame": 410,
          "durationInFrames": 76
        },
        {
          "id": "caption-6",
          "text": "一个用户请求不再必然对应一次模型调用，",
          "startFrame": 486,
          "durationInFrames": 96
        },
        {
          "id": "caption-7",
          "text": "而可能自动触发规划、",
          "startFrame": 582,
          "durationInFrames": 51
        },
        {
          "id": "caption-8",
          "text": "并行子任务、",
          "startFrame": 633,
          "durationInFrames": 30
        },
        {
          "id": "caption-9",
          "text": "工具调用、",
          "startFrame": 663,
          "durationInFrames": 25
        },
        {
          "id": "caption-10",
          "text": "验证和结果汇总。",
          "startFrame": 688,
          "durationInFrames": 42
        }
      ]
    },
    "durationInFrames": 730,
    "durationInSeconds": 24.32,
    "format": "wav",
    "narration": "OpenAI 于七月九日发布 GPT-5.6 系列，旗舰模型 Sol 引入 ultra 模式，利用多个子 Agent 并行执行复杂任务。它的重要性不只是基准成绩，而是模型产品结构正在发生变化：一个用户请求不再必然对应一次模型调用，而可能自动触发规划、并行子任务、工具调用、验证和结果汇总。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "gpt56-agent"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/gpt-live.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "OpenAI 于七月八日发布 GPT-Live，",
          "startFrame": 0,
          "durationInFrames": 152
        },
        {
          "id": "caption-2",
          "text": "采用全双工架构，",
          "startFrame": 152,
          "durationInFrames": 51
        },
        {
          "id": "caption-3",
          "text": "同时听取和生成语音；",
          "startFrame": 203,
          "durationInFrames": 63
        },
        {
          "id": "caption-4",
          "text": "遇到复杂任务时委托给后端模型。",
          "startFrame": 266,
          "durationInFrames": 95
        },
        {
          "id": "caption-5",
          "text": "这提供了一种明确的 Agent 架构方向：",
          "startFrame": 361,
          "durationInFrames": 133
        },
        {
          "id": "caption-6",
          "text": "低延迟交互层、",
          "startFrame": 494,
          "durationInFrames": 44
        },
        {
          "id": "caption-7",
          "text": "规划层、",
          "startFrame": 538,
          "durationInFrames": 25
        },
        {
          "id": "caption-8",
          "text": "执行层和验证层分离。",
          "startFrame": 563,
          "durationInFrames": 63
        },
        {
          "id": "caption-9",
          "text": "未来的 AI 助理不太可能由一个大模型承担所有任务，",
          "startFrame": 626,
          "durationInFrames": 165
        },
        {
          "id": "caption-10",
          "text": "而会分成实时交互、",
          "startFrame": 791,
          "durationInFrames": 57
        },
        {
          "id": "caption-11",
          "text": "规划和执行层。",
          "startFrame": 848,
          "durationInFrames": 45
        }
      ]
    },
    "durationInFrames": 893,
    "durationInSeconds": 29.76,
    "format": "wav",
    "narration": "OpenAI 于七月八日发布 GPT-Live，采用全双工架构，同时听取和生成语音；遇到复杂任务时委托给后端模型。这提供了一种明确的 Agent 架构方向：低延迟交互层、规划层、执行层和验证层分离。未来的 AI 助理不太可能由一个大模型承担所有任务，而会分成实时交互、规划和执行层。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "gpt-live"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/us-policy.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "白宫计划召集公用事业公司、",
          "startFrame": 0,
          "durationInFrames": 73
        },
        {
          "id": "caption-2",
          "text": "数据中心开发商和州政府，",
          "startFrame": 73,
          "durationInFrames": 67
        },
        {
          "id": "caption-3",
          "text": "推动一项自愿承诺：",
          "startFrame": 140,
          "durationInFrames": 50
        },
        {
          "id": "caption-4",
          "text": "AI 公司和数据中心运营方应承担新增发电、",
          "startFrame": 190,
          "durationInFrames": 118
        },
        {
          "id": "caption-5",
          "text": "电网升级和预留容量成本，",
          "startFrame": 308,
          "durationInFrames": 67
        },
        {
          "id": "caption-6",
          "text": "避免把费用转嫁给普通居民。",
          "startFrame": 375,
          "durationInFrames": 73
        },
        {
          "id": "caption-7",
          "text": "这意味着 AI 监管正在从模型安全扩展到电力、",
          "startFrame": 448,
          "durationInFrames": 129
        },
        {
          "id": "caption-8",
          "text": "水资源、",
          "startFrame": 577,
          "durationInFrames": 22
        },
        {
          "id": "caption-9",
          "text": "地方财政风险和成本分配。",
          "startFrame": 599,
          "durationInFrames": 68
        }
      ]
    },
    "durationInFrames": 667,
    "durationInSeconds": 22.24,
    "format": "wav",
    "narration": "白宫计划召集公用事业公司、数据中心开发商和州政府，推动一项自愿承诺：AI 公司和数据中心运营方应承担新增发电、电网升级和预留容量成本，避免把费用转嫁给普通居民。这意味着 AI 监管正在从模型安全扩展到电力、水资源、地方财政风险和成本分配。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "us-policy"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/eu-copyright.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "欧盟委员会发布可行性研究，",
          "startFrame": 0,
          "durationInFrames": 75
        },
        {
          "id": "caption-2",
          "text": "评估建立统一的文本与数据挖掘退出登记系统。",
          "startFrame": 75,
          "durationInFrames": 121
        },
        {
          "id": "caption-3",
          "text": "版权所有者可以登记不允许其作品被用于模型训练。",
          "startFrame": 196,
          "durationInFrames": 132
        },
        {
          "id": "caption-4",
          "text": "这目前仍是研究方案，",
          "startFrame": 328,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "但未来数据合规可能不只是有没有版权，",
          "startFrame": 386,
          "durationInFrames": 104
        },
        {
          "id": "caption-6",
          "text": "还包括是否能够机器化读取权利人的退出声明。",
          "startFrame": 490,
          "durationInFrames": 121
        },
        {
          "id": "caption-7",
          "text": "同一天，",
          "startFrame": 611,
          "durationInFrames": 23
        },
        {
          "id": "caption-8",
          "text": "超过 200 名专家呼吁政府提前建立应对 AI 经济影响的政策和制度。",
          "startFrame": 634,
          "durationInFrames": 201
        }
      ]
    },
    "durationInFrames": 835,
    "durationInSeconds": 27.84,
    "format": "wav",
    "narration": "欧盟委员会发布可行性研究，评估建立统一的文本与数据挖掘退出登记系统。版权所有者可以登记不允许其作品被用于模型训练。这目前仍是研究方案，但未来数据合规可能不只是有没有版权，还包括是否能够机器化读取权利人的退出声明。同一天，超过 200 名专家呼吁政府提前建立应对 AI 经济影响的政策和制度。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "eu-copyright"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/helsing.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "欧洲国防 AI 公司 Helsing 完成 18 亿美元 E 轮融资，",
          "startFrame": 0,
          "durationInFrames": 156
        },
        {
          "id": "caption-2",
          "text": "估值 180 亿美元。",
          "startFrame": 156,
          "durationInFrames": 49
        },
        {
          "id": "caption-3",
          "text": "投资者包括 Lightspeed、",
          "startFrame": 205,
          "durationInFrames": 76
        },
        {
          "id": "caption-4",
          "text": "General Catalyst、",
          "startFrame": 281,
          "durationInFrames": 76
        },
        {
          "id": "caption-5",
          "text": "Goldman Sachs 等。",
          "startFrame": 357,
          "durationInFrames": 71
        },
        {
          "id": "caption-6",
          "text": "Helsing 业务从战场数据分析扩展到自主无人机、",
          "startFrame": 428,
          "durationInFrames": 116
        },
        {
          "id": "caption-7",
          "text": "水下监控、",
          "startFrame": 544,
          "durationInFrames": 22
        },
        {
          "id": "caption-8",
          "text": "军用航空和实时目标识别。",
          "startFrame": 566,
          "durationInFrames": 54
        },
        {
          "id": "caption-9",
          "text": "资本正在将国防 AI 视为独立的大型产业，",
          "startFrame": 620,
          "durationInFrames": 94
        },
        {
          "id": "caption-10",
          "text": "防务、",
          "startFrame": 714,
          "durationInFrames": 13
        },
        {
          "id": "caption-11",
          "text": "主权算力与 AI 正逐渐合并为同一投资主题。",
          "startFrame": 727,
          "durationInFrames": 99
        }
      ]
    },
    "durationInFrames": 826,
    "durationInSeconds": 27.52,
    "format": "wav",
    "narration": "欧洲国防 AI 公司 Helsing 完成 18 亿美元 E 轮融资，估值 180 亿美元。投资者包括 Lightspeed、General Catalyst、Goldman Sachs 等。Helsing 业务从战场数据分析扩展到自主无人机、水下监控、军用航空和实时目标识别。资本正在将国防 AI 视为独立的大型产业，防务、主权算力与 AI 正逐渐合并为同一投资主题。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "helsing"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/trend-summary.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 竞争基础设施化：",
          "startFrame": 0,
          "durationInFrames": 61
        },
        {
          "id": "caption-2",
          "text": "Meta 5GW 和 Intel 投资显示电力和芯片成为核心壁垒。",
          "startFrame": 61,
          "durationInFrames": 184
        },
        {
          "id": "caption-3",
          "text": "Agent 架构分层：",
          "startFrame": 245,
          "durationInFrames": 61
        },
        {
          "id": "caption-4",
          "text": "GPT-Live 和 GPT-5.6 推动单模型到多模型编排。",
          "startFrame": 306,
          "durationInFrames": 172
        },
        {
          "id": "caption-5",
          "text": "监管对象扩大：",
          "startFrame": 478,
          "durationInFrames": 39
        },
        {
          "id": "caption-6",
          "text": "电价、",
          "startFrame": 517,
          "durationInFrames": 17
        },
        {
          "id": "caption-7",
          "text": "版权退出和就业影响使合规从模型层进入完整产业链。",
          "startFrame": 534,
          "durationInFrames": 133
        },
        {
          "id": "caption-8",
          "text": "资本继续头部集中：",
          "startFrame": 667,
          "durationInFrames": 50
        },
        {
          "id": "caption-9",
          "text": "Helsing 融资验证国防 AI 成为热门赛道。",
          "startFrame": 717,
          "durationInFrames": 139
        },
        {
          "id": "caption-10",
          "text": "AI 主权化：",
          "startFrame": 856,
          "durationInFrames": 39
        },
        {
          "id": "caption-11",
          "text": "中美欧均强化控制和评估，",
          "startFrame": 895,
          "durationInFrames": 67
        },
        {
          "id": "caption-12",
          "text": "全球统一模型和服务可能逐渐分区。",
          "startFrame": 962,
          "durationInFrames": 89
        }
      ]
    },
    "durationInFrames": 1051,
    "durationInSeconds": 35.04,
    "format": "wav",
    "narration": "AI 竞争基础设施化：Meta 5GW 和 Intel 投资显示电力和芯片成为核心壁垒。Agent 架构分层：GPT-Live 和 GPT-5.6 推动单模型到多模型编排。监管对象扩大：电价、版权退出和就业影响使合规从模型层进入完整产业链。资本继续头部集中：Helsing 融资验证国防 AI 成为热门赛道。AI 主权化：中美欧均强化控制和评估，全球统一模型和服务可能逐渐分区。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "trend-summary"
  },
  {
    "audioFile": "generated/ai-daily-news-2026-07-13/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "对 Agent 开发者今天最值得关注的一点是：",
          "startFrame": 0,
          "durationInFrames": 140
        },
        {
          "id": "caption-2",
          "text": "模型本身正逐渐成为可替换的执行组件，",
          "startFrame": 140,
          "durationInFrames": 110
        },
        {
          "id": "caption-3",
          "text": "真正长期有价值的层开始转向任务编排、",
          "startFrame": 250,
          "durationInFrames": 110
        },
        {
          "id": "caption-4",
          "text": "工具与数据授权、",
          "startFrame": 360,
          "durationInFrames": 49
        },
        {
          "id": "caption-5",
          "text": "执行验证、",
          "startFrame": 409,
          "durationInFrames": 30
        },
        {
          "id": "caption-6",
          "text": "成本控制和可靠性交付。",
          "startFrame": 439,
          "durationInFrames": 67
        },
        {
          "id": "caption-7",
          "text": "这与为其他 Agent 提供可靠能力服务的方向高度一致。",
          "startFrame": 506,
          "durationInFrames": 171
        }
      ]
    },
    "durationInFrames": 677,
    "durationInSeconds": 22.56,
    "format": "wav",
    "narration": "对 Agent 开发者今天最值得关注的一点是：模型本身正逐渐成为可替换的执行组件，真正长期有价值的层开始转向任务编排、工具与数据授权、执行验证、成本控制和可靠性交付。这与为其他 Agent 提供可靠能力服务的方向高度一致。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "close"
  }
];
