// Generated by the direct VoxCPM Producer runtime for the editorial TCP handshake proof.

import type { TcpHandshakeEditorialAudioTrack } from "./types";

export const tcpHandshakeEditorialAudio = [
  {
    sceneId: "syn",
    narration: "第一步，客户端发送 SYN，并带上自己的初始序列号，请求建立 TCP 连接。",
    audioFile: "generated/tcp-handshake-editorial/audio/syn.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第一步，",
          startFrame: 0,
          durationInFrames: 26,
        },
        {
          id: "caption-2",
          text: "客户端发送 SYN，",
          startFrame: 26,
          durationInFrames: 56,
        },
        {
          id: "caption-3",
          text: "并带上自己的初始序列号，",
          startFrame: 82,
          durationInFrames: 61,
        },
        {
          id: "caption-4",
          text: "请求建立 TCP 连接。",
          startFrame: 143,
          durationInFrames: 67,
        },
      ],
    },
    durationInFrames: 210,
    durationInSeconds: 6.998083333333334,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "syn-ack",
    narration: "第二步，服务端回复 SYN-ACK，既确认客户端的序列号，也发送自己的初始序列号。",
    audioFile: "generated/tcp-handshake-editorial/audio/syn-ack.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第二步，",
          startFrame: 0,
          durationInFrames: 22,
        },
        {
          id: "caption-2",
          text: "服务端回复 SYN-ACK，",
          startFrame: 22,
          durationInFrames: 82,
        },
        {
          id: "caption-3",
          text: "既确认客户端的序列号，",
          startFrame: 104,
          durationInFrames: 59,
        },
        {
          id: "caption-4",
          text: "也发送自己的初始序列号。",
          startFrame: 163,
          durationInFrames: 67,
        },
      ],
    },
    durationInFrames: 230,
    durationInSeconds: 7.656770833333334,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "ack",
    narration: "第三步，客户端发送 ACK 完成确认，双方进入已建立状态，可以开始传输数据。",
    audioFile: "generated/tcp-handshake-editorial/audio/ack.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "第三步，",
          startFrame: 0,
          durationInFrames: 25,
        },
        {
          id: "caption-2",
          text: "客户端发送 ACK 完成确认，",
          startFrame: 25,
          durationInFrames: 84,
        },
        {
          id: "caption-3",
          text: "双方进入已建立状态，",
          startFrame: 109,
          durationInFrames: 62,
        },
        {
          id: "caption-4",
          text: "可以开始传输数据。",
          startFrame: 171,
          durationInFrames: 47,
        },
      ],
    },
    durationInFrames: 218,
    durationInSeconds: 7.273541666666667,
    provider: "voxcpm",
    format: "wav",
  },
] satisfies readonly TcpHandshakeEditorialAudioTrack[];
