#!/usr/bin/env node

import { readFile } from "node:fs/promises";

import {
  createVoxcpmProducerRequestPlan,
  readProducerVoxcpmConfig,
  requestProducerNarrationAsset,
  runProducerAudioGeneration,
} from "../../../scripts/lib/producer-audio/index.js";
import { tcpHandshakeEditorialNarrationBeats } from "./script.js";

const root = "src/remotion/TcpHandshakeEditorial";
const slug = "tcp-handshake-editorial";
const voxcpmConfig = readProducerVoxcpmConfig();

await runProducerAudioGeneration({
  compositionId: "TcpHandshakeEditorial",
  beats: tcpHandshakeEditorialNarrationBeats,
  createRequestPlan: (beat) =>
    createVoxcpmProducerRequestPlan({
      beat,
      mode: "high-fidelity-clone",
      promptAudioPath: "voices/clone/lyy.wav",
      promptTranscriptPath: "voices/clone/lyy.txt",
      referenceAudioPath: "voices/clone/lyy-r.wav",
    }),
  requestNarration: ({ plan }) =>
    requestProducerNarrationAsset({ config: voxcpmConfig, plan, slug }),
  progressDestination: `public/generated/${slug}/audio/progress.json`,
  metadata: {
    header:
      "Generated by the direct VoxCPM Producer runtime for the editorial TCP handshake proof.",
    exportName: "tcpHandshakeEditorialAudio",
    typeImport: { name: "TcpHandshakeEditorialAudioTrack", path: "./types" },
    destination: `${root}/audio.generated.ts`,
  },
  duration: {
    source: await readFile(`${root}/types.ts`, "utf8"),
    constantName: "TCP_HANDSHAKE_EDITORIAL_DURATION_IN_FRAMES",
    destination: `${root}/types.ts`,
  },
  summaryDestination: `public/generated/${slug}/audio/summary.json`,
  writeOutputs: true,
});
