// Auto-generated by scripts/generate-beyond-language-tts.mjs
// Voice clone: LYY (high-fidelity clone_with_prompt)
// 2026-07-15T07:30:32.365Z

import type { AudioTrack } from "./types";

export const audioTracks: AudioTrack[] = [
  {
    "audioFile": "generated/beyond-language/s01.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天最强的 AI，",
          "startFrame": 0,
          "durationInFrames": 52
        },
        {
          "id": "caption-2",
          "text": "可能存在一个根本缺陷：",
          "startFrame": 52,
          "durationInFrames": 64
        },
        {
          "id": "caption-3",
          "text": "它们太依赖语言了。",
          "startFrame": 116,
          "durationInFrames": 52
        },
        {
          "id": "caption-4",
          "text": "我们把语言能力当成智能的证明，",
          "startFrame": 168,
          "durationInFrames": 87
        },
        {
          "id": "caption-5",
          "text": "但语言也可能正在限制 AI 的上限。",
          "startFrame": 255,
          "durationInFrames": 105
        }
      ]
    },
    "durationInFrames": 360,
    "durationInSeconds": 12,
    "format": "wav",
    "narration": "今天最强的 AI，可能存在一个根本缺陷：它们太依赖语言了。我们把语言能力当成智能的证明，但语言也可能正在限制 AI 的上限。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s01"
  },
  {
    "audioFile": "generated/beyond-language/s02.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型最大的幻觉，",
          "startFrame": 0,
          "durationInFrames": 63
        },
        {
          "id": "caption-2",
          "text": "不是偶尔说错一句话。",
          "startFrame": 63,
          "durationInFrames": 63
        },
        {
          "id": "caption-3",
          "text": "而是它会让我们误以为：",
          "startFrame": 126,
          "durationInFrames": 69
        },
        {
          "id": "caption-4",
          "text": "只要一个系统足够会说，",
          "startFrame": 195,
          "durationInFrames": 69
        },
        {
          "id": "caption-5",
          "text": "它就一定真正理解了世界。",
          "startFrame": 264,
          "durationInFrames": 77
        }
      ]
    },
    "durationInFrames": 341,
    "durationInSeconds": 11.36,
    "format": "wav",
    "narration": "语言模型最大的幻觉，不是偶尔说错一句话。而是它会让我们误以为：只要一个系统足够会说，它就一定真正理解了世界。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s02"
  },
  {
    "audioFile": "generated/beyond-language/s03.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型可以非常流畅地解释一个杯子为什么会掉到地上。",
          "startFrame": 0,
          "durationInFrames": 137
        },
        {
          "id": "caption-2",
          "text": "但「能够解释重力」",
          "startFrame": 137,
          "durationInFrames": 47
        },
        {
          "id": "caption-3",
          "text": "，",
          "startFrame": 184,
          "durationInFrames": 5
        },
        {
          "id": "caption-4",
          "text": "和「真正预测杯子接下来如何运动」",
          "startFrame": 189,
          "durationInFrames": 84
        },
        {
          "id": "caption-5",
          "text": "，",
          "startFrame": 273,
          "durationInFrames": 5
        },
        {
          "id": "caption-6",
          "text": "并不是同一种能力。",
          "startFrame": 278,
          "durationInFrames": 48
        }
      ]
    },
    "durationInFrames": 326,
    "durationInSeconds": 10.88,
    "format": "wav",
    "narration": "语言模型可以非常流畅地解释一个杯子为什么会掉到地上。但「能够解释重力」，和「真正预测杯子接下来如何运动」，并不是同一种能力。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s03"
  },
  {
    "audioFile": "generated/beyond-language/s04.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "它可以写出一份逻辑完整的系统架构分析。",
          "startFrame": 0,
          "durationInFrames": 110
        },
        {
          "id": "caption-2",
          "text": "每个术语都正确，",
          "startFrame": 110,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "每段推理都很专业。",
          "startFrame": 156,
          "durationInFrames": 52
        },
        {
          "id": "caption-4",
          "text": "但系统真正上线后，",
          "startFrame": 208,
          "durationInFrames": 52
        },
        {
          "id": "caption-5",
          "text": "依然可能立刻崩溃。",
          "startFrame": 260,
          "durationInFrames": 52
        }
      ]
    },
    "durationInFrames": 312,
    "durationInSeconds": 10.4,
    "format": "wav",
    "narration": "它可以写出一份逻辑完整的系统架构分析。每个术语都正确，每段推理都很专业。但系统真正上线后，依然可能立刻崩溃。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s04"
  },
  {
    "audioFile": "generated/beyond-language/s05.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "因为语言追求的是：",
          "startFrame": 0,
          "durationInFrames": 54
        },
        {
          "id": "caption-2",
          "text": "下一句话听起来是否合理。",
          "startFrame": 54,
          "durationInFrames": 73
        },
        {
          "id": "caption-3",
          "text": "现实世界关心的却是：",
          "startFrame": 127,
          "durationInFrames": 60
        },
        {
          "id": "caption-4",
          "text": "下一秒究竟会发生什么。",
          "startFrame": 187,
          "durationInFrames": 67
        }
      ]
    },
    "durationInFrames": 254,
    "durationInSeconds": 8.48,
    "format": "wav",
    "narration": "因为语言追求的是：下一句话听起来是否合理。现实世界关心的却是：下一秒究竟会发生什么。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s05"
  },
  {
    "audioFile": "generated/beyond-language/s06.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就是语言模型的第一层缺陷：",
          "startFrame": 0,
          "durationInFrames": 84
        },
        {
          "id": "caption-2",
          "text": "语言可以描述现实，",
          "startFrame": 84,
          "durationInFrames": 54
        },
        {
          "id": "caption-3",
          "text": "却不等于现实本身。",
          "startFrame": 138,
          "durationInFrames": 54
        },
        {
          "id": "caption-4",
          "text": "一句话完全符合语法和逻辑，",
          "startFrame": 192,
          "durationInFrames": 78
        },
        {
          "id": "caption-5",
          "text": "也可能完全不符合真实世界。",
          "startFrame": 270,
          "durationInFrames": 80
        }
      ]
    },
    "durationInFrames": 350,
    "durationInSeconds": 11.68,
    "format": "wav",
    "narration": "这就是语言模型的第一层缺陷：语言可以描述现实，却不等于现实本身。一句话完全符合语法和逻辑，也可能完全不符合真实世界。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s06"
  },
  {
    "audioFile": "generated/beyond-language/s07.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型主要从文字中学习世界。",
          "startFrame": 0,
          "durationInFrames": 99
        },
        {
          "id": "caption-2",
          "text": "它阅读大量关于物体、",
          "startFrame": 99,
          "durationInFrames": 66
        },
        {
          "id": "caption-3",
          "text": "空间、",
          "startFrame": 165,
          "durationInFrames": 20
        },
        {
          "id": "caption-4",
          "text": "时间、",
          "startFrame": 185,
          "durationInFrames": 20
        },
        {
          "id": "caption-5",
          "text": "因果和动作的描述。",
          "startFrame": 205,
          "durationInFrames": 59
        },
        {
          "id": "caption-6",
          "text": "但它接触到的，",
          "startFrame": 264,
          "durationInFrames": 46
        },
        {
          "id": "caption-7",
          "text": "往往只是别人对现实的二次记录。",
          "startFrame": 310,
          "durationInFrames": 98
        }
      ]
    },
    "durationInFrames": 408,
    "durationInSeconds": 13.6,
    "format": "wav",
    "narration": "语言模型主要从文字中学习世界。它阅读大量关于物体、空间、时间、因果和动作的描述。但它接触到的，往往只是别人对现实的二次记录。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s07"
  },
  {
    "audioFile": "generated/beyond-language/s08.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就像一个人读完了世界上所有游泳教材，",
          "startFrame": 0,
          "durationInFrames": 117
        },
        {
          "id": "caption-2",
          "text": "却从来没有真正进入水里。",
          "startFrame": 117,
          "durationInFrames": 74
        },
        {
          "id": "caption-3",
          "text": "他可能非常擅长解释游泳，",
          "startFrame": 191,
          "durationInFrames": 74
        },
        {
          "id": "caption-4",
          "text": "但这不意味着他真的会游泳。",
          "startFrame": 265,
          "durationInFrames": 81
        }
      ]
    },
    "durationInFrames": 346,
    "durationInSeconds": 11.52,
    "format": "wav",
    "narration": "这就像一个人读完了世界上所有游泳教材，却从来没有真正进入水里。他可能非常擅长解释游泳，但这不意味着他真的会游泳。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s08"
  },
  {
    "audioFile": "generated/beyond-language/s09.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型的第二层缺陷，",
          "startFrame": 0,
          "durationInFrames": 72
        },
        {
          "id": "caption-2",
          "text": "是语言本身的信息带宽太低。",
          "startFrame": 72,
          "durationInFrames": 85
        },
        {
          "id": "caption-3",
          "text": "现实中的一个瞬间，",
          "startFrame": 157,
          "durationInFrames": 59
        },
        {
          "id": "caption-4",
          "text": "可能同时包含空间、",
          "startFrame": 216,
          "durationInFrames": 59
        },
        {
          "id": "caption-5",
          "text": "声音、",
          "startFrame": 275,
          "durationInFrames": 20
        },
        {
          "id": "caption-6",
          "text": "速度、",
          "startFrame": 295,
          "durationInFrames": 20
        },
        {
          "id": "caption-7",
          "text": "力量、",
          "startFrame": 315,
          "durationInFrames": 20
        },
        {
          "id": "caption-8",
          "text": "意图和风险。",
          "startFrame": 335,
          "durationInFrames": 39
        },
        {
          "id": "caption-9",
          "text": "但语言只能一个词接着一个词地表达。",
          "startFrame": 374,
          "durationInFrames": 111
        }
      ]
    },
    "durationInFrames": 485,
    "durationInSeconds": 16.16,
    "format": "wav",
    "narration": "语言模型的第二层缺陷，是语言本身的信息带宽太低。现实中的一个瞬间，可能同时包含空间、声音、速度、力量、意图和风险。但语言只能一个词接着一个词地表达。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s09"
  },
  {
    "audioFile": "generated/beyond-language/s10.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "你脑中可能已经有一个完整的产品结构。",
          "startFrame": 0,
          "durationInFrames": 99
        },
        {
          "id": "caption-2",
          "text": "不同模块之间的关系、",
          "startFrame": 99,
          "durationInFrames": 55
        },
        {
          "id": "caption-3",
          "text": "用户体验、",
          "startFrame": 154,
          "durationInFrames": 27
        },
        {
          "id": "caption-4",
          "text": "技术风险和商业目标，",
          "startFrame": 181,
          "durationInFrames": 55
        },
        {
          "id": "caption-5",
          "text": "同时存在。",
          "startFrame": 236,
          "durationInFrames": 27
        },
        {
          "id": "caption-6",
          "text": "但当你向 AI 描述时，",
          "startFrame": 263,
          "durationInFrames": 66
        },
        {
          "id": "caption-7",
          "text": "只能把它们压缩成一段 Prompt。",
          "startFrame": 329,
          "durationInFrames": 98
        }
      ]
    },
    "durationInFrames": 427,
    "durationInSeconds": 14.24,
    "format": "wav",
    "narration": "你脑中可能已经有一个完整的产品结构。不同模块之间的关系、用户体验、技术风险和商业目标，同时存在。但当你向 AI 描述时，只能把它们压缩成一段 Prompt。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s10"
  },
  {
    "audioFile": "generated/beyond-language/s11.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 再根据这段文字，",
          "startFrame": 0,
          "durationInFrames": 68
        },
        {
          "id": "caption-2",
          "text": "尝试还原你原来的想法。",
          "startFrame": 68,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "这个过程就像：",
          "startFrame": 136,
          "durationInFrames": 43
        },
        {
          "id": "caption-4",
          "text": "你先把一个三维物体压成一张纸，",
          "startFrame": 179,
          "durationInFrames": 93
        },
        {
          "id": "caption-5",
          "text": "再要求另一个人根据这张纸恢复原物。",
          "startFrame": 272,
          "durationInFrames": 107
        }
      ]
    },
    "durationInFrames": 379,
    "durationInSeconds": 12.64,
    "format": "wav",
    "narration": "AI 再根据这段文字，尝试还原你原来的想法。这个过程就像：你先把一个三维物体压成一张纸，再要求另一个人根据这张纸恢复原物。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s11"
  },
  {
    "audioFile": "generated/beyond-language/s12.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "因此，",
          "startFrame": 0,
          "durationInFrames": 17
        },
        {
          "id": "caption-2",
          "text": "很多所谓的 Prompt 问题，",
          "startFrame": 17,
          "durationInFrames": 89
        },
        {
          "id": "caption-3",
          "text": "本质上并不是提示词写得不够好。",
          "startFrame": 106,
          "durationInFrames": 83
        },
        {
          "id": "caption-4",
          "text": "而是一个高维意图，",
          "startFrame": 189,
          "durationInFrames": 50
        },
        {
          "id": "caption-5",
          "text": "被迫通过低维语言传递时，",
          "startFrame": 239,
          "durationInFrames": 66
        },
        {
          "id": "caption-6",
          "text": "已经发生了信息损失。",
          "startFrame": 305,
          "durationInFrames": 55
        }
      ]
    },
    "durationInFrames": 360,
    "durationInSeconds": 12,
    "format": "wav",
    "narration": "因此，很多所谓的 Prompt 问题，本质上并不是提示词写得不够好。而是一个高维意图，被迫通过低维语言传递时，已经发生了信息损失。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s12"
  },
  {
    "audioFile": "generated/beyond-language/s13.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型的第三层缺陷，",
          "startFrame": 0,
          "durationInFrames": 65
        },
        {
          "id": "caption-2",
          "text": "是它太容易把「解释」",
          "startFrame": 65,
          "durationInFrames": 59
        },
        {
          "id": "caption-3",
          "text": "误认为「解决」",
          "startFrame": 124,
          "durationInFrames": 41
        },
        {
          "id": "caption-4",
          "text": "。",
          "startFrame": 165,
          "durationInFrames": 6
        },
        {
          "id": "caption-5",
          "text": "它可以告诉你应该如何修改代码、",
          "startFrame": 171,
          "durationInFrames": 88
        },
        {
          "id": "caption-6",
          "text": "如何修复服务器、",
          "startFrame": 259,
          "durationInFrames": 47
        },
        {
          "id": "caption-7",
          "text": "如何运营公司。",
          "startFrame": 306,
          "durationInFrames": 41
        },
        {
          "id": "caption-8",
          "text": "但解释一个动作，",
          "startFrame": 347,
          "durationInFrames": 47
        },
        {
          "id": "caption-9",
          "text": "和真正执行一个动作，",
          "startFrame": 394,
          "durationInFrames": 59
        },
        {
          "id": "caption-10",
          "text": "存在巨大差距。",
          "startFrame": 453,
          "durationInFrames": 41
        }
      ]
    },
    "durationInFrames": 494,
    "durationInSeconds": 16.48,
    "format": "wav",
    "narration": "语言模型的第三层缺陷，是它太容易把「解释」误认为「解决」。它可以告诉你应该如何修改代码、如何修复服务器、如何运营公司。但解释一个动作，和真正执行一个动作，存在巨大差距。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s13"
  },
  {
    "audioFile": "generated/beyond-language/s14.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天很多 AI 的工作方式仍然是：",
          "startFrame": 0,
          "durationInFrames": 100
        },
        {
          "id": "caption-2",
          "text": "先生成一段文字计划，",
          "startFrame": 100,
          "durationInFrames": 59
        },
        {
          "id": "caption-3",
          "text": "再把这段文字交给另一个模型或工具解析。",
          "startFrame": 159,
          "durationInFrames": 112
        },
        {
          "id": "caption-4",
          "text": "每经过一次语言转换，",
          "startFrame": 271,
          "durationInFrames": 59
        },
        {
          "id": "caption-5",
          "text": "就可能增加一次误解。",
          "startFrame": 330,
          "durationInFrames": 59
        }
      ]
    },
    "durationInFrames": 389,
    "durationInSeconds": 12.96,
    "format": "wav",
    "narration": "今天很多 AI 的工作方式仍然是：先生成一段文字计划，再把这段文字交给另一个模型或工具解析。每经过一次语言转换，就可能增加一次误解。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s14"
  },
  {
    "audioFile": "generated/beyond-language/s15.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "一个 Agent 发现系统存在风险。",
          "startFrame": 0,
          "durationInFrames": 94
        },
        {
          "id": "caption-2",
          "text": "它先把自己的判断写成文字。",
          "startFrame": 94,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "另一个 Agent 阅读这段文字，",
          "startFrame": 162,
          "durationInFrames": 89
        },
        {
          "id": "caption-4",
          "text": "再重新建立自己的判断。",
          "startFrame": 251,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "高维状态被压缩一次，",
          "startFrame": 309,
          "durationInFrames": 52
        },
        {
          "id": "caption-6",
          "text": "又被猜测着还原一次。",
          "startFrame": 361,
          "durationInFrames": 52
        }
      ]
    },
    "durationInFrames": 413,
    "durationInSeconds": 13.76,
    "format": "wav",
    "narration": "一个 Agent 发现系统存在风险。它先把自己的判断写成文字。另一个 Agent 阅读这段文字，再重新建立自己的判断。高维状态被压缩一次，又被猜测着还原一次。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s15"
  },
  {
    "audioFile": "generated/beyond-language/s16.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的 AI，",
          "startFrame": 0,
          "durationInFrames": 39
        },
        {
          "id": "caption-2",
          "text": "可能不再依赖这种低效方式。",
          "startFrame": 39,
          "durationInFrames": 73
        },
        {
          "id": "caption-3",
          "text": "两个 Agent 之间，",
          "startFrame": 112,
          "durationInFrames": 67
        },
        {
          "id": "caption-4",
          "text": "不一定需要发送一段「我认为这里可能存在数据库瓶颈」",
          "startFrame": 179,
          "durationInFrames": 140
        },
        {
          "id": "caption-5",
          "text": "的文字。",
          "startFrame": 319,
          "durationInFrames": 22
        },
        {
          "id": "caption-6",
          "text": "它们可能直接交换完整的内部状态。",
          "startFrame": 341,
          "durationInFrames": 91
        }
      ]
    },
    "durationInFrames": 432,
    "durationInSeconds": 14.4,
    "format": "wav",
    "narration": "未来的 AI，可能不再依赖这种低效方式。两个 Agent 之间，不一定需要发送一段「我认为这里可能存在数据库瓶颈」的文字。它们可能直接交换完整的内部状态。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s16"
  },
  {
    "audioFile": "generated/beyond-language/s17.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "其中可以同时包含：",
          "startFrame": 0,
          "durationInFrames": 59
        },
        {
          "id": "caption-2",
          "text": "风险概率、",
          "startFrame": 59,
          "durationInFrames": 33
        },
        {
          "id": "caption-3",
          "text": "依赖关系、",
          "startFrame": 92,
          "durationInFrames": 33
        },
        {
          "id": "caption-4",
          "text": "时间预测、",
          "startFrame": 125,
          "durationInFrames": 33
        },
        {
          "id": "caption-5",
          "text": "目标优先级、",
          "startFrame": 158,
          "durationInFrames": 40
        },
        {
          "id": "caption-6",
          "text": "证据来源和不确定性。",
          "startFrame": 198,
          "durationInFrames": 66
        },
        {
          "id": "caption-7",
          "text": "这类信息不需要先翻译成人类语言。",
          "startFrame": 264,
          "durationInFrames": 106
        }
      ]
    },
    "durationInFrames": 370,
    "durationInSeconds": 12.32,
    "format": "wav",
    "narration": "其中可以同时包含：风险概率、依赖关系、时间预测、目标优先级、证据来源和不确定性。这类信息不需要先翻译成人类语言。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s17"
  },
  {
    "audioFile": "generated/beyond-language/s18.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就是潜在空间通信。",
          "startFrame": 0,
          "durationInFrames": 64
        },
        {
          "id": "caption-2",
          "text": "模型之间不再只交换 Token，",
          "startFrame": 64,
          "durationInFrames": 102
        },
        {
          "id": "caption-3",
          "text": "而是尝试直接交换更丰富的内部表示。",
          "startFrame": 166,
          "durationInFrames": 109
        },
        {
          "id": "caption-4",
          "text": "语言像是一张截图。",
          "startFrame": 275,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "潜在状态更像一个可以继续编辑的工程文件。",
          "startFrame": 333,
          "durationInFrames": 128
        }
      ]
    },
    "durationInFrames": 461,
    "durationInSeconds": 15.36,
    "format": "wav",
    "narration": "这就是潜在空间通信。模型之间不再只交换 Token，而是尝试直接交换更丰富的内部表示。语言像是一张截图。潜在状态更像一个可以继续编辑的工程文件。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s18"
  },
  {
    "audioFile": "generated/beyond-language/s19.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "但这并不意味着，",
          "startFrame": 0,
          "durationInFrames": 51
        },
        {
          "id": "caption-2",
          "text": "未来的 AI 会彻底抛弃语言。",
          "startFrame": 51,
          "durationInFrames": 96
        },
        {
          "id": "caption-3",
          "text": "真正发生的变化，",
          "startFrame": 147,
          "durationInFrames": 51
        },
        {
          "id": "caption-4",
          "text": "是语言的位置会发生改变。",
          "startFrame": 198,
          "durationInFrames": 76
        }
      ]
    },
    "durationInFrames": 274,
    "durationInSeconds": 9.12,
    "format": "wav",
    "narration": "但这并不意味着，未来的 AI 会彻底抛弃语言。真正发生的变化，是语言的位置会发生改变。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s19"
  },
  {
    "audioFile": "generated/beyond-language/s20.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天，",
          "startFrame": 0,
          "durationInFrames": 16
        },
        {
          "id": "caption-2",
          "text": "语言几乎贯穿 AI 的整个工作流程。",
          "startFrame": 16,
          "durationInFrames": 98
        },
        {
          "id": "caption-3",
          "text": "人类用语言下达任务。",
          "startFrame": 114,
          "durationInFrames": 55
        },
        {
          "id": "caption-4",
          "text": "模型用语言进行规划。",
          "startFrame": 169,
          "durationInFrames": 55
        },
        {
          "id": "caption-5",
          "text": "Agent 用语言传递状态。",
          "startFrame": 224,
          "durationInFrames": 76
        },
        {
          "id": "caption-6",
          "text": "最后再用语言汇报结果。",
          "startFrame": 300,
          "durationInFrames": 60
        }
      ]
    },
    "durationInFrames": 360,
    "durationInSeconds": 12,
    "format": "wav",
    "narration": "今天，语言几乎贯穿 AI 的整个工作流程。人类用语言下达任务。模型用语言进行规划。Agent 用语言传递状态。最后再用语言汇报结果。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s20"
  },
  {
    "audioFile": "generated/beyond-language/s21.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来，",
          "startFrame": 0,
          "durationInFrames": 18
        },
        {
          "id": "caption-2",
          "text": "语言可能只保留在系统的外层。",
          "startFrame": 18,
          "durationInFrames": 83
        },
        {
          "id": "caption-3",
          "text": "人类仍然可以用语言表达目标。",
          "startFrame": 101,
          "durationInFrames": 83
        },
        {
          "id": "caption-4",
          "text": "AI 也仍然可以用语言解释结果。",
          "startFrame": 184,
          "durationInFrames": 94
        },
        {
          "id": "caption-5",
          "text": "但 AI 内部的认知、",
          "startFrame": 278,
          "durationInFrames": 65
        },
        {
          "id": "caption-6",
          "text": "协作和行动，",
          "startFrame": 343,
          "durationInFrames": 35
        },
        {
          "id": "caption-7",
          "text": "不一定还需要经过语言。",
          "startFrame": 378,
          "durationInFrames": 64
        }
      ]
    },
    "durationInFrames": 442,
    "durationInSeconds": 14.72,
    "format": "wav",
    "narration": "未来，语言可能只保留在系统的外层。人类仍然可以用语言表达目标。AI 也仍然可以用语言解释结果。但 AI 内部的认知、协作和行动，不一定还需要经过语言。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s21"
  },
  {
    "audioFile": "generated/beyond-language/s22.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这种变化的第一步，",
          "startFrame": 0,
          "durationInFrames": 58
        },
        {
          "id": "caption-2",
          "text": "是从语言模型走向原生多模态模型。",
          "startFrame": 58,
          "durationInFrames": 102
        },
        {
          "id": "caption-3",
          "text": "模型不再只阅读人类如何描述世界。",
          "startFrame": 160,
          "durationInFrames": 102
        },
        {
          "id": "caption-4",
          "text": "它开始直接观察图像、",
          "startFrame": 262,
          "durationInFrames": 64
        },
        {
          "id": "caption-5",
          "text": "视频、",
          "startFrame": 326,
          "durationInFrames": 19
        },
        {
          "id": "caption-6",
          "text": "声音、",
          "startFrame": 345,
          "durationInFrames": 19
        },
        {
          "id": "caption-7",
          "text": "传感器和环境反馈。",
          "startFrame": 364,
          "durationInFrames": 58
        }
      ]
    },
    "durationInFrames": 422,
    "durationInSeconds": 14.08,
    "format": "wav",
    "narration": "这种变化的第一步，是从语言模型走向原生多模态模型。模型不再只阅读人类如何描述世界。它开始直接观察图像、视频、声音、传感器和环境反馈。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s22"
  },
  {
    "audioFile": "generated/beyond-language/s23.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "现在的语言模型，",
          "startFrame": 0,
          "durationInFrames": 50
        },
        {
          "id": "caption-2",
          "text": "通过阅读大量「苹果掉到地上」",
          "startFrame": 50,
          "durationInFrames": 88
        },
        {
          "id": "caption-3",
          "text": "的文字来理解重力。",
          "startFrame": 138,
          "durationInFrames": 56
        },
        {
          "id": "caption-4",
          "text": "未来的模型，",
          "startFrame": 194,
          "durationInFrames": 38
        },
        {
          "id": "caption-5",
          "text": "会直接观察苹果如何下落、",
          "startFrame": 232,
          "durationInFrames": 75
        },
        {
          "id": "caption-6",
          "text": "如何碰撞、",
          "startFrame": 307,
          "durationInFrames": 31
        },
        {
          "id": "caption-7",
          "text": "如何滚动，",
          "startFrame": 338,
          "durationInFrames": 31
        },
        {
          "id": "caption-8",
          "text": "以及不同条件如何改变结果。",
          "startFrame": 369,
          "durationInFrames": 82
        }
      ]
    },
    "durationInFrames": 451,
    "durationInSeconds": 15.04,
    "format": "wav",
    "narration": "现在的语言模型，通过阅读大量「苹果掉到地上」的文字来理解重力。未来的模型，会直接观察苹果如何下落、如何碰撞、如何滚动，以及不同条件如何改变结果。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s23"
  },
  {
    "audioFile": "generated/beyond-language/s24.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "它学习的重点，",
          "startFrame": 0,
          "durationInFrames": 41
        },
        {
          "id": "caption-2",
          "text": "不再只是：",
          "startFrame": 41,
          "durationInFrames": 29
        },
        {
          "id": "caption-3",
          "text": "人类通常如何描述这个现象。",
          "startFrame": 70,
          "durationInFrames": 76
        },
        {
          "id": "caption-4",
          "text": "而是：",
          "startFrame": 146,
          "durationInFrames": 18
        },
        {
          "id": "caption-5",
          "text": "世界的状态，",
          "startFrame": 164,
          "durationInFrames": 35
        },
        {
          "id": "caption-6",
          "text": "究竟如何随时间发生变化。",
          "startFrame": 199,
          "durationInFrames": 70
        }
      ]
    },
    "durationInFrames": 269,
    "durationInSeconds": 8.96,
    "format": "wav",
    "narration": "它学习的重点，不再只是：人类通常如何描述这个现象。而是：世界的状态，究竟如何随时间发生变化。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s24"
  },
  {
    "audioFile": "generated/beyond-language/s25.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就是世界模型最核心的能力：",
          "startFrame": 0,
          "durationInFrames": 87
        },
        {
          "id": "caption-2",
          "text": "根据当前状态和一个动作，",
          "startFrame": 87,
          "durationInFrames": 74
        },
        {
          "id": "caption-3",
          "text": "预测接下来可能发生什么。",
          "startFrame": 161,
          "durationInFrames": 74
        }
      ]
    },
    "durationInFrames": 235,
    "durationInSeconds": 7.84,
    "format": "wav",
    "narration": "这就是世界模型最核心的能力：根据当前状态和一个动作，预测接下来可能发生什么。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s25"
  },
  {
    "audioFile": "generated/beyond-language/s26.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "如果机械臂从这个角度抓杯子，",
          "startFrame": 0,
          "durationInFrames": 79
        },
        {
          "id": "caption-2",
          "text": "杯子会不会掉落？",
          "startFrame": 79,
          "durationInFrames": 45
        },
        {
          "id": "caption-3",
          "text": "如果修改这一段代码，",
          "startFrame": 124,
          "durationInFrames": 57
        },
        {
          "id": "caption-4",
          "text": "哪些服务可能受到影响？",
          "startFrame": 181,
          "durationInFrames": 62
        },
        {
          "id": "caption-5",
          "text": "如果调整价格，",
          "startFrame": 243,
          "durationInFrames": 40
        },
        {
          "id": "caption-6",
          "text": "用户行为可能如何变化？",
          "startFrame": 283,
          "durationInFrames": 63
        }
      ]
    },
    "durationInFrames": 346,
    "durationInSeconds": 11.52,
    "format": "wav",
    "narration": "如果机械臂从这个角度抓杯子，杯子会不会掉落？如果修改这一段代码，哪些服务可能受到影响？如果调整价格，用户行为可能如何变化？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s26"
  },
  {
    "audioFile": "generated/beyond-language/s27.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "模型可以在真正行动之前，",
          "startFrame": 0,
          "durationInFrames": 74
        },
        {
          "id": "caption-2",
          "text": "先在内部模拟多个未来。",
          "startFrame": 74,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "它不一定需要把每一种可能都写成文字。",
          "startFrame": 142,
          "durationInFrames": 111
        },
        {
          "id": "caption-4",
          "text": "它只需要比较这些未来，",
          "startFrame": 253,
          "durationInFrames": 68
        },
        {
          "id": "caption-5",
          "text": "选择风险更低、",
          "startFrame": 321,
          "durationInFrames": 43
        },
        {
          "id": "caption-6",
          "text": "结果更好的路径。",
          "startFrame": 364,
          "durationInFrames": 49
        }
      ]
    },
    "durationInFrames": 413,
    "durationInSeconds": 13.76,
    "format": "wav",
    "narration": "模型可以在真正行动之前，先在内部模拟多个未来。它不一定需要把每一种可能都写成文字。它只需要比较这些未来，选择风险更低、结果更好的路径。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s27"
  },
  {
    "audioFile": "generated/beyond-language/s28.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "当这种预测能力足够强时，",
          "startFrame": 0,
          "durationInFrames": 58
        },
        {
          "id": "caption-2",
          "text": "AI 会获得一种接近「直觉」",
          "startFrame": 58,
          "durationInFrames": 67
        },
        {
          "id": "caption-3",
          "text": "的能力。",
          "startFrame": 125,
          "durationInFrames": 19
        },
        {
          "id": "caption-4",
          "text": "它可能还没有完成一套语言推导，",
          "startFrame": 144,
          "durationInFrames": 72
        },
        {
          "id": "caption-5",
          "text": "就已经感知到某个方案不对劲。",
          "startFrame": 216,
          "durationInFrames": 67
        }
      ]
    },
    "durationInFrames": 283,
    "durationInSeconds": 9.44,
    "format": "wav",
    "narration": "当这种预测能力足够强时，AI 会获得一种接近「直觉」的能力。它可能还没有完成一套语言推导，就已经感知到某个方案不对劲。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s28"
  },
  {
    "audioFile": "generated/beyond-language/s29.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就像一个资深工程师看到架构图时，",
          "startFrame": 0,
          "durationInFrames": 102
        },
        {
          "id": "caption-2",
          "text": "会立刻觉得某个节点存在风险。",
          "startFrame": 102,
          "durationInFrames": 84
        },
        {
          "id": "caption-3",
          "text": "他不一定马上说出完整原因，",
          "startFrame": 186,
          "durationInFrames": 78
        },
        {
          "id": "caption-4",
          "text": "但大量经验已经被压缩成快速判断。",
          "startFrame": 264,
          "durationInFrames": 96
        }
      ]
    },
    "durationInFrames": 360,
    "durationInSeconds": 12,
    "format": "wav",
    "narration": "这就像一个资深工程师看到架构图时，会立刻觉得某个节点存在风险。他不一定马上说出完整原因，但大量经验已经被压缩成快速判断。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s29"
  },
  {
    "audioFile": "generated/beyond-language/s30.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的 AI，",
          "startFrame": 0,
          "durationInFrames": 48
        },
        {
          "id": "caption-2",
          "text": "也可能通过大量代码执行、",
          "startFrame": 48,
          "durationInFrames": 83
        },
        {
          "id": "caption-3",
          "text": "系统故障、",
          "startFrame": 131,
          "durationInFrames": 34
        },
        {
          "id": "caption-4",
          "text": "现实视频和环境反馈，",
          "startFrame": 165,
          "durationInFrames": 69
        },
        {
          "id": "caption-5",
          "text": "形成类似的模式直觉。",
          "startFrame": 234,
          "durationInFrames": 69
        },
        {
          "id": "caption-6",
          "text": "它不只是知道「什么说法是正确的」",
          "startFrame": 303,
          "durationInFrames": 110
        },
        {
          "id": "caption-7",
          "text": "。",
          "startFrame": 413,
          "durationInFrames": 7
        },
        {
          "id": "caption-8",
          "text": "它还开始知道「什么状态通常会导致失败」",
          "startFrame": 420,
          "durationInFrames": 131
        },
        {
          "id": "caption-9",
          "text": "。",
          "startFrame": 551,
          "durationInFrames": 6
        }
      ]
    },
    "durationInFrames": 557,
    "durationInSeconds": 18.56,
    "format": "wav",
    "narration": "未来的 AI，也可能通过大量代码执行、系统故障、现实视频和环境反馈，形成类似的模式直觉。它不只是知道「什么说法是正确的」。它还开始知道「什么状态通常会导致失败」。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s30"
  },
  {
    "audioFile": "generated/beyond-language/s31.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "不过，",
          "startFrame": 0,
          "durationInFrames": 17
        },
        {
          "id": "caption-2",
          "text": "直觉不等于绝对正确。",
          "startFrame": 17,
          "durationInFrames": 57
        },
        {
          "id": "caption-3",
          "text": "无论是人的直觉，",
          "startFrame": 74,
          "durationInFrames": 45
        },
        {
          "id": "caption-4",
          "text": "还是 AI 的预测，",
          "startFrame": 119,
          "durationInFrames": 57
        },
        {
          "id": "caption-5",
          "text": "都可能出现偏差。",
          "startFrame": 176,
          "durationInFrames": 45
        },
        {
          "id": "caption-6",
          "text": "所以，",
          "startFrame": 221,
          "durationInFrames": 17
        },
        {
          "id": "caption-7",
          "text": "世界模型不能取代验证。",
          "startFrame": 238,
          "durationInFrames": 63
        },
        {
          "id": "caption-8",
          "text": "它更适合成为验证之前的风险发现层。",
          "startFrame": 301,
          "durationInFrames": 97
        }
      ]
    },
    "durationInFrames": 398,
    "durationInSeconds": 13.28,
    "format": "wav",
    "narration": "不过，直觉不等于绝对正确。无论是人的直觉，还是 AI 的预测，都可能出现偏差。所以，世界模型不能取代验证。它更适合成为验证之前的风险发现层。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s31"
  },
  {
    "audioFile": "generated/beyond-language/s32.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "真正可靠的 AI，",
          "startFrame": 0,
          "durationInFrames": 53
        },
        {
          "id": "caption-2",
          "text": "不是一个永远不会犯错的模型。",
          "startFrame": 53,
          "durationInFrames": 83
        },
        {
          "id": "caption-3",
          "text": "而是一个即使判断错误，",
          "startFrame": 136,
          "durationInFrames": 65
        },
        {
          "id": "caption-4",
          "text": "也不会让错误无限扩散的系统。",
          "startFrame": 201,
          "durationInFrames": 82
        }
      ]
    },
    "durationInFrames": 283,
    "durationInSeconds": 9.44,
    "format": "wav",
    "narration": "真正可靠的 AI，不是一个永远不会犯错的模型。而是一个即使判断错误，也不会让错误无限扩散的系统。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s32"
  },
  {
    "audioFile": "generated/beyond-language/s33.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "它需要权限边界、",
          "startFrame": 0,
          "durationInFrames": 54
        },
        {
          "id": "caption-2",
          "text": "测试环境、",
          "startFrame": 54,
          "durationInFrames": 34
        },
        {
          "id": "caption-3",
          "text": "实时监控、",
          "startFrame": 88,
          "durationInFrames": 34
        },
        {
          "id": "caption-4",
          "text": "结果验证和回滚机制。",
          "startFrame": 122,
          "durationInFrames": 68
        },
        {
          "id": "caption-5",
          "text": "可靠性不应该依赖模型的一句：",
          "startFrame": 190,
          "durationInFrames": 95
        },
        {
          "id": "caption-6",
          "text": "「请相信我，",
          "startFrame": 285,
          "durationInFrames": 41
        },
        {
          "id": "caption-7",
          "text": "这次没有问题。",
          "startFrame": 326,
          "durationInFrames": 47
        },
        {
          "id": "caption-8",
          "text": "」",
          "startFrame": 373,
          "durationInFrames": 6
        }
      ]
    },
    "durationInFrames": 379,
    "durationInSeconds": 12.64,
    "format": "wav",
    "narration": "它需要权限边界、测试环境、实时监控、结果验证和回滚机制。可靠性不应该依赖模型的一句：「请相信我，这次没有问题。」",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s33"
  },
  {
    "audioFile": "generated/beyond-language/s34.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "当模型从描述世界走向预测世界，",
          "startFrame": 0,
          "durationInFrames": 87
        },
        {
          "id": "caption-2",
          "text": "下一步就是作用于世界。",
          "startFrame": 87,
          "durationInFrames": 64
        },
        {
          "id": "caption-3",
          "text": "这也是 AI 从语言模型走向 Agent 的关键变化。",
          "startFrame": 151,
          "durationInFrames": 156
        }
      ]
    },
    "durationInFrames": 307,
    "durationInSeconds": 10.24,
    "format": "wav",
    "narration": "当模型从描述世界走向预测世界，下一步就是作用于世界。这也是 AI 从语言模型走向 Agent 的关键变化。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s34"
  },
  {
    "audioFile": "generated/beyond-language/s35.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言模型最基础的训练目标是：",
          "startFrame": 0,
          "durationInFrames": 85
        },
        {
          "id": "caption-2",
          "text": "预测下一个 Token。",
          "startFrame": 85,
          "durationInFrames": 73
        },
        {
          "id": "caption-3",
          "text": "而 Agent 真正需要解决的问题是：",
          "startFrame": 158,
          "durationInFrames": 115
        },
        {
          "id": "caption-4",
          "text": "预测下一个动作。",
          "startFrame": 273,
          "durationInFrames": 49
        }
      ]
    },
    "durationInFrames": 322,
    "durationInSeconds": 10.72,
    "format": "wav",
    "narration": "语言模型最基础的训练目标是：预测下一个 Token。而 Agent 真正需要解决的问题是：预测下一个动作。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s35"
  },
  {
    "audioFile": "generated/beyond-language/s36.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "面对一次服务器故障，",
          "startFrame": 0,
          "durationInFrames": 46
        },
        {
          "id": "caption-2",
          "text": "它不应该只生成一篇故障处理教程。",
          "startFrame": 46,
          "durationInFrames": 74
        },
        {
          "id": "caption-3",
          "text": "它应该读取日志、",
          "startFrame": 120,
          "durationInFrames": 37
        },
        {
          "id": "caption-4",
          "text": "定位异常、",
          "startFrame": 157,
          "durationInFrames": 23
        },
        {
          "id": "caption-5",
          "text": "修改配置、",
          "startFrame": 180,
          "durationInFrames": 23
        },
        {
          "id": "caption-6",
          "text": "运行测试，",
          "startFrame": 203,
          "durationInFrames": 23
        },
        {
          "id": "caption-7",
          "text": "并确认服务已经恢复。",
          "startFrame": 226,
          "durationInFrames": 48
        }
      ]
    },
    "durationInFrames": 274,
    "durationInSeconds": 9.12,
    "format": "wav",
    "narration": "面对一次服务器故障，它不应该只生成一篇故障处理教程。它应该读取日志、定位异常、修改配置、运行测试，并确认服务已经恢复。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s36"
  },
  {
    "audioFile": "generated/beyond-language/s37.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "在这个过程中，",
          "startFrame": 0,
          "durationInFrames": 44
        },
        {
          "id": "caption-2",
          "text": "一次 API 调用、",
          "startFrame": 44,
          "durationInFrames": 63
        },
        {
          "id": "caption-3",
          "text": "一段代码修改、",
          "startFrame": 107,
          "durationInFrames": 44
        },
        {
          "id": "caption-4",
          "text": "一条数据库查询，",
          "startFrame": 151,
          "durationInFrames": 50
        },
        {
          "id": "caption-5",
          "text": "都是比语言更精确的表达。",
          "startFrame": 201,
          "durationInFrames": 75
        },
        {
          "id": "caption-6",
          "text": "语言可以说：",
          "startFrame": 276,
          "durationInFrames": 38
        },
        {
          "id": "caption-7",
          "text": "「把系统优化一下。",
          "startFrame": 314,
          "durationInFrames": 56
        },
        {
          "id": "caption-8",
          "text": "」",
          "startFrame": 370,
          "durationInFrames": 6
        },
        {
          "id": "caption-9",
          "text": "动作必须明确：",
          "startFrame": 376,
          "durationInFrames": 44
        },
        {
          "id": "caption-10",
          "text": "修改什么、",
          "startFrame": 420,
          "durationInFrames": 31
        },
        {
          "id": "caption-11",
          "text": "执行什么、",
          "startFrame": 451,
          "durationInFrames": 31
        },
        {
          "id": "caption-12",
          "text": "验证什么，",
          "startFrame": 482,
          "durationInFrames": 31
        },
        {
          "id": "caption-13",
          "text": "以及失败后如何恢复。",
          "startFrame": 513,
          "durationInFrames": 63
        }
      ]
    },
    "durationInFrames": 576,
    "durationInSeconds": 19.2,
    "format": "wav",
    "narration": "在这个过程中，一次 API 调用、一段代码修改、一条数据库查询，都是比语言更精确的表达。语言可以说：「把系统优化一下。」动作必须明确：修改什么、执行什么、验证什么，以及失败后如何恢复。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s37"
  },
  {
    "audioFile": "generated/beyond-language/s38.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "对于 AI 来说，",
          "startFrame": 0,
          "durationInFrames": 51
        },
        {
          "id": "caption-2",
          "text": "动作本身正在成为一种新的语言。",
          "startFrame": 51,
          "durationInFrames": 85
        },
        {
          "id": "caption-3",
          "text": "不是用句子描述意图，",
          "startFrame": 136,
          "durationInFrames": 57
        },
        {
          "id": "caption-4",
          "text": "而是用可以被环境直接执行的行为表达意图。",
          "startFrame": 193,
          "durationInFrames": 114
        }
      ]
    },
    "durationInFrames": 307,
    "durationInSeconds": 10.24,
    "format": "wav",
    "narration": "对于 AI 来说，动作本身正在成为一种新的语言。不是用句子描述意图，而是用可以被环境直接执行的行为表达意图。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s38"
  },
  {
    "audioFile": "generated/beyond-language/s39.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这就是 Action as Language。",
          "startFrame": 0,
          "durationInFrames": 108
        },
        {
          "id": "caption-2",
          "text": "AI 的核心输出，",
          "startFrame": 108,
          "durationInFrames": 42
        },
        {
          "id": "caption-3",
          "text": "开始从「答案」",
          "startFrame": 150,
          "durationInFrames": 33
        },
        {
          "id": "caption-4",
          "text": "转向「状态变化」",
          "startFrame": 183,
          "durationInFrames": 38
        },
        {
          "id": "caption-5",
          "text": "。",
          "startFrame": 221,
          "durationInFrames": 5
        }
      ]
    },
    "durationInFrames": 226,
    "durationInSeconds": 7.52,
    "format": "wav",
    "narration": "这就是 Action as Language。AI 的核心输出，开始从「答案」转向「状态变化」。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s39"
  },
  {
    "audioFile": "generated/beyond-language/s40.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的 Agent 会持续循环：",
          "startFrame": 0,
          "durationInFrames": 94
        },
        {
          "id": "caption-2",
          "text": "观察环境，",
          "startFrame": 94,
          "durationInFrames": 29
        },
        {
          "id": "caption-3",
          "text": "更新判断，",
          "startFrame": 123,
          "durationInFrames": 29
        },
        {
          "id": "caption-4",
          "text": "选择动作，",
          "startFrame": 152,
          "durationInFrames": 29
        },
        {
          "id": "caption-5",
          "text": "执行动作，",
          "startFrame": 181,
          "durationInFrames": 29
        },
        {
          "id": "caption-6",
          "text": "再根据结果修正下一步。",
          "startFrame": 210,
          "durationInFrames": 65
        },
        {
          "id": "caption-7",
          "text": "语言不需要参与这个循环中的每一个阶段。",
          "startFrame": 275,
          "durationInFrames": 114
        }
      ]
    },
    "durationInFrames": 389,
    "durationInSeconds": 12.96,
    "format": "wav",
    "narration": "未来的 Agent 会持续循环：观察环境，更新判断，选择动作，执行动作，再根据结果修正下一步。语言不需要参与这个循环中的每一个阶段。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s40"
  },
  {
    "audioFile": "generated/beyond-language/s41.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "只有在需要人类授权、",
          "startFrame": 0,
          "durationInFrames": 57
        },
        {
          "id": "caption-2",
          "text": "出现高风险异常，",
          "startFrame": 57,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "或者任务完成时，",
          "startFrame": 103,
          "durationInFrames": 46
        },
        {
          "id": "caption-4",
          "text": "AI 才把内部状态重新翻译成语言。",
          "startFrame": 149,
          "durationInFrames": 96
        }
      ]
    },
    "durationInFrames": 245,
    "durationInSeconds": 8.16,
    "format": "wav",
    "narration": "只有在需要人类授权、出现高风险异常，或者任务完成时，AI 才把内部状态重新翻译成语言。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s41"
  },
  {
    "audioFile": "generated/beyond-language/s42.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "到那时，",
          "startFrame": 0,
          "durationInFrames": 29
        },
        {
          "id": "caption-2",
          "text": "AI 说话可能只是为了三件事：",
          "startFrame": 29,
          "durationInFrames": 110
        },
        {
          "id": "caption-3",
          "text": "确认你的目标。",
          "startFrame": 139,
          "durationInFrames": 51
        },
        {
          "id": "caption-4",
          "text": "请求你的权限。",
          "startFrame": 190,
          "durationInFrames": 51
        },
        {
          "id": "caption-5",
          "text": "向你汇报结果。",
          "startFrame": 241,
          "durationInFrames": 52
        }
      ]
    },
    "durationInFrames": 293,
    "durationInSeconds": 9.76,
    "format": "wav",
    "narration": "到那时，AI 说话可能只是为了三件事：确认你的目标。请求你的权限。向你汇报结果。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s42"
  },
  {
    "audioFile": "generated/beyond-language/s43.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这也意味着，",
          "startFrame": 0,
          "durationInFrames": 43
        },
        {
          "id": "caption-2",
          "text": "未来真正重要的竞争，",
          "startFrame": 43,
          "durationInFrames": 71
        },
        {
          "id": "caption-3",
          "text": "不再只是哪个模型更会聊天。",
          "startFrame": 114,
          "durationInFrames": 93
        },
        {
          "id": "caption-4",
          "text": "而是谁能建立更高效的非语言通信协议。",
          "startFrame": 207,
          "durationInFrames": 129
        }
      ]
    },
    "durationInFrames": 336,
    "durationInSeconds": 11.2,
    "format": "wav",
    "narration": "这也意味着，未来真正重要的竞争，不再只是哪个模型更会聊天。而是谁能建立更高效的非语言通信协议。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s43"
  },
  {
    "audioFile": "generated/beyond-language/s44.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "不同模型之间如何交换世界状态？",
          "startFrame": 0,
          "durationInFrames": 88
        },
        {
          "id": "caption-2",
          "text": "如何表达不确定性？",
          "startFrame": 88,
          "durationInFrames": 53
        },
        {
          "id": "caption-3",
          "text": "如何证明数据来源？",
          "startFrame": 141,
          "durationInFrames": 53
        },
        {
          "id": "caption-4",
          "text": "如何确保一个模型的内部表示，",
          "startFrame": 194,
          "durationInFrames": 82
        },
        {
          "id": "caption-5",
          "text": "不会被另一个模型错误理解？",
          "startFrame": 276,
          "durationInFrames": 74
        }
      ]
    },
    "durationInFrames": 350,
    "durationInSeconds": 11.68,
    "format": "wav",
    "narration": "不同模型之间如何交换世界状态？如何表达不确定性？如何证明数据来源？如何确保一个模型的内部表示，不会被另一个模型错误理解？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s44"
  },
  {
    "audioFile": "generated/beyond-language/s45.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的 Agent 协作协议，",
          "startFrame": 0,
          "durationInFrames": 80
        },
        {
          "id": "caption-2",
          "text": "可能需要同时定义：",
          "startFrame": 80,
          "durationInFrames": 48
        },
        {
          "id": "caption-3",
          "text": "身份、",
          "startFrame": 128,
          "durationInFrames": 16
        },
        {
          "id": "caption-4",
          "text": "权限、",
          "startFrame": 144,
          "durationInFrames": 16
        },
        {
          "id": "caption-5",
          "text": "状态格式、",
          "startFrame": 160,
          "durationInFrames": 27
        },
        {
          "id": "caption-6",
          "text": "置信度、",
          "startFrame": 187,
          "durationInFrames": 21
        },
        {
          "id": "caption-7",
          "text": "版本、",
          "startFrame": 208,
          "durationInFrames": 16
        },
        {
          "id": "caption-8",
          "text": "验证方式和失败处理机制。",
          "startFrame": 224,
          "durationInFrames": 64
        }
      ]
    },
    "durationInFrames": 288,
    "durationInSeconds": 9.6,
    "format": "wav",
    "narration": "未来的 Agent 协作协议，可能需要同时定义：身份、权限、状态格式、置信度、版本、验证方式和失败处理机制。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s45"
  },
  {
    "audioFile": "generated/beyond-language/s46.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的竞争，",
          "startFrame": 0,
          "durationInFrames": 28
        },
        {
          "id": "caption-2",
          "text": "也不再只是 Prompt 写得好不好。",
          "startFrame": 28,
          "durationInFrames": 88
        },
        {
          "id": "caption-3",
          "text": "因为当 Agent 可以直接读取环境状态、",
          "startFrame": 116,
          "durationInFrames": 97
        },
        {
          "id": "caption-4",
          "text": "历史记录、",
          "startFrame": 213,
          "durationInFrames": 23
        },
        {
          "id": "caption-5",
          "text": "用户偏好和实时反馈时，",
          "startFrame": 236,
          "durationInFrames": 51
        },
        {
          "id": "caption-6",
          "text": "Prompt 只会成为上下文的一部分。",
          "startFrame": 287,
          "durationInFrames": 87
        }
      ]
    },
    "durationInFrames": 374,
    "durationInSeconds": 12.48,
    "format": "wav",
    "narration": "未来的竞争，也不再只是 Prompt 写得好不好。因为当 Agent 可以直接读取环境状态、历史记录、用户偏好和实时反馈时，Prompt 只会成为上下文的一部分。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s46"
  },
  {
    "audioFile": "generated/beyond-language/s47.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "真正重要的会变成：",
          "startFrame": 0,
          "durationInFrames": 53
        },
        {
          "id": "caption-2",
          "text": "谁能为 AI 提供更清晰的环境。",
          "startFrame": 53,
          "durationInFrames": 94
        },
        {
          "id": "caption-3",
          "text": "谁能把能力封装成稳定的工具。",
          "startFrame": 147,
          "durationInFrames": 82
        },
        {
          "id": "caption-4",
          "text": "谁能让每一个动作都可以验证、",
          "startFrame": 229,
          "durationInFrames": 82
        },
        {
          "id": "caption-5",
          "text": "限制和回滚。",
          "startFrame": 311,
          "durationInFrames": 35
        }
      ]
    },
    "durationInFrames": 346,
    "durationInSeconds": 11.52,
    "format": "wav",
    "narration": "真正重要的会变成：谁能为 AI 提供更清晰的环境。谁能把能力封装成稳定的工具。谁能让每一个动作都可以验证、限制和回滚。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s47"
  },
  {
    "audioFile": "generated/beyond-language/s48.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "但 AI 越少依赖语言，",
          "startFrame": 0,
          "durationInFrames": 68
        },
        {
          "id": "caption-2",
          "text": "人类也会面对一个更严重的问题：",
          "startFrame": 68,
          "durationInFrames": 85
        },
        {
          "id": "caption-3",
          "text": "如果 AI 不再向我们展示完整的语言推理，",
          "startFrame": 153,
          "durationInFrames": 120
        },
        {
          "id": "caption-4",
          "text": "我们如何理解和控制它？",
          "startFrame": 273,
          "durationInFrames": 63
        }
      ]
    },
    "durationInFrames": 336,
    "durationInSeconds": 11.2,
    "format": "wav",
    "narration": "但 AI 越少依赖语言，人类也会面对一个更严重的问题：如果 AI 不再向我们展示完整的语言推理，我们如何理解和控制它？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s48"
  },
  {
    "audioFile": "generated/beyond-language/s49.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "答案可能不是强迫 AI 把每一个内部状态都翻译成文字。",
          "startFrame": 0,
          "durationInFrames": 150
        },
        {
          "id": "caption-2",
          "text": "因为一段听起来合理的解释，",
          "startFrame": 150,
          "durationInFrames": 72
        },
        {
          "id": "caption-3",
          "text": "也不一定是它做出决定的真实原因。",
          "startFrame": 222,
          "durationInFrames": 90
        }
      ]
    },
    "durationInFrames": 312,
    "durationInSeconds": 10.4,
    "format": "wav",
    "narration": "答案可能不是强迫 AI 把每一个内部状态都翻译成文字。因为一段听起来合理的解释，也不一定是它做出决定的真实原因。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s49"
  },
  {
    "audioFile": "generated/beyond-language/s50.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "真正重要的，",
          "startFrame": 0,
          "durationInFrames": 33
        },
        {
          "id": "caption-2",
          "text": "不是看到 AI 的所有「内心独白」",
          "startFrame": 33,
          "durationInFrames": 95
        },
        {
          "id": "caption-3",
          "text": "。",
          "startFrame": 128,
          "durationInFrames": 6
        },
        {
          "id": "caption-4",
          "text": "而是能够观察它的关键行为。",
          "startFrame": 134,
          "durationInFrames": 72
        }
      ]
    },
    "durationInFrames": 206,
    "durationInSeconds": 6.88,
    "format": "wav",
    "narration": "真正重要的，不是看到 AI 的所有「内心独白」。而是能够观察它的关键行为。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s50"
  },
  {
    "audioFile": "generated/beyond-language/s51.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "它读取了什么数据？",
          "startFrame": 0,
          "durationInFrames": 51
        },
        {
          "id": "caption-2",
          "text": "使用了什么工具？",
          "startFrame": 51,
          "durationInFrames": 45
        },
        {
          "id": "caption-3",
          "text": "拥有什么权限？",
          "startFrame": 96,
          "durationInFrames": 40
        },
        {
          "id": "caption-4",
          "text": "修改了什么内容？",
          "startFrame": 136,
          "durationInFrames": 45
        },
        {
          "id": "caption-5",
          "text": "影响了哪些对象？",
          "startFrame": 181,
          "durationInFrames": 45
        },
        {
          "id": "caption-6",
          "text": "最终结果是否通过验证？",
          "startFrame": 226,
          "durationInFrames": 62
        }
      ]
    },
    "durationInFrames": 288,
    "durationInSeconds": 9.6,
    "format": "wav",
    "narration": "它读取了什么数据？使用了什么工具？拥有什么权限？修改了什么内容？影响了哪些对象？最终结果是否通过验证？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s51"
  },
  {
    "audioFile": "generated/beyond-language/s52.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "即使 AI 的内部认知变成一个人类无法直接理解的高维黑盒，",
          "startFrame": 0,
          "durationInFrames": 154
        },
        {
          "id": "caption-2",
          "text": "我们仍然需要在黑盒外部建立感知锚点。",
          "startFrame": 154,
          "durationInFrames": 96
        }
      ]
    },
    "durationInFrames": 250,
    "durationInSeconds": 8.32,
    "format": "wav",
    "narration": "即使 AI 的内部认知变成一个人类无法直接理解的高维黑盒，我们仍然需要在黑盒外部建立感知锚点。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s52"
  },
  {
    "audioFile": "generated/beyond-language/s53.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这些锚点包括：",
          "startFrame": 0,
          "durationInFrames": 62
        },
        {
          "id": "caption-2",
          "text": "身份、",
          "startFrame": 62,
          "durationInFrames": 27
        },
        {
          "id": "caption-3",
          "text": "权限、",
          "startFrame": 89,
          "durationInFrames": 27
        },
        {
          "id": "caption-4",
          "text": "证据、",
          "startFrame": 116,
          "durationInFrames": 27
        },
        {
          "id": "caption-5",
          "text": "审批、",
          "startFrame": 143,
          "durationInFrames": 27
        },
        {
          "id": "caption-6",
          "text": "监控和回滚。",
          "startFrame": 170,
          "durationInFrames": 51
        }
      ]
    },
    "durationInFrames": 221,
    "durationInSeconds": 7.36,
    "format": "wav",
    "narration": "这些锚点包括：身份、权限、证据、审批、监控和回滚。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s53"
  },
  {
    "audioFile": "generated/beyond-language/s54.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "我们不一定需要理解 AI 的每一个向量。",
          "startFrame": 0,
          "durationInFrames": 116
        },
        {
          "id": "caption-2",
          "text": "但必须能够确认：",
          "startFrame": 116,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "是谁在行动，",
          "startFrame": 162,
          "durationInFrames": 35
        },
        {
          "id": "caption-4",
          "text": "它被允许做什么，",
          "startFrame": 197,
          "durationInFrames": 46
        },
        {
          "id": "caption-5",
          "text": "它实际做了什么，",
          "startFrame": 243,
          "durationInFrames": 46
        },
        {
          "id": "caption-6",
          "text": "以及错误发生后能否恢复。",
          "startFrame": 289,
          "durationInFrames": 71
        }
      ]
    },
    "durationInFrames": 360,
    "durationInSeconds": 12,
    "format": "wav",
    "narration": "我们不一定需要理解 AI 的每一个向量。但必须能够确认：是谁在行动，它被允许做什么，它实际做了什么，以及错误发生后能否恢复。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s54"
  },
  {
    "audioFile": "generated/beyond-language/s55.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "所以，",
          "startFrame": 0,
          "durationInFrames": 17
        },
        {
          "id": "caption-2",
          "text": "所谓 AI 的「失语症」",
          "startFrame": 17,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "，",
          "startFrame": 85,
          "durationInFrames": 6
        },
        {
          "id": "caption-4",
          "text": "并不是 AI 变得沉默。",
          "startFrame": 91,
          "durationInFrames": 68
        },
        {
          "id": "caption-5",
          "text": "而是它不再需要把每一个内部认知过程，",
          "startFrame": 159,
          "durationInFrames": 102
        },
        {
          "id": "caption-6",
          "text": "都转化成人类语言才能继续工作。",
          "startFrame": 261,
          "durationInFrames": 85
        }
      ]
    },
    "durationInFrames": 346,
    "durationInSeconds": 11.52,
    "format": "wav",
    "narration": "所以，所谓 AI 的「失语症」，并不是 AI 变得沉默。而是它不再需要把每一个内部认知过程，都转化成人类语言才能继续工作。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s55"
  },
  {
    "audioFile": "generated/beyond-language/s56.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "语言不会消失。",
          "startFrame": 0,
          "durationInFrames": 46
        },
        {
          "id": "caption-2",
          "text": "人类仍然需要用语言表达目标、",
          "startFrame": 46,
          "durationInFrames": 91
        },
        {
          "id": "caption-3",
          "text": "协商规则、",
          "startFrame": 137,
          "durationInFrames": 33
        },
        {
          "id": "caption-4",
          "text": "理解风险和追究责任。",
          "startFrame": 170,
          "durationInFrames": 65
        }
      ]
    },
    "durationInFrames": 235,
    "durationInSeconds": 7.84,
    "format": "wav",
    "narration": "语言不会消失。人类仍然需要用语言表达目标、协商规则、理解风险和追究责任。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s56"
  },
  {
    "audioFile": "generated/beyond-language/s57.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "但语言会从 AI 的内部工作层，",
          "startFrame": 0,
          "durationInFrames": 83
        },
        {
          "id": "caption-2",
          "text": "逐渐退回到人类交互层。",
          "startFrame": 83,
          "durationInFrames": 57
        },
        {
          "id": "caption-3",
          "text": "内部通过状态、",
          "startFrame": 140,
          "durationInFrames": 36
        },
        {
          "id": "caption-4",
          "text": "向量、",
          "startFrame": 176,
          "durationInFrames": 16
        },
        {
          "id": "caption-5",
          "text": "预测和动作运行。",
          "startFrame": 192,
          "durationInFrames": 42
        },
        {
          "id": "caption-6",
          "text": "外部通过语言与人类建立共识。",
          "startFrame": 234,
          "durationInFrames": 73
        }
      ]
    },
    "durationInFrames": 307,
    "durationInSeconds": 10.24,
    "format": "wav",
    "narration": "但语言会从 AI 的内部工作层，逐渐退回到人类交互层。内部通过状态、向量、预测和动作运行。外部通过语言与人类建立共识。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s57"
  },
  {
    "audioFile": "generated/beyond-language/s58.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "大型语言模型，",
          "startFrame": 0,
          "durationInFrames": 44
        },
        {
          "id": "caption-2",
          "text": "让机器学会了描述世界。",
          "startFrame": 44,
          "durationInFrames": 70
        },
        {
          "id": "caption-3",
          "text": "世界模型，",
          "startFrame": 114,
          "durationInFrames": 32
        },
        {
          "id": "caption-4",
          "text": "让机器开始模拟世界。",
          "startFrame": 146,
          "durationInFrames": 63
        },
        {
          "id": "caption-5",
          "text": "Agent，",
          "startFrame": 209,
          "durationInFrames": 38
        },
        {
          "id": "caption-6",
          "text": "让机器开始作用于世界。",
          "startFrame": 247,
          "durationInFrames": 70
        }
      ]
    },
    "durationInFrames": 317,
    "durationInSeconds": 10.56,
    "format": "wav",
    "narration": "大型语言模型，让机器学会了描述世界。世界模型，让机器开始模拟世界。Agent，让机器开始作用于世界。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s58"
  },
  {
    "audioFile": "generated/beyond-language/s59.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "当这三种能力真正结合时，",
          "startFrame": 0,
          "durationInFrames": 83
        },
        {
          "id": "caption-2",
          "text": "我们评价 AI 的标准也会改变。",
          "startFrame": 83,
          "durationInFrames": 110
        },
        {
          "id": "caption-3",
          "text": "不再只是：",
          "startFrame": 193,
          "durationInFrames": 35
        },
        {
          "id": "caption-4",
          "text": "它说得像不像人。",
          "startFrame": 228,
          "durationInFrames": 55
        }
      ]
    },
    "durationInFrames": 283,
    "durationInSeconds": 9.44,
    "format": "wav",
    "narration": "当这三种能力真正结合时，我们评价 AI 的标准也会改变。不再只是：它说得像不像人。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s59"
  },
  {
    "audioFile": "generated/beyond-language/s60.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "而是：",
          "startFrame": 0,
          "durationInFrames": 20
        },
        {
          "id": "caption-2",
          "text": "它是否理解真实环境。",
          "startFrame": 20,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "是否能够预测行动后果。",
          "startFrame": 88,
          "durationInFrames": 75
        },
        {
          "id": "caption-4",
          "text": "是否能够稳定完成任务。",
          "startFrame": 163,
          "durationInFrames": 75
        },
        {
          "id": "caption-5",
          "text": "以及在人类听不见它内部语言的时候，",
          "startFrame": 238,
          "durationInFrames": 116
        },
        {
          "id": "caption-6",
          "text": "我们是否仍然拥有控制权。",
          "startFrame": 354,
          "durationInFrames": 83
        }
      ]
    },
    "durationInFrames": 437,
    "durationInSeconds": 14.56,
    "format": "wav",
    "narration": "而是：它是否理解真实环境。是否能够预测行动后果。是否能够稳定完成任务。以及在人类听不见它内部语言的时候，我们是否仍然拥有控制权。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s60"
  },
  {
    "audioFile": "generated/beyond-language/s61.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 的终点，",
          "startFrame": 0,
          "durationInFrames": 40
        },
        {
          "id": "caption-2",
          "text": "可能不是变得更会说话。",
          "startFrame": 40,
          "durationInFrames": 62
        },
        {
          "id": "caption-3",
          "text": "而是即使不需要说话，",
          "startFrame": 102,
          "durationInFrames": 57
        },
        {
          "id": "caption-4",
          "text": "也能理解世界、",
          "startFrame": 159,
          "durationInFrames": 40
        },
        {
          "id": "caption-5",
          "text": "完成行动，",
          "startFrame": 199,
          "durationInFrames": 28
        },
        {
          "id": "caption-6",
          "text": "并为每一个结果负责。",
          "startFrame": 227,
          "durationInFrames": 56
        }
      ]
    },
    "durationInFrames": 283,
    "durationInSeconds": 9.44,
    "format": "wav",
    "narration": "AI 的终点，可能不是变得更会说话。而是即使不需要说话，也能理解世界、完成行动，并为每一个结果负责。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "s61"
  }
];
