// Generated by the direct VoxCPM Producer runtime for Phase 7 proof.

import type { AgentProducerMediaSoundProofAudioTrack } from "./types";

export const agentProducerMediaSoundProofAudio = [
  {
    sceneId: "open",
    narration: "现成素材进入清单后，画面与声音都能被可靠复用。",
    audioFile: "generated/agent-producer-media-sound-proof/audio/open.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "现成素材进入清单后，",
          startFrame: 0,
          durationInFrames: 55,
        },
        {
          id: "caption-2",
          text: "画面与声音都能被可靠复用。",
          startFrame: 55,
          durationInFrames: 73,
        },
      ],
    },
    durationInFrames: 128,
    durationInSeconds: 4.2705625,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "media",
    narration: "本地视频可以裁切、循环和变速，背景音乐会在旁白出现时自动降低音量。",
    audioFile: "generated/agent-producer-media-sound-proof/audio/media.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "本地视频可以裁切、循环和变速，",
          startFrame: 0,
          durationInFrames: 100,
        },
        {
          id: "caption-2",
          text: "背景音乐会在旁白出现时自动降低音量。",
          startFrame: 100,
          durationInFrames: 101,
        },
      ],
    },
    durationInFrames: 201,
    durationInSeconds: 6.713291666666667,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "signal",
    narration: "动画、转场音效和环境声保持逐帧确定，最终结果可以重复审核。",
    audioFile: "generated/agent-producer-media-sound-proof/audio/signal.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "动画、转场音效和环境声保持逐帧确定，",
          startFrame: 0,
          durationInFrames: 131,
        },
        {
          id: "caption-2",
          text: "最终结果可以重复审核。",
          startFrame: 131,
          durationInFrames: 86,
        },
      ],
    },
    durationInFrames: 217,
    durationInSeconds: 7.2298125,
    provider: "voxcpm",
    format: "wav",
  },
] satisfies readonly AgentProducerMediaSoundProofAudioTrack[];
