#!/usr/bin/env node

import { readFile } from "node:fs/promises";

import {
  createVoxcpmProducerRequestPlan,
  readProducerVoxcpmConfig,
  requestProducerNarrationAsset,
  runProducerAudioGeneration,
} from "../../../scripts/lib/producer-audio/index.js";
import { agentProducerMediaSoundProofNarrationBeats } from "./script.js";

const root = "src/remotion/AgentProducerMediaSoundProof";
const slug = "agent-producer-media-sound-proof";
const voxcpmConfig = readProducerVoxcpmConfig();

await runProducerAudioGeneration({
  compositionId: "AgentProducerMediaSoundProof",
  beats: agentProducerMediaSoundProofNarrationBeats,
  createRequestPlan: (beat) =>
    createVoxcpmProducerRequestPlan({
      beat,
      mode: "voice-design",
      control: "清晰、克制、现代科技纪录片语气，中速，句尾自然收束",
    }),
  requestNarration: ({ plan }) =>
    requestProducerNarrationAsset({ config: voxcpmConfig, plan, slug }),
  progressDestination: `public/generated/${slug}/audio/progress.json`,
  metadata: {
    header: "Generated by the direct VoxCPM Producer runtime for Phase 7 proof.",
    exportName: "agentProducerMediaSoundProofAudio",
    typeImport: { name: "AgentProducerMediaSoundProofAudioTrack", path: "./types" },
    destination: `${root}/audio.generated.ts`,
  },
  duration: {
    source: await readFile(`${root}/types.ts`, "utf8"),
    constantName: "AGENT_PRODUCER_MEDIA_SOUND_PROOF_NARRATION_DURATION_IN_FRAMES",
    destination: `${root}/types.ts`,
  },
  summaryDestination: `public/generated/${slug}/audio/summary.json`,
  writeOutputs: true,
});
