export type PrimitiveCatalogCategory =
  | "background"
  | "chart"
  | "cinematic"
  | "logo"
  | "media"
  | "scene"
  | "text"
  | "transition";

export type PrimitiveCatalogStatus = "candidate" | "ported" | "adopted" | "deprecated";

export type PrimitiveCatalogEntry = {
  category: PrimitiveCatalogCategory;
  component: string;
  description: string;
  durationInFrames: number;
  id: string;
  label: string;
  source: {
    commit: string;
    file: string;
    license: "MIT";
    repository: string;
  };
  status: PrimitiveCatalogStatus;
};

const rveSource = {
  commit: "6209b724798e48ff395f8df1a6fa2d26082372b5",
  license: "MIT" as const,
  repository: "https://github.com/reactvideoeditor/remotion-templates",
};

export const primitiveCatalog = [
  {
    id: "rve-chart-animation",
    label: "Bar Chart",
    category: "chart",
    component: "BarChart",
    description: "Animated SVG bar chart with staggered bar growth.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/chart-animation.tsx" },
    status: "ported",
  },
  {
    id: "rve-line-chart",
    label: "Line Chart",
    category: "chart",
    component: "LineChart",
    description: "SVG polyline drawing left-to-right with data points.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/line-chart.tsx" },
    status: "ported",
  },
  {
    id: "rve-pie-chart",
    label: "Pie Chart",
    category: "chart",
    component: "PieChart",
    description: "Segmented circle with sequential segment reveals.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/pie-chart.tsx" },
    status: "ported",
  },
  {
    id: "rve-donut-chart",
    label: "Donut Chart",
    category: "chart",
    component: "DonutChart",
    description: "Ring chart with animated segments and centre metric.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/donut-chart.tsx" },
    status: "ported",
  },
  {
    id: "rve-area-chart",
    label: "Area Chart",
    category: "chart",
    component: "AreaChart",
    description: "Gradient-filled area under a line, revealing left to right.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/area-chart.tsx" },
    status: "ported",
  },
  {
    id: "rve-progress-bars",
    label: "Progress Bars",
    category: "chart",
    component: "ProgressBars",
    description: "Horizontal bars filling to different widths.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/progress-bars.tsx" },
    status: "ported",
  },
  {
    id: "rve-stat-counter",
    label: "Stat Counter",
    category: "chart",
    component: "StatCounter",
    description: "Large number counting up with comma formatting.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/stat-counter.tsx" },
    status: "ported",
  },
  {
    id: "rve-comparison-chart",
    label: "Comparison Chart",
    category: "chart",
    component: "ComparisonChart",
    description: "Side-by-side before/after metric comparison.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/comparison-chart.tsx" },
    status: "ported",
  },
  {
    id: "rve-circular-progress",
    label: "Circular Progress",
    category: "chart",
    component: "CircularProgress",
    description: "Animated progress ring with percentage.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/circular-progress.tsx" },
    status: "ported",
  },
  {
    id: "rve-animated-text",
    label: "Animated Text",
    category: "text",
    component: "AnimatedText",
    description: "Character-by-character text reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/animated-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-bounce-text",
    label: "Bounce Text",
    category: "text",
    component: "BounceText",
    description: "Spring bounce entrance for titles.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/bounce-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-bubble-pop-text",
    label: "Bubble Pop Text",
    category: "text",
    component: "BubblePopText",
    description: "Characters pop in inside bubbles.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/bubble-pop-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-floating-bubble-text",
    label: "Floating Text Chip",
    category: "text",
    component: "FloatingBubbleText",
    description: "Floating label with sine-wave wobble.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/floating-bubble-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-glitch-text",
    label: "Glitch Text",
    category: "text",
    component: "GlitchText",
    description: "RGB split glitch with decay.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/glitch-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-popping-text",
    label: "Popping Scale Text",
    category: "text",
    component: "PoppingText",
    description: "Spring-based scale pop entrance.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/popping-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-pulsing-text",
    label: "Pulsing Text",
    category: "text",
    component: "PulsingText",
    description: "Continuous scale pulse for emphasis.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/pulsing-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-slide-text",
    label: "Slide Text",
    category: "text",
    component: "SlideText",
    description: "Directional slide-in text.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/slide-text.tsx" },
    status: "ported",
  },
  {
    id: "rve-typewriter-subtitle",
    label: "Typewriter Subtitle",
    category: "text",
    component: "TypewriterSubtitle",
    description: "Character-by-character typing with cursor.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/typewriter-subtitle.tsx" },
    status: "ported",
  },
  {
    id: "rve-animated-list",
    label: "Animated List",
    category: "scene",
    component: "AnimatedList",
    description: "Staggered list item entrance.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/animated-list.tsx" },
    status: "ported",
  },
  {
    id: "rve-card-flip",
    label: "Card Flip",
    category: "scene",
    component: "CardFlip",
    description: "3D card flip with front/back content.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/card-flip.tsx" },
    status: "ported",
  },
  {
    id: "rve-countdown-timer",
    label: "Countdown Timer",
    category: "scene",
    component: "CountdownTimer",
    description: "5-4-3-2-1-GO with spring scale.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/countdown-timer.tsx" },
    status: "ported",
  },
  {
    id: "rve-notification-pop",
    label: "Notification Pop",
    category: "scene",
    component: "NotificationPop",
    description: "Stacking notification toasts.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/notification-pop.tsx" },
    status: "ported",
  },
  {
    id: "rve-particle-explosion",
    label: "Particle Explosion",
    category: "scene",
    component: "ParticleExplosion",
    description: "Burst particles from centre.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/particle-explosion.tsx" },
    status: "ported",
  },
  {
    id: "rve-progress-steps",
    label: "Progress Steps",
    category: "scene",
    component: "ProgressSteps",
    description: "Step indicator filling in sequence.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/progress-steps.tsx" },
    status: "ported",
  },
  {
    id: "rve-rotating-carousel",
    label: "Rotating Carousel",
    category: "scene",
    component: "RotatingCarousel",
    description: "3D rotating card carousel.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/rotating-carousel.tsx" },
    status: "ported",
  },
  {
    id: "rve-sound-wave",
    label: "Sound Wave",
    category: "scene",
    component: "SoundWave",
    description: "Audio waveform bar visualiser.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/sound-wave.tsx" },
    status: "ported",
  },
  {
    id: "rve-text-highlight",
    label: "Text Highlight",
    category: "scene",
    component: "TextHighlight",
    description: "Sequential word highlighting.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/text-highlight.tsx" },
    status: "ported",
  },
  {
    id: "rve-bokeh-circles",
    label: "Bokeh Circles",
    category: "background",
    component: "BokehCircles",
    description: "Floating soft circles with drift.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/bokeh-circles.tsx" },
    status: "ported",
  },
  {
    id: "rve-geometric-patterns",
    label: "Geometric Patterns",
    category: "background",
    component: "GeometricPatterns",
    description: "Rotating/scaling geometric shapes.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/geometric-patterns.tsx" },
    status: "ported",
  },
  {
    id: "rve-gradient-shift",
    label: "Gradient Shift",
    category: "background",
    component: "GradientShiftBackground",
    description: "Slowly shifting ambient gradient.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/gradient-shift.tsx" },
    status: "ported",
  },
  {
    id: "rve-grid-pulse",
    label: "Grid Pulse",
    category: "background",
    component: "GridPulse",
    description: "Dot grid with ripple wave pulse.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/grid-pulse.tsx" },
    status: "ported",
  },
  {
    id: "rve-liquid-wave",
    label: "Liquid Wave",
    category: "background",
    component: "LiquidWave",
    description: "Flowing SVG wave shapes.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/liquid-wave.tsx" },
    status: "ported",
  },
  {
    id: "rve-matrix-rain",
    label: "Matrix Rain",
    category: "background",
    component: "MatrixRain",
    description: "Falling code rain columns.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/matrix-rain.tsx" },
    status: "ported",
  },
  {
    id: "rve-noise-grain",
    label: "Noise Grain",
    category: "background",
    component: "NoiseGrain",
    description: "Subtle film grain overlay.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/noise-grain.tsx" },
    status: "ported",
  },
  {
    id: "rve-pixel-transition",
    label: "Pixel Transition",
    category: "background",
    component: "PixelTransition",
    description: "Pixelated grid reveal.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/pixel-transition.tsx" },
    status: "ported",
  },
  {
    id: "rve-starfield",
    label: "Starfield",
    category: "background",
    component: "Starfield",
    description: "Flying-through-space star effect.",
    durationInFrames: 180,
    source: { ...rveSource, file: "templates/starfield.tsx" },
    status: "ported",
  },
  {
    id: "rve-camera-shake",
    label: "Camera Shake",
    category: "cinematic",
    component: "CameraShake",
    description: "Decaying shake for impact moments.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/camera-shake.tsx" },
    status: "ported",
  },
  {
    id: "rve-film-burn",
    label: "Film Burn",
    category: "cinematic",
    component: "FilmBurn",
    description: "Warm light leak overlay.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/film-burn.tsx" },
    status: "ported",
  },
  {
    id: "rve-ken-burns",
    label: "Ken Burns",
    category: "cinematic",
    component: "KenBurns",
    description: "Pan and zoom for images.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/ken-burns.tsx" },
    status: "ported",
  },
  {
    id: "rve-letterbox-reveal",
    label: "Letterbox Reveal",
    category: "cinematic",
    component: "LetterboxReveal",
    description: "Black bars retracting to reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/letterbox-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-parallax-pan",
    label: "Parallax Pan",
    category: "cinematic",
    component: "ParallaxPan",
    description: "Multi-layer parallax scrolling.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/parallax-pan.tsx" },
    status: "ported",
  },
  {
    id: "rve-spotlight-reveal",
    label: "Spotlight Reveal",
    category: "cinematic",
    component: "SpotlightReveal",
    description: "Expanding circle clip-path reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/spotlight-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-vignette-pulse",
    label: "Vignette Pulse",
    category: "cinematic",
    component: "VignettePulse",
    description: "Pulsing darkened edges overlay.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/vignette-pulse.tsx" },
    status: "ported",
  },
  {
    id: "rve-whip-pan",
    label: "Whip Pan",
    category: "cinematic",
    component: "WhipPan",
    description: "Fast horizontal pan with motion blur.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/whip-pan.tsx" },
    status: "ported",
  },
  {
    id: "rve-zoom-pulse",
    label: "Zoom Pulse",
    category: "cinematic",
    component: "ZoomPulse",
    description: "Rhythmic zoom in/out pulse.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/zoom-pulse.tsx" },
    status: "ported",
  },
  {
    id: "rve-blinds-transition",
    label: "Blinds Transition",
    category: "transition",
    component: "BlindsTransition",
    description: "Horizontal blinds opening.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/blinds-transition.tsx" },
    status: "ported",
  },
  {
    id: "rve-clock-wipe",
    label: "Clock Wipe",
    category: "transition",
    component: "ClockWipe",
    description: "Radial clock-hand sweep.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/clock-wipe.tsx" },
    status: "ported",
  },
  {
    id: "rve-cross-dissolve",
    label: "Cross Dissolve",
    category: "transition",
    component: "CrossDissolve",
    description: "Classic cross-fade between scenes.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/cross-dissolve.tsx" },
    status: "ported",
  },
  {
    id: "rve-fade-through-black",
    label: "Fade Through Black",
    category: "transition",
    component: "FadeThroughBlack",
    description: "Dip to black between scenes.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/fade-through-black.tsx" },
    status: "ported",
  },
  {
    id: "rve-iris-transition",
    label: "Iris Transition",
    category: "transition",
    component: "IrisTransition",
    description: "Circular iris close/open.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/iris-transition.tsx" },
    status: "ported",
  },
  {
    id: "rve-morph-transition",
    label: "Morph Transition",
    category: "transition",
    component: "MorphTransition",
    description: "Scale-and-fade morph.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/morph-transition.tsx" },
    status: "ported",
  },
  {
    id: "rve-push-transition",
    label: "Push Transition",
    category: "transition",
    component: "PushTransition",
    description: "New scene pushes old off-screen.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/push-transition.tsx" },
    status: "ported",
  },
  {
    id: "rve-slide-wipe",
    label: "Slide Wipe",
    category: "transition",
    component: "SlideWipe",
    description: "Spring-driven panel slide.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/slide-wipe.tsx" },
    status: "ported",
  },
  {
    id: "rve-zoom-through",
    label: "Zoom Through",
    category: "transition",
    component: "ZoomThrough",
    description: "Zoom in then zoom out reveal.",
    durationInFrames: 90,
    source: { ...rveSource, file: "templates/zoom-through.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-blur-reveal",
    label: "Logo Blur Reveal",
    category: "logo",
    component: "LogoBlurReveal",
    description: "Focus-pull blur to sharp.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-blur-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-bounce-drop",
    label: "Logo Bounce Drop",
    category: "logo",
    component: "LogoBounceDrop",
    description: "Drop from above with bounce.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-bounce-drop.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-fade-reveal",
    label: "Logo Fade Reveal",
    category: "logo",
    component: "LogoFadeReveal",
    description: "Fade in with subtle scale-up.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-fade-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-glitch-reveal",
    label: "Logo Glitch Reveal",
    category: "logo",
    component: "LogoGlitchReveal",
    description: "RGB split glitch decaying to clean.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-glitch-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-scale-rotate",
    label: "Logo Scale Rotate",
    category: "logo",
    component: "LogoScaleRotate",
    description: "Spinning scale entrance.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-scale-rotate.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-spin-reveal",
    label: "Logo Spin Reveal",
    category: "logo",
    component: "LogoSpinReveal",
    description: "3D Y-axis spin reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-spin-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-split-reveal",
    label: "Logo Split Reveal",
    category: "logo",
    component: "LogoSplitReveal",
    description: "Left/right halves expanding.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-split-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-stroke-draw",
    label: "Logo Stroke Draw",
    category: "logo",
    component: "LogoStrokeDraw",
    description: "SVG stroke drawing animation.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-stroke-draw.tsx" },
    status: "ported",
  },
  {
    id: "rve-logo-typewriter",
    label: "Logo Typewriter",
    category: "logo",
    component: "LogoTypewriter",
    description: "Icon + typed company name.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/logo-typewriter.tsx" },
    status: "ported",
  },
  {
    id: "rve-chapter-title",
    label: "Chapter Title",
    category: "scene",
    component: "ChapterTitle",
    description: "Chapter number with extending lines.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/chapter-title.tsx" },
    status: "ported",
  },
  {
    id: "rve-cinematic-title-intro",
    label: "Cinematic Title Intro",
    category: "scene",
    component: "CinematicTitleIntro",
    description: "Title spring-in with growing underline.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/cinematic-title-intro.tsx" },
    status: "ported",
  },
  {
    id: "rve-countdown-intro",
    label: "Countdown Intro",
    category: "scene",
    component: "CountdownIntro",
    description: "Ring countdown 3-2-1-GO.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/countdown-intro.tsx" },
    status: "ported",
  },
  {
    id: "rve-credits-roll",
    label: "Credits Roll",
    category: "scene",
    component: "CreditsRoll",
    description: "Scrolling movie-style credits.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/credits-roll.tsx" },
    status: "ported",
  },
  {
    id: "rve-end-card",
    label: "End Card",
    category: "scene",
    component: "EndCard",
    description: "Outro with subscribe CTA.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/end-card.tsx" },
    status: "ported",
  },
  {
    id: "rve-lower-third",
    label: "Lower Third",
    category: "scene",
    component: "LowerThird",
    description: "News-style name/title bar.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/lower-third.tsx" },
    status: "ported",
  },
  {
    id: "rve-quote-card",
    label: "Quote Card",
    category: "scene",
    component: "QuoteCard",
    description: "Animated quotation with attribution.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/quote-card.tsx" },
    status: "ported",
  },
  {
    id: "rve-subscribe-reminder",
    label: "Subscribe Reminder",
    category: "scene",
    component: "SubscribeReminder",
    description: "Floating subscribe overlay.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/subscribe-reminder.tsx" },
    status: "ported",
  },
  {
    id: "rve-title-split",
    label: "Title Split",
    category: "scene",
    component: "TitleSplit",
    description: "Split text meeting in centre.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/title-split.tsx" },
    status: "ported",
  },
  {
    id: "rve-gallery-grid",
    label: "Gallery Grid",
    category: "media",
    component: "GalleryGrid",
    description: "Staggered 2x3 grid reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/gallery-grid.tsx" },
    status: "ported",
  },
  {
    id: "rve-image-carousel",
    label: "Image Carousel",
    category: "media",
    component: "ImageCarousel",
    description: "Horizontal sliding with centre focus.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/image-carousel.tsx" },
    status: "ported",
  },
  {
    id: "rve-image-comparison-slider",
    label: "Image Comparison Slider",
    category: "media",
    component: "ImageComparisonSlider",
    description: "Before/after sliding divider.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/image-comparison-slider.tsx" },
    status: "ported",
  },
  {
    id: "rve-image-zoom-reveal",
    label: "Image Zoom Reveal",
    category: "media",
    component: "ImageZoomReveal",
    description: "Zoom-out focus-pull reveal.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/image-zoom-reveal.tsx" },
    status: "ported",
  },
  {
    id: "rve-masonry-gallery",
    label: "Masonry Gallery",
    category: "media",
    component: "MasonryGallery",
    description: "Pinterest-style staggered grid.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/masonry-gallery.tsx" },
    status: "ported",
  },
  {
    id: "rve-photo-stack",
    label: "Photo Stack",
    category: "media",
    component: "PhotoStack",
    description: "Overlapping frames with rotation.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/photo-stack.tsx" },
    status: "ported",
  },
  {
    id: "rve-picture-in-picture",
    label: "Picture in Picture",
    category: "media",
    component: "PictureInPicture",
    description: "PiP overlay layout.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/picture-in-picture.tsx" },
    status: "ported",
  },
  {
    id: "rve-polaroid-frame",
    label: "Polaroid Frame",
    category: "media",
    component: "PolaroidFrame",
    description: "Polaroid-style photo with drop-in.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/polaroid-frame.tsx" },
    status: "ported",
  },
  {
    id: "rve-split-screen",
    label: "Split Screen",
    category: "media",
    component: "SplitScreen",
    description: "Two panels sliding to meet.",
    durationInFrames: 120,
    source: { ...rveSource, file: "templates/split-screen.tsx" },
    status: "ported",
  },
] as const satisfies readonly PrimitiveCatalogEntry[];

export type PrimitiveCatalogId = (typeof primitiveCatalog)[number]["id"];

export const defaultPrimitiveCatalogId: PrimitiveCatalogId = "rve-popping-text";
