// Generated by the direct VoxCPM Producer runtime for the 2026-07-19 AI daily news brief.

import type { AudioTrack } from "./types";

export const aiDailyNews20260719Audio = [
  {
    "sceneId": "open",
    "narration": "AI 行业正在从模型竞赛进一步转向四个更具体的竞争层：算力交易、开放模型、Agent 安全和运行责任。Meta 可能把自建算力出售给其他模型公司；Kimi K3 继续推动开放模型向前沿能力逼近；Capital One 将 Agent 引入代码安全；澳大利亚则准备限制政府使用自动化 AI 决策。资本仍大量进入数据和算力基础设施，但投资者开始表现出更明显的价格纪律。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI 行业正在从模型竞赛进一步转向四个更具体的竞争层：",
          "startFrame": 0,
          "durationInFrames": 153
        },
        {
          "id": "caption-2",
          "text": "算力交易、开放模型、Agent 安全和运行责任。",
          "startFrame": 153,
          "durationInFrames": 128
        },
        {
          "id": "caption-3",
          "text": "Meta 可能把自建算力出售给其他模型公司；",
          "startFrame": 281,
          "durationInFrames": 104
        },
        {
          "id": "caption-4",
          "text": "Kimi K3 继续推动开放模型向前沿能力逼近；",
          "startFrame": 385,
          "durationInFrames": 117
        },
        {
          "id": "caption-5",
          "text": "Capital One 将 Agent 引入代码安全；",
          "startFrame": 502,
          "durationInFrames": 90
        },
        {
          "id": "caption-6",
          "text": "澳大利亚则准备限制政府使用自动化 AI 决策。",
          "startFrame": 592,
          "durationInFrames": 116
        },
        {
          "id": "caption-7",
          "text": "资本仍大量进入数据和算力基础设施，",
          "startFrame": 708,
          "durationInFrames": 98
        },
        {
          "id": "caption-8",
          "text": "但投资者开始表现出更明显的价格纪律。",
          "startFrame": 806,
          "durationInFrames": 97
        }
      ]
    },
    "durationInFrames": 903,
    "durationInSeconds": 30.1161875,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "meta-anthropic",
    "narration": "Meta 正与 Anthropic 初步讨论一项最高约 100 亿美元的算力租赁协议。交易尚未确定，如果落地，Anthropic 将购买 Meta 数据中心提供的计算能力。这意味着 Meta 的基础设施定位可能发生变化：从为广告、推荐系统和自有模型建设算力，转向建设超大规模 AI 基础设施，并向其他模型公司出售计算能力。Meta 此前主要是 AWS、Azure 和 Google Cloud 的客户或竞争者。现在它可能利用自建数据中心进入 AI 云计算市场，而 Anthropic 则可以继续分散算力供应商，降低对 Amazon、Google 等单一平台的依赖。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/meta-anthropic.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Meta 正与 Anthropic 初步讨论一项最高约 100 亿美元的算力租赁协议。",
          "startFrame": 0,
          "durationInFrames": 161
        },
        {
          "id": "caption-2",
          "text": "交易尚未确定，",
          "startFrame": 161,
          "durationInFrames": 41
        },
        {
          "id": "caption-3",
          "text": "如果落地，",
          "startFrame": 202,
          "durationInFrames": 27
        },
        {
          "id": "caption-4",
          "text": "Anthropic 将购买 Meta 数据中心提供的计算能力。",
          "startFrame": 229,
          "durationInFrames": 126
        },
        {
          "id": "caption-5",
          "text": "这意味着 Meta 的基础设施定位可能发生变化：",
          "startFrame": 355,
          "durationInFrames": 108
        },
        {
          "id": "caption-6",
          "text": "从为广告、推荐系统和自有模型建设算力，",
          "startFrame": 463,
          "durationInFrames": 123
        },
        {
          "id": "caption-7",
          "text": "转向建设超大规模 AI 基础设施，",
          "startFrame": 586,
          "durationInFrames": 84
        },
        {
          "id": "caption-8",
          "text": "并向其他模型公司出售计算能力。",
          "startFrame": 670,
          "durationInFrames": 86
        },
        {
          "id": "caption-9",
          "text": "Meta 此前主要是 AWS、Azure 和 Google Cloud 的客户或竞争者。",
          "startFrame": 756,
          "durationInFrames": 168
        },
        {
          "id": "caption-10",
          "text": "现在它可能利用自建数据中心进入 AI 云计算市场，",
          "startFrame": 924,
          "durationInFrames": 130
        },
        {
          "id": "caption-11",
          "text": "而 Anthropic 则可以继续分散算力供应商，",
          "startFrame": 1054,
          "durationInFrames": 111
        },
        {
          "id": "caption-12",
          "text": "降低对 Amazon、Google 等单一平台的依赖。",
          "startFrame": 1165,
          "durationInFrames": 114
        }
      ]
    },
    "durationInFrames": 1279,
    "durationInSeconds": 42.6295625,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "vulnhunter",
    "narration": "Capital One 发布并开源 VulnHunter。它不是传统的规则匹配式静态扫描器，而是从攻击者视角分析源代码，判断缺陷是否真正可利用，追踪潜在攻击路径，并给出有证据支持的修复建议。该项目使用 Apache 2.0 许可证。其核心方向是让 Agent 完成一条更完整的安全分析链：理解代码结构，查找可疑入口，追踪数据流和调用链，判断是否可利用，构建攻击路径，提出针对性修复。这说明企业级代码 Agent 正从生成代码和审查代码风格，进入漏洞验证、攻击面分析和修复证明等高风险任务。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/vulnhunter.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Capital One 发布并开源 VulnHunter。",
          "startFrame": 0,
          "durationInFrames": 92
        },
        {
          "id": "caption-2",
          "text": "它不是传统的规则匹配式静态扫描器，",
          "startFrame": 92,
          "durationInFrames": 97
        },
        {
          "id": "caption-3",
          "text": "而是从攻击者视角分析源代码，",
          "startFrame": 189,
          "durationInFrames": 87
        },
        {
          "id": "caption-4",
          "text": "判断缺陷是否真正可利用，",
          "startFrame": 276,
          "durationInFrames": 83
        },
        {
          "id": "caption-5",
          "text": "追踪潜在攻击路径，",
          "startFrame": 359,
          "durationInFrames": 51
        },
        {
          "id": "caption-6",
          "text": "并给出有证据支持的修复建议。",
          "startFrame": 410,
          "durationInFrames": 83
        },
        {
          "id": "caption-7",
          "text": "该项目使用 Apache 2.0 许可证。",
          "startFrame": 493,
          "durationInFrames": 84
        },
        {
          "id": "caption-8",
          "text": "其核心方向是让 Agent 完成一条更完整的安全分析链：",
          "startFrame": 577,
          "durationInFrames": 139
        },
        {
          "id": "caption-9",
          "text": "理解代码结构，",
          "startFrame": 716,
          "durationInFrames": 30
        },
        {
          "id": "caption-10",
          "text": "查找可疑入口，",
          "startFrame": 746,
          "durationInFrames": 43
        },
        {
          "id": "caption-11",
          "text": "追踪数据流和调用链，",
          "startFrame": 789,
          "durationInFrames": 58
        },
        {
          "id": "caption-12",
          "text": "判断是否可利用，",
          "startFrame": 847,
          "durationInFrames": 67
        },
        {
          "id": "caption-13",
          "text": "构建攻击路径，",
          "startFrame": 914,
          "durationInFrames": 45
        },
        {
          "id": "caption-14",
          "text": "提出针对性修复。",
          "startFrame": 959,
          "durationInFrames": 50
        },
        {
          "id": "caption-15",
          "text": "这说明企业级代码 Agent 正从生成代码和审查代码风格，",
          "startFrame": 1009,
          "durationInFrames": 147
        },
        {
          "id": "caption-16",
          "text": "进入漏洞验证、攻击面分析和修复证明等高风险任务。",
          "startFrame": 1156,
          "durationInFrames": 150
        }
      ]
    },
    "durationInFrames": 1306,
    "durationInSeconds": 43.53477083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "kimi-k3",
    "narration": "Moonshot AI 将 Kimi K3 定位为其目前最强的旗舰模型。总参数量达到 2.8 万亿，上下文窗口为 100 万 Token，支持原生文本与视觉理解。架构创新包括 Kimi Delta Attention 和 Attention Residuals。官方称其为首个达到约 3 万亿参数规模的开放模型。早期第三方结果显示，其前端编程能力在 Arena 排名靠前，但综合可靠性、推理成本和长任务成功率仍需要更多独立测试。K3 的意义不只是参数更大，而是开放模型开始同时具备百万级上下文、原生多模态、长周期工具调用和面向大型代码库的 Agent 能力。需要注意，开放模型不等于普通设备可以本地运行。2.8 万亿参数仍需要大型算力集群或托管推理服务。它真正改变的是企业的议价能力、私有化选择和模型替换能力。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/kimi-k3.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Moonshot AI 将 Kimi K3 定位为其目前最强的旗舰模型。",
          "startFrame": 0,
          "durationInFrames": 147
        },
        {
          "id": "caption-2",
          "text": "总参数量达到 2.8 万亿，",
          "startFrame": 147,
          "durationInFrames": 68
        },
        {
          "id": "caption-3",
          "text": "上下文窗口为 100 万 Token，",
          "startFrame": 215,
          "durationInFrames": 69
        },
        {
          "id": "caption-4",
          "text": "支持原生文本与视觉理解。",
          "startFrame": 284,
          "durationInFrames": 86
        },
        {
          "id": "caption-5",
          "text": "架构创新包括 Kimi Delta Attention 和 Attention Residuals。",
          "startFrame": 370,
          "durationInFrames": 130
        },
        {
          "id": "caption-6",
          "text": "官方称其为首个达到约 3 万亿参数规模的开放模型。",
          "startFrame": 500,
          "durationInFrames": 131
        },
        {
          "id": "caption-7",
          "text": "早期第三方结果显示，",
          "startFrame": 631,
          "durationInFrames": 61
        },
        {
          "id": "caption-8",
          "text": "其前端编程能力在 Arena 排名靠前，",
          "startFrame": 692,
          "durationInFrames": 112
        },
        {
          "id": "caption-9",
          "text": "但综合可靠性、推理成本和长任务成功率仍需要更多独立测试。",
          "startFrame": 804,
          "durationInFrames": 168
        },
        {
          "id": "caption-10",
          "text": "K3 的意义不只是参数更大，",
          "startFrame": 972,
          "durationInFrames": 82
        },
        {
          "id": "caption-11",
          "text": "而是开放模型开始同时具备百万级上下文、原生多模态、长周期工具调用和面向大型代码库的 Agent 能力。",
          "startFrame": 1054,
          "durationInFrames": 278
        },
        {
          "id": "caption-12",
          "text": "需要注意，",
          "startFrame": 1332,
          "durationInFrames": 50
        },
        {
          "id": "caption-13",
          "text": "开放模型不等于普通设备可以本地运行。",
          "startFrame": 1382,
          "durationInFrames": 101
        },
        {
          "id": "caption-14",
          "text": "2.8 万亿参数仍需要大型算力集群或托管推理服务。",
          "startFrame": 1483,
          "durationInFrames": 155
        },
        {
          "id": "caption-15",
          "text": "它真正改变的是企业的议价能力、私有化选择和模型替换能力。",
          "startFrame": 1638,
          "durationInFrames": 187
        }
      ]
    },
    "durationInFrames": 1825,
    "durationInSeconds": 60.822854166666666,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "australia-regulation",
    "narration": "澳大利亚正在制定新的 AI 治理措施，重点限制政府部门在公共服务中使用完全自动化的 AI 决策系统，并强化透明度、人工复核和责任追踪。相关改革仍处于推进阶段，并非所有措施都已完成立法。计划还包括建立中央级 AI 办公室，推动面向 AI 企业的数字注意义务，更新隐私和消费者保护规则，监管基于个人数据进行差异化定价的行为，以及评估数据中心对电网、土地和基础设施的影响。这代表 AI 监管正在从模型本身扩展到完整运行环境：训练数据是否合法，模型输出是否安全，自动决策能否申诉，人类是否保留最终责任，数据中心由谁承担基础设施成本。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/australia-regulation.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "澳大利亚正在制定新的 AI 治理措施，",
          "startFrame": 0,
          "durationInFrames": 83
        },
        {
          "id": "caption-2",
          "text": "重点限制政府部门在公共服务中使用完全自动化的 AI 决策系统，",
          "startFrame": 83,
          "durationInFrames": 161
        },
        {
          "id": "caption-3",
          "text": "并强化透明度、人工复核和责任追踪。",
          "startFrame": 244,
          "durationInFrames": 103
        },
        {
          "id": "caption-4",
          "text": "相关改革仍处于推进阶段，",
          "startFrame": 347,
          "durationInFrames": 66
        },
        {
          "id": "caption-5",
          "text": "并非所有措施都已完成立法。",
          "startFrame": 413,
          "durationInFrames": 80
        },
        {
          "id": "caption-6",
          "text": "计划还包括建立中央级 AI 办公室，",
          "startFrame": 493,
          "durationInFrames": 89
        },
        {
          "id": "caption-7",
          "text": "推动面向 AI 企业的数字注意义务，",
          "startFrame": 582,
          "durationInFrames": 83
        },
        {
          "id": "caption-8",
          "text": "更新隐私和消费者保护规则，",
          "startFrame": 665,
          "durationInFrames": 79
        },
        {
          "id": "caption-9",
          "text": "监管基于个人数据进行差异化定价的行为，",
          "startFrame": 744,
          "durationInFrames": 112
        },
        {
          "id": "caption-10",
          "text": "以及评估数据中心对电网、土地和基础设施的影响。",
          "startFrame": 856,
          "durationInFrames": 147
        },
        {
          "id": "caption-11",
          "text": "这代表 AI 监管正在从模型本身扩展到完整运行环境：",
          "startFrame": 1003,
          "durationInFrames": 143
        },
        {
          "id": "caption-12",
          "text": "训练数据是否合法，",
          "startFrame": 1146,
          "durationInFrames": 55
        },
        {
          "id": "caption-13",
          "text": "模型输出是否安全，",
          "startFrame": 1201,
          "durationInFrames": 57
        },
        {
          "id": "caption-14",
          "text": "自动决策能否申诉，",
          "startFrame": 1258,
          "durationInFrames": 50
        },
        {
          "id": "caption-15",
          "text": "人类是否保留最终责任，",
          "startFrame": 1308,
          "durationInFrames": 64
        },
        {
          "id": "caption-16",
          "text": "数据中心由谁承担基础设施成本。",
          "startFrame": 1372,
          "durationInFrames": 89
        }
      ]
    },
    "durationInFrames": 1461,
    "durationInSeconds": 48.712,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "databricks",
    "narration": "Databricks 已签署新一轮战略融资的条款清单，估值达到 1880 亿美元。该轮由现有投资者 Coatue 领投，预计在今年夏季完成。Databricks 的高估值说明，资本正在押注模型之下的数据与运行平台。当模型能够快速替换时，掌握企业数据、权限和生产工作流的平台，可能拥有更稳定的长期壁垒。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/databricks.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Databricks 已签署新一轮战略融资的条款清单，",
          "startFrame": 0,
          "durationInFrames": 113
        },
        {
          "id": "caption-2",
          "text": "估值达到 1880 亿美元。",
          "startFrame": 113,
          "durationInFrames": 80
        },
        {
          "id": "caption-3",
          "text": "该轮由现有投资者 Coatue 领投，",
          "startFrame": 193,
          "durationInFrames": 83
        },
        {
          "id": "caption-4",
          "text": "预计在今年夏季完成。",
          "startFrame": 276,
          "durationInFrames": 64
        },
        {
          "id": "caption-5",
          "text": "Databricks 的高估值说明，",
          "startFrame": 340,
          "durationInFrames": 67
        },
        {
          "id": "caption-6",
          "text": "资本正在押注模型之下的数据与运行平台。",
          "startFrame": 407,
          "durationInFrames": 125
        },
        {
          "id": "caption-7",
          "text": "当模型能够快速替换时，",
          "startFrame": 532,
          "durationInFrames": 65
        },
        {
          "id": "caption-8",
          "text": "掌握企业数据、权限和生产工作流的平台，",
          "startFrame": 597,
          "durationInFrames": 106
        },
        {
          "id": "caption-9",
          "text": "可能拥有更稳定的长期壁垒。",
          "startFrame": 703,
          "durationInFrames": 67
        }
      ]
    },
    "durationInFrames": 770,
    "durationInSeconds": 25.65525,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "csquare-ipo",
    "narration": "数据中心运营商 Csquare 通过美国 IPO 融资 10.5 亿美元，发行价为每股 21 美元，低于原计划的 23 至 27 美元区间，公司估值约为 32.5 亿美元。这显示市场仍愿意为 AI 数据中心投入大额资本，但已经不再无条件接受高估值。投资者仍然看好 AI 基础设施需求，同时开始更加关注债务、利用率、电力成本和实际盈利能力。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/csquare-ipo.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "数据中心运营商 Csquare 通过美国 IPO 融资 10.5 亿美元，",
          "startFrame": 0,
          "durationInFrames": 176
        },
        {
          "id": "caption-2",
          "text": "发行价为每股 21 美元，",
          "startFrame": 176,
          "durationInFrames": 67
        },
        {
          "id": "caption-3",
          "text": "低于原计划的 23 至 27 美元区间，",
          "startFrame": 243,
          "durationInFrames": 104
        },
        {
          "id": "caption-4",
          "text": "公司估值约为 32.5 亿美元。",
          "startFrame": 347,
          "durationInFrames": 105
        },
        {
          "id": "caption-5",
          "text": "这显示市场仍愿意为 AI 数据中心投入大额资本，",
          "startFrame": 452,
          "durationInFrames": 132
        },
        {
          "id": "caption-6",
          "text": "但已经不再无条件接受高估值。",
          "startFrame": 584,
          "durationInFrames": 78
        },
        {
          "id": "caption-7",
          "text": "投资者仍然看好 AI 基础设施需求，",
          "startFrame": 662,
          "durationInFrames": 84
        },
        {
          "id": "caption-8",
          "text": "同时开始更加关注债务、利用率、电力成本和实际盈利能力。",
          "startFrame": 746,
          "durationInFrames": 145
        }
      ]
    },
    "durationInFrames": 891,
    "durationInSeconds": 29.692625,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "trend-summary",
    "narration": "算力成为独立商品，Meta 或向 Anthropic 出售算力，模型公司与云厂商边界模糊。开放模型继续前沿化，Kimi K3 达到 2.8 万亿参数，闭源模型价格与锁定能力承压。Agent 进入安全核心流程，Capital One 开源 VulnHunter，Agent 从辅助工具转向主动验证系统。自动化决策成为监管重点，澳大利亚限制政府 AI 决策，人工复核和责任链成为强制能力。资本集中于数据平台，Databricks 估值 1880 亿美元，企业数据层比单个模型更稳定。基建投资出现价格纪律，Csquare IPO 低于目标定价，AI 基建仍热但估值不再无限扩张。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/trend-summary.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "算力成为独立商品，",
          "startFrame": 0,
          "durationInFrames": 57
        },
        {
          "id": "caption-2",
          "text": "Meta 或向 Anthropic 出售算力，",
          "startFrame": 57,
          "durationInFrames": 87
        },
        {
          "id": "caption-3",
          "text": "模型公司与云厂商边界模糊。",
          "startFrame": 144,
          "durationInFrames": 83
        },
        {
          "id": "caption-4",
          "text": "开放模型继续前沿化，",
          "startFrame": 227,
          "durationInFrames": 56
        },
        {
          "id": "caption-5",
          "text": "Kimi K3 达到 2.8 万亿参数，",
          "startFrame": 283,
          "durationInFrames": 77
        },
        {
          "id": "caption-6",
          "text": "闭源模型价格与锁定能力承压。",
          "startFrame": 360,
          "durationInFrames": 76
        },
        {
          "id": "caption-7",
          "text": "Agent 进入安全核心流程，",
          "startFrame": 436,
          "durationInFrames": 81
        },
        {
          "id": "caption-8",
          "text": "Capital One 开源 VulnHunter，",
          "startFrame": 517,
          "durationInFrames": 66
        },
        {
          "id": "caption-9",
          "text": "Agent 从辅助工具转向主动验证系统。",
          "startFrame": 583,
          "durationInFrames": 109
        },
        {
          "id": "caption-10",
          "text": "自动化决策成为监管重点，",
          "startFrame": 692,
          "durationInFrames": 69
        },
        {
          "id": "caption-11",
          "text": "澳大利亚限制政府 AI 决策，",
          "startFrame": 761,
          "durationInFrames": 80
        },
        {
          "id": "caption-12",
          "text": "人工复核和责任链成为强制能力。",
          "startFrame": 841,
          "durationInFrames": 85
        },
        {
          "id": "caption-13",
          "text": "资本集中于数据平台，",
          "startFrame": 926,
          "durationInFrames": 53
        },
        {
          "id": "caption-14",
          "text": "Databricks 估值 1880 亿美元，",
          "startFrame": 979,
          "durationInFrames": 119
        },
        {
          "id": "caption-15",
          "text": "企业数据层比单个模型更稳定。",
          "startFrame": 1098,
          "durationInFrames": 85
        },
        {
          "id": "caption-16",
          "text": "基建投资出现价格纪律，",
          "startFrame": 1183,
          "durationInFrames": 67
        },
        {
          "id": "caption-17",
          "text": "Csquare IPO 低于目标定价，",
          "startFrame": 1250,
          "durationInFrames": 76
        },
        {
          "id": "caption-18",
          "text": "AI 基建仍热但估值不再无限扩张。",
          "startFrame": 1326,
          "durationInFrames": 92
        }
      ]
    },
    "durationInFrames": 1418,
    "durationInSeconds": 47.26425,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "close",
    "narration": "下一阶段 Agent 系统不能只解决模型会不会调用工具，还需要解决：每次外部操作是否具有明确授权；Agent 的判断能否提供证据链；高风险动作是否需要人工确认；模型、工具和数据之间是否可以替换；失败、重试和人工接管是否被完整记录；一次成功任务的总成本是否可计算。Agent 的长期价值正在从自主性转向可验证的自主性。",
    "audioFile": "generated/ai-daily-news-2026-07-19/audio/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "下一阶段 Agent 系统不能只解决模型会不会调用工具，",
          "startFrame": 0,
          "durationInFrames": 140
        },
        {
          "id": "caption-2",
          "text": "还需要解决：",
          "startFrame": 140,
          "durationInFrames": 46
        },
        {
          "id": "caption-3",
          "text": "每次外部操作是否具有明确授权；",
          "startFrame": 186,
          "durationInFrames": 105
        },
        {
          "id": "caption-4",
          "text": "Agent 的判断能否提供证据链；",
          "startFrame": 291,
          "durationInFrames": 84
        },
        {
          "id": "caption-5",
          "text": "高风险动作是否需要人工确认；",
          "startFrame": 375,
          "durationInFrames": 82
        },
        {
          "id": "caption-6",
          "text": "模型、工具和数据之间是否可以替换；",
          "startFrame": 457,
          "durationInFrames": 116
        },
        {
          "id": "caption-7",
          "text": "失败、重试和人工接管是否被完整记录；",
          "startFrame": 573,
          "durationInFrames": 117
        },
        {
          "id": "caption-8",
          "text": "一次成功任务的总成本是否可计算。",
          "startFrame": 690,
          "durationInFrames": 98
        },
        {
          "id": "caption-9",
          "text": "Agent 的长期价值正在从自主性转向可验证的自主性。",
          "startFrame": 788,
          "durationInFrames": 142
        }
      ]
    },
    "durationInFrames": 930,
    "durationInSeconds": 30.9854375,
    "provider": "voxcpm",
    "format": "wav"
  }
] satisfies readonly AudioTrack[];
