#!/usr/bin/env node

import { readFile } from "node:fs/promises";

import {
  createVoxcpmProducerRequestPlan,
  readProducerVoxcpmConfig,
  requestProducerNarrationAsset,
  runProducerAudioGeneration,
} from "../../../scripts/lib/producer-audio/index.js";

import { narrationBeats } from "./script.js";

const root = "src/remotion/AiDailyNews20260719";
const slug = "ai-daily-news-2026-07-19";
const voxcpmConfig = readProducerVoxcpmConfig();

const beats = narrationBeats.map((beat) => ({
  id: beat.id,
  narrationRequired: true,
  ttsText: beat.narration,
  language: "zh-CN",
}));

await runProducerAudioGeneration({
  compositionId: "AiDailyNews20260719",
  beats,
  createRequestPlan: (beat) =>
    createVoxcpmProducerRequestPlan({
      beat,
      mode: "high-fidelity-clone",
      promptAudioPath: "voices/clone/lyy.wav",
      promptTranscriptPath: "voices/clone/lyy.txt",
      referenceAudioPath: "voices/clone/lyy-r.wav",
    }),
  requestNarration: ({ plan }) =>
    requestProducerNarrationAsset({ config: voxcpmConfig, plan, slug }),
  progressDestination: `public/generated/${slug}/audio/progress.json`,
  metadata: {
    header:
      "Generated by the direct VoxCPM Producer runtime for the 2026-07-19 AI daily news brief.",
    exportName: "aiDailyNews20260719Audio",
    typeImport: { name: "AudioTrack", path: "./types" },
    destination: `${root}/audio.generated.ts`,
  },
  duration: {
    source: await readFile(`${root}/types.ts`, "utf8"),
    constantName: "AI_DAILY_NEWS_20260719_DURATION_IN_FRAMES",
    destination: `${root}/types.ts`,
  },
  summaryDestination: `public/generated/${slug}/audio/summary.json`,
  writeOutputs: true,
});

console.log("Audio generation complete.");
console.log("Then run:");
console.log("  npm run producer:validate -- --module src/remotion/AiDailyNews20260719/validation.ts");
console.log("  npm run producer:stills -- --composition AiDailyNews20260719");