import type { QualityGatedMaintainedProducerSampleManifest } from "../producer-samples/manifest";
import { AI_DAILY_NEWS_20260719_COMPOSITION_ID } from "./types";

export const aiDailyNews20260719Manifest = {
  sampleStatus: "maintained",
  compositionId: AI_DAILY_NEWS_20260719_COMPOSITION_ID,
  sampleName: "AiDailyNews20260719",
  slug: "ai-daily-news-2026-07-19",
  contentFamily: "trend-briefing",
  canvasProfile: "landscape-16x9",
  styleProfileId: "hand-drawn-explainer",
  localArtifactRoot: "public/generated/ai-daily-news-2026-07-19/",
  ttsStatus: "generated-local",
  productionBrief: {
    audience: "AI software engineers and developers interested in daily AI industry news.",
    publishingSurface: "Local review, landscape social media, and technical explainer publishing.",
    durationTargetSeconds: 300,
  },
  narration: {
    required: true,
    provider: "voxcpm",
    mode: "high-fidelity-clone",
    scriptPath: "src/remotion/AiDailyNews20260719/script.ts",
    audioMetadataPath: "src/remotion/AiDailyNews20260719/audio.generated.ts",
  },
  assets: {
    manifestPath: "src/remotion/AiDailyNews20260719/assets.manifest.json",
  },
  validationModule: "src/remotion/AiDailyNews20260719/validation.ts",
  qualityModule: "src/remotion/AiDailyNews20260719/quality.ts",
  render: {
    metadataPath: "src/remotion/AiDailyNews20260719/render-metadata.json",
    cover16x9CompositionId: "AiDailyNews20260719Cover16x9",
    cover9x16CompositionId: "AiDailyNews20260719Cover9x16",
  },
  publishingCopyPath: "src/remotion/AiDailyNews20260719/publishing.md",
  reviewFrames: [
    { frame: 30, label: "opening-thesis", purpose: "Check opening headline hierarchy, paper texture, and safe margins." },
    { frame: 300, label: "meta-anthropic", purpose: "Check Meta/Anthropic compute deal scene with $10B badge." },
    { frame: 800, label: "vulnhunter", purpose: "Check VulnHunter security chain scene and accent color." },
    { frame: 1400, label: "kimi-k3", purpose: "Check Kimi K3 data badges and caveat sketch frame." },
    { frame: 2200, label: "australia-regulation", purpose: "Check Australia regulation scene with bullet list." },
    { frame: 2800, label: "databricks", purpose: "Check Databricks $1880B valuation scene." },
    { frame: 3200, label: "csquare-ipo", purpose: "Check Csquare IPO data badges and quote frame." },
    { frame: 3600, label: "trend-summary", purpose: "Check summary matrix with six data badges." },
    { frame: 4000, label: "closing", purpose: "Check closing statement, caption clearance, and safe area." },
  ],
  sourceFiles: [
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}.tsx`, kind: "renderer" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/types.ts`, kind: "types" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/script.ts`, kind: "script" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/data.ts`, kind: "data" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/audio.generated.ts`, kind: "audio-metadata" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/manifest.ts`, kind: "manifest" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/assets.manifest.json`, kind: "asset-manifest" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/soundtrack.tsx`, kind: "soundtrack" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/validation.ts`, kind: "validation" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/quality.ts`, kind: "quality" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/cover.tsx`, kind: "cover" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/render-metadata.json`, kind: "render-metadata" },
    { path: `src/remotion/${AI_DAILY_NEWS_20260719_COMPOSITION_ID}/publishing.md`, kind: "publishing-copy" },
    { path: "src/remotion/Root.tsx", kind: "root-registration" },
  ],
  promotionCandidates: [],
  notes: [
    "This composition proves hand-drawn-explainer style profile in landscape 16:9 format for a daily AI news brief.",
    "Generated narration, localized assets, review frames, covers, metadata, and MP4 remain local-only.",
    "Content is user-provided AI daily news from July 19, 2026 covering Meta/Anthropic, VulnHunter, Kimi K3, Australia regulation, Databricks, and Csquare IPO.",
    "Uses LYY high-fidelity-clone voice for non-science narration.",
  ],
} as const satisfies QualityGatedMaintainedProducerSampleManifest;