// Generated by the direct VoxCPM Producer runtime for DnsResolutionExplainer.

import type { DnsResolutionExplainerAudioTrack } from "./types";

export const dnsResolutionExplainerAudio = [
  {
    sceneId: "cache",
    narration: "输入域名后，浏览器先检查本机和系统缓存；没有答案，才把问题交给递归解析器。",
    audioFile: "generated/dns-resolution-explainer/audio/cache.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "输入域名后，",
          startFrame: 0,
          durationInFrames: 34,
        },
        {
          id: "caption-2",
          text: "浏览器先检查本机和系统缓存；",
          startFrame: 34,
          durationInFrames: 88,
        },
        {
          id: "caption-3",
          text: "没有答案，",
          startFrame: 122,
          durationInFrames: 28,
        },
        {
          id: "caption-4",
          text: "才把问题交给递归解析器。",
          startFrame: 150,
          durationInFrames: 68,
        },
      ],
    },
    durationInFrames: 218,
    durationInSeconds: 7.282375,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "delegation",
    narration:
      "解析器先问根服务器，再找到顶级域服务器，最后抵达权威服务器；每一步都返回下一站的线索。",
    audioFile: "generated/dns-resolution-explainer/audio/delegation.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "解析器先问根服务器，",
          startFrame: 0,
          durationInFrames: 55,
        },
        {
          id: "caption-2",
          text: "再找到顶级域服务器，",
          startFrame: 55,
          durationInFrames: 53,
        },
        {
          id: "caption-3",
          text: "最后抵达权威服务器；",
          startFrame: 108,
          durationInFrames: 71,
        },
        {
          id: "caption-4",
          text: "每一步都返回下一站的线索。",
          startFrame: 179,
          durationInFrames: 79,
        },
      ],
    },
    durationInFrames: 258,
    durationInSeconds: 8.592229166666666,
    provider: "voxcpm",
    format: "wav",
  },
  {
    sceneId: "answer",
    narration:
      "权威服务器给出记录和生存时间；解析器缓存结果，把 IP 地址交回浏览器，后续查询因此更快。",
    audioFile: "generated/dns-resolution-explainer/audio/answer.wav",
    captions: {
      language: "zh-CN",
      cues: [
        {
          id: "caption-1",
          text: "权威服务器给出记录和生存时间；",
          startFrame: 0,
          durationInFrames: 99,
        },
        {
          id: "caption-2",
          text: "解析器缓存结果，",
          startFrame: 99,
          durationInFrames: 54,
        },
        {
          id: "caption-3",
          text: "把 IP 地址交回浏览器，",
          startFrame: 153,
          durationInFrames: 55,
        },
        {
          id: "caption-4",
          text: "后续查询因此更快。",
          startFrame: 208,
          durationInFrames: 53,
        },
      ],
    },
    durationInFrames: 261,
    durationInSeconds: 8.698770833333333,
    provider: "voxcpm",
    format: "wav",
  },
] satisfies readonly DnsResolutionExplainerAudioTrack[];
