// Generated by the direct VoxCPM Producer runtime.

import type { AudioTrack } from "./types";

export const aiDailyNews20260717Audio = [
  {
    "sceneId": "open",
    "narration": "今天最重要的变化，是 AI 行业开始出现明显分化：模型能力继续快速提升，但资本市场已经开始追问投入回报、基础设施成本和实际任务完成率。Moonshot 发布超大规模开放权重模型，Databricks 获得接近两千亿美元估值；与此同时，投资者开始降低对芯片股和无限制数据中心扩张的预期，企业则把评价指标从每百万 Token 价格转向了完成一个可靠任务的总成本。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天最重要的变化，",
          "startFrame": 0,
          "durationInFrames": 50
        },
        {
          "id": "caption-2",
          "text": "是 AI 行业开始出现明显分化：",
          "startFrame": 50,
          "durationInFrames": 81
        },
        {
          "id": "caption-3",
          "text": "模型能力继续快速提升，",
          "startFrame": 131,
          "durationInFrames": 66
        },
        {
          "id": "caption-4",
          "text": "但资本市场已经开始追问投入回报、基础设施成本和实际任务完成率。",
          "startFrame": 197,
          "durationInFrames": 192
        },
        {
          "id": "caption-5",
          "text": "Moonshot 发布超大规模开放权重模型，",
          "startFrame": 389,
          "durationInFrames": 99
        },
        {
          "id": "caption-6",
          "text": "Databricks 获得接近两千亿美元估值；",
          "startFrame": 488,
          "durationInFrames": 97
        },
        {
          "id": "caption-7",
          "text": "与此同时，",
          "startFrame": 585,
          "durationInFrames": 33
        },
        {
          "id": "caption-8",
          "text": "投资者开始降低对芯片股和无限制数据中心扩张的预期，",
          "startFrame": 618,
          "durationInFrames": 148
        },
        {
          "id": "caption-9",
          "text": "企业则把评价指标从每百万 Token 价格转向了完成一个可靠任务的总成本。",
          "startFrame": 766,
          "durationInFrames": 180
        }
      ]
    },
    "durationInFrames": 946,
    "durationInSeconds": 31.538708333333332,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "moonshot-k3",
    "narration": "Moonshot AI 发布 Kimi K3，总参数量达到 2.8 万亿，上下文窗口为 100 万 Token。路透称其是目前参数规模最大的开放权重模型。早期第三方测试显示，Arena AI 将其网页界面构建能力排在首位，Vals AI 将其综合能力排在 Fable 5 之后、GPT-5.6 Sol 之前，Artificial Analysis 认为其复杂多步骤任务表现接近 GPT-5.5 和 Claude Opus 4.8。但需要区分三个概念：总参数规模不等于实际推理质量，开放权重不等于普通用户可以本地运行，基准成绩不等于长期生产环境可靠性。2.8 万亿参数意味着即使模型开放，多数开发者仍需要通过云端推理服务使用，其真实成本、并发性能和 Agent 稳定性仍需进一步验证。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/moonshot-k3.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Moonshot AI 发布 Kimi K3，",
          "startFrame": 0,
          "durationInFrames": 72
        },
        {
          "id": "caption-2",
          "text": "总参数量达到 2.8 万亿，",
          "startFrame": 72,
          "durationInFrames": 75
        },
        {
          "id": "caption-3",
          "text": "上下文窗口为 100 万 Token。",
          "startFrame": 147,
          "durationInFrames": 69
        },
        {
          "id": "caption-4",
          "text": "路透称其是目前参数规模最大的开放权重模型。",
          "startFrame": 216,
          "durationInFrames": 134
        },
        {
          "id": "caption-5",
          "text": "早期第三方测试显示，",
          "startFrame": 350,
          "durationInFrames": 62
        },
        {
          "id": "caption-6",
          "text": "Arena AI 将其网页界面构建能力排在首位，",
          "startFrame": 412,
          "durationInFrames": 123
        },
        {
          "id": "caption-7",
          "text": "Vals AI 将其综合能力排在 Fable 5 之后、GPT-5.6 Sol 之前，",
          "startFrame": 535,
          "durationInFrames": 187
        },
        {
          "id": "caption-8",
          "text": "Artificial Analysis 认为其复杂多步骤任务表现接近 GPT-5.5 和 Claude Opus 4.8。",
          "startFrame": 722,
          "durationInFrames": 278
        },
        {
          "id": "caption-9",
          "text": "但需要区分三个概念：",
          "startFrame": 1000,
          "durationInFrames": 53
        },
        {
          "id": "caption-10",
          "text": "总参数规模不等于实际推理质量，",
          "startFrame": 1053,
          "durationInFrames": 83
        },
        {
          "id": "caption-11",
          "text": "开放权重不等于普通用户可以本地运行，",
          "startFrame": 1136,
          "durationInFrames": 111
        },
        {
          "id": "caption-12",
          "text": "基准成绩不等于长期生产环境可靠性。",
          "startFrame": 1247,
          "durationInFrames": 102
        },
        {
          "id": "caption-13",
          "text": "2.8 万亿参数意味着即使模型开放，",
          "startFrame": 1349,
          "durationInFrames": 110
        },
        {
          "id": "caption-14",
          "text": "多数开发者仍需要通过云端推理服务使用，",
          "startFrame": 1459,
          "durationInFrames": 115
        },
        {
          "id": "caption-15",
          "text": "其真实成本、并发性能和 Agent 稳定性仍需进一步验证。",
          "startFrame": 1574,
          "durationInFrames": 169
        }
      ]
    },
    "durationInFrames": 1743,
    "durationInSeconds": 58.108020833333335,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "enterprise-ai",
    "narration": "美国银行任命专门负责全球市场部门 AI 转型的高级管理人员，任务包括生成式 AI 工具部署和技术平台现代化，该行计划投入数十亿美元扩展 AI 等技术。这表明大型企业的 AI 战略正在从员工自行使用聊天工具，转向建立专门管理层、预算、数据团队和实施责任；下一步，AI 将直接进入交易、风控、分析和运营流程。同日，OpenAI 提出新的企业衡量框架：企业不应只比较 Token 单价，而应衡量 AI 完成了多少有用工作、每个成功任务的完整成本、结果有多少可以直接使用，以及规模扩大后每单位算力创造多少价值。所谓完整成本不仅包括 API 费用，还包括人工复核、重试、等待时间和失败后的返工。模型价格不再是核心指标，成功完成业务任务的总成本才是。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/enterprise-ai.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "美国银行任命专门负责全球市场部门 AI 转型的高级管理人员，",
          "startFrame": 0,
          "durationInFrames": 168
        },
        {
          "id": "caption-2",
          "text": "任务包括生成式 AI 工具部署和技术平台现代化，",
          "startFrame": 168,
          "durationInFrames": 119
        },
        {
          "id": "caption-3",
          "text": "该行计划投入数十亿美元扩展 AI 等技术。",
          "startFrame": 287,
          "durationInFrames": 110
        },
        {
          "id": "caption-4",
          "text": "这表明大型企业的 AI 战略正在从员工自行使用聊天工具，",
          "startFrame": 397,
          "durationInFrames": 145
        },
        {
          "id": "caption-5",
          "text": "转向建立专门管理层、预算、数据团队和实施责任；",
          "startFrame": 542,
          "durationInFrames": 153
        },
        {
          "id": "caption-6",
          "text": "下一步，",
          "startFrame": 695,
          "durationInFrames": 24
        },
        {
          "id": "caption-7",
          "text": "AI 将直接进入交易、风控、分析和运营流程。",
          "startFrame": 719,
          "durationInFrames": 133
        },
        {
          "id": "caption-8",
          "text": "同日，",
          "startFrame": 852,
          "durationInFrames": 20
        },
        {
          "id": "caption-9",
          "text": "OpenAI 提出新的企业衡量框架：",
          "startFrame": 872,
          "durationInFrames": 81
        },
        {
          "id": "caption-10",
          "text": "企业不应只比较 Token 单价，",
          "startFrame": 953,
          "durationInFrames": 75
        },
        {
          "id": "caption-11",
          "text": "而应衡量 AI 完成了多少有用工作、每个成功任务的完整成本、结果有多少可以直接使用，",
          "startFrame": 1028,
          "durationInFrames": 227
        },
        {
          "id": "caption-12",
          "text": "以及规模扩大后每单位算力创造多少价值。",
          "startFrame": 1255,
          "durationInFrames": 118
        },
        {
          "id": "caption-13",
          "text": "所谓完整成本不仅包括 API 费用，",
          "startFrame": 1373,
          "durationInFrames": 94
        },
        {
          "id": "caption-14",
          "text": "还包括人工复核、重试、等待时间和失败后的返工。",
          "startFrame": 1467,
          "durationInFrames": 132
        },
        {
          "id": "caption-15",
          "text": "模型价格不再是核心指标，",
          "startFrame": 1599,
          "durationInFrames": 68
        },
        {
          "id": "caption-16",
          "text": "成功完成业务任务的总成本才是。",
          "startFrame": 1667,
          "durationInFrames": 83
        }
      ]
    },
    "durationInFrames": 1750,
    "durationInSeconds": 58.34402083333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "tech-breakthroughs",
    "narration": "Kimi K3 表明开放权重路线不再局限于中小型模型。百万 Token 上下文、万亿级 MoE 架构、长周期编码和 Agent 任务正成为开放模型的新竞争标准。但开放的主要价值可能不是人人本地运行，而是降低单一模型厂商的控制力，让云平台、企业和研究机构能够进行定制。另有一项引人注目的突破来自 KAIST 与斯坦福团队，他们展示了一种嵌入衣物的软体藤蔓机器人，利用气压驱动柔性结构沿身体移动，约 10 秒即可完成完整防护服穿戴。该研究说明物理智能并不一定依赖巨型视觉语言模型，材料、传感器和简单控制系统结合，也可以产生高度适应性的实际能力。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/tech-breakthroughs.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Kimi K3 表明开放权重路线不再局限于中小型模型。",
          "startFrame": 0,
          "durationInFrames": 143
        },
        {
          "id": "caption-2",
          "text": "百万 Token 上下文、万亿级 MoE 架构、长周期编码和 Agent 任务正成为开放模型的新竞争标准。",
          "startFrame": 143,
          "durationInFrames": 263
        },
        {
          "id": "caption-3",
          "text": "但开放的主要价值可能不是人人本地运行，",
          "startFrame": 406,
          "durationInFrames": 112
        },
        {
          "id": "caption-4",
          "text": "而是降低单一模型厂商的控制力，",
          "startFrame": 518,
          "durationInFrames": 79
        },
        {
          "id": "caption-5",
          "text": "让云平台、企业和研究机构能够进行定制。",
          "startFrame": 597,
          "durationInFrames": 121
        },
        {
          "id": "caption-6",
          "text": "另有一项引人注目的突破来自 KAIST 与斯坦福团队，",
          "startFrame": 718,
          "durationInFrames": 160
        },
        {
          "id": "caption-7",
          "text": "他们展示了一种嵌入衣物的软体藤蔓机器人，",
          "startFrame": 878,
          "durationInFrames": 118
        },
        {
          "id": "caption-8",
          "text": "利用气压驱动柔性结构沿身体移动，",
          "startFrame": 996,
          "durationInFrames": 104
        },
        {
          "id": "caption-9",
          "text": "约 10 秒即可完成完整防护服穿戴。",
          "startFrame": 1100,
          "durationInFrames": 98
        },
        {
          "id": "caption-10",
          "text": "该研究说明物理智能并不一定依赖巨型视觉语言模型，",
          "startFrame": 1198,
          "durationInFrames": 152
        },
        {
          "id": "caption-11",
          "text": "材料、传感器和简单控制系统结合，",
          "startFrame": 1350,
          "durationInFrames": 102
        },
        {
          "id": "caption-12",
          "text": "也可以产生高度适应性的实际能力。",
          "startFrame": 1452,
          "durationInFrames": 98
        }
      ]
    },
    "durationInFrames": 1550,
    "durationInSeconds": 51.67814583333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "policy",
    "narration": "印度尼西亚正在讨论新的版权法草案。草案提出平台使用内容进行 AI 训练时需要付费或获得许可，新闻链接预览和内容聚合需向出版商支付补偿，禁止 AI 模仿创作者的独特风格，并且完全由 AI 生成的内容可能不受版权保护。不符合要求的平台可能面临撤销本地运营许可。另一方面，英国的新制度将 AWS、Microsoft、Google Cloud 等云服务商视为金融行业的关键第三方，要求其进行韧性测试、报告重大中断并修复已发现的风险。AWS 与 Microsoft 合计占英国核心云服务收入的八成左右。监管重点正在从模型回答是否安全，扩展为云服务韧性、数据主权、供应商集中风险和基础设施可靠性。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/policy.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "印度尼西亚正在讨论新的版权法草案。",
          "startFrame": 0,
          "durationInFrames": 91
        },
        {
          "id": "caption-2",
          "text": "草案提出平台使用内容进行 AI 训练时需要付费或获得许可，",
          "startFrame": 91,
          "durationInFrames": 183
        },
        {
          "id": "caption-3",
          "text": "新闻链接预览和内容聚合需向出版商支付补偿，",
          "startFrame": 274,
          "durationInFrames": 140
        },
        {
          "id": "caption-4",
          "text": "禁止 AI 模仿创作者的独特风格，",
          "startFrame": 414,
          "durationInFrames": 96
        },
        {
          "id": "caption-5",
          "text": "并且完全由 AI 生成的内容可能不受版权保护。",
          "startFrame": 510,
          "durationInFrames": 120
        },
        {
          "id": "caption-6",
          "text": "不符合要求的平台可能面临撤销本地运营许可。",
          "startFrame": 630,
          "durationInFrames": 117
        },
        {
          "id": "caption-7",
          "text": "另一方面，",
          "startFrame": 747,
          "durationInFrames": 28
        },
        {
          "id": "caption-8",
          "text": "英国的新制度将 AWS、Microsoft、Google Cloud 等云服务商视为金融行业的关键第三方，",
          "startFrame": 775,
          "durationInFrames": 240
        },
        {
          "id": "caption-9",
          "text": "要求其进行韧性测试、报告重大中断并修复已发现的风险。",
          "startFrame": 1015,
          "durationInFrames": 163
        },
        {
          "id": "caption-10",
          "text": "AWS 与 Microsoft 合计占英国核心云服务收入的八成左右。",
          "startFrame": 1178,
          "durationInFrames": 172
        },
        {
          "id": "caption-11",
          "text": "监管重点正在从模型回答是否安全，",
          "startFrame": 1350,
          "durationInFrames": 97
        },
        {
          "id": "caption-12",
          "text": "扩展为云服务韧性、数据主权、供应商集中风险和基础设施可靠性。",
          "startFrame": 1447,
          "durationInFrames": 182
        }
      ]
    },
    "durationInFrames": 1629,
    "durationInSeconds": 54.28604166666667,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "capital-markets",
    "narration": "Databricks 签署新一轮战略融资条款，估值达到 1880 亿美元，由现有投资者 Coatue 领投。这一高估值表明资本仍然重视连接企业原始数据、数据清洗与治理、模型训练和微调、RAG 与 Agent 以及生产部署和监控的平台型公司。资金并不只押注模型实验室，也在押注能够控制企业数据和 AI 应用开发入口的基础设施公司。与此同时，UBS 预计主要云厂商资本支出将在 2026 年增长约百分之七十六，但增速可能在 2027 年降至百分之二十五。美国银行调查中百分之八十二的受访者认为半导体是当前最拥挤的市场交易，部分基金正在减少芯片股配置，转向可能从 AI 应用中获益的行业。资本逻辑正在变化：从购买 GPU 和建设数据中心，转向提高算力利用率和推理效率，再到寻找能够产生真实利润的 AI 应用。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/capital-markets.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "Databricks 签署新一轮战略融资条款，",
          "startFrame": 0,
          "durationInFrames": 107
        },
        {
          "id": "caption-2",
          "text": "估值达到 1880 亿美元，",
          "startFrame": 107,
          "durationInFrames": 90
        },
        {
          "id": "caption-3",
          "text": "由现有投资者 Coatue 领投。",
          "startFrame": 197,
          "durationInFrames": 80
        },
        {
          "id": "caption-4",
          "text": "这一高估值表明资本仍然重视连接企业原始数据、数据清洗与治理、模型训练和微调、RAG 与 Agent 以及生产部署和监控的平台型公司。",
          "startFrame": 277,
          "durationInFrames": 395
        },
        {
          "id": "caption-5",
          "text": "资金并不只押注模型实验室，",
          "startFrame": 672,
          "durationInFrames": 77
        },
        {
          "id": "caption-6",
          "text": "也在押注能够控制企业数据和 AI 应用开发入口的基础设施公司。",
          "startFrame": 749,
          "durationInFrames": 167
        },
        {
          "id": "caption-7",
          "text": "与此同时，",
          "startFrame": 916,
          "durationInFrames": 35
        },
        {
          "id": "caption-8",
          "text": "UBS 预计主要云厂商资本支出将在 2026 年增长约百分之七十六，",
          "startFrame": 951,
          "durationInFrames": 218
        },
        {
          "id": "caption-9",
          "text": "但增速可能在 2027 年降至百分之二十五。",
          "startFrame": 1169,
          "durationInFrames": 125
        },
        {
          "id": "caption-10",
          "text": "美国银行调查中百分之八十二的受访者认为半导体是当前最拥挤的市场交易，",
          "startFrame": 1294,
          "durationInFrames": 209
        },
        {
          "id": "caption-11",
          "text": "部分基金正在减少芯片股配置，",
          "startFrame": 1503,
          "durationInFrames": 77
        },
        {
          "id": "caption-12",
          "text": "转向可能从 AI 应用中获益的行业。",
          "startFrame": 1580,
          "durationInFrames": 93
        },
        {
          "id": "caption-13",
          "text": "资本逻辑正在变化：",
          "startFrame": 1673,
          "durationInFrames": 54
        },
        {
          "id": "caption-14",
          "text": "从购买 GPU 和建设数据中心，",
          "startFrame": 1727,
          "durationInFrames": 78
        },
        {
          "id": "caption-15",
          "text": "转向提高算力利用率和推理效率，",
          "startFrame": 1805,
          "durationInFrames": 84
        },
        {
          "id": "caption-16",
          "text": "再到寻找能够产生真实利润的 AI 应用。",
          "startFrame": 1889,
          "durationInFrames": 101
        }
      ]
    },
    "durationInFrames": 1990,
    "durationInSeconds": 66.34358333333333,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "trend-summary",
    "narration": "开放模型继续大型化，Kimi K3 达到 2.8 万亿参数，开放与闭源模型差距继续缩小。企业 AI 进入组织化实施，美国银行设立 AI 转型管理岗位，AI 从员工工具进入核心业务流程。衡量方式转向任务结果，OpenAI 提出成功任务成本框架，Agent 需要证明可靠性和投资回报。版权规则直接覆盖训练数据，印尼版权法草案预示数据授权与来源追踪成本上升。云平台成为监管对象，英国关键第三方制度将 AI 基础设施视为系统性风险。资本仍集中但开始分化，Databricks 估值 1880 亿美元的同时芯片交易降温，资金从算力建设转向数据和应用层。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/trend-summary.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "开放模型继续大型化，",
          "startFrame": 0,
          "durationInFrames": 61
        },
        {
          "id": "caption-2",
          "text": "Kimi K3 达到 2.8 万亿参数，",
          "startFrame": 61,
          "durationInFrames": 75
        },
        {
          "id": "caption-3",
          "text": "开放与闭源模型差距继续缩小。",
          "startFrame": 136,
          "durationInFrames": 84
        },
        {
          "id": "caption-4",
          "text": "企业 AI 进入组织化实施，",
          "startFrame": 220,
          "durationInFrames": 76
        },
        {
          "id": "caption-5",
          "text": "美国银行设立 AI 转型管理岗位，",
          "startFrame": 296,
          "durationInFrames": 87
        },
        {
          "id": "caption-6",
          "text": "AI 从员工工具进入核心业务流程。",
          "startFrame": 383,
          "durationInFrames": 88
        },
        {
          "id": "caption-7",
          "text": "衡量方式转向任务结果，",
          "startFrame": 471,
          "durationInFrames": 65
        },
        {
          "id": "caption-8",
          "text": "OpenAI 提出成功任务成本框架，",
          "startFrame": 536,
          "durationInFrames": 90
        },
        {
          "id": "caption-9",
          "text": "Agent 需要证明可靠性和投资回报。",
          "startFrame": 626,
          "durationInFrames": 98
        },
        {
          "id": "caption-10",
          "text": "版权规则直接覆盖训练数据，",
          "startFrame": 724,
          "durationInFrames": 76
        },
        {
          "id": "caption-11",
          "text": "印尼版权法草案预示数据授权与来源追踪成本上升。",
          "startFrame": 800,
          "durationInFrames": 135
        },
        {
          "id": "caption-12",
          "text": "云平台成为监管对象，",
          "startFrame": 935,
          "durationInFrames": 65
        },
        {
          "id": "caption-13",
          "text": "英国关键第三方制度将 AI 基础设施视为系统性风险。",
          "startFrame": 1000,
          "durationInFrames": 140
        },
        {
          "id": "caption-14",
          "text": "资本仍集中但开始分化，",
          "startFrame": 1140,
          "durationInFrames": 73
        },
        {
          "id": "caption-15",
          "text": "Databricks 估值 1880 亿美元的同时芯片交易降温，",
          "startFrame": 1213,
          "durationInFrames": 155
        },
        {
          "id": "caption-16",
          "text": "资金从算力建设转向数据和应用层。",
          "startFrame": 1368,
          "durationInFrames": 99
        }
      ]
    },
    "durationInFrames": 1467,
    "durationInSeconds": 48.899,
    "provider": "voxcpm",
    "format": "wav"
  },
  {
    "sceneId": "close",
    "narration": "今天最明确的趋势是：Agent 系统将越来越按照业务结果收费和评估，而不是按照模型参数、Token 数量或基准分数。真正需要记录的指标包括一次成功任务的总成本、无需人工修改的任务比例、重试和人工接管次数、每个工具调用的成功率、错误操作造成的潜在损失，以及更换模型后业务流程能否保持稳定。因此，Agent 运行时、评估系统、权限控制、执行审计和模型路由，会比单纯封装模型 API 更具长期价值。",
    "audioFile": "generated/ai-daily-news-2026-07-17/audio/close.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "今天最明确的趋势是：",
          "startFrame": 0,
          "durationInFrames": 56
        },
        {
          "id": "caption-2",
          "text": "Agent 系统将越来越按照业务结果收费和评估，",
          "startFrame": 56,
          "durationInFrames": 118
        },
        {
          "id": "caption-3",
          "text": "而不是按照模型参数、Token 数量或基准分数。",
          "startFrame": 174,
          "durationInFrames": 116
        },
        {
          "id": "caption-4",
          "text": "真正需要记录的指标包括一次成功任务的总成本、无需人工修改的任务比例、重试和人工接管次数、每个工具调用的成功率、错误操作造成的潜在损失，",
          "startFrame": 290,
          "durationInFrames": 414
        },
        {
          "id": "caption-5",
          "text": "以及更换模型后业务流程能否保持稳定。",
          "startFrame": 704,
          "durationInFrames": 106
        },
        {
          "id": "caption-6",
          "text": "因此，",
          "startFrame": 810,
          "durationInFrames": 24
        },
        {
          "id": "caption-7",
          "text": "Agent 运行时、评估系统、权限控制、执行审计和模型路由，",
          "startFrame": 834,
          "durationInFrames": 193
        },
        {
          "id": "caption-8",
          "text": "会比单纯封装模型 API 更具长期价值。",
          "startFrame": 1027,
          "durationInFrames": 114
        }
      ]
    },
    "durationInFrames": 1141,
    "durationInSeconds": 38.0186875,
    "provider": "voxcpm",
    "format": "wav"
  }
] satisfies readonly AudioTrack[];
