// Auto-generated by scripts/generate-ai-concepts-redefined-tts.mjs (silence-detected captions)
// Voice clone: LYY (high-fidelity clone_with_prompt)
// Caption timing rebuilt from ffmpeg silence detection: 2026-07-15T00:33:10.857609
import type { AudioTrack } from "./types";

export const audioTracks = [
  {
    "audioFile": "generated/ai-concepts-redefined/open.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI出现之后，",
          "startFrame": 0,
          "durationInFrames": 48
        },
        {
          "id": "caption-2",
          "text": "很多过去很稳定的互联网概念，",
          "startFrame": 48,
          "durationInFrames": 84
        },
        {
          "id": "caption-3",
          "text": "开始变得不够用了。",
          "startFrame": 132,
          "durationInFrames": 60
        },
        {
          "id": "caption-4",
          "text": "比如：",
          "startFrame": 192,
          "durationInFrames": 21
        },
        {
          "id": "caption-5",
          "text": "流量、",
          "startFrame": 213,
          "durationInFrames": 23
        },
        {
          "id": "caption-6",
          "text": "服务、",
          "startFrame": 236,
          "durationInFrames": 20
        },
        {
          "id": "caption-7",
          "text": "鉴权、",
          "startFrame": 256,
          "durationInFrames": 29
        },
        {
          "id": "caption-8",
          "text": "隐私、",
          "startFrame": 285,
          "durationInFrames": 25
        },
        {
          "id": "caption-9",
          "text": "数据、",
          "startFrame": 310,
          "durationInFrames": 24
        },
        {
          "id": "caption-10",
          "text": "交互。",
          "startFrame": 334,
          "durationInFrames": 33
        },
        {
          "id": "caption-11",
          "text": "这些词不是消失了，",
          "startFrame": 367,
          "durationInFrames": 55
        },
        {
          "id": "caption-12",
          "text": "而是它们的定义正在改变。",
          "startFrame": 422,
          "durationInFrames": 68
        }
      ]
    },
    "durationInFrames": 490,
    "durationInSeconds": 16.32,
    "format": "wav",
    "narration": "AI出现之后，很多过去很稳定的互联网概念，开始变得不够用了。比如：流量、服务、鉴权、隐私、数据、交互。这些词不是消失了，而是它们的定义正在改变。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "open"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/core-change.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的互联网，",
          "startFrame": 0,
          "durationInFrames": 57
        },
        {
          "id": "caption-2",
          "text": "是人使用软件。",
          "startFrame": 57,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "人打开网站，",
          "startFrame": 115,
          "durationInFrames": 43
        },
        {
          "id": "caption-4",
          "text": "点击按钮，",
          "startFrame": 158,
          "durationInFrames": 37
        },
        {
          "id": "caption-5",
          "text": "填写表单，",
          "startFrame": 195,
          "durationInFrames": 39
        },
        {
          "id": "caption-6",
          "text": "提交信息，",
          "startFrame": 234,
          "durationInFrames": 36
        },
        {
          "id": "caption-7",
          "text": "然后得到结果。",
          "startFrame": 270,
          "durationInFrames": 54
        },
        {
          "id": "caption-8",
          "text": "但AI时代，",
          "startFrame": 324,
          "durationInFrames": 39
        },
        {
          "id": "caption-9",
          "text": "越来越多场景会变成：",
          "startFrame": 363,
          "durationInFrames": 64
        },
        {
          "id": "caption-10",
          "text": "人只表达目标，",
          "startFrame": 427,
          "durationInFrames": 52
        },
        {
          "id": "caption-11",
          "text": "Agent替人调用软件、",
          "startFrame": 479,
          "durationInFrames": 63
        },
        {
          "id": "caption-12",
          "text": "服务、",
          "startFrame": 542,
          "durationInFrames": 20
        },
        {
          "id": "caption-13",
          "text": "工具和数据，",
          "startFrame": 562,
          "durationInFrames": 20
        },
        {
          "id": "caption-14",
          "text": "最后完成任务。",
          "startFrame": 582,
          "durationInFrames": 71
        }
      ]
    },
    "durationInFrames": 653,
    "durationInSeconds": 21.76,
    "format": "wav",
    "narration": "过去的互联网，是人使用软件。人打开网站，点击按钮，填写表单，提交信息，然后得到结果。但AI时代，越来越多场景会变成：人只表达目标，Agent替人调用软件、服务、工具和数据，最后完成任务。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "core-change"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/why-rewrite.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "问题不在于AI多了一个聊天框。",
          "startFrame": 0,
          "durationInFrames": 90
        },
        {
          "id": "caption-2",
          "text": "真正的变化是：",
          "startFrame": 90,
          "durationInFrames": 47
        },
        {
          "id": "caption-3",
          "text": "操作主体变了。",
          "startFrame": 137,
          "durationInFrames": 53
        },
        {
          "id": "caption-4",
          "text": "过去软件主要面对人。",
          "startFrame": 190,
          "durationInFrames": 69
        },
        {
          "id": "caption-5",
          "text": "未来很多软件、",
          "startFrame": 259,
          "durationInFrames": 46
        },
        {
          "id": "caption-6",
          "text": "服务和数据，",
          "startFrame": 305,
          "durationInFrames": 43
        },
        {
          "id": "caption-7",
          "text": "首先要面对Agent。",
          "startFrame": 348,
          "durationInFrames": 58
        },
        {
          "id": "caption-8",
          "text": "所以，",
          "startFrame": 406,
          "durationInFrames": 24
        },
        {
          "id": "caption-9",
          "text": "互联网的很多基础概念，",
          "startFrame": 430,
          "durationInFrames": 67
        },
        {
          "id": "caption-10",
          "text": "都要从人类视角，",
          "startFrame": 497,
          "durationInFrames": 49
        },
        {
          "id": "caption-11",
          "text": "重新转向Agent视角。",
          "startFrame": 546,
          "durationInFrames": 59
        }
      ]
    },
    "durationInFrames": 605,
    "durationInSeconds": 20.16,
    "format": "wav",
    "narration": "问题不在于AI多了一个聊天框。真正的变化是：操作主体变了。过去软件主要面对人。未来很多软件、服务和数据，首先要面对Agent。所以，互联网的很多基础概念，都要从人类视角，重新转向Agent视角。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "why-rewrite"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/six-concepts.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这条视频主要讲六个概念的变化：",
          "startFrame": 0,
          "durationInFrames": 98
        },
        {
          "id": "caption-2",
          "text": "流量，",
          "startFrame": 98,
          "durationInFrames": 25
        },
        {
          "id": "caption-3",
          "text": "服务，",
          "startFrame": 123,
          "durationInFrames": 25
        },
        {
          "id": "caption-4",
          "text": "鉴权，",
          "startFrame": 148,
          "durationInFrames": 27
        },
        {
          "id": "caption-5",
          "text": "隐私，",
          "startFrame": 175,
          "durationInFrames": 26
        },
        {
          "id": "caption-6",
          "text": "数据，",
          "startFrame": 201,
          "durationInFrames": 26
        },
        {
          "id": "caption-7",
          "text": "交互。",
          "startFrame": 227,
          "durationInFrames": 21
        },
        {
          "id": "caption-8",
          "text": "它们共同指向一个核心判断：",
          "startFrame": 248,
          "durationInFrames": 71
        },
        {
          "id": "caption-9",
          "text": "AI时代，",
          "startFrame": 319,
          "durationInFrames": 32
        },
        {
          "id": "caption-10",
          "text": "互联网正在从人操作软件，",
          "startFrame": 351,
          "durationInFrames": 74
        },
        {
          "id": "caption-11",
          "text": "变成Agent代表人调用世界。",
          "startFrame": 425,
          "durationInFrames": 74
        }
      ]
    },
    "durationInFrames": 499,
    "durationInSeconds": 16.64,
    "format": "wav",
    "narration": "这条视频主要讲六个概念的变化：流量，服务，鉴权，隐私，数据，交互。它们共同指向一个核心判断：AI时代，互联网正在从人操作软件，变成Agent代表人调用世界。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "six-concepts"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-traffic.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "在传统互联网里，",
          "startFrame": 0,
          "durationInFrames": 61
        },
        {
          "id": "caption-2",
          "text": "流量就是人有没有来。",
          "startFrame": 61,
          "durationInFrames": 62
        },
        {
          "id": "caption-3",
          "text": "用户有没有打开你的网站，",
          "startFrame": 123,
          "durationInFrames": 114
        },
        {
          "id": "caption-4",
          "text": "有没有刷到你的内容，",
          "startFrame": 237,
          "durationInFrames": 48
        },
        {
          "id": "caption-5",
          "text": "有没有点击你的按钮，",
          "startFrame": 285,
          "durationInFrames": 44
        },
        {
          "id": "caption-6",
          "text": "有没有停留，",
          "startFrame": 329,
          "durationInFrames": 27
        },
        {
          "id": "caption-7",
          "text": "有没有转化。",
          "startFrame": 356,
          "durationInFrames": 27
        },
        {
          "id": "caption-8",
          "text": "所以过去大家关注的是UV、",
          "startFrame": 383,
          "durationInFrames": 58
        },
        {
          "id": "caption-9",
          "text": "PV、",
          "startFrame": 441,
          "durationInFrames": 13
        },
        {
          "id": "caption-10",
          "text": "点击率、",
          "startFrame": 454,
          "durationInFrames": 18
        },
        {
          "id": "caption-11",
          "text": "停留时长、",
          "startFrame": 472,
          "durationInFrames": 23
        },
        {
          "id": "caption-12",
          "text": "转化率。",
          "startFrame": 495,
          "durationInFrames": 19
        }
      ]
    },
    "durationInFrames": 514,
    "durationInSeconds": 17.12,
    "format": "wav",
    "narration": "在传统互联网里，流量就是人有没有来。用户有没有打开你的网站，有没有刷到你的内容，有没有点击你的按钮，有没有停留，有没有转化。所以过去大家关注的是UV、PV、点击率、停留时长、转化率。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-traffic"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/new-traffic.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代，",
          "startFrame": 0,
          "durationInFrames": 42
        },
        {
          "id": "caption-2",
          "text": "用户可能根本不会访问你的网页。",
          "startFrame": 42,
          "durationInFrames": 88
        },
        {
          "id": "caption-3",
          "text": "他可能只是对自己的Agent说：",
          "startFrame": 130,
          "durationInFrames": 77
        },
        {
          "id": "caption-4",
          "text": "帮我做一条视频，",
          "startFrame": 207,
          "durationInFrames": 49
        },
        {
          "id": "caption-5",
          "text": "帮我订一次行程，",
          "startFrame": 256,
          "durationInFrames": 47
        },
        {
          "id": "caption-6",
          "text": "帮我整理一份报告。",
          "startFrame": 303,
          "durationInFrames": 52
        },
        {
          "id": "caption-7",
          "text": "然后Agent会自动选择工具、",
          "startFrame": 355,
          "durationInFrames": 69
        },
        {
          "id": "caption-8",
          "text": "调用服务、",
          "startFrame": 424,
          "durationInFrames": 30
        },
        {
          "id": "caption-9",
          "text": "处理数据。",
          "startFrame": 454,
          "durationInFrames": 35
        },
        {
          "id": "caption-10",
          "text": "这时候，",
          "startFrame": 489,
          "durationInFrames": 26
        },
        {
          "id": "caption-11",
          "text": "真正的流量不是用户有没有看到你，",
          "startFrame": 515,
          "durationInFrames": 87
        },
        {
          "id": "caption-12",
          "text": "而是Agent会不会调用你。",
          "startFrame": 602,
          "durationInFrames": 56
        }
      ]
    },
    "durationInFrames": 658,
    "durationInSeconds": 21.92,
    "format": "wav",
    "narration": "AI时代，用户可能根本不会访问你的网页。他可能只是对自己的Agent说：帮我做一条视频，帮我订一次行程，帮我整理一份报告。然后Agent会自动选择工具、调用服务、处理数据。这时候，真正的流量不是用户有没有看到你，而是Agent会不会调用你。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "new-traffic"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/traffic-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代的流量，",
          "startFrame": 0,
          "durationInFrames": 139
        },
        {
          "id": "caption-2",
          "text": "本质上会从访问量变成调用量。",
          "startFrame": 139,
          "durationInFrames": 82
        },
        {
          "id": "caption-3",
          "text": "一个服务可能没有多少网页访问，",
          "startFrame": 221,
          "durationInFrames": 68
        },
        {
          "id": "caption-4",
          "text": "但它可能被大量Agent调用。",
          "startFrame": 289,
          "durationInFrames": 107
        },
        {
          "id": "caption-5",
          "text": "未来很多服务的价值，",
          "startFrame": 396,
          "durationInFrames": 26
        },
        {
          "id": "caption-6",
          "text": "不是看人类访问量，",
          "startFrame": 422,
          "durationInFrames": 23
        },
        {
          "id": "caption-7",
          "text": "而是看它在任务链路里被调用的频率。",
          "startFrame": 445,
          "durationInFrames": 45
        }
      ]
    },
    "durationInFrames": 490,
    "durationInSeconds": 16.32,
    "format": "wav",
    "narration": "AI时代的流量，本质上会从访问量变成调用量。一个服务可能没有多少网页访问，但它可能被大量Agent调用。未来很多服务的价值，不是看人类访问量，而是看它在任务链路里被调用的频率。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "traffic-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/traffic-metrics.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "传统流量看点击率、",
          "startFrame": 0,
          "durationInFrames": 62
        },
        {
          "id": "caption-2",
          "text": "曝光量、",
          "startFrame": 62,
          "durationInFrames": 61
        },
        {
          "id": "caption-3",
          "text": "停留时长。",
          "startFrame": 123,
          "durationInFrames": 221
        },
        {
          "id": "caption-4",
          "text": "Agent流量看的是：",
          "startFrame": 344,
          "durationInFrames": 91
        },
        {
          "id": "caption-5",
          "text": "调用成功率、",
          "startFrame": 435,
          "durationInFrames": 60
        },
        {
          "id": "caption-6",
          "text": "响应速度、",
          "startFrame": 495,
          "durationInFrames": 6
        },
        {
          "id": "caption-7",
          "text": "结果质量、",
          "startFrame": 501,
          "durationInFrames": 6
        },
        {
          "id": "caption-8",
          "text": "成本、",
          "startFrame": 507,
          "durationInFrames": 4
        },
        {
          "id": "caption-9",
          "text": "稳定性、",
          "startFrame": 511,
          "durationInFrames": 5
        },
        {
          "id": "caption-10",
          "text": "可组合性。",
          "startFrame": 516,
          "durationInFrames": 7
        },
        {
          "id": "caption-11",
          "text": "Agent不会因为页面好看就调用你。",
          "startFrame": 523,
          "durationInFrames": 25
        },
        {
          "id": "caption-12",
          "text": "它更关心你是否可靠、",
          "startFrame": 548,
          "durationInFrames": 14
        },
        {
          "id": "caption-13",
          "text": "便宜、",
          "startFrame": 562,
          "durationInFrames": 4
        },
        {
          "id": "caption-14",
          "text": "稳定、",
          "startFrame": 566,
          "durationInFrames": 4
        },
        {
          "id": "caption-15",
          "text": "清晰、",
          "startFrame": 570,
          "durationInFrames": 4
        },
        {
          "id": "caption-16",
          "text": "好接入。",
          "startFrame": 574,
          "durationInFrames": 7
        }
      ]
    },
    "durationInFrames": 581,
    "durationInSeconds": 19.36,
    "format": "wav",
    "narration": "传统流量看点击率、曝光量、停留时长。Agent流量看的是：调用成功率、响应速度、结果质量、成本、稳定性、可组合性。Agent不会因为页面好看就调用你。它更关心你是否可靠、便宜、稳定、清晰、好接入。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "traffic-metrics"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-service.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去我们说做一个服务，",
          "startFrame": 0,
          "durationInFrames": 59
        },
        {
          "id": "caption-2",
          "text": "通常指的是做一个网站、",
          "startFrame": 59,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "App或者SaaS。",
          "startFrame": 117,
          "durationInFrames": 21
        },
        {
          "id": "caption-4",
          "text": "它有首页，",
          "startFrame": 138,
          "durationInFrames": 34
        },
        {
          "id": "caption-5",
          "text": "有注册登录，",
          "startFrame": 172,
          "durationInFrames": 32
        },
        {
          "id": "caption-6",
          "text": "有控制台，",
          "startFrame": 204,
          "durationInFrames": 39
        },
        {
          "id": "caption-7",
          "text": "有按钮和表单。",
          "startFrame": 243,
          "durationInFrames": 32
        },
        {
          "id": "caption-8",
          "text": "用户进入系统后，",
          "startFrame": 275,
          "durationInFrames": 49
        },
        {
          "id": "caption-9",
          "text": "自己一步一步操作。",
          "startFrame": 324,
          "durationInFrames": 94
        }
      ]
    },
    "durationInFrames": 418,
    "durationInSeconds": 13.92,
    "format": "wav",
    "narration": "过去我们说做一个服务，通常指的是做一个网站、App或者SaaS。它有首页，有注册登录，有控制台，有按钮和表单。用户进入系统后，自己一步一步操作。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-service"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/new-service.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代，",
          "startFrame": 0,
          "durationInFrames": 34
        },
        {
          "id": "caption-2",
          "text": "服务会越来越像一个可以被Agent调用的能力单元。",
          "startFrame": 34,
          "durationInFrames": 122
        },
        {
          "id": "caption-3",
          "text": "它不一定是完整的软件产品。",
          "startFrame": 156,
          "durationInFrames": 76
        },
        {
          "id": "caption-4",
          "text": "它可能只是一个API、",
          "startFrame": 232,
          "durationInFrames": 55
        },
        {
          "id": "caption-5",
          "text": "一个MCP Server、",
          "startFrame": 287,
          "durationInFrames": 47
        },
        {
          "id": "caption-6",
          "text": "一个Tool、",
          "startFrame": 334,
          "durationInFrames": 25
        },
        {
          "id": "caption-7",
          "text": "一个Skill、",
          "startFrame": 359,
          "durationInFrames": 26
        },
        {
          "id": "caption-8",
          "text": "一个Workflow。",
          "startFrame": 385,
          "durationInFrames": 38
        },
        {
          "id": "caption-9",
          "text": "比如：",
          "startFrame": 423,
          "durationInFrames": 71
        },
        {
          "id": "caption-10",
          "text": "识别图片、",
          "startFrame": 494,
          "durationInFrames": 31
        },
        {
          "id": "caption-11",
          "text": "生成文案、",
          "startFrame": 525,
          "durationInFrames": 29
        },
        {
          "id": "caption-12",
          "text": "剪辑视频、",
          "startFrame": 554,
          "durationInFrames": 12
        },
        {
          "id": "caption-13",
          "text": "查询数据、",
          "startFrame": 566,
          "durationInFrames": 13
        },
        {
          "id": "caption-14",
          "text": "发送邮件、",
          "startFrame": 579,
          "durationInFrames": 13
        },
        {
          "id": "caption-15",
          "text": "安排日程。",
          "startFrame": 592,
          "durationInFrames": 13
        }
      ]
    },
    "durationInFrames": 605,
    "durationInSeconds": 20.16,
    "format": "wav",
    "narration": "AI时代，服务会越来越像一个可以被Agent调用的能力单元。它不一定是完整的软件产品。它可能只是一个API、一个MCP Server、一个Tool、一个Skill、一个Workflow。比如：识别图片、生成文案、剪辑视频、查询数据、发送邮件、安排日程。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "new-service"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/service-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的服务，",
          "startFrame": 0,
          "durationInFrames": 44
        },
        {
          "id": "caption-2",
          "text": "是给人操作的产品。",
          "startFrame": 44,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "AI时代的服务，",
          "startFrame": 102,
          "durationInFrames": 108
        },
        {
          "id": "caption-4",
          "text": "是给Agent调用的能力。",
          "startFrame": 210,
          "durationInFrames": 91
        },
        {
          "id": "caption-5",
          "text": "所以服务的重点会从界面好不好用，",
          "startFrame": 301,
          "durationInFrames": 56
        },
        {
          "id": "caption-6",
          "text": "变成能力好不好接。",
          "startFrame": 357,
          "durationInFrames": 62
        },
        {
          "id": "caption-7",
          "text": "输入输出是否清晰，",
          "startFrame": 419,
          "durationInFrames": 45
        },
        {
          "id": "caption-8",
          "text": "边界是否明确，",
          "startFrame": 464,
          "durationInFrames": 42
        },
        {
          "id": "caption-9",
          "text": "返回是否稳定，",
          "startFrame": 506,
          "durationInFrames": 40
        },
        {
          "id": "caption-10",
          "text": "权限是否可控，",
          "startFrame": 546,
          "durationInFrames": 19
        },
        {
          "id": "caption-11",
          "text": "这些会变得更重要。",
          "startFrame": 565,
          "durationInFrames": 25
        }
      ]
    },
    "durationInFrames": 590,
    "durationInSeconds": 19.68,
    "format": "wav",
    "narration": "过去的服务，是给人操作的产品。AI时代的服务，是给Agent调用的能力。所以服务的重点会从界面好不好用，变成能力好不好接。输入输出是否清晰，边界是否明确，返回是否稳定，权限是否可控，这些会变得更重要。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "service-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/skill-value.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "如果未来每个人都有自己的Agent，",
          "startFrame": 0,
          "durationInFrames": 88
        },
        {
          "id": "caption-2",
          "text": "那么很多服务就不再需要用户亲自学习怎么用。",
          "startFrame": 88,
          "durationInFrames": 117
        },
        {
          "id": "caption-3",
          "text": "服务只需要让Agent知道：",
          "startFrame": 205,
          "durationInFrames": 69
        },
        {
          "id": "caption-4",
          "text": "你能做什么，",
          "startFrame": 274,
          "durationInFrames": 34
        },
        {
          "id": "caption-5",
          "text": "怎么调用你，",
          "startFrame": 308,
          "durationInFrames": 61
        },
        {
          "id": "caption-6",
          "text": "输入什么，",
          "startFrame": 369,
          "durationInFrames": 62
        },
        {
          "id": "caption-7",
          "text": "输出什么，",
          "startFrame": 431,
          "durationInFrames": 39
        },
        {
          "id": "caption-8",
          "text": "失败怎么办，",
          "startFrame": 470,
          "durationInFrames": 42
        },
        {
          "id": "caption-9",
          "text": "费用怎么算。",
          "startFrame": 512,
          "durationInFrames": 15
        },
        {
          "id": "caption-10",
          "text": "这就是Skill、",
          "startFrame": 527,
          "durationInFrames": 68
        },
        {
          "id": "caption-11",
          "text": "Tool、",
          "startFrame": 595,
          "durationInFrames": 12
        },
        {
          "id": "caption-12",
          "text": "Workflow这类东西的价值。",
          "startFrame": 607,
          "durationInFrames": 40
        },
        {
          "id": "caption-13",
          "text": "它们本质上是在给Agent提供可复用能力。",
          "startFrame": 647,
          "durationInFrames": 54
        }
      ]
    },
    "durationInFrames": 701,
    "durationInSeconds": 23.36,
    "format": "wav",
    "narration": "如果未来每个人都有自己的Agent，那么很多服务就不再需要用户亲自学习怎么用。服务只需要让Agent知道：你能做什么，怎么调用你，输入什么，输出什么，失败怎么办，费用怎么算。这就是Skill、Tool、Workflow这类东西的价值。它们本质上是在给Agent提供可复用能力。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "skill-value"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-auth.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的鉴权主要是证明你是谁。",
          "startFrame": 0,
          "durationInFrames": 234
        },
        {
          "id": "caption-2",
          "text": "你输入账号密码，",
          "startFrame": 234,
          "durationInFrames": 8
        },
        {
          "id": "caption-3",
          "text": "系统确认身份，",
          "startFrame": 242,
          "durationInFrames": 20
        },
        {
          "id": "caption-4",
          "text": "然后给你登录状态。",
          "startFrame": 262,
          "durationInFrames": 48
        },
        {
          "id": "caption-5",
          "text": "之后，",
          "startFrame": 310,
          "durationInFrames": 10
        },
        {
          "id": "caption-6",
          "text": "你自己在系统里操作。",
          "startFrame": 320,
          "durationInFrames": 33
        },
        {
          "id": "caption-7",
          "text": "这个逻辑在人类亲自使用软件时是够用的。",
          "startFrame": 353,
          "durationInFrames": 65
        }
      ]
    },
    "durationInFrames": 418,
    "durationInSeconds": 13.92,
    "format": "wav",
    "narration": "过去的鉴权主要是证明你是谁。你输入账号密码，系统确认身份，然后给你登录状态。之后，你自己在系统里操作。这个逻辑在人类亲自使用软件时是够用的。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-auth"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/auth-problem.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代的问题变复杂了。",
          "startFrame": 0,
          "durationInFrames": 185
        },
        {
          "id": "caption-2",
          "text": "因为很多操作不是你亲自做，",
          "startFrame": 185,
          "durationInFrames": 72
        },
        {
          "id": "caption-3",
          "text": "而是Agent替你做。",
          "startFrame": 257,
          "durationInFrames": 18
        },
        {
          "id": "caption-4",
          "text": "所以核心问题不只是你是谁。",
          "startFrame": 275,
          "durationInFrames": 65
        },
        {
          "id": "caption-5",
          "text": "而是：",
          "startFrame": 340,
          "durationInFrames": 48
        },
        {
          "id": "caption-6",
          "text": "这个Agent能不能代表你行动？",
          "startFrame": 388,
          "durationInFrames": 45
        },
        {
          "id": "caption-7",
          "text": "能行动到什么程度？",
          "startFrame": 433,
          "durationInFrames": 27
        },
        {
          "id": "caption-8",
          "text": "能访问哪些数据？",
          "startFrame": 460,
          "durationInFrames": 24
        },
        {
          "id": "caption-9",
          "text": "能不能花钱？",
          "startFrame": 484,
          "durationInFrames": 18
        },
        {
          "id": "caption-10",
          "text": "能不能发邮件？",
          "startFrame": 502,
          "durationInFrames": 21
        },
        {
          "id": "caption-11",
          "text": "能不能删除文件？",
          "startFrame": 523,
          "durationInFrames": 24
        }
      ]
    },
    "durationInFrames": 547,
    "durationInSeconds": 18.24,
    "format": "wav",
    "narration": "AI时代的问题变复杂了。因为很多操作不是你亲自做，而是Agent替你做。所以核心问题不只是你是谁。而是：这个Agent能不能代表你行动？能行动到什么程度？能访问哪些数据？能不能花钱？能不能发邮件？能不能删除文件？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "auth-problem"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/auth-essence.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代的鉴权，",
          "startFrame": 0,
          "durationInFrames": 58
        },
        {
          "id": "caption-2",
          "text": "本质上是委托授权。",
          "startFrame": 58,
          "durationInFrames": 61
        },
        {
          "id": "caption-3",
          "text": "你不是简单登录一个系统，",
          "startFrame": 119,
          "durationInFrames": 116
        },
        {
          "id": "caption-4",
          "text": "而是在授权某个Agent，",
          "startFrame": 235,
          "durationInFrames": 95
        },
        {
          "id": "caption-5",
          "text": "在某个范围内，",
          "startFrame": 330,
          "durationInFrames": 65
        },
        {
          "id": "caption-6",
          "text": "代表你执行某些动作。",
          "startFrame": 395,
          "durationInFrames": 25
        },
        {
          "id": "caption-7",
          "text": "这个权限必须是可限制、",
          "startFrame": 420,
          "durationInFrames": 17
        },
        {
          "id": "caption-8",
          "text": "可撤销、",
          "startFrame": 437,
          "durationInFrames": 6
        },
        {
          "id": "caption-9",
          "text": "可审计的。",
          "startFrame": 443,
          "durationInFrames": 8
        }
      ]
    },
    "durationInFrames": 451,
    "durationInSeconds": 15.04,
    "format": "wav",
    "narration": "AI时代的鉴权，本质上是委托授权。你不是简单登录一个系统，而是在授权某个Agent，在某个范围内，代表你执行某些动作。这个权限必须是可限制、可撤销、可审计的。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "auth-essence"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/auth-example.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "你可以允许Agent查看邮件，",
          "startFrame": 0,
          "durationInFrames": 157
        },
        {
          "id": "caption-2",
          "text": "但不允许它直接发送邮件。",
          "startFrame": 157,
          "durationInFrames": 135
        },
        {
          "id": "caption-3",
          "text": "你可以允许Agent生成草稿，",
          "startFrame": 292,
          "durationInFrames": 69
        },
        {
          "id": "caption-4",
          "text": "但发送前必须由你确认。",
          "startFrame": 361,
          "durationInFrames": 61
        },
        {
          "id": "caption-5",
          "text": "你可以允许Agent挑选商品，",
          "startFrame": 422,
          "durationInFrames": 139
        },
        {
          "id": "caption-6",
          "text": "但不允许它直接付款。",
          "startFrame": 561,
          "durationInFrames": 48
        },
        {
          "id": "caption-7",
          "text": "你可以允许Agent整理文件，",
          "startFrame": 609,
          "durationInFrames": 18
        },
        {
          "id": "caption-8",
          "text": "但删除文件必须二次确认。",
          "startFrame": 627,
          "durationInFrames": 14
        },
        {
          "id": "caption-9",
          "text": "这就是AI时代更细粒度的权限系统。",
          "startFrame": 641,
          "durationInFrames": 21
        }
      ]
    },
    "durationInFrames": 662,
    "durationInSeconds": 22.08,
    "format": "wav",
    "narration": "你可以允许Agent查看邮件，但不允许它直接发送邮件。你可以允许Agent生成草稿，但发送前必须由你确认。你可以允许Agent挑选商品，但不允许它直接付款。你可以允许Agent整理文件，但删除文件必须二次确认。这就是AI时代更细粒度的权限系统。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "auth-example"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/auth-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的鉴权是：",
          "startFrame": 0,
          "durationInFrames": 59
        },
        {
          "id": "caption-2",
          "text": "证明用户身份。",
          "startFrame": 59,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "AI时代的鉴权是：",
          "startFrame": 117,
          "durationInFrames": 60
        },
        {
          "id": "caption-4",
          "text": "管理Agent的代理权限。",
          "startFrame": 177,
          "durationInFrames": 74
        },
        {
          "id": "caption-5",
          "text": "它需要回答四个问题：",
          "startFrame": 251,
          "durationInFrames": 69
        },
        {
          "id": "caption-6",
          "text": "谁授权的？",
          "startFrame": 320,
          "durationInFrames": 41
        },
        {
          "id": "caption-7",
          "text": "授权给哪个Agent？",
          "startFrame": 361,
          "durationInFrames": 55
        },
        {
          "id": "caption-8",
          "text": "允许它做什么？",
          "startFrame": 416,
          "durationInFrames": 49
        },
        {
          "id": "caption-9",
          "text": "做了之后能不能审计和撤销？",
          "startFrame": 465,
          "durationInFrames": 92
        }
      ]
    },
    "durationInFrames": 557,
    "durationInSeconds": 18.56,
    "format": "wav",
    "narration": "过去的鉴权是：证明用户身份。AI时代的鉴权是：管理Agent的代理权限。它需要回答四个问题：谁授权的？授权给哪个Agent？允许它做什么？做了之后能不能审计和撤销？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "auth-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-privacy.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去谈隐私，",
          "startFrame": 0,
          "durationInFrames": 45
        },
        {
          "id": "caption-2",
          "text": "主要关注数据有没有泄露。",
          "startFrame": 45,
          "durationInFrames": 77
        },
        {
          "id": "caption-3",
          "text": "比如账号密码有没有被盗，",
          "startFrame": 122,
          "durationInFrames": 66
        },
        {
          "id": "caption-4",
          "text": "数据库有没有被拖走，",
          "startFrame": 188,
          "durationInFrames": 54
        },
        {
          "id": "caption-5",
          "text": "平台有没有乱收集用户信息。",
          "startFrame": 242,
          "durationInFrames": 78
        },
        {
          "id": "caption-6",
          "text": "这是传统互联网里的隐私问题。",
          "startFrame": 320,
          "durationInFrames": 78
        }
      ]
    },
    "durationInFrames": 398,
    "durationInSeconds": 13.28,
    "format": "wav",
    "narration": "过去谈隐私，主要关注数据有没有泄露。比如账号密码有没有被盗，数据库有没有被拖走，平台有没有乱收集用户信息。这是传统互联网里的隐私问题。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-privacy"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/privacy-complexity.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代，",
          "startFrame": 0,
          "durationInFrames": 36
        },
        {
          "id": "caption-2",
          "text": "Agent要完成任务，",
          "startFrame": 36,
          "durationInFrames": 50
        },
        {
          "id": "caption-3",
          "text": "就需要上下文。",
          "startFrame": 86,
          "durationInFrames": 42
        },
        {
          "id": "caption-4",
          "text": "比如你让Agent帮你安排出差，",
          "startFrame": 128,
          "durationInFrames": 18
        },
        {
          "id": "caption-5",
          "text": "它可能需要读取你的日历、",
          "startFrame": 146,
          "durationInFrames": 63
        },
        {
          "id": "caption-6",
          "text": "邮件、",
          "startFrame": 209,
          "durationInFrames": 63
        },
        {
          "id": "caption-7",
          "text": "预算、",
          "startFrame": 272,
          "durationInFrames": 20
        },
        {
          "id": "caption-8",
          "text": "身份信息、",
          "startFrame": 292,
          "durationInFrames": 19
        },
        {
          "id": "caption-9",
          "text": "公司政策、",
          "startFrame": 311,
          "durationInFrames": 33
        },
        {
          "id": "caption-10",
          "text": "历史行程、",
          "startFrame": 344,
          "durationInFrames": 29
        },
        {
          "id": "caption-11",
          "text": "酒店偏好。",
          "startFrame": 373,
          "durationInFrames": 28
        },
        {
          "id": "caption-12",
          "text": "这些信息可能都是完成任务需要的。",
          "startFrame": 401,
          "durationInFrames": 121
        },
        {
          "id": "caption-13",
          "text": "但问题是：",
          "startFrame": 522,
          "durationInFrames": 43
        },
        {
          "id": "caption-14",
          "text": "它到底该知道多少？",
          "startFrame": 565,
          "durationInFrames": 59
        }
      ]
    },
    "durationInFrames": 624,
    "durationInSeconds": 20.8,
    "format": "wav",
    "narration": "AI时代，Agent要完成任务，就需要上下文。比如你让Agent帮你安排出差，它可能需要读取你的日历、邮件、预算、身份信息、公司政策、历史行程、酒店偏好。这些信息可能都是完成任务需要的。但问题是：它到底该知道多少？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "privacy-complexity"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/privacy-problem.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代的隐私问题，",
          "startFrame": 0,
          "durationInFrames": 63
        },
        {
          "id": "caption-2",
          "text": "不只是数据有没有泄露。",
          "startFrame": 63,
          "durationInFrames": 63
        },
        {
          "id": "caption-3",
          "text": "更重要的是：",
          "startFrame": 126,
          "durationInFrames": 35
        },
        {
          "id": "caption-4",
          "text": "上下文有没有被过度使用。",
          "startFrame": 161,
          "durationInFrames": 75
        },
        {
          "id": "caption-5",
          "text": "Agent为了完成一个小任务，",
          "startFrame": 236,
          "durationInFrames": 129
        },
        {
          "id": "caption-6",
          "text": "是否拿到了过多信息？",
          "startFrame": 365,
          "durationInFrames": 73
        },
        {
          "id": "caption-7",
          "text": "它是否读取了不相关的数据？",
          "startFrame": 438,
          "durationInFrames": 73
        },
        {
          "id": "caption-8",
          "text": "它是否把临时任务需要的信息，",
          "startFrame": 511,
          "durationInFrames": 29
        },
        {
          "id": "caption-9",
          "text": "变成了长期记忆？",
          "startFrame": 540,
          "durationInFrames": 17
        }
      ]
    },
    "durationInFrames": 557,
    "durationInSeconds": 18.56,
    "format": "wav",
    "narration": "AI时代的隐私问题，不只是数据有没有泄露。更重要的是：上下文有没有被过度使用。Agent为了完成一个小任务，是否拿到了过多信息？它是否读取了不相关的数据？它是否把临时任务需要的信息，变成了长期记忆？",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "privacy-problem"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/privacy-principle.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代隐私的核心原则，",
          "startFrame": 0,
          "durationInFrames": 72
        },
        {
          "id": "caption-2",
          "text": "应该是最小上下文。",
          "startFrame": 72,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "也就是：",
          "startFrame": 130,
          "durationInFrames": 25
        },
        {
          "id": "caption-4",
          "text": "只给Agent完成当前任务所需的最小信息。",
          "startFrame": 155,
          "durationInFrames": 108
        },
        {
          "id": "caption-5",
          "text": "能给摘要，",
          "startFrame": 263,
          "durationInFrames": 32
        },
        {
          "id": "caption-6",
          "text": "就不要给原文。",
          "startFrame": 295,
          "durationInFrames": 45
        },
        {
          "id": "caption-7",
          "text": "能给临时权限，",
          "startFrame": 340,
          "durationInFrames": 44
        },
        {
          "id": "caption-8",
          "text": "就不要给永久权限。",
          "startFrame": 384,
          "durationInFrames": 56
        },
        {
          "id": "caption-9",
          "text": "能给局部数据，",
          "startFrame": 440,
          "durationInFrames": 40
        },
        {
          "id": "caption-10",
          "text": "就不要给全量数据。",
          "startFrame": 480,
          "durationInFrames": 53
        }
      ]
    },
    "durationInFrames": 533,
    "durationInSeconds": 17.76,
    "format": "wav",
    "narration": "AI时代隐私的核心原则，应该是最小上下文。也就是：只给Agent完成当前任务所需的最小信息。能给摘要，就不要给原文。能给临时权限，就不要给永久权限。能给局部数据，就不要给全量数据。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "privacy-principle"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/privacy-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的隐私，",
          "startFrame": 0,
          "durationInFrames": 48
        },
        {
          "id": "caption-2",
          "text": "是防止数据泄露。",
          "startFrame": 48,
          "durationInFrames": 55
        },
        {
          "id": "caption-3",
          "text": "AI时代的隐私，",
          "startFrame": 103,
          "durationInFrames": 49
        },
        {
          "id": "caption-4",
          "text": "是控制上下文边界。",
          "startFrame": 152,
          "durationInFrames": 65
        },
        {
          "id": "caption-5",
          "text": "不是完全不给Agent数据，",
          "startFrame": 217,
          "durationInFrames": 67
        },
        {
          "id": "caption-6",
          "text": "而是精确控制：",
          "startFrame": 284,
          "durationInFrames": 50
        },
        {
          "id": "caption-7",
          "text": "给什么，",
          "startFrame": 334,
          "durationInFrames": 28
        },
        {
          "id": "caption-8",
          "text": "给多久，",
          "startFrame": 362,
          "durationInFrames": 26
        },
        {
          "id": "caption-9",
          "text": "给到什么程度，",
          "startFrame": 388,
          "durationInFrames": 43
        },
        {
          "id": "caption-10",
          "text": "能不能撤销，",
          "startFrame": 431,
          "durationInFrames": 36
        },
        {
          "id": "caption-11",
          "text": "能不能审计。",
          "startFrame": 467,
          "durationInFrames": 32
        }
      ]
    },
    "durationInFrames": 499,
    "durationInSeconds": 16.64,
    "format": "wav",
    "narration": "过去的隐私，是防止数据泄露。AI时代的隐私，是控制上下文边界。不是完全不给Agent数据，而是精确控制：给什么，给多久，给到什么程度，能不能撤销，能不能审计。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "privacy-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-data.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的数据，",
          "startFrame": 0,
          "durationInFrames": 42
        },
        {
          "id": "caption-2",
          "text": "主要被看作一种可存储资产。",
          "startFrame": 42,
          "durationInFrames": 86
        },
        {
          "id": "caption-3",
          "text": "文档、",
          "startFrame": 128,
          "durationInFrames": 24
        },
        {
          "id": "caption-4",
          "text": "图片、",
          "startFrame": 152,
          "durationInFrames": 23
        },
        {
          "id": "caption-5",
          "text": "表格、",
          "startFrame": 175,
          "durationInFrames": 59
        },
        {
          "id": "caption-6",
          "text": "数据库记录、",
          "startFrame": 234,
          "durationInFrames": 31
        },
        {
          "id": "caption-7",
          "text": "用户行为、",
          "startFrame": 265,
          "durationInFrames": 21
        },
        {
          "id": "caption-8",
          "text": "日志，",
          "startFrame": 286,
          "durationInFrames": 45
        },
        {
          "id": "caption-9",
          "text": "这些都叫数据。",
          "startFrame": 331,
          "durationInFrames": 44
        },
        {
          "id": "caption-10",
          "text": "传统数据价值经常来自规模、",
          "startFrame": 375,
          "durationInFrames": 61
        },
        {
          "id": "caption-11",
          "text": "数量、",
          "startFrame": 436,
          "durationInFrames": 14
        },
        {
          "id": "caption-12",
          "text": "独家性和历史积累。",
          "startFrame": 450,
          "durationInFrames": 44
        }
      ]
    },
    "durationInFrames": 494,
    "durationInSeconds": 16.48,
    "format": "wav",
    "narration": "过去的数据，主要被看作一种可存储资产。文档、图片、表格、数据库记录、用户行为、日志，这些都叫数据。传统数据价值经常来自规模、数量、独家性和历史积累。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-data"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/data-change.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代，",
          "startFrame": 0,
          "durationInFrames": 123
        },
        {
          "id": "caption-2",
          "text": "数据不只是存储起来的内容。",
          "startFrame": 123,
          "durationInFrames": 134
        },
        {
          "id": "caption-3",
          "text": "它更像是Agent完成任务时需要调用的上下文。",
          "startFrame": 257,
          "durationInFrames": 54
        },
        {
          "id": "caption-4",
          "text": "一份文档的价值，",
          "startFrame": 311,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "不只是人能不能读。",
          "startFrame": 369,
          "durationInFrames": 61
        },
        {
          "id": "caption-6",
          "text": "而是Agent能不能理解、",
          "startFrame": 430,
          "durationInFrames": 24
        },
        {
          "id": "caption-7",
          "text": "检索、",
          "startFrame": 454,
          "durationInFrames": 22
        },
        {
          "id": "caption-8",
          "text": "引用、",
          "startFrame": 476,
          "durationInFrames": 24
        },
        {
          "id": "caption-9",
          "text": "推理，",
          "startFrame": 500,
          "durationInFrames": 14
        },
        {
          "id": "caption-10",
          "text": "并且用它完成任务。",
          "startFrame": 514,
          "durationInFrames": 43
        }
      ]
    },
    "durationInFrames": 557,
    "durationInSeconds": 18.56,
    "format": "wav",
    "narration": "AI时代，数据不只是存储起来的内容。它更像是Agent完成任务时需要调用的上下文。一份文档的价值，不只是人能不能读。而是Agent能不能理解、检索、引用、推理，并且用它完成任务。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "data-change"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/data-value.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去看数据，",
          "startFrame": 0,
          "durationInFrames": 44
        },
        {
          "id": "caption-2",
          "text": "可能看数量大不大，",
          "startFrame": 44,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "用户多不多，",
          "startFrame": 102,
          "durationInFrames": 36
        },
        {
          "id": "caption-4",
          "text": "积累久不久。",
          "startFrame": 138,
          "durationInFrames": 39
        },
        {
          "id": "caption-5",
          "text": "AI时代更重要的是：",
          "startFrame": 177,
          "durationInFrames": 62
        },
        {
          "id": "caption-6",
          "text": "结构是否清晰，",
          "startFrame": 239,
          "durationInFrames": 48
        },
        {
          "id": "caption-7",
          "text": "权限是否明确，",
          "startFrame": 287,
          "durationInFrames": 50
        },
        {
          "id": "caption-8",
          "text": "来源是否可信，",
          "startFrame": 337,
          "durationInFrames": 48
        },
        {
          "id": "caption-9",
          "text": "是否可追溯，",
          "startFrame": 385,
          "durationInFrames": 41
        },
        {
          "id": "caption-10",
          "text": "是否可检索，",
          "startFrame": 426,
          "durationInFrames": 42
        },
        {
          "id": "caption-11",
          "text": "是否能进入Agent工作流。",
          "startFrame": 468,
          "durationInFrames": 75
        },
        {
          "id": "caption-12",
          "text": "数据的价值从我拥有多少，",
          "startFrame": 543,
          "durationInFrames": 64
        },
        {
          "id": "caption-13",
          "text": "变成Agent能不能用好。",
          "startFrame": 607,
          "durationInFrames": 70
        }
      ]
    },
    "durationInFrames": 677,
    "durationInSeconds": 22.56,
    "format": "wav",
    "narration": "过去看数据，可能看数量大不大，用户多不多，积累久不久。AI时代更重要的是：结构是否清晰，权限是否明确，来源是否可信，是否可追溯，是否可检索，是否能进入Agent工作流。数据的价值从我拥有多少，变成Agent能不能用好。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "data-value"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/rag-memory.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "企业知识库、",
          "startFrame": 0,
          "durationInFrames": 48
        },
        {
          "id": "caption-2",
          "text": "个人知识库、",
          "startFrame": 48,
          "durationInFrames": 40
        },
        {
          "id": "caption-3",
          "text": "RAG、",
          "startFrame": 88,
          "durationInFrames": 63
        },
        {
          "id": "caption-4",
          "text": "Agent Memory，",
          "startFrame": 151,
          "durationInFrames": 67
        },
        {
          "id": "caption-5",
          "text": "本质上不是简单存资料。",
          "startFrame": 218,
          "durationInFrames": 45
        },
        {
          "id": "caption-6",
          "text": "它们真正的意义，",
          "startFrame": 263,
          "durationInFrames": 86
        },
        {
          "id": "caption-7",
          "text": "是给Agent提供高质量上下文。",
          "startFrame": 349,
          "durationInFrames": 80
        },
        {
          "id": "caption-8",
          "text": "如果知识库只是给人看的资料库，",
          "startFrame": 429,
          "durationInFrames": 41
        },
        {
          "id": "caption-9",
          "text": "价值有限。",
          "startFrame": 470,
          "durationInFrames": 86
        },
        {
          "id": "caption-10",
          "text": "如果知识库能让Agent稳定完成任务，",
          "startFrame": 556,
          "durationInFrames": 38
        },
        {
          "id": "caption-11",
          "text": "它就会变成新的基础设施。",
          "startFrame": 594,
          "durationInFrames": 25
        }
      ]
    },
    "durationInFrames": 619,
    "durationInSeconds": 20.64,
    "format": "wav",
    "narration": "企业知识库、个人知识库、RAG、Agent Memory，本质上不是简单存资料。它们真正的意义，是给Agent提供高质量上下文。如果知识库只是给人看的资料库，价值有限。如果知识库能让Agent稳定完成任务，它就会变成新的基础设施。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "rag-memory"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/data-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的数据，",
          "startFrame": 0,
          "durationInFrames": 43
        },
        {
          "id": "caption-2",
          "text": "是被存储的资产。",
          "startFrame": 43,
          "durationInFrames": 55
        },
        {
          "id": "caption-3",
          "text": "AI时代的数据，",
          "startFrame": 98,
          "durationInFrames": 45
        },
        {
          "id": "caption-4",
          "text": "是可被Agent使用的行动上下文。",
          "startFrame": 143,
          "durationInFrames": 94
        },
        {
          "id": "caption-5",
          "text": "数据不再只是记录过去，",
          "startFrame": 237,
          "durationInFrames": 68
        },
        {
          "id": "caption-6",
          "text": "而是参与未来的任务执行。",
          "startFrame": 305,
          "durationInFrames": 65
        }
      ]
    },
    "durationInFrames": 370,
    "durationInSeconds": 12.32,
    "format": "wav",
    "narration": "过去的数据，是被存储的资产。AI时代的数据，是可被Agent使用的行动上下文。数据不再只是记录过去，而是参与未来的任务执行。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "data-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/old-interaction.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "传统交互是人围绕界面操作。",
          "startFrame": 0,
          "durationInFrames": 15
        },
        {
          "id": "caption-2",
          "text": "用户打开页面，",
          "startFrame": 15,
          "durationInFrames": 88
        },
        {
          "id": "caption-3",
          "text": "寻找菜单，",
          "startFrame": 103,
          "durationInFrames": 43
        },
        {
          "id": "caption-4",
          "text": "点击按钮，",
          "startFrame": 146,
          "durationInFrames": 35
        },
        {
          "id": "caption-5",
          "text": "填写表单，",
          "startFrame": 181,
          "durationInFrames": 31
        },
        {
          "id": "caption-6",
          "text": "提交信息，",
          "startFrame": 212,
          "durationInFrames": 62
        },
        {
          "id": "caption-7",
          "text": "然后等待结果。",
          "startFrame": 274,
          "durationInFrames": 47
        },
        {
          "id": "caption-8",
          "text": "整个流程中，",
          "startFrame": 321,
          "durationInFrames": 35
        },
        {
          "id": "caption-9",
          "text": "人是执行者，",
          "startFrame": 356,
          "durationInFrames": 36
        },
        {
          "id": "caption-10",
          "text": "软件是工具。",
          "startFrame": 392,
          "durationInFrames": 40
        }
      ]
    },
    "durationInFrames": 432,
    "durationInSeconds": 14.4,
    "format": "wav",
    "narration": "传统交互是人围绕界面操作。用户打开页面，寻找菜单，点击按钮，填写表单，提交信息，然后等待结果。整个流程中，人是执行者，软件是工具。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "old-interaction"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/interaction-change.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代，",
          "startFrame": 0,
          "durationInFrames": 33
        },
        {
          "id": "caption-2",
          "text": "交互会越来越像目标表达。",
          "startFrame": 33,
          "durationInFrames": 83
        },
        {
          "id": "caption-3",
          "text": "你不需要一步一步告诉系统怎么做。",
          "startFrame": 116,
          "durationInFrames": 94
        },
        {
          "id": "caption-4",
          "text": "你只要告诉Agent你要什么。",
          "startFrame": 210,
          "durationInFrames": 59
        },
        {
          "id": "caption-5",
          "text": "Agent会自己拆解任务、",
          "startFrame": 269,
          "durationInFrames": 56
        },
        {
          "id": "caption-6",
          "text": "调用工具、",
          "startFrame": 325,
          "durationInFrames": 30
        },
        {
          "id": "caption-7",
          "text": "检查结果，",
          "startFrame": 355,
          "durationInFrames": 32
        },
        {
          "id": "caption-8",
          "text": "并在关键节点让你确认。",
          "startFrame": 387,
          "durationInFrames": 64
        }
      ]
    },
    "durationInFrames": 451,
    "durationInSeconds": 15.04,
    "format": "wav",
    "narration": "AI时代，交互会越来越像目标表达。你不需要一步一步告诉系统怎么做。你只要告诉Agent你要什么。Agent会自己拆解任务、调用工具、检查结果，并在关键节点让你确认。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "interaction-change"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/ui-persists.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这不代表UI会消失。",
          "startFrame": 0,
          "durationInFrames": 72
        },
        {
          "id": "caption-2",
          "text": "UI的角色会改变。",
          "startFrame": 72,
          "durationInFrames": 59
        },
        {
          "id": "caption-3",
          "text": "过去UI主要是操作入口。",
          "startFrame": 131,
          "durationInFrames": 6
        },
        {
          "id": "caption-4",
          "text": "未来UI更像是监督面板、",
          "startFrame": 137,
          "durationInFrames": 73
        },
        {
          "id": "caption-5",
          "text": "确认入口、",
          "startFrame": 210,
          "durationInFrames": 181
        },
        {
          "id": "caption-6",
          "text": "状态中心和审计界面。",
          "startFrame": 391,
          "durationInFrames": 68
        },
        {
          "id": "caption-7",
          "text": "人不一定每一步都操作，",
          "startFrame": 459,
          "durationInFrames": 73
        },
        {
          "id": "caption-8",
          "text": "但需要知道Agent做了什么，",
          "startFrame": 532,
          "durationInFrames": 32
        },
        {
          "id": "caption-9",
          "text": "做到哪一步，",
          "startFrame": 564,
          "durationInFrames": 18
        },
        {
          "id": "caption-10",
          "text": "哪里需要确认。",
          "startFrame": 582,
          "durationInFrames": 23
        }
      ]
    },
    "durationInFrames": 605,
    "durationInSeconds": 20.16,
    "format": "wav",
    "narration": "这不代表UI会消失。UI的角色会改变。过去UI主要是操作入口。未来UI更像是监督面板、确认入口、状态中心和审计界面。人不一定每一步都操作，但需要知道Agent做了什么，做到哪一步，哪里需要确认。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "ui-persists"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/interaction-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的交互，",
          "startFrame": 0,
          "durationInFrames": 43
        },
        {
          "id": "caption-2",
          "text": "是人操作界面。",
          "startFrame": 43,
          "durationInFrames": 52
        },
        {
          "id": "caption-3",
          "text": "AI时代的交互，",
          "startFrame": 95,
          "durationInFrames": 45
        },
        {
          "id": "caption-4",
          "text": "是人设定目标，",
          "startFrame": 140,
          "durationInFrames": 47
        },
        {
          "id": "caption-5",
          "text": "Agent执行路径，",
          "startFrame": 187,
          "durationInFrames": 46
        },
        {
          "id": "caption-6",
          "text": "人监督结果。",
          "startFrame": 233,
          "durationInFrames": 85
        },
        {
          "id": "caption-7",
          "text": "所以未来好的交互，",
          "startFrame": 318,
          "durationInFrames": 53
        },
        {
          "id": "caption-8",
          "text": "不一定是按钮最少，",
          "startFrame": 371,
          "durationInFrames": 54
        },
        {
          "id": "caption-9",
          "text": "而是目标表达清楚、",
          "startFrame": 425,
          "durationInFrames": 44
        },
        {
          "id": "caption-10",
          "text": "执行过程透明、",
          "startFrame": 469,
          "durationInFrames": 20
        },
        {
          "id": "caption-11",
          "text": "关键动作可控。",
          "startFrame": 489,
          "durationInFrames": 20
        }
      ]
    },
    "durationInFrames": 509,
    "durationInSeconds": 16.96,
    "format": "wav",
    "narration": "过去的交互，是人操作界面。AI时代的交互，是人设定目标，Agent执行路径，人监督结果。所以未来好的交互，不一定是按钮最少，而是目标表达清楚、执行过程透明、关键动作可控。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "interaction-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/product-metrics.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "如果交互主体变了，",
          "startFrame": 0,
          "durationInFrames": 65
        },
        {
          "id": "caption-2",
          "text": "产品指标也会变化。",
          "startFrame": 65,
          "durationInFrames": 58
        },
        {
          "id": "caption-3",
          "text": "过去产品关注日活、",
          "startFrame": 123,
          "durationInFrames": 59
        },
        {
          "id": "caption-4",
          "text": "月活、",
          "startFrame": 182,
          "durationInFrames": 26
        },
        {
          "id": "caption-5",
          "text": "留存、",
          "startFrame": 208,
          "durationInFrames": 20
        },
        {
          "id": "caption-6",
          "text": "使用时长。",
          "startFrame": 228,
          "durationInFrames": 39
        },
        {
          "id": "caption-7",
          "text": "AI时代，",
          "startFrame": 267,
          "durationInFrames": 35
        },
        {
          "id": "caption-8",
          "text": "很多产品可能不需要用户每天打开。",
          "startFrame": 302,
          "durationInFrames": 98
        },
        {
          "id": "caption-9",
          "text": "只要用户的Agent每天调用它，",
          "startFrame": 400,
          "durationInFrames": 74
        },
        {
          "id": "caption-10",
          "text": "它就是高频产品。",
          "startFrame": 474,
          "durationInFrames": 44
        }
      ]
    },
    "durationInFrames": 518,
    "durationInSeconds": 17.28,
    "format": "wav",
    "narration": "如果交互主体变了，产品指标也会变化。过去产品关注日活、月活、留存、使用时长。AI时代，很多产品可能不需要用户每天打开。只要用户的Agent每天调用它，它就是高频产品。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "product-metrics"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/new-product-metrics.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来产品会更关注任务完成率、",
          "startFrame": 0,
          "durationInFrames": 86
        },
        {
          "id": "caption-2",
          "text": "自动化成功率、",
          "startFrame": 86,
          "durationInFrames": 84
        },
        {
          "id": "caption-3",
          "text": "人工介入次数、",
          "startFrame": 170,
          "durationInFrames": 104
        },
        {
          "id": "caption-4",
          "text": "错误恢复能力、",
          "startFrame": 274,
          "durationInFrames": 25
        },
        {
          "id": "caption-5",
          "text": "调用成本和结果可信度。",
          "startFrame": 299,
          "durationInFrames": 39
        },
        {
          "id": "caption-6",
          "text": "也就是说，",
          "startFrame": 338,
          "durationInFrames": 18
        },
        {
          "id": "caption-7",
          "text": "产品竞争会从让用户多停留，",
          "startFrame": 356,
          "durationInFrames": 46
        },
        {
          "id": "caption-8",
          "text": "转向让任务更可靠地完成。",
          "startFrame": 402,
          "durationInFrames": 44
        }
      ]
    },
    "durationInFrames": 446,
    "durationInSeconds": 14.88,
    "format": "wav",
    "narration": "未来产品会更关注任务完成率、自动化成功率、人工介入次数、错误恢复能力、调用成本和结果可信度。也就是说，产品竞争会从让用户多停留，转向让任务更可靠地完成。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "new-product-metrics"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/content-redefined.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去内容主要是给人阅读。",
          "startFrame": 0,
          "durationInFrames": 78
        },
        {
          "id": "caption-2",
          "text": "AI时代，",
          "startFrame": 78,
          "durationInFrames": 32
        },
        {
          "id": "caption-3",
          "text": "很多内容会先被Agent读取、",
          "startFrame": 110,
          "durationInFrames": 90
        },
        {
          "id": "caption-4",
          "text": "提取、",
          "startFrame": 200,
          "durationInFrames": 37
        },
        {
          "id": "caption-5",
          "text": "总结、",
          "startFrame": 237,
          "durationInFrames": 58
        },
        {
          "id": "caption-6",
          "text": "整合，",
          "startFrame": 295,
          "durationInFrames": 106
        },
        {
          "id": "caption-7",
          "text": "然后再呈现给用户。",
          "startFrame": 401,
          "durationInFrames": 40
        },
        {
          "id": "caption-8",
          "text": "所以泛泛而谈的SEO内容价值会下降。",
          "startFrame": 441,
          "durationInFrames": 32
        },
        {
          "id": "caption-9",
          "text": "结构化知识、",
          "startFrame": 473,
          "durationInFrames": 60
        },
        {
          "id": "caption-10",
          "text": "权威资料、",
          "startFrame": 533,
          "durationInFrames": 33
        },
        {
          "id": "caption-11",
          "text": "教程流程、",
          "startFrame": 566,
          "durationInFrames": 12
        },
        {
          "id": "caption-12",
          "text": "素材库、",
          "startFrame": 578,
          "durationInFrames": 10
        },
        {
          "id": "caption-13",
          "text": "行业经验，",
          "startFrame": 588,
          "durationInFrames": 12
        },
        {
          "id": "caption-14",
          "text": "会更容易变成Agent可用的能力。",
          "startFrame": 600,
          "durationInFrames": 43
        }
      ]
    },
    "durationInFrames": 643,
    "durationInSeconds": 21.44,
    "format": "wav",
    "narration": "过去内容主要是给人阅读。AI时代，很多内容会先被Agent读取、提取、总结、整合，然后再呈现给用户。所以泛泛而谈的SEO内容价值会下降。结构化知识、权威资料、教程流程、素材库、行业经验，会更容易变成Agent可用的能力。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "content-redefined"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/content-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的内容，",
          "startFrame": 0,
          "durationInFrames": 96
        },
        {
          "id": "caption-2",
          "text": "是吸引人阅读的信息。",
          "startFrame": 96,
          "durationInFrames": 130
        },
        {
          "id": "caption-3",
          "text": "AI时代的内容，",
          "startFrame": 226,
          "durationInFrames": 32
        },
        {
          "id": "caption-4",
          "text": "是可被Agent消费的知识资源。",
          "startFrame": 258,
          "durationInFrames": 58
        },
        {
          "id": "caption-5",
          "text": "一篇教程，",
          "startFrame": 316,
          "durationInFrames": 42
        },
        {
          "id": "caption-6",
          "text": "如果能被Agent稳定复用，",
          "startFrame": 358,
          "durationInFrames": 41
        },
        {
          "id": "caption-7",
          "text": "它就不只是文章。",
          "startFrame": 399,
          "durationInFrames": 39
        },
        {
          "id": "caption-8",
          "text": "它可以变成Skill，",
          "startFrame": 438,
          "durationInFrames": 18
        },
        {
          "id": "caption-9",
          "text": "可以变成Workflow，",
          "startFrame": 456,
          "durationInFrames": 21
        },
        {
          "id": "caption-10",
          "text": "可以变成任务能力的一部分。",
          "startFrame": 477,
          "durationInFrames": 22
        }
      ]
    },
    "durationInFrames": 499,
    "durationInSeconds": 16.64,
    "format": "wav",
    "narration": "过去的内容，是吸引人阅读的信息。AI时代的内容，是可被Agent消费的知识资源。一篇教程，如果能被Agent稳定复用，它就不只是文章。它可以变成Skill，可以变成Workflow，可以变成任务能力的一部分。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "content-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/trust-changes.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "过去的信任来自品牌、",
          "startFrame": 0,
          "durationInFrames": 65
        },
        {
          "id": "caption-2",
          "text": "排名、",
          "startFrame": 65,
          "durationInFrames": 22
        },
        {
          "id": "caption-3",
          "text": "评价、",
          "startFrame": 87,
          "durationInFrames": 14
        },
        {
          "id": "caption-4",
          "text": "平台背书。",
          "startFrame": 101,
          "durationInFrames": 24
        },
        {
          "id": "caption-5",
          "text": "AI时代，",
          "startFrame": 125,
          "durationInFrames": 24
        },
        {
          "id": "caption-6",
          "text": "当Agent可以自动调用服务，",
          "startFrame": 149,
          "durationInFrames": 72
        },
        {
          "id": "caption-7",
          "text": "信任就必须更可验证。",
          "startFrame": 221,
          "durationInFrames": 48
        },
        {
          "id": "caption-8",
          "text": "因为一旦Agent自动执行错误，",
          "startFrame": 269,
          "durationInFrames": 76
        },
        {
          "id": "caption-9",
          "text": "可能直接造成损失。",
          "startFrame": 345,
          "durationInFrames": 44
        }
      ]
    },
    "durationInFrames": 389,
    "durationInSeconds": 12.96,
    "format": "wav",
    "narration": "过去的信任来自品牌、排名、评价、平台背书。AI时代，当Agent可以自动调用服务，信任就必须更可验证。因为一旦Agent自动执行错误，可能直接造成损失。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "trust-changes"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/trust-definition.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来的信任，",
          "startFrame": 0,
          "durationInFrames": 52
        },
        {
          "id": "caption-2",
          "text": "不只是我听过这个品牌。",
          "startFrame": 52,
          "durationInFrames": 77
        },
        {
          "id": "caption-3",
          "text": "而是这个服务是否有来源，",
          "startFrame": 129,
          "durationInFrames": 79
        },
        {
          "id": "caption-4",
          "text": "是否能验证，",
          "startFrame": 208,
          "durationInFrames": 210
        },
        {
          "id": "caption-5",
          "text": "是否有日志，",
          "startFrame": 418,
          "durationInFrames": 83
        },
        {
          "id": "caption-6",
          "text": "是否能审计，",
          "startFrame": 501,
          "durationInFrames": 88
        },
        {
          "id": "caption-7",
          "text": "是否能回滚，",
          "startFrame": 589,
          "durationInFrames": 7
        },
        {
          "id": "caption-8",
          "text": "是否有权限边界，",
          "startFrame": 596,
          "durationInFrames": 9
        },
        {
          "id": "caption-9",
          "text": "失败时能不能处理。",
          "startFrame": 605,
          "durationInFrames": 10
        },
        {
          "id": "caption-10",
          "text": "AI时代的信任，",
          "startFrame": 615,
          "durationInFrames": 9
        },
        {
          "id": "caption-11",
          "text": "会从品牌信任，",
          "startFrame": 624,
          "durationInFrames": 8
        },
        {
          "id": "caption-12",
          "text": "转向可验证信任。",
          "startFrame": 632,
          "durationInFrames": 11
        }
      ]
    },
    "durationInFrames": 643,
    "durationInSeconds": 21.44,
    "format": "wav",
    "narration": "未来的信任，不只是我听过这个品牌。而是这个服务是否有来源，是否能验证，是否有日志，是否能审计，是否能回滚，是否有权限边界，失败时能不能处理。AI时代的信任，会从品牌信任，转向可验证信任。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "trust-definition"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/summary-table.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "把这些变化放在一起看，",
          "startFrame": 0,
          "durationInFrames": 85
        },
        {
          "id": "caption-2",
          "text": "可以得到一张新的对照表。",
          "startFrame": 85,
          "durationInFrames": 73
        },
        {
          "id": "caption-3",
          "text": "流量，",
          "startFrame": 158,
          "durationInFrames": 21
        },
        {
          "id": "caption-4",
          "text": "从访问量变成调用量。",
          "startFrame": 179,
          "durationInFrames": 72
        },
        {
          "id": "caption-5",
          "text": "服务，",
          "startFrame": 251,
          "durationInFrames": 20
        },
        {
          "id": "caption-6",
          "text": "从软件产品变成能力单元。",
          "startFrame": 271,
          "durationInFrames": 86
        },
        {
          "id": "caption-7",
          "text": "鉴权，",
          "startFrame": 357,
          "durationInFrames": 21
        },
        {
          "id": "caption-8",
          "text": "从登录变成委托授权。",
          "startFrame": 378,
          "durationInFrames": 72
        },
        {
          "id": "caption-9",
          "text": "隐私，",
          "startFrame": 450,
          "durationInFrames": 23
        },
        {
          "id": "caption-10",
          "text": "从防泄露变成控制上下文。",
          "startFrame": 473,
          "durationInFrames": 79
        },
        {
          "id": "caption-11",
          "text": "数据，",
          "startFrame": 552,
          "durationInFrames": 23
        },
        {
          "id": "caption-12",
          "text": "从存储资产变成行动上下文。",
          "startFrame": 575,
          "durationInFrames": 83
        },
        {
          "id": "caption-13",
          "text": "交互，",
          "startFrame": 658,
          "durationInFrames": 8
        },
        {
          "id": "caption-14",
          "text": "从点击按钮变成表达目标。",
          "startFrame": 666,
          "durationInFrames": 92
        }
      ]
    },
    "durationInFrames": 758,
    "durationInSeconds": 25.28,
    "format": "wav",
    "narration": "把这些变化放在一起看，可以得到一张新的对照表。流量，从访问量变成调用量。服务，从软件产品变成能力单元。鉴权，从登录变成委托授权。隐私，从防泄露变成控制上下文。数据，从存储资产变成行动上下文。交互，从点击按钮变成表达目标。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "summary-table"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/real-change.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "这些变化背后的本质，",
          "startFrame": 0,
          "durationInFrames": 62
        },
        {
          "id": "caption-2",
          "text": "是互联网的操作主体正在改变。",
          "startFrame": 62,
          "durationInFrames": 96
        },
        {
          "id": "caption-3",
          "text": "过去是人直接使用软件。",
          "startFrame": 158,
          "durationInFrames": 73
        },
        {
          "id": "caption-4",
          "text": "未来越来越像Agent代表人使用软件、",
          "startFrame": 231,
          "durationInFrames": 99
        },
        {
          "id": "caption-5",
          "text": "数据、",
          "startFrame": 330,
          "durationInFrames": 22
        },
        {
          "id": "caption-6",
          "text": "服务和工具。",
          "startFrame": 352,
          "durationInFrames": 52
        },
        {
          "id": "caption-7",
          "text": "所以AI时代不是简单多了一个聊天入口，",
          "startFrame": 404,
          "durationInFrames": 106
        },
        {
          "id": "caption-8",
          "text": "而是整个软件世界的接口对象变了。",
          "startFrame": 510,
          "durationInFrames": 90
        }
      ]
    },
    "durationInFrames": 600,
    "durationInSeconds": 20,
    "format": "wav",
    "narration": "这些变化背后的本质，是互联网的操作主体正在改变。过去是人直接使用软件。未来越来越像Agent代表人使用软件、数据、服务和工具。所以AI时代不是简单多了一个聊天入口，而是整个软件世界的接口对象变了。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "real-change"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/final-view.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "未来最重要的问题，",
          "startFrame": 0,
          "durationInFrames": 52
        },
        {
          "id": "caption-2",
          "text": "不再只是人如何使用软件。",
          "startFrame": 52,
          "durationInFrames": 71
        },
        {
          "id": "caption-3",
          "text": "而是Agent如何代表人，",
          "startFrame": 123,
          "durationInFrames": 32
        },
        {
          "id": "caption-4",
          "text": "安全、",
          "startFrame": 155,
          "durationInFrames": 40
        },
        {
          "id": "caption-5",
          "text": "可靠、",
          "startFrame": 195,
          "durationInFrames": 20
        },
        {
          "id": "caption-6",
          "text": "低成本地使用世界。",
          "startFrame": 215,
          "durationInFrames": 22
        },
        {
          "id": "caption-7",
          "text": "谁能让Agent更容易调用，",
          "startFrame": 237,
          "durationInFrames": 175
        },
        {
          "id": "caption-8",
          "text": "谁能提供更可靠的能力，",
          "startFrame": 412,
          "durationInFrames": 88
        },
        {
          "id": "caption-9",
          "text": "谁能建立更清晰的权限和信任机制，",
          "startFrame": 500,
          "durationInFrames": 43
        },
        {
          "id": "caption-10",
          "text": "谁就可能成为AI时代的新基础设施。",
          "startFrame": 543,
          "durationInFrames": 47
        }
      ]
    },
    "durationInFrames": 590,
    "durationInSeconds": 19.68,
    "format": "wav",
    "narration": "未来最重要的问题，不再只是人如何使用软件。而是Agent如何代表人，安全、可靠、低成本地使用世界。谁能让Agent更容易调用，谁能提供更可靠的能力，谁能建立更清晰的权限和信任机制，谁就可能成为AI时代的新基础设施。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "final-view"
  },
  {
    "audioFile": "generated/ai-concepts-redefined/closing.wav",
    "captions": {
      "language": "zh-CN",
      "cues": [
        {
          "id": "caption-1",
          "text": "AI时代的真正变化，",
          "startFrame": 0,
          "durationInFrames": 58
        },
        {
          "id": "caption-2",
          "text": "不是换了一个入口。",
          "startFrame": 58,
          "durationInFrames": 102
        },
        {
          "id": "caption-3",
          "text": "而是换了一个操作主体。",
          "startFrame": 160,
          "durationInFrames": 65
        },
        {
          "id": "caption-4",
          "text": "过去互联网围绕人设计。",
          "startFrame": 225,
          "durationInFrames": 36
        },
        {
          "id": "caption-5",
          "text": "未来的互联网，",
          "startFrame": 261,
          "durationInFrames": 72
        },
        {
          "id": "caption-6",
          "text": "很可能会围绕Agent重新组织。",
          "startFrame": 333,
          "durationInFrames": 45
        },
        {
          "id": "caption-7",
          "text": "这就是为什么流量、",
          "startFrame": 378,
          "durationInFrames": 19
        },
        {
          "id": "caption-8",
          "text": "服务、",
          "startFrame": 397,
          "durationInFrames": 22
        },
        {
          "id": "caption-9",
          "text": "鉴权、",
          "startFrame": 419,
          "durationInFrames": 22
        },
        {
          "id": "caption-10",
          "text": "隐私、",
          "startFrame": 441,
          "durationInFrames": 41
        },
        {
          "id": "caption-11",
          "text": "数据、",
          "startFrame": 482,
          "durationInFrames": 8
        },
        {
          "id": "caption-12",
          "text": "交互，",
          "startFrame": 490,
          "durationInFrames": 9
        },
        {
          "id": "caption-13",
          "text": "都需要重新定义。",
          "startFrame": 499,
          "durationInFrames": 24
        }
      ]
    },
    "durationInFrames": 523,
    "durationInSeconds": 17.44,
    "format": "wav",
    "narration": "AI时代的真正变化，不是换了一个入口。而是换了一个操作主体。过去互联网围绕人设计。未来的互联网，很可能会围绕Agent重新组织。这就是为什么流量、服务、鉴权、隐私、数据、交互，都需要重新定义。",
    "provider": "voxcpm-clone-lyy",
    "sceneId": "closing"
  }
] satisfies readonly AudioTrack[];
