import type { Data, Scene } from "./types";

const buildScenes = (): Scene[] => {
  const s: Scene[] = [];
  s.push({
    accent: "#FFB45E",
    audioFile: "generated/ai-concepts-redefined/open.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI出现之后，", "startFrame": 0, "durationInFrames": 40}, {"id": "caption-2", "text": "很多过去很稳定的互联网概念，", "startFrame": 40, "durationInFrames": 70}, {"id": "caption-3", "text": "开始变得不够用了。", "startFrame": 110, "durationInFrames": 50}, {"id": "caption-4", "text": "比如：", "startFrame": 160, "durationInFrames": 18}, {"id": "caption-5", "text": "流量、", "startFrame": 178, "durationInFrames": 19}, {"id": "caption-6", "text": "服务、", "startFrame": 197, "durationInFrames": 17}, {"id": "caption-7", "text": "鉴权、", "startFrame": 213, "durationInFrames": 24}, {"id": "caption-8", "text": "隐私、", "startFrame": 238, "durationInFrames": 21}, {"id": "caption-9", "text": "数据、", "startFrame": 258, "durationInFrames": 20}, {"id": "caption-10", "text": "交互。", "startFrame": 278, "durationInFrames": 28}, {"id": "caption-11", "text": "这些词不是消失了，", "startFrame": 306, "durationInFrames": 46}, {"id": "caption-12", "text": "而是它们的定义正在改变。", "startFrame": 352, "durationInFrames": 57}]},
    chapter: "开场",
    durationInFrames: 422,
    headline: "很多概念，都要重新定义",
    id: "open",
    narration: "AI出现之后，很多过去很稳定的互联网概念，开始变得不够用了。比如：流量、服务、鉴权、隐私、数据、交互。这些词不是消失了，而是它们的定义正在改变。",
    primitiveMap: [],
    supportingText: "旧容器，装不下新世界",
    visual: { kind: "thesis" },
  });
  s.push({
    accent: "#8BD5FF",
    audioFile: "generated/ai-concepts-redefined/core-change.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的互联网，", "startFrame": 0, "durationInFrames": 48}, {"id": "caption-2", "text": "是人使用软件。", "startFrame": 48, "durationInFrames": 48}, {"id": "caption-3", "text": "人打开网站，", "startFrame": 96, "durationInFrames": 36}, {"id": "caption-4", "text": "点击按钮，", "startFrame": 132, "durationInFrames": 31}, {"id": "caption-5", "text": "填写表单，", "startFrame": 162, "durationInFrames": 32}, {"id": "caption-6", "text": "提交信息，", "startFrame": 195, "durationInFrames": 30}, {"id": "caption-7", "text": "然后得到结果。", "startFrame": 225, "durationInFrames": 45}, {"id": "caption-8", "text": "但AI时代，", "startFrame": 270, "durationInFrames": 32}, {"id": "caption-9", "text": "越来越多场景会变成：", "startFrame": 302, "durationInFrames": 53}, {"id": "caption-10", "text": "人只表达目标，", "startFrame": 356, "durationInFrames": 43}, {"id": "caption-11", "text": "Agent替人调用软件、", "startFrame": 399, "durationInFrames": 52}, {"id": "caption-12", "text": "服务、", "startFrame": 452, "durationInFrames": 17}, {"id": "caption-13", "text": "工具和数据，", "startFrame": 468, "durationInFrames": 17}, {"id": "caption-14", "text": "最后完成任务。", "startFrame": 485, "durationInFrames": 59}]},
    chapter: "开场",
    durationInFrames: 558,
    headline: "人使用软件 → 人表达目标",
    id: "core-change",
    narration: "过去的互联网，是人使用软件。人打开网站，点击按钮，填写表单，提交信息，然后得到结果。但AI时代，越来越多场景会变成：人只表达目标，Agent替人调用软件、服务、工具和数据，最后完成任务。",
    primitiveMap: [],
    supportingText: "操作者从「人」变成了「Agent」",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#FFD166",
    audioFile: "generated/ai-concepts-redefined/why-rewrite.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "问题不在于AI多了一个聊天框。", "startFrame": 0, "durationInFrames": 75}, {"id": "caption-2", "text": "真正的变化是：", "startFrame": 75, "durationInFrames": 39}, {"id": "caption-3", "text": "操作主体变了。", "startFrame": 114, "durationInFrames": 44}, {"id": "caption-4", "text": "过去软件主要面对人。", "startFrame": 158, "durationInFrames": 58}, {"id": "caption-5", "text": "未来很多软件、", "startFrame": 216, "durationInFrames": 38}, {"id": "caption-6", "text": "服务和数据，", "startFrame": 254, "durationInFrames": 36}, {"id": "caption-7", "text": "首先要面对Agent。", "startFrame": 290, "durationInFrames": 48}, {"id": "caption-8", "text": "所以，", "startFrame": 338, "durationInFrames": 20}, {"id": "caption-9", "text": "互联网的很多基础概念，", "startFrame": 358, "durationInFrames": 56}, {"id": "caption-10", "text": "都要从人类视角，", "startFrame": 414, "durationInFrames": 41}, {"id": "caption-11", "text": "重新转向Agent视角。", "startFrame": 455, "durationInFrames": 49}]},
    chapter: "开场",
    durationInFrames: 518,
    headline: "操作主体变了",
    id: "why-rewrite",
    narration: "问题不在于AI多了一个聊天框。真正的变化是：操作主体变了。过去软件主要面对人。未来很多软件、服务和数据，首先要面对Agent。所以，互联网的很多基础概念，都要从人类视角，重新转向Agent视角。",
    primitiveMap: [],
    supportingText: "不再是「人操作软件」，而是「Agent代表人操作软件」",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/six-concepts.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "这条视频主要讲六个概念的变化：", "startFrame": 0, "durationInFrames": 82}, {"id": "caption-2", "text": "流量，", "startFrame": 82, "durationInFrames": 21}, {"id": "caption-3", "text": "服务，", "startFrame": 102, "durationInFrames": 21}, {"id": "caption-4", "text": "鉴权，", "startFrame": 123, "durationInFrames": 22}, {"id": "caption-5", "text": "隐私，", "startFrame": 146, "durationInFrames": 22}, {"id": "caption-6", "text": "数据，", "startFrame": 168, "durationInFrames": 22}, {"id": "caption-7", "text": "交互。", "startFrame": 189, "durationInFrames": 18}, {"id": "caption-8", "text": "它们共同指向一个核心判断：", "startFrame": 207, "durationInFrames": 59}, {"id": "caption-9", "text": "AI时代，", "startFrame": 266, "durationInFrames": 27}, {"id": "caption-10", "text": "互联网正在从人操作软件，", "startFrame": 292, "durationInFrames": 62}, {"id": "caption-11", "text": "变成Agent代表人调用世界。", "startFrame": 354, "durationInFrames": 62}]},
    chapter: "开场",
    durationInFrames: 429,
    headline: "六个概念，一个核心判断",
    id: "six-concepts",
    narration: "这条视频主要讲六个概念的变化：流量，服务，鉴权，隐私，数据，交互。它们共同指向一个核心判断：AI时代，互联网正在从人操作软件，变成Agent代表人调用世界。",
    primitiveMap: [],
    supportingText: "六个概念的共同方向：Agent视角",
    visual: { kind: "thesis" },
  });
  s.push({
    accent: "#FF8E72",
    audioFile: "generated/ai-concepts-redefined/old-traffic.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "在传统互联网里，", "startFrame": 0, "durationInFrames": 51}, {"id": "caption-2", "text": "流量就是人有没有来。", "startFrame": 51, "durationInFrames": 52}, {"id": "caption-3", "text": "用户有没有打开你的网站，", "startFrame": 102, "durationInFrames": 95}, {"id": "caption-4", "text": "有没有刷到你的内容，", "startFrame": 198, "durationInFrames": 40}, {"id": "caption-5", "text": "有没有点击你的按钮，", "startFrame": 238, "durationInFrames": 37}, {"id": "caption-6", "text": "有没有停留，", "startFrame": 274, "durationInFrames": 22}, {"id": "caption-7", "text": "有没有转化。", "startFrame": 297, "durationInFrames": 22}, {"id": "caption-8", "text": "所以过去大家关注的是UV、", "startFrame": 319, "durationInFrames": 48}, {"id": "caption-9", "text": "PV、", "startFrame": 368, "durationInFrames": 11}, {"id": "caption-10", "text": "点击率、", "startFrame": 378, "durationInFrames": 15}, {"id": "caption-11", "text": "停留时长、", "startFrame": 393, "durationInFrames": 19}, {"id": "caption-12", "text": "转化率。", "startFrame": 412, "durationInFrames": 16}]},
    chapter: "流量",
    durationInFrames: 442,
    headline: "旧流量：人有没有来",
    id: "old-traffic",
    narration: "在传统互联网里，流量就是人有没有来。用户有没有打开你的网站，有没有刷到你的内容，有没有点击你的按钮，有没有停留，有没有转化。所以过去大家关注的是UV、PV、点击率、停留时长、转化率。",
    primitiveMap: [],
    supportingText: "传统指标：UV、PV、点击率、停留时长、转化率",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#72E6B1",
    audioFile: "generated/ai-concepts-redefined/new-traffic.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代，", "startFrame": 0, "durationInFrames": 35}, {"id": "caption-2", "text": "用户可能根本不会访问你的网页。", "startFrame": 35, "durationInFrames": 73}, {"id": "caption-3", "text": "他可能只是对自己的Agent说：", "startFrame": 108, "durationInFrames": 64}, {"id": "caption-4", "text": "帮我做一条视频，", "startFrame": 172, "durationInFrames": 41}, {"id": "caption-5", "text": "帮我订一次行程，", "startFrame": 213, "durationInFrames": 39}, {"id": "caption-6", "text": "帮我整理一份报告。", "startFrame": 252, "durationInFrames": 43}, {"id": "caption-7", "text": "然后Agent会自动选择工具、", "startFrame": 296, "durationInFrames": 58}, {"id": "caption-8", "text": "调用服务、", "startFrame": 353, "durationInFrames": 25}, {"id": "caption-9", "text": "处理数据。", "startFrame": 378, "durationInFrames": 29}, {"id": "caption-10", "text": "这时候，", "startFrame": 408, "durationInFrames": 22}, {"id": "caption-11", "text": "真正的流量不是用户有没有看到你，", "startFrame": 429, "durationInFrames": 72}, {"id": "caption-12", "text": "而是Agent会不会调用你。", "startFrame": 502, "durationInFrames": 47}]},
    chapter: "流量",
    durationInFrames: 562,
    headline: "新流量：Agent会不会调用你",
    id: "new-traffic",
    narration: "AI时代，用户可能根本不会访问你的网页。他可能只是对自己的Agent说：帮我做一条视频，帮我订一次行程，帮我整理一份报告。然后Agent会自动选择工具、调用服务、处理数据。这时候，真正的流量不是用户有没有看到你，而是Agent会不会调用你。",
    primitiveMap: [],
    supportingText: "用户说目标，Agent选工具",
    visual: { kind: "new-way" },
  });
  s.push({
    accent: "#5EE7F7",
    audioFile: "generated/ai-concepts-redefined/traffic-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代的流量，", "startFrame": 0, "durationInFrames": 116}, {"id": "caption-2", "text": "本质上会从访问量变成调用量。", "startFrame": 116, "durationInFrames": 68}, {"id": "caption-3", "text": "一个服务可能没有多少网页访问，", "startFrame": 184, "durationInFrames": 57}, {"id": "caption-4", "text": "但它可能被大量Agent调用。", "startFrame": 241, "durationInFrames": 89}, {"id": "caption-5", "text": "未来很多服务的价值，", "startFrame": 330, "durationInFrames": 22}, {"id": "caption-6", "text": "不是看人类访问量，", "startFrame": 352, "durationInFrames": 19}, {"id": "caption-7", "text": "而是看它在任务链路里被调用的频率。", "startFrame": 371, "durationInFrames": 38}]},
    chapter: "流量",
    durationInFrames: 422,
    headline: "流量新定义：访问量 → 调用量",
    id: "traffic-definition",
    narration: "AI时代的流量，本质上会从访问量变成调用量。一个服务可能没有多少网页访问，但它可能被大量Agent调用。未来很多服务的价值，不是看人类访问量，而是看它在任务链路里被调用的频率。",
    primitiveMap: [],
    supportingText: "Agent调用频率 > 人类访问量",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#FFCA6A",
    audioFile: "generated/ai-concepts-redefined/traffic-metrics.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "传统流量看点击率、", "startFrame": 0, "durationInFrames": 52}, {"id": "caption-2", "text": "曝光量、", "startFrame": 52, "durationInFrames": 51}, {"id": "caption-3", "text": "停留时长。", "startFrame": 102, "durationInFrames": 184}, {"id": "caption-4", "text": "Agent流量看的是：", "startFrame": 287, "durationInFrames": 76}, {"id": "caption-5", "text": "调用成功率、", "startFrame": 362, "durationInFrames": 50}, {"id": "caption-6", "text": "响应速度、", "startFrame": 412, "durationInFrames": 5}, {"id": "caption-7", "text": "结果质量、", "startFrame": 418, "durationInFrames": 5}, {"id": "caption-8", "text": "成本、", "startFrame": 422, "durationInFrames": 3}, {"id": "caption-9", "text": "稳定性、", "startFrame": 426, "durationInFrames": 4}, {"id": "caption-10", "text": "可组合性。", "startFrame": 430, "durationInFrames": 6}, {"id": "caption-11", "text": "Agent不会因为页面好看就调用你。", "startFrame": 436, "durationInFrames": 21}, {"id": "caption-12", "text": "它更关心你是否可靠、", "startFrame": 457, "durationInFrames": 12}, {"id": "caption-13", "text": "便宜、", "startFrame": 468, "durationInFrames": 3}, {"id": "caption-14", "text": "稳定、", "startFrame": 472, "durationInFrames": 3}, {"id": "caption-15", "text": "清晰、", "startFrame": 475, "durationInFrames": 3}, {"id": "caption-16", "text": "好接入。", "startFrame": 478, "durationInFrames": 6}]},
    chapter: "流量",
    durationInFrames: 498,
    headline: "Agent流量看什么",
    id: "traffic-metrics",
    narration: "传统流量看点击率、曝光量、停留时长。Agent流量看的是：调用成功率、响应速度、结果质量、成本、稳定性、可组合性。Agent不会因为页面好看就调用你。它更关心你是否可靠、便宜、稳定、清晰、好接入。",
    primitiveMap: [],
    supportingText: "可靠性 > 美观度；稳定性 > 曝光量",
    visual: { kind: "comparison-list" },
  });
  s.push({
    accent: "#FFB45E",
    audioFile: "generated/ai-concepts-redefined/old-service.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去我们说做一个服务，", "startFrame": 0, "durationInFrames": 49}, {"id": "caption-2", "text": "通常指的是做一个网站、", "startFrame": 49, "durationInFrames": 48}, {"id": "caption-3", "text": "App或者SaaS。", "startFrame": 98, "durationInFrames": 18}, {"id": "caption-4", "text": "它有首页，", "startFrame": 115, "durationInFrames": 28}, {"id": "caption-5", "text": "有注册登录，", "startFrame": 143, "durationInFrames": 27}, {"id": "caption-6", "text": "有控制台，", "startFrame": 170, "durationInFrames": 32}, {"id": "caption-7", "text": "有按钮和表单。", "startFrame": 202, "durationInFrames": 27}, {"id": "caption-8", "text": "用户进入系统后，", "startFrame": 229, "durationInFrames": 41}, {"id": "caption-9", "text": "自己一步一步操作。", "startFrame": 270, "durationInFrames": 78}]},
    chapter: "服务",
    durationInFrames: 362,
    headline: "旧服务：给人类用的产品",
    id: "old-service",
    narration: "过去我们说做一个服务，通常指的是做一个网站、App或者SaaS。它有首页，有注册登录，有控制台，有按钮和表单。用户进入系统后，自己一步一步操作。",
    primitiveMap: [],
    supportingText: "网站 / App / SaaS：人直接操作",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#F58BFF",
    audioFile: "generated/ai-concepts-redefined/new-service.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代，", "startFrame": 0, "durationInFrames": 28}, {"id": "caption-2", "text": "服务会越来越像一个可以被Agent调用的能力单元。", "startFrame": 28, "durationInFrames": 102}, {"id": "caption-3", "text": "它不一定是完整的软件产品。", "startFrame": 130, "durationInFrames": 63}, {"id": "caption-4", "text": "它可能只是一个API、", "startFrame": 193, "durationInFrames": 46}, {"id": "caption-5", "text": "一个MCP Server、", "startFrame": 239, "durationInFrames": 39}, {"id": "caption-6", "text": "一个Tool、", "startFrame": 278, "durationInFrames": 21}, {"id": "caption-7", "text": "一个Skill、", "startFrame": 299, "durationInFrames": 22}, {"id": "caption-8", "text": "一个Workflow。", "startFrame": 321, "durationInFrames": 32}, {"id": "caption-9", "text": "比如：", "startFrame": 352, "durationInFrames": 59}, {"id": "caption-10", "text": "识别图片、", "startFrame": 412, "durationInFrames": 26}, {"id": "caption-11", "text": "生成文案、", "startFrame": 438, "durationInFrames": 24}, {"id": "caption-12", "text": "剪辑视频、", "startFrame": 462, "durationInFrames": 10}, {"id": "caption-13", "text": "查询数据、", "startFrame": 472, "durationInFrames": 11}, {"id": "caption-14", "text": "发送邮件、", "startFrame": 482, "durationInFrames": 11}, {"id": "caption-15", "text": "安排日程。", "startFrame": 493, "durationInFrames": 11}]},
    chapter: "服务",
    durationInFrames: 518,
    headline: "新服务：Agent可调用的能力单元",
    id: "new-service",
    narration: "AI时代，服务会越来越像一个可以被Agent调用的能力单元。它不一定是完整的软件产品。它可能只是一个API、一个MCP Server、一个Tool、一个Skill、一个Workflow。比如：识别图片、生成文案、剪辑视频、查询数据、发送邮件、安排日程。",
    primitiveMap: [],
    supportingText: "API / MCP / Tool / Skill / Workflow",
    visual: { kind: "new-way" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/service-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的服务，", "startFrame": 0, "durationInFrames": 37}, {"id": "caption-2", "text": "是给人操作的产品。", "startFrame": 37, "durationInFrames": 48}, {"id": "caption-3", "text": "AI时代的服务，", "startFrame": 85, "durationInFrames": 90}, {"id": "caption-4", "text": "是给Agent调用的能力。", "startFrame": 175, "durationInFrames": 76}, {"id": "caption-5", "text": "所以服务的重点会从界面好不好用，", "startFrame": 251, "durationInFrames": 47}, {"id": "caption-6", "text": "变成能力好不好接。", "startFrame": 298, "durationInFrames": 52}, {"id": "caption-7", "text": "输入输出是否清晰，", "startFrame": 349, "durationInFrames": 38}, {"id": "caption-8", "text": "边界是否明确，", "startFrame": 387, "durationInFrames": 35}, {"id": "caption-9", "text": "返回是否稳定，", "startFrame": 422, "durationInFrames": 33}, {"id": "caption-10", "text": "权限是否可控，", "startFrame": 455, "durationInFrames": 16}, {"id": "caption-11", "text": "这些会变得更重要。", "startFrame": 471, "durationInFrames": 21}]},
    chapter: "服务",
    durationInFrames: 505,
    headline: "服务新定义：产品 → 能力",
    id: "service-definition",
    narration: "过去的服务，是给人操作的产品。AI时代的服务，是给Agent调用的能力。所以服务的重点会从界面好不好用，变成能力好不好接。输入输出是否清晰，边界是否明确，返回是否稳定，权限是否可控，这些会变得更重要。",
    primitiveMap: [],
    supportingText: "界面友好度 → 接入清晰度",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#5EE7F7",
    audioFile: "generated/ai-concepts-redefined/skill-value.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "如果未来每个人都有自己的Agent，", "startFrame": 0, "durationInFrames": 73}, {"id": "caption-2", "text": "那么很多服务就不再需要用户亲自学习怎么用。", "startFrame": 73, "durationInFrames": 98}, {"id": "caption-3", "text": "服务只需要让Agent知道：", "startFrame": 171, "durationInFrames": 58}, {"id": "caption-4", "text": "你能做什么，", "startFrame": 228, "durationInFrames": 28}, {"id": "caption-5", "text": "怎么调用你，", "startFrame": 257, "durationInFrames": 51}, {"id": "caption-6", "text": "输入什么，", "startFrame": 308, "durationInFrames": 52}, {"id": "caption-7", "text": "输出什么，", "startFrame": 359, "durationInFrames": 32}, {"id": "caption-8", "text": "失败怎么办，", "startFrame": 392, "durationInFrames": 35}, {"id": "caption-9", "text": "费用怎么算。", "startFrame": 427, "durationInFrames": 12}, {"id": "caption-10", "text": "这就是Skill、", "startFrame": 439, "durationInFrames": 57}, {"id": "caption-11", "text": "Tool、", "startFrame": 496, "durationInFrames": 10}, {"id": "caption-12", "text": "Workflow这类东西的价值。", "startFrame": 506, "durationInFrames": 33}, {"id": "caption-13", "text": "它们本质上是在给Agent提供可复用能力。", "startFrame": 539, "durationInFrames": 45}]},
    chapter: "服务",
    durationInFrames: 598,
    headline: "为什么Skill会变重要",
    id: "skill-value",
    narration: "如果未来每个人都有自己的Agent，那么很多服务就不再需要用户亲自学习怎么用。服务只需要让Agent知道：你能做什么，怎么调用你，输入什么，输出什么，失败怎么办，费用怎么算。这就是Skill、Tool、Workflow这类东西的价值。它们本质上是在给Agent提供可复用能力。",
    primitiveMap: [],
    supportingText: "Agent不需要界面说明书，需要能力说明书",
    visual: { kind: "question-statement" },
  });
  s.push({
    accent: "#8BD5FF",
    audioFile: "generated/ai-concepts-redefined/old-auth.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的鉴权主要是证明你是谁。", "startFrame": 0, "durationInFrames": 195}, {"id": "caption-2", "text": "你输入账号密码，", "startFrame": 195, "durationInFrames": 7}, {"id": "caption-3", "text": "系统确认身份，", "startFrame": 202, "durationInFrames": 17}, {"id": "caption-4", "text": "然后给你登录状态。", "startFrame": 218, "durationInFrames": 40}, {"id": "caption-5", "text": "之后，", "startFrame": 258, "durationInFrames": 8}, {"id": "caption-6", "text": "你自己在系统里操作。", "startFrame": 267, "durationInFrames": 28}, {"id": "caption-7", "text": "这个逻辑在人类亲自使用软件时是够用的。", "startFrame": 294, "durationInFrames": 54}]},
    chapter: "鉴权",
    durationInFrames: 362,
    headline: "旧鉴权：证明你是谁",
    id: "old-auth",
    narration: "过去的鉴权主要是证明你是谁。你输入账号密码，系统确认身份，然后给你登录状态。之后，你自己在系统里操作。这个逻辑在人类亲自使用软件时是够用的。",
    primitiveMap: [],
    supportingText: "账号+密码 → 登录状态 → 自行操作",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#FFD166",
    audioFile: "generated/ai-concepts-redefined/auth-problem.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代的问题变复杂了。", "startFrame": 0, "durationInFrames": 154}, {"id": "caption-2", "text": "因为很多操作不是你亲自做，", "startFrame": 154, "durationInFrames": 60}, {"id": "caption-3", "text": "而是Agent替你做。", "startFrame": 214, "durationInFrames": 15}, {"id": "caption-4", "text": "所以核心问题不只是你是谁。", "startFrame": 229, "durationInFrames": 54}, {"id": "caption-5", "text": "而是：", "startFrame": 283, "durationInFrames": 40}, {"id": "caption-6", "text": "这个Agent能不能代表你行动？", "startFrame": 323, "durationInFrames": 38}, {"id": "caption-7", "text": "能行动到什么程度？", "startFrame": 361, "durationInFrames": 22}, {"id": "caption-8", "text": "能访问哪些数据？", "startFrame": 383, "durationInFrames": 20}, {"id": "caption-9", "text": "能不能花钱？", "startFrame": 403, "durationInFrames": 15}, {"id": "caption-10", "text": "能不能发邮件？", "startFrame": 418, "durationInFrames": 18}, {"id": "caption-11", "text": "能不能删除文件？", "startFrame": 436, "durationInFrames": 20}]},
    chapter: "鉴权",
    durationInFrames: 469,
    headline: "AI时代的鉴权问题",
    id: "auth-problem",
    narration: "AI时代的问题变复杂了。因为很多操作不是你亲自做，而是Agent替你做。所以核心问题不只是你是谁。而是：这个Agent能不能代表你行动？能行动到什么程度？能访问哪些数据？能不能花钱？能不能发邮件？能不能删除文件？",
    primitiveMap: [],
    supportingText: "不只是身份认证，而是代理权限管理",
    visual: { kind: "question-statement" },
  });
  s.push({
    accent: "#72E6B1",
    audioFile: "generated/ai-concepts-redefined/auth-essence.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代的鉴权，", "startFrame": 0, "durationInFrames": 48}, {"id": "caption-2", "text": "本质上是委托授权。", "startFrame": 48, "durationInFrames": 51}, {"id": "caption-3", "text": "你不是简单登录一个系统，", "startFrame": 99, "durationInFrames": 97}, {"id": "caption-4", "text": "而是在授权某个Agent，", "startFrame": 196, "durationInFrames": 79}, {"id": "caption-5", "text": "在某个范围内，", "startFrame": 275, "durationInFrames": 54}, {"id": "caption-6", "text": "代表你执行某些动作。", "startFrame": 329, "durationInFrames": 21}, {"id": "caption-7", "text": "这个权限必须是可限制、", "startFrame": 350, "durationInFrames": 14}, {"id": "caption-8", "text": "可撤销、", "startFrame": 364, "durationInFrames": 5}, {"id": "caption-9", "text": "可审计的。", "startFrame": 369, "durationInFrames": 7}]},
    chapter: "鉴权",
    durationInFrames: 389,
    headline: "新鉴权的本质：委托授权",
    id: "auth-essence",
    narration: "AI时代的鉴权，本质上是委托授权。你不是简单登录一个系统，而是在授权某个Agent，在某个范围内，代表你执行某些动作。这个权限必须是可限制、可撤销、可审计的。",
    primitiveMap: [],
    supportingText: "可限制 · 可撤销 · 可审计",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#FFCA6A",
    audioFile: "generated/ai-concepts-redefined/auth-example.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "你可以允许Agent查看邮件，", "startFrame": 0, "durationInFrames": 131}, {"id": "caption-2", "text": "但不允许它直接发送邮件。", "startFrame": 131, "durationInFrames": 112}, {"id": "caption-3", "text": "你可以允许Agent生成草稿，", "startFrame": 243, "durationInFrames": 58}, {"id": "caption-4", "text": "但发送前必须由你确认。", "startFrame": 301, "durationInFrames": 51}, {"id": "caption-5", "text": "你可以允许Agent挑选商品，", "startFrame": 352, "durationInFrames": 116}, {"id": "caption-6", "text": "但不允许它直接付款。", "startFrame": 468, "durationInFrames": 40}, {"id": "caption-7", "text": "你可以允许Agent整理文件，", "startFrame": 508, "durationInFrames": 15}, {"id": "caption-8", "text": "但删除文件必须二次确认。", "startFrame": 522, "durationInFrames": 12}, {"id": "caption-9", "text": "这就是AI时代更细粒度的权限系统。", "startFrame": 534, "durationInFrames": 18}]},
    chapter: "鉴权",
    durationInFrames: 565,
    headline: "Agent权限的粒度",
    id: "auth-example",
    narration: "你可以允许Agent查看邮件，但不允许它直接发送邮件。你可以允许Agent生成草稿，但发送前必须由你确认。你可以允许Agent挑选商品，但不允许它直接付款。你可以允许Agent整理文件，但删除文件必须二次确认。这就是AI时代更细粒度的权限系统。",
    primitiveMap: [],
    supportingText: "精细到读/写/执行/确认，每一个动作独立控制",
    visual: { kind: "callout-list" },
  });
  s.push({
    accent: "#F58BFF",
    audioFile: "generated/ai-concepts-redefined/auth-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的鉴权是：", "startFrame": 0, "durationInFrames": 49}, {"id": "caption-2", "text": "证明用户身份。", "startFrame": 49, "durationInFrames": 48}, {"id": "caption-3", "text": "AI时代的鉴权是：", "startFrame": 98, "durationInFrames": 50}, {"id": "caption-4", "text": "管理Agent的代理权限。", "startFrame": 148, "durationInFrames": 62}, {"id": "caption-5", "text": "它需要回答四个问题：", "startFrame": 209, "durationInFrames": 58}, {"id": "caption-6", "text": "谁授权的？", "startFrame": 267, "durationInFrames": 34}, {"id": "caption-7", "text": "授权给哪个Agent？", "startFrame": 301, "durationInFrames": 46}, {"id": "caption-8", "text": "允许它做什么？", "startFrame": 347, "durationInFrames": 41}, {"id": "caption-9", "text": "做了之后能不能审计和撤销？", "startFrame": 388, "durationInFrames": 77}]},
    chapter: "鉴权",
    durationInFrames: 478,
    headline: "鉴权新定义",
    id: "auth-definition",
    narration: "过去的鉴权是：证明用户身份。AI时代的鉴权是：管理Agent的代理权限。它需要回答四个问题：谁授权的？授权给哪个Agent？允许它做什么？做了之后能不能审计和撤销？",
    primitiveMap: [],
    supportingText: "身份证明 → 代理权限管理",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#5EE7F7",
    audioFile: "generated/ai-concepts-redefined/old-privacy.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去谈隐私，", "startFrame": 0, "durationInFrames": 38}, {"id": "caption-2", "text": "主要关注数据有没有泄露。", "startFrame": 38, "durationInFrames": 64}, {"id": "caption-3", "text": "比如账号密码有没有被盗，", "startFrame": 102, "durationInFrames": 55}, {"id": "caption-4", "text": "数据库有没有被拖走，", "startFrame": 157, "durationInFrames": 45}, {"id": "caption-5", "text": "平台有没有乱收集用户信息。", "startFrame": 202, "durationInFrames": 65}, {"id": "caption-6", "text": "这是传统互联网里的隐私问题。", "startFrame": 267, "durationInFrames": 65}]},
    chapter: "隐私",
    durationInFrames: 345,
    headline: "旧隐私：防数据泄露",
    id: "old-privacy",
    narration: "过去谈隐私，主要关注数据有没有泄露。比如账号密码有没有被盗，数据库有没有被拖走，平台有没有乱收集用户信息。这是传统互联网里的隐私问题。",
    primitiveMap: [],
    supportingText: "核心关注：数据泄露",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#FF8E72",
    audioFile: "generated/ai-concepts-redefined/privacy-complexity.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代，", "startFrame": 0, "durationInFrames": 30}, {"id": "caption-2", "text": "Agent要完成任务，", "startFrame": 30, "durationInFrames": 42}, {"id": "caption-3", "text": "就需要上下文。", "startFrame": 72, "durationInFrames": 35}, {"id": "caption-4", "text": "比如你让Agent帮你安排出差，", "startFrame": 107, "durationInFrames": 15}, {"id": "caption-5", "text": "它可能需要读取你的日历、", "startFrame": 122, "durationInFrames": 52}, {"id": "caption-6", "text": "邮件、", "startFrame": 174, "durationInFrames": 52}, {"id": "caption-7", "text": "预算、", "startFrame": 227, "durationInFrames": 17}, {"id": "caption-8", "text": "身份信息、", "startFrame": 243, "durationInFrames": 16}, {"id": "caption-9", "text": "公司政策、", "startFrame": 259, "durationInFrames": 28}, {"id": "caption-10", "text": "历史行程、", "startFrame": 287, "durationInFrames": 24}, {"id": "caption-11", "text": "酒店偏好。", "startFrame": 311, "durationInFrames": 23}, {"id": "caption-12", "text": "这些信息可能都是完成任务需要的。", "startFrame": 334, "durationInFrames": 101}, {"id": "caption-13", "text": "但问题是：", "startFrame": 435, "durationInFrames": 36}, {"id": "caption-14", "text": "它到底该知道多少？", "startFrame": 471, "durationInFrames": 49}]},
    chapter: "隐私",
    durationInFrames: 534,
    headline: "为什么AI时代隐私更复杂",
    id: "privacy-complexity",
    narration: "AI时代，Agent要完成任务，就需要上下文。比如你让Agent帮你安排出差，它可能需要读取你的日历、邮件、预算、身份信息、公司政策、历史行程、酒店偏好。这些信息可能都是完成任务需要的。但问题是：它到底该知道多少？",
    primitiveMap: [],
    supportingText: "完成任务需要多少上下文？",
    visual: { kind: "question-statement" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/privacy-problem.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代的隐私问题，", "startFrame": 0, "durationInFrames": 52}, {"id": "caption-2", "text": "不只是数据有没有泄露。", "startFrame": 52, "durationInFrames": 52}, {"id": "caption-3", "text": "更重要的是：", "startFrame": 105, "durationInFrames": 29}, {"id": "caption-4", "text": "上下文有没有被过度使用。", "startFrame": 134, "durationInFrames": 62}, {"id": "caption-5", "text": "Agent为了完成一个小任务，", "startFrame": 197, "durationInFrames": 108}, {"id": "caption-6", "text": "是否拿到了过多信息？", "startFrame": 304, "durationInFrames": 61}, {"id": "caption-7", "text": "它是否读取了不相关的数据？", "startFrame": 365, "durationInFrames": 61}, {"id": "caption-8", "text": "它是否把临时任务需要的信息，", "startFrame": 426, "durationInFrames": 24}, {"id": "caption-9", "text": "变成了长期记忆？", "startFrame": 450, "durationInFrames": 14}]},
    chapter: "隐私",
    durationInFrames: 478,
    headline: "隐私的新问题：上下文过度使用",
    id: "privacy-problem",
    narration: "AI时代的隐私问题，不只是数据有没有泄露。更重要的是：上下文有没有被过度使用。Agent为了完成一个小任务，是否拿到了过多信息？它是否读取了不相关的数据？它是否把临时任务需要的信息，变成了长期记忆？",
    primitiveMap: [],
    supportingText: "不只是防泄露，更要防上下文滥用",
    visual: { kind: "question-statement" },
  });
  s.push({
    accent: "#72E6B1",
    audioFile: "generated/ai-concepts-redefined/privacy-principle.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代隐私的核心原则，", "startFrame": 0, "durationInFrames": 60}, {"id": "caption-2", "text": "应该是最小上下文。", "startFrame": 60, "durationInFrames": 48}, {"id": "caption-3", "text": "也就是：", "startFrame": 108, "durationInFrames": 21}, {"id": "caption-4", "text": "只给Agent完成当前任务所需的最小信息。", "startFrame": 129, "durationInFrames": 90}, {"id": "caption-5", "text": "能给摘要，", "startFrame": 219, "durationInFrames": 27}, {"id": "caption-6", "text": "就不要给原文。", "startFrame": 246, "durationInFrames": 38}, {"id": "caption-7", "text": "能给临时权限，", "startFrame": 283, "durationInFrames": 37}, {"id": "caption-8", "text": "就不要给永久权限。", "startFrame": 320, "durationInFrames": 47}, {"id": "caption-9", "text": "能给局部数据，", "startFrame": 367, "durationInFrames": 33}, {"id": "caption-10", "text": "就不要给全量数据。", "startFrame": 400, "durationInFrames": 44}]},
    chapter: "隐私",
    durationInFrames: 458,
    headline: "隐私新原则：最小上下文",
    id: "privacy-principle",
    narration: "AI时代隐私的核心原则，应该是最小上下文。也就是：只给Agent完成当前任务所需的最小信息。能给摘要，就不要给原文。能给临时权限，就不要给永久权限。能给局部数据，就不要给全量数据。",
    primitiveMap: [],
    supportingText: "摘要 > 原文 · 临时 > 永久 · 局部 > 全量",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#FFB45E",
    audioFile: "generated/ai-concepts-redefined/privacy-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的隐私，", "startFrame": 0, "durationInFrames": 40}, {"id": "caption-2", "text": "是防止数据泄露。", "startFrame": 40, "durationInFrames": 46}, {"id": "caption-3", "text": "AI时代的隐私，", "startFrame": 86, "durationInFrames": 41}, {"id": "caption-4", "text": "是控制上下文边界。", "startFrame": 127, "durationInFrames": 54}, {"id": "caption-5", "text": "不是完全不给Agent数据，", "startFrame": 181, "durationInFrames": 56}, {"id": "caption-6", "text": "而是精确控制：", "startFrame": 237, "durationInFrames": 42}, {"id": "caption-7", "text": "给什么，", "startFrame": 278, "durationInFrames": 23}, {"id": "caption-8", "text": "给多久，", "startFrame": 302, "durationInFrames": 22}, {"id": "caption-9", "text": "给到什么程度，", "startFrame": 323, "durationInFrames": 36}, {"id": "caption-10", "text": "能不能撤销，", "startFrame": 359, "durationInFrames": 30}, {"id": "caption-11", "text": "能不能审计。", "startFrame": 389, "durationInFrames": 27}]},
    chapter: "隐私",
    durationInFrames: 429,
    headline: "隐私新定义",
    id: "privacy-definition",
    narration: "过去的隐私，是防止数据泄露。AI时代的隐私，是控制上下文边界。不是完全不给Agent数据，而是精确控制：给什么，给多久，给到什么程度，能不能撤销，能不能审计。",
    primitiveMap: [],
    supportingText: "防泄露 → 控边界",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#8BD5FF",
    audioFile: "generated/ai-concepts-redefined/old-data.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的数据，", "startFrame": 0, "durationInFrames": 35}, {"id": "caption-2", "text": "主要被看作一种可存储资产。", "startFrame": 35, "durationInFrames": 72}, {"id": "caption-3", "text": "文档、", "startFrame": 107, "durationInFrames": 20}, {"id": "caption-4", "text": "图片、", "startFrame": 127, "durationInFrames": 19}, {"id": "caption-5", "text": "表格、", "startFrame": 146, "durationInFrames": 49}, {"id": "caption-6", "text": "数据库记录、", "startFrame": 195, "durationInFrames": 26}, {"id": "caption-7", "text": "用户行为、", "startFrame": 221, "durationInFrames": 18}, {"id": "caption-8", "text": "日志，", "startFrame": 238, "durationInFrames": 38}, {"id": "caption-9", "text": "这些都叫数据。", "startFrame": 276, "durationInFrames": 37}, {"id": "caption-10", "text": "传统数据价值经常来自规模、", "startFrame": 312, "durationInFrames": 51}, {"id": "caption-11", "text": "数量、", "startFrame": 363, "durationInFrames": 12}, {"id": "caption-12", "text": "独家性和历史积累。", "startFrame": 375, "durationInFrames": 37}]},
    chapter: "数据",
    durationInFrames: 425,
    headline: "旧数据：被存储的资产",
    id: "old-data",
    narration: "过去的数据，主要被看作一种可存储资产。文档、图片、表格、数据库记录、用户行为、日志，这些都叫数据。传统数据价值经常来自规模、数量、独家性和历史积累。",
    primitiveMap: [],
    supportingText: "价值来源：规模、数量、独家性、积累",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#FFCA6A",
    audioFile: "generated/ai-concepts-redefined/data-change.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代，", "startFrame": 0, "durationInFrames": 102}, {"id": "caption-2", "text": "数据不只是存储起来的内容。", "startFrame": 102, "durationInFrames": 112}, {"id": "caption-3", "text": "它更像是Agent完成任务时需要调用的上下文。", "startFrame": 214, "durationInFrames": 45}, {"id": "caption-4", "text": "一份文档的价值，", "startFrame": 259, "durationInFrames": 48}, {"id": "caption-5", "text": "不只是人能不能读。", "startFrame": 308, "durationInFrames": 51}, {"id": "caption-6", "text": "而是Agent能不能理解、", "startFrame": 358, "durationInFrames": 20}, {"id": "caption-7", "text": "检索、", "startFrame": 378, "durationInFrames": 18}, {"id": "caption-8", "text": "引用、", "startFrame": 397, "durationInFrames": 20}, {"id": "caption-9", "text": "推理，", "startFrame": 417, "durationInFrames": 12}, {"id": "caption-10", "text": "并且用它完成任务。", "startFrame": 428, "durationInFrames": 36}]},
    chapter: "数据",
    durationInFrames: 478,
    headline: "AI时代的数据变化",
    id: "data-change",
    narration: "AI时代，数据不只是存储起来的内容。它更像是Agent完成任务时需要调用的上下文。一份文档的价值，不只是人能不能读。而是Agent能不能理解、检索、引用、推理，并且用它完成任务。",
    primitiveMap: [],
    supportingText: "存储资产 → 行动上下文",
    visual: { kind: "new-way" },
  });
  s.push({
    accent: "#FFD166",
    audioFile: "generated/ai-concepts-redefined/data-value.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去看数据，", "startFrame": 0, "durationInFrames": 37}, {"id": "caption-2", "text": "可能看数量大不大，", "startFrame": 37, "durationInFrames": 48}, {"id": "caption-3", "text": "用户多不多，", "startFrame": 85, "durationInFrames": 30}, {"id": "caption-4", "text": "积累久不久。", "startFrame": 115, "durationInFrames": 32}, {"id": "caption-5", "text": "AI时代更重要的是：", "startFrame": 148, "durationInFrames": 52}, {"id": "caption-6", "text": "结构是否清晰，", "startFrame": 199, "durationInFrames": 40}, {"id": "caption-7", "text": "权限是否明确，", "startFrame": 239, "durationInFrames": 42}, {"id": "caption-8", "text": "来源是否可信，", "startFrame": 281, "durationInFrames": 40}, {"id": "caption-9", "text": "是否可追溯，", "startFrame": 321, "durationInFrames": 34}, {"id": "caption-10", "text": "是否可检索，", "startFrame": 355, "durationInFrames": 35}, {"id": "caption-11", "text": "是否能进入Agent工作流。", "startFrame": 390, "durationInFrames": 62}, {"id": "caption-12", "text": "数据的价值从我拥有多少，", "startFrame": 452, "durationInFrames": 53}, {"id": "caption-13", "text": "变成Agent能不能用好。", "startFrame": 506, "durationInFrames": 58}]},
    chapter: "数据",
    durationInFrames: 578,
    headline: "数据的新价值标准",
    id: "data-value",
    narration: "过去看数据，可能看数量大不大，用户多不多，积累久不久。AI时代更重要的是：结构是否清晰，权限是否明确，来源是否可信，是否可追溯，是否可检索，是否能进入Agent工作流。数据的价值从我拥有多少，变成Agent能不能用好。",
    primitiveMap: [],
    supportingText: "我拥有多少 → Agent能不能用好",
    visual: { kind: "comparison-list" },
  });
  s.push({
    accent: "#F58BFF",
    audioFile: "generated/ai-concepts-redefined/rag-memory.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "企业知识库、", "startFrame": 0, "durationInFrames": 40}, {"id": "caption-2", "text": "个人知识库、", "startFrame": 40, "durationInFrames": 33}, {"id": "caption-3", "text": "RAG、", "startFrame": 73, "durationInFrames": 52}, {"id": "caption-4", "text": "Agent Memory，", "startFrame": 126, "durationInFrames": 56}, {"id": "caption-5", "text": "本质上不是简单存资料。", "startFrame": 182, "durationInFrames": 38}, {"id": "caption-6", "text": "它们真正的意义，", "startFrame": 219, "durationInFrames": 72}, {"id": "caption-7", "text": "是给Agent提供高质量上下文。", "startFrame": 291, "durationInFrames": 67}, {"id": "caption-8", "text": "如果知识库只是给人看的资料库，", "startFrame": 358, "durationInFrames": 34}, {"id": "caption-9", "text": "价值有限。", "startFrame": 392, "durationInFrames": 72}, {"id": "caption-10", "text": "如果知识库能让Agent稳定完成任务，", "startFrame": 463, "durationInFrames": 32}, {"id": "caption-11", "text": "它就会变成新的基础设施。", "startFrame": 495, "durationInFrames": 21}]},
    chapter: "数据",
    durationInFrames: 529,
    headline: "RAG和Agent Memory的本质",
    id: "rag-memory",
    narration: "企业知识库、个人知识库、RAG、Agent Memory，本质上不是简单存资料。它们真正的意义，是给Agent提供高质量上下文。如果知识库只是给人看的资料库，价值有限。如果知识库能让Agent稳定完成任务，它就会变成新的基础设施。",
    primitiveMap: [],
    supportingText: "不只是存储，而是让Agent可用的上下文基础设施",
    visual: { kind: "question-statement" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/data-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的数据，", "startFrame": 0, "durationInFrames": 36}, {"id": "caption-2", "text": "是被存储的资产。", "startFrame": 36, "durationInFrames": 46}, {"id": "caption-3", "text": "AI时代的数据，", "startFrame": 82, "durationInFrames": 38}, {"id": "caption-4", "text": "是可被Agent使用的行动上下文。", "startFrame": 119, "durationInFrames": 78}, {"id": "caption-5", "text": "数据不再只是记录过去，", "startFrame": 198, "durationInFrames": 57}, {"id": "caption-6", "text": "而是参与未来的任务执行。", "startFrame": 254, "durationInFrames": 54}]},
    chapter: "数据",
    durationInFrames: 322,
    headline: "数据新定义",
    id: "data-definition",
    narration: "过去的数据，是被存储的资产。AI时代的数据，是可被Agent使用的行动上下文。数据不再只是记录过去，而是参与未来的任务执行。",
    primitiveMap: [],
    supportingText: "存储资产 → 行动上下文",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#5EE7F7",
    audioFile: "generated/ai-concepts-redefined/old-interaction.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "传统交互是人围绕界面操作。", "startFrame": 0, "durationInFrames": 12}, {"id": "caption-2", "text": "用户打开页面，", "startFrame": 12, "durationInFrames": 73}, {"id": "caption-3", "text": "寻找菜单，", "startFrame": 86, "durationInFrames": 36}, {"id": "caption-4", "text": "点击按钮，", "startFrame": 122, "durationInFrames": 29}, {"id": "caption-5", "text": "填写表单，", "startFrame": 151, "durationInFrames": 26}, {"id": "caption-6", "text": "提交信息，", "startFrame": 177, "durationInFrames": 52}, {"id": "caption-7", "text": "然后等待结果。", "startFrame": 228, "durationInFrames": 39}, {"id": "caption-8", "text": "整个流程中，", "startFrame": 268, "durationInFrames": 29}, {"id": "caption-9", "text": "人是执行者，", "startFrame": 297, "durationInFrames": 30}, {"id": "caption-10", "text": "软件是工具。", "startFrame": 327, "durationInFrames": 33}]},
    chapter: "交互",
    durationInFrames: 374,
    headline: "旧交互：人围绕界面操作",
    id: "old-interaction",
    narration: "传统交互是人围绕界面操作。用户打开页面，寻找菜单，点击按钮，填写表单，提交信息，然后等待结果。整个流程中，人是执行者，软件是工具。",
    primitiveMap: [],
    supportingText: "人是执行者，软件是工具",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#FFB45E",
    audioFile: "generated/ai-concepts-redefined/interaction-change.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代，", "startFrame": 0, "durationInFrames": 28}, {"id": "caption-2", "text": "交互会越来越像目标表达。", "startFrame": 28, "durationInFrames": 69}, {"id": "caption-3", "text": "你不需要一步一步告诉系统怎么做。", "startFrame": 97, "durationInFrames": 78}, {"id": "caption-4", "text": "你只要告诉Agent你要什么。", "startFrame": 175, "durationInFrames": 49}, {"id": "caption-5", "text": "Agent会自己拆解任务、", "startFrame": 224, "durationInFrames": 47}, {"id": "caption-6", "text": "调用工具、", "startFrame": 271, "durationInFrames": 25}, {"id": "caption-7", "text": "检查结果，", "startFrame": 296, "durationInFrames": 27}, {"id": "caption-8", "text": "并在关键节点让你确认。", "startFrame": 322, "durationInFrames": 53}]},
    chapter: "交互",
    durationInFrames: 389,
    headline: "AI时代的交互：目标表达",
    id: "interaction-change",
    narration: "AI时代，交互会越来越像目标表达。你不需要一步一步告诉系统怎么做。你只要告诉Agent你要什么。Agent会自己拆解任务、调用工具、检查结果，并在关键节点让你确认。",
    primitiveMap: [],
    supportingText: "告诉Agent「要什么」，而不是「怎么做」",
    visual: { kind: "new-way" },
  });
  s.push({
    accent: "#72E6B1",
    audioFile: "generated/ai-concepts-redefined/ui-persists.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "这不代表UI会消失。", "startFrame": 0, "durationInFrames": 60}, {"id": "caption-2", "text": "UI的角色会改变。", "startFrame": 60, "durationInFrames": 49}, {"id": "caption-3", "text": "过去UI主要是操作入口。", "startFrame": 109, "durationInFrames": 5}, {"id": "caption-4", "text": "未来UI更像是监督面板、", "startFrame": 114, "durationInFrames": 61}, {"id": "caption-5", "text": "确认入口、", "startFrame": 175, "durationInFrames": 151}, {"id": "caption-6", "text": "状态中心和审计界面。", "startFrame": 326, "durationInFrames": 57}, {"id": "caption-7", "text": "人不一定每一步都操作，", "startFrame": 382, "durationInFrames": 61}, {"id": "caption-8", "text": "但需要知道Agent做了什么，", "startFrame": 443, "durationInFrames": 27}, {"id": "caption-9", "text": "做到哪一步，", "startFrame": 470, "durationInFrames": 15}, {"id": "caption-10", "text": "哪里需要确认。", "startFrame": 485, "durationInFrames": 19}]},
    chapter: "交互",
    durationInFrames: 518,
    headline: "UI不会消失",
    id: "ui-persists",
    narration: "这不代表UI会消失。UI的角色会改变。过去UI主要是操作入口。未来UI更像是监督面板、确认入口、状态中心和审计界面。人不一定每一步都操作，但需要知道Agent做了什么，做到哪一步，哪里需要确认。",
    primitiveMap: [],
    supportingText: "UI从操作入口 → 监督面板",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#FF8E72",
    audioFile: "generated/ai-concepts-redefined/interaction-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的交互，", "startFrame": 0, "durationInFrames": 36}, {"id": "caption-2", "text": "是人操作界面。", "startFrame": 36, "durationInFrames": 43}, {"id": "caption-3", "text": "AI时代的交互，", "startFrame": 79, "durationInFrames": 38}, {"id": "caption-4", "text": "是人设定目标，", "startFrame": 117, "durationInFrames": 39}, {"id": "caption-5", "text": "Agent执行路径，", "startFrame": 156, "durationInFrames": 38}, {"id": "caption-6", "text": "人监督结果。", "startFrame": 194, "durationInFrames": 71}, {"id": "caption-7", "text": "所以未来好的交互，", "startFrame": 265, "durationInFrames": 44}, {"id": "caption-8", "text": "不一定是按钮最少，", "startFrame": 309, "durationInFrames": 45}, {"id": "caption-9", "text": "而是目标表达清楚、", "startFrame": 354, "durationInFrames": 37}, {"id": "caption-10", "text": "执行过程透明、", "startFrame": 391, "durationInFrames": 17}, {"id": "caption-11", "text": "关键动作可控。", "startFrame": 408, "durationInFrames": 17}]},
    chapter: "交互",
    durationInFrames: 438,
    headline: "交互新定义",
    id: "interaction-definition",
    narration: "过去的交互，是人操作界面。AI时代的交互，是人设定目标，Agent执行路径，人监督结果。所以未来好的交互，不一定是按钮最少，而是目标表达清楚、执行过程透明、关键动作可控。",
    primitiveMap: [],
    supportingText: "操作界面 → 设定目标·监督结果",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/product-metrics.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "如果交互主体变了，", "startFrame": 0, "durationInFrames": 54}, {"id": "caption-2", "text": "产品指标也会变化。", "startFrame": 54, "durationInFrames": 48}, {"id": "caption-3", "text": "过去产品关注日活、", "startFrame": 102, "durationInFrames": 49}, {"id": "caption-4", "text": "月活、", "startFrame": 152, "durationInFrames": 22}, {"id": "caption-5", "text": "留存、", "startFrame": 173, "durationInFrames": 17}, {"id": "caption-6", "text": "使用时长。", "startFrame": 190, "durationInFrames": 32}, {"id": "caption-7", "text": "AI时代，", "startFrame": 222, "durationInFrames": 29}, {"id": "caption-8", "text": "很多产品可能不需要用户每天打开。", "startFrame": 252, "durationInFrames": 82}, {"id": "caption-9", "text": "只要用户的Agent每天调用它，", "startFrame": 333, "durationInFrames": 62}, {"id": "caption-10", "text": "它就是高频产品。", "startFrame": 395, "durationInFrames": 37}]},
    chapter: "交互",
    durationInFrames: 445,
    headline: "产品指标也会变化",
    id: "product-metrics",
    narration: "如果交互主体变了，产品指标也会变化。过去产品关注日活、月活、留存、使用时长。AI时代，很多产品可能不需要用户每天打开。只要用户的Agent每天调用它，它就是高频产品。",
    primitiveMap: [],
    supportingText: "DAU/MAU → TAU（Agent每日调用量）",
    visual: { kind: "comparison-list" },
  });
  s.push({
    accent: "#FFD166",
    audioFile: "generated/ai-concepts-redefined/new-product-metrics.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "未来产品会更关注任务完成率、", "startFrame": 0, "durationInFrames": 72}, {"id": "caption-2", "text": "自动化成功率、", "startFrame": 72, "durationInFrames": 70}, {"id": "caption-3", "text": "人工介入次数、", "startFrame": 142, "durationInFrames": 87}, {"id": "caption-4", "text": "错误恢复能力、", "startFrame": 228, "durationInFrames": 21}, {"id": "caption-5", "text": "调用成本和结果可信度。", "startFrame": 249, "durationInFrames": 32}, {"id": "caption-6", "text": "也就是说，", "startFrame": 282, "durationInFrames": 15}, {"id": "caption-7", "text": "产品竞争会从让用户多停留，", "startFrame": 297, "durationInFrames": 38}, {"id": "caption-8", "text": "转向让任务更可靠地完成。", "startFrame": 335, "durationInFrames": 37}]},
    chapter: "交互",
    durationInFrames: 385,
    headline: "产品的新指标",
    id: "new-product-metrics",
    narration: "未来产品会更关注任务完成率、自动化成功率、人工介入次数、错误恢复能力、调用成本和结果可信度。也就是说，产品竞争会从让用户多停留，转向让任务更可靠地完成。",
    primitiveMap: [],
    supportingText: "停留时长 → 任务完成率",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#FFCA6A",
    audioFile: "generated/ai-concepts-redefined/content-redefined.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去内容主要是给人阅读。", "startFrame": 0, "durationInFrames": 65}, {"id": "caption-2", "text": "AI时代，", "startFrame": 65, "durationInFrames": 27}, {"id": "caption-3", "text": "很多内容会先被Agent读取、", "startFrame": 92, "durationInFrames": 75}, {"id": "caption-4", "text": "提取、", "startFrame": 167, "durationInFrames": 31}, {"id": "caption-5", "text": "总结、", "startFrame": 198, "durationInFrames": 48}, {"id": "caption-6", "text": "整合，", "startFrame": 246, "durationInFrames": 88}, {"id": "caption-7", "text": "然后再呈现给用户。", "startFrame": 334, "durationInFrames": 33}, {"id": "caption-8", "text": "所以泛泛而谈的SEO内容价值会下降。", "startFrame": 368, "durationInFrames": 27}, {"id": "caption-9", "text": "结构化知识、", "startFrame": 394, "durationInFrames": 50}, {"id": "caption-10", "text": "权威资料、", "startFrame": 444, "durationInFrames": 28}, {"id": "caption-11", "text": "教程流程、", "startFrame": 472, "durationInFrames": 10}, {"id": "caption-12", "text": "素材库、", "startFrame": 482, "durationInFrames": 8}, {"id": "caption-13", "text": "行业经验，", "startFrame": 490, "durationInFrames": 10}, {"id": "caption-14", "text": "会更容易变成Agent可用的能力。", "startFrame": 500, "durationInFrames": 36}]},
    chapter: "延伸",
    durationInFrames: 549,
    headline: "内容也会被重新定义",
    id: "content-redefined",
    narration: "过去内容主要是给人阅读。AI时代，很多内容会先被Agent读取、提取、总结、整合，然后再呈现给用户。所以泛泛而谈的SEO内容价值会下降。结构化知识、权威资料、教程流程、素材库、行业经验，会更容易变成Agent可用的能力。",
    primitiveMap: [],
    supportingText: "Agent先读 → 提取整合 → 再给人看",
    visual: { kind: "new-way" },
  });
  s.push({
    accent: "#8BD5FF",
    audioFile: "generated/ai-concepts-redefined/content-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的内容，", "startFrame": 0, "durationInFrames": 80}, {"id": "caption-2", "text": "是吸引人阅读的信息。", "startFrame": 80, "durationInFrames": 108}, {"id": "caption-3", "text": "AI时代的内容，", "startFrame": 188, "durationInFrames": 27}, {"id": "caption-4", "text": "是可被Agent消费的知识资源。", "startFrame": 215, "durationInFrames": 48}, {"id": "caption-5", "text": "一篇教程，", "startFrame": 263, "durationInFrames": 35}, {"id": "caption-6", "text": "如果能被Agent稳定复用，", "startFrame": 298, "durationInFrames": 34}, {"id": "caption-7", "text": "它就不只是文章。", "startFrame": 332, "durationInFrames": 32}, {"id": "caption-8", "text": "它可以变成Skill，", "startFrame": 365, "durationInFrames": 15}, {"id": "caption-9", "text": "可以变成Workflow，", "startFrame": 380, "durationInFrames": 18}, {"id": "caption-10", "text": "可以变成任务能力的一部分。", "startFrame": 398, "durationInFrames": 18}]},
    chapter: "延伸",
    durationInFrames: 429,
    headline: "内容新定义",
    id: "content-definition",
    narration: "过去的内容，是吸引人阅读的信息。AI时代的内容，是可被Agent消费的知识资源。一篇教程，如果能被Agent稳定复用，它就不只是文章。它可以变成Skill，可以变成Workflow，可以变成任务能力的一部分。",
    primitiveMap: [],
    supportingText: "吸引人阅读 → 可被Agent消费的知识资源",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#F58BFF",
    audioFile: "generated/ai-concepts-redefined/trust-changes.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "过去的信任来自品牌、", "startFrame": 0, "durationInFrames": 54}, {"id": "caption-2", "text": "排名、", "startFrame": 54, "durationInFrames": 18}, {"id": "caption-3", "text": "评价、", "startFrame": 72, "durationInFrames": 12}, {"id": "caption-4", "text": "平台背书。", "startFrame": 84, "durationInFrames": 20}, {"id": "caption-5", "text": "AI时代，", "startFrame": 104, "durationInFrames": 20}, {"id": "caption-6", "text": "当Agent可以自动调用服务，", "startFrame": 124, "durationInFrames": 60}, {"id": "caption-7", "text": "信任就必须更可验证。", "startFrame": 184, "durationInFrames": 40}, {"id": "caption-8", "text": "因为一旦Agent自动执行错误，", "startFrame": 224, "durationInFrames": 63}, {"id": "caption-9", "text": "可能直接造成损失。", "startFrame": 288, "durationInFrames": 37}]},
    chapter: "延伸",
    durationInFrames: 338,
    headline: "信任也会变化",
    id: "trust-changes",
    narration: "过去的信任来自品牌、排名、评价、平台背书。AI时代，当Agent可以自动调用服务，信任就必须更可验证。因为一旦Agent自动执行错误，可能直接造成损失。",
    primitiveMap: [],
    supportingText: "品牌信任 → 可验证信任",
    visual: { kind: "old-way" },
  });
  s.push({
    accent: "#5EE7F7",
    audioFile: "generated/ai-concepts-redefined/trust-definition.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "未来的信任，", "startFrame": 0, "durationInFrames": 43}, {"id": "caption-2", "text": "不只是我听过这个品牌。", "startFrame": 43, "durationInFrames": 64}, {"id": "caption-3", "text": "而是这个服务是否有来源，", "startFrame": 108, "durationInFrames": 66}, {"id": "caption-4", "text": "是否能验证，", "startFrame": 173, "durationInFrames": 175}, {"id": "caption-5", "text": "是否有日志，", "startFrame": 348, "durationInFrames": 69}, {"id": "caption-6", "text": "是否能审计，", "startFrame": 418, "durationInFrames": 73}, {"id": "caption-7", "text": "是否能回滚，", "startFrame": 491, "durationInFrames": 6}, {"id": "caption-8", "text": "是否有权限边界，", "startFrame": 497, "durationInFrames": 8}, {"id": "caption-9", "text": "失败时能不能处理。", "startFrame": 504, "durationInFrames": 8}, {"id": "caption-10", "text": "AI时代的信任，", "startFrame": 512, "durationInFrames": 8}, {"id": "caption-11", "text": "会从品牌信任，", "startFrame": 520, "durationInFrames": 7}, {"id": "caption-12", "text": "转向可验证信任。", "startFrame": 527, "durationInFrames": 9}]},
    chapter: "延伸",
    durationInFrames: 549,
    headline: "信任新定义",
    id: "trust-definition",
    narration: "未来的信任，不只是我听过这个品牌。而是这个服务是否有来源，是否能验证，是否有日志，是否能审计，是否能回滚，是否有权限边界，失败时能不能处理。AI时代的信任，会从品牌信任，转向可验证信任。",
    primitiveMap: [],
    supportingText: "品牌信任 → 可验证信任（来源·日志·审计·回滚）",
    visual: { kind: "new-definition" },
  });
  s.push({
    accent: "#72E6B1",
    audioFile: "generated/ai-concepts-redefined/summary-table.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "把这些变化放在一起看，", "startFrame": 0, "durationInFrames": 71}, {"id": "caption-2", "text": "可以得到一张新的对照表。", "startFrame": 71, "durationInFrames": 61}, {"id": "caption-3", "text": "流量，", "startFrame": 132, "durationInFrames": 18}, {"id": "caption-4", "text": "从访问量变成调用量。", "startFrame": 149, "durationInFrames": 60}, {"id": "caption-5", "text": "服务，", "startFrame": 209, "durationInFrames": 17}, {"id": "caption-6", "text": "从软件产品变成能力单元。", "startFrame": 226, "durationInFrames": 72}, {"id": "caption-7", "text": "鉴权，", "startFrame": 298, "durationInFrames": 18}, {"id": "caption-8", "text": "从登录变成委托授权。", "startFrame": 315, "durationInFrames": 60}, {"id": "caption-9", "text": "隐私，", "startFrame": 375, "durationInFrames": 19}, {"id": "caption-10", "text": "从防泄露变成控制上下文。", "startFrame": 394, "durationInFrames": 66}, {"id": "caption-11", "text": "数据，", "startFrame": 460, "durationInFrames": 19}, {"id": "caption-12", "text": "从存储资产变成行动上下文。", "startFrame": 479, "durationInFrames": 69}, {"id": "caption-13", "text": "交互，", "startFrame": 548, "durationInFrames": 7}, {"id": "caption-14", "text": "从点击按钮变成表达目标。", "startFrame": 555, "durationInFrames": 77}]},
    chapter: "总结",
    durationInFrames: 645,
    headline: "一张新的对照表",
    id: "summary-table",
    narration: "把这些变化放在一起看，可以得到一张新的对照表。流量，从访问量变成调用量。服务，从软件产品变成能力单元。鉴权，从登录变成委托授权。隐私，从防泄露变成控制上下文。数据，从存储资产变成行动上下文。交互，从点击按钮变成表达目标。",
    primitiveMap: [],
    supportingText: "六组对比，一个方向：Agent视角",
    visual: { kind: "summary" },
  });
  s.push({
    accent: "#FFB45E",
    audioFile: "generated/ai-concepts-redefined/real-change.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "这些变化背后的本质，", "startFrame": 0, "durationInFrames": 52}, {"id": "caption-2", "text": "是互联网的操作主体正在改变。", "startFrame": 52, "durationInFrames": 80}, {"id": "caption-3", "text": "过去是人直接使用软件。", "startFrame": 132, "durationInFrames": 61}, {"id": "caption-4", "text": "未来越来越像Agent代表人使用软件、", "startFrame": 192, "durationInFrames": 82}, {"id": "caption-5", "text": "数据、", "startFrame": 275, "durationInFrames": 18}, {"id": "caption-6", "text": "服务和工具。", "startFrame": 293, "durationInFrames": 43}, {"id": "caption-7", "text": "所以AI时代不是简单多了一个聊天入口，", "startFrame": 337, "durationInFrames": 88}, {"id": "caption-8", "text": "而是整个软件世界的接口对象变了。", "startFrame": 425, "durationInFrames": 75}]},
    chapter: "总结",
    durationInFrames: 514,
    headline: "真正的底层变化",
    id: "real-change",
    narration: "这些变化背后的本质，是互联网的操作主体正在改变。过去是人直接使用软件。未来越来越像Agent代表人使用软件、数据、服务和工具。所以AI时代不是简单多了一个聊天入口，而是整个软件世界的接口对象变了。",
    primitiveMap: [],
    supportingText: "接口对象从人变成了Agent",
    visual: { kind: "thesis" },
  });
  s.push({
    accent: "#C9A7FF",
    audioFile: "generated/ai-concepts-redefined/final-view.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "未来最重要的问题，", "startFrame": 0, "durationInFrames": 43}, {"id": "caption-2", "text": "不再只是人如何使用软件。", "startFrame": 43, "durationInFrames": 59}, {"id": "caption-3", "text": "而是Agent如何代表人，", "startFrame": 102, "durationInFrames": 27}, {"id": "caption-4", "text": "安全、", "startFrame": 129, "durationInFrames": 33}, {"id": "caption-5", "text": "可靠、", "startFrame": 162, "durationInFrames": 17}, {"id": "caption-6", "text": "低成本地使用世界。", "startFrame": 179, "durationInFrames": 18}, {"id": "caption-7", "text": "谁能让Agent更容易调用，", "startFrame": 198, "durationInFrames": 146}, {"id": "caption-8", "text": "谁能提供更可靠的能力，", "startFrame": 343, "durationInFrames": 73}, {"id": "caption-9", "text": "谁能建立更清晰的权限和信任机制，", "startFrame": 417, "durationInFrames": 36}, {"id": "caption-10", "text": "谁就可能成为AI时代的新基础设施。", "startFrame": 452, "durationInFrames": 39}]},
    chapter: "总结",
    durationInFrames: 505,
    headline: "未来最重要的问题",
    id: "final-view",
    narration: "未来最重要的问题，不再只是人如何使用软件。而是Agent如何代表人，安全、可靠、低成本地使用世界。谁能让Agent更容易调用，谁能提供更可靠的能力，谁能建立更清晰的权限和信任机制，谁就可能成为AI时代的新基础设施。",
    primitiveMap: [],
    supportingText: "Agent可调用性 → 新基础设施",
    visual: { kind: "thesis" },
  });
  s.push({
    accent: "#FF8E72",
    audioFile: "generated/ai-concepts-redefined/closing.wav",
    captions: {"language": "zh-CN", "cues": [{"id": "caption-1", "text": "AI时代的真正变化，", "startFrame": 0, "durationInFrames": 48}, {"id": "caption-2", "text": "不是换了一个入口。", "startFrame": 48, "durationInFrames": 85}, {"id": "caption-3", "text": "而是换了一个操作主体。", "startFrame": 133, "durationInFrames": 54}, {"id": "caption-4", "text": "过去互联网围绕人设计。", "startFrame": 188, "durationInFrames": 30}, {"id": "caption-5", "text": "未来的互联网，", "startFrame": 218, "durationInFrames": 60}, {"id": "caption-6", "text": "很可能会围绕Agent重新组织。", "startFrame": 278, "durationInFrames": 38}, {"id": "caption-7", "text": "这就是为什么流量、", "startFrame": 315, "durationInFrames": 16}, {"id": "caption-8", "text": "服务、", "startFrame": 331, "durationInFrames": 18}, {"id": "caption-9", "text": "鉴权、", "startFrame": 349, "durationInFrames": 18}, {"id": "caption-10", "text": "隐私、", "startFrame": 368, "durationInFrames": 34}, {"id": "caption-11", "text": "数据、", "startFrame": 402, "durationInFrames": 7}, {"id": "caption-12", "text": "交互，", "startFrame": 408, "durationInFrames": 8}, {"id": "caption-13", "text": "都需要重新定义。", "startFrame": 416, "durationInFrames": 20}]},
    chapter: "结尾",
    durationInFrames: 449,
    headline: "互联网会围绕Agent重新组织",
    id: "closing",
    narration: "AI时代的真正变化，不是换了一个入口。而是换了一个操作主体。过去互联网围绕人设计。未来的互联网，很可能会围绕Agent重新组织。这就是为什么流量、服务、鉴权、隐私、数据、交互，都需要重新定义。",
    primitiveMap: [],
    supportingText: "人视角 → Agent视角",
    visual: { kind: "closing" },
  });
  return s;
};

const scenes = buildScenes();
export const totalDuration = scenes.reduce((s, c) => s + c.durationInFrames, 0);

export const data: Data = {
  contentFamily: "tutorial" as const,
  generatedAt: "2026-07-14T16:02:24.464Z",
  profileId: "landscape-16x9" as const,
  scenes,
  topic: { audience: "AI developers and internet practitioners" as const, title: "AI时代，很多概念都要重新定义" as const },
};